In [1]:
pip install kaggle

Collecting kaggle
  Downloading kaggle-2.2.4-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: bleach in ./.venv/lib/python3.13/site-packages (from kaggle) (6.4.0)
Collecting jupytext (from kaggle)
  Downloading jupytext-1.19.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in ./.venv/lib/python3.13/site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in ./.venv/lib/python3.13/site-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in ./.venv/lib/python3.13/site-packages (from kaggle) (7.36.0)
Requirement already satisfied: python-dateutil in ./.venv/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in ./.venv/lib/python3.13/site-packages (from kaggle) (1.2.3)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in ./.venv/lib/python3.13/site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from kaggle) (4.70.0)
Requirement already satisfied: urllib3>=1.15.1 in ./.venv/lib/python3.13/site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in ./.venv/lib/python3.13/site-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (4.2.0)
Collecting mdit-py-plugins (from jupytext->kaggle)
  Downloading mdit_py_plugins-0.6.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: nbformat in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.13/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.16.1)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.4)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests->kaggle) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests->kaggle) (3.19)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.13/site-packages (from requests->kaggle) (2026.7.22)
Downloading kaggle-2.2.4-py3-none-any.whl (126 kB)
Downloading jupytext-1.19.5-py3-none-any.whl (229 kB)
Downloading mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Installing collected packages: text-unidecode, python-slugify, mdit-py-plugins, jupytext, kaggle
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [kaggle]
Successfully installed jupytext-1.19.5 kaggle-2.2.4 mdit-py-plugins-0.6.1 python-slugify-8.0.4 text-unidecode-1.3

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install kaggle

Requirement already satisfied: kaggle in ./.venv/lib/python3.13/site-packages (2.2.4)
Requirement already satisfied: bleach in ./.venv/lib/python3.13/site-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in ./.venv/lib/python3.13/site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in ./.venv/lib/python3.13/site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in ./.venv/lib/python3.13/site-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in ./.venv/lib/python3.13/site-packages (from kaggle) (7.36.0)
Requirement already satisfied: python-dateutil in ./.venv/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in ./.venv/lib/python3.13/site-packages (from kaggle) (1.2.3)
Requirement already satisfied: python-slugify in ./.venv/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in ./.venv/lib/python3.13/site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from kaggle) (4.70.0)
Requirement already satisfied: urllib3>=1.15.1 in ./.venv/lib/python3.13/site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in ./.venv/lib/python3.13/site-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.13/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.13/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in ./.venv/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.16.1)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.4)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in ./.venv/lib/python3.13/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests->kaggle) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests->kaggle) (3.19)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.13/site-packages (from requests->kaggle) (2026.7.22)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
mkdir -p experiments/zyra_training/data/raw

In [2]:
!kaggle datasets download -d ronakbokaria/myntra-products-dataset -p ../data/raw

Dataset URL: https://www.kaggle.com/datasets/ronakbokaria/myntra-products-dataset
License(s): CC0-1.0
Downloading myntra-products-dataset.zip to ../data/raw
100%|███████████████████████████████████████| 115M/115M [00:26<00:00, 4.59MB/s]

In [3]:
import zipfile

Extracted: myntra-products-dataset.zip

In [4]:
for path in raw.rglob("*"):
    if path.is_file():
        print(path)

../data/raw/.DS_Store
../data/raw/myntra-products-dataset.zip
../data/raw/myntra-products-dataset/myntra202305041052.csv

In [12]:
import pandas as pd 
csv = "../data/raw/myntra-products-dataset/myntra202305041052.csv"
df = pd.read_csv(csv)
print("Shape:", df.shape)
df.head(10)
missing = pd.DataFrame({
    "missing": df.isnull().sum(),
    "missing_%": (df.isnull().mean() * 100).round(2),
    "dtype": df.dtypes
})

display(missing)
df.info()
missing = pd.DataFrame({
    "missing": df.isnull().sum(),
    "missing_%": (df.isnull().mean() * 100).round(2),
    "dtype": df.dtypes
})

display(missing)
print(df.columns.tolist())

Shape: (1060213, 11)

             missing  missing_%    dtype
id                 0        0.0    int64
name               0        0.0      str
img                0        0.0      str
asin               0        0.0      str
price              0        0.0  float64
mrp                0        0.0  float64
rating             0        0.0  float64
ratingTotal        0        0.0    int64
discount           0        0.0    int64
seller             0        0.0      str
purl               0        0.0      str

<class 'pandas.DataFrame'>
RangeIndex: 1060213 entries, 0 to 1060212
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1060213 non-null  int64
 1   name         1060213 non-null  str
 2   img          1060213 non-null  str
 3   asin         1060213 non-null  str
 4   price        1060213 non-null  float64
 5   mrp          1060213 non-null  float64
 6   rating       1060213 non-null  float64
 7   ratingTotal  1060213 non-null  int64
 8   discount     1060213 non-null  int64
 9   seller       1060213 non-null  str
 10  purl         1060213 non-null  str
dtypes: float64(3), int64(3), str(5)
memory usage: 89.0 MB

             missing  missing_%    dtype
id                 0        0.0    int64
name               0        0.0      str
img                0        0.0      str
asin               0        0.0      str
price              0        0.0  float64
mrp                0        0.0  float64
rating             0        0.0  float64
ratingTotal        0        0.0    int64
discount           0        0.0    int64
seller             0        0.0      str
purl               0        0.0      str

['id', 'name', 'img', 'asin', 'price', 'mrp', 'rating', 'ratingTotal', 'discount', 'seller', 'purl']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1060213 entries, 0 to 1060212
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1060213 non-null  int64
 1   name         1060213 non-null  str
 2   img          1060213 non-null  str
 3   asin         1060213 non-null  str
 4   price        1060213 non-null  float64
 5   mrp          1060213 non-null  float64
 6   rating       1060213 non-null  float64
 7   ratingTotal  1060213 non-null  int64
 8   discount     1060213 non-null  int64
 9   seller       1060213 non-null  str
 10  purl         1060213 non-null  str
dtypes: float64(3), int64(3), str(5)
memory usage: 89.0 MB

In [13]:
print(df.columns.tolist())

['id', 'name', 'img', 'asin', 'price', 'mrp', 'rating', 'ratingTotal', 'discount', 'seller', 'purl']

In [15]:
# Basic dataset statistics

print("Rows:", len(df))
print("Unique IDs:", df["id"].nunique())
print("Unique ASINs:", df["asin"].nunique())
print("Unique Product Names:", df["name"].nunique())
print("Unique Sellers:", df["seller"].nunique())

print("\nDuplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df["id"].duplicated().sum())
print("Duplicate ASINs:", df["asin"].duplicated().sum())
df.describe().T

Rows: 1060213
Unique IDs: 1060213
Unique ASINs: 1
Unique Product Names: 217738
Unique Sellers: 5496

Duplicate rows: 0
Duplicate IDs: 0
Duplicate ASINs: 1060212

,count,mean,std,min,25%,50%,75%,max
id,1060213.0,530107.000000,306057.274812,1.0,265054.0,530107.0,795160.0,1060213.0
price,1060213.0,1536.235155,3051.140381,25.0,499.0,811.0,1497.0,257500.0
mrp,1060213.0,2668.379334,3877.900441,25.0,999.0,1780.0,2999.0,257500.0
rating,1060213.0,1.060150,1.829632,0.0,0.0,0.0,2.8,5.0
ratingTotal,1060213.0,41.896183,747.664535,0.0,0.0,0.0,3.0,76400.0
discount,1060213.0,149.641952,564.878137,0.0,15.0,50.0,68.0,19996.0

In [17]:
images_per_product = df.groupby("id")["img"].nunique()

print("Average images per product:", images_per_product.mean())
print("Minimum:", images_per_product.min())
print("Maximum:", images_per_product.max())

display(images_per_product.value_counts().sort_index())

Average images per product: 1.0
Minimum: 1
Maximum: 1

img
1    1060213
Name: count, dtype: int64

In [21]:
from pathlib import Path

list(Path("../data/raw/myntra-fashion-products").rglob("*.csv"))

[]

In [22]:
!kaggle datasets download -d nirokey/myntra-fashion-products -p ../data/raw

Dataset URL: https://www.kaggle.com/datasets/nirokey/myntra-fashion-products
License(s): CC0-1.0
Downloading myntra-fashion-products.zip to ../data/raw
100%|█████████████████████████████████████| 2.96M/2.96M [00:01<00:00, 1.85MB/s]

In [47]:
from pathlib import Path

list(Path("../data/raw").glob("*"))
import zipfile
from pathlib import Path

zip_path = Path("../data/raw/myntra-fashion-products.zip")

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall("../data/raw/myntra-fashion-products")

print("Done")

Done

In [51]:
## P1 — Text quality

In [52]:
df2["name"].str.len().describe()
df2["description"].str.len().describe()

count    12491.000000
mean       159.206789
std        155.099275
min          7.000000
25%         91.000000
50%        119.000000
75%        171.000000
max       3670.000000
Name: description, dtype: float64

In [54]:
print(df2[df2["name"].str.len() < 10][["name", "description", "gender"]].to_string())
print(df2[df2["description"].str.len() < 20][["name", "description", "gender"]].to_string())

          name                                                         description gender
8378  Sherlock  Grey and Grey printed T-shirt, has a round neck, and short sleeves  Women
9529  Superman          Black printed T-shirt, has a round neck, and short sleeves    Men
                                                                   name          description gender
128    Difference of Opinion Men Olive Green Printed Round Neck T-shirt              T-shirt    Men
412                        Raymond Men Yellow Solid Polo Collar T-shirt              T-shirt    Men
837                        Raymond Men Orange Solid Polo Collar T-shirt              T-shirt    Men
1478                           Wild stone Men Stone Body Perfume 120 ml   Stone Body Perfume    Men
1794                           Wild Stone Men Edge Eau de Parfum 100 ml   Edge Eau de Parfum    Men
3637                       Smiley World Women Burgundy Solid Sweatshirt         Closed Front  Women
4043                           Secret Temptation Romance Perfume 100 ml      Romance Perfume  Women
4717                              Secret Temptation Adore Perfume 50 ml        Adore Perfume  Women
8772                               Franco Leone Men Beige Driving Shoes  Beige Driving Shoes    Men
11790                                  Louis Philippe Red Solid Bow Tie    Red solid bow tie    Men

# **P2 — Image count quality**

## We already know:

## Average ≈ 4.91
## Min = 1
## Max = 10
## 511 tested images → 0 failures
## All tested images = 1080 × 1440

## That's actually excellent.

# **P3 — Price quality**

In [60]:
print(df2["price"].describe())
print("Zero/negative prices:", (df2["price"] <= 0).sum())

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
count    12491.000000
mean      1452.660956
std       2118.503976
min         90.000000
25%        649.000000
50%        920.000000
75%       1499.000000
max      63090.000000
Name: price, dtype: float64
Zero/negative prices: 0

## **P4 — Stock**

In [61]:
print(df2["in_stock"].value_counts(dropna=False))

in_stock
True     12188
False      303
Name: count, dtype: int64

In [62]:
print(df2["in_stock"].value_counts(dropna=False))

in_stock
True     12188
False      303
Name: count, dtype: int64

In [63]:
print(ProductTextEncoderInput)
print(ProductAttributeEncoderInput)
print(ProductAttributes)
print(ProductImageEncoderInput)
print(ProductImageInput)

NameError: name 'ProductTextEncoderInput' is not defined