In [2]:
import sys
import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

# Apple Silicon GPU
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

print("Python :", sys.version)
print("PyTorch:", torch.__version__)
print("Device :", device)

if device.type == "mps":
    print("✅ Apple Metal (MPS) is available")
else:
    print("⚠️ MPS unavailable — using CPU")

Python : 3.13.13 | packaged by conda-forge | (main, Apr  8 2026, 02:29:07) [Clang 19.1.7 ]
PyTorch: 2.13.0
Device : mps
✅ Apple Metal (MPS) is available

In [5]:
USER_DIM = 662
PRODUCT_DIM = 662

print(f"User vector dimension    : {USER_DIM}")
print(f"Product vector dimension : {PRODUCT_DIM}")
print(f"Device                   : {device}")

assert USER_DIM == PRODUCT_DIM == 662

print("✅ V2 input contract verified")

import os
import numpy as np

# Change this only if your V1 artifacts are in another location
ARTIFACT_DIR = "p10_production_artifacts"

user_path = os.path.join(ARTIFACT_DIR, "user_embeddings.npy")
product_path = os.path.join(ARTIFACT_DIR, "product_embeddings.npy")

print("User embeddings :", user_path)
print("Product embeddings:", product_path)

user_embeddings = np.load(user_path)
product_embeddings = np.load(product_path)

print("\nUser shape    :", user_embeddings.shape)
print("Product shape :", product_embeddings.shape)
print("User dtype    :", user_embeddings.dtype)
print("Product dtype :", product_embeddings.dtype)

User vector dimension    : 662
Product vector dimension : 662
Device                   : mps
✅ V2 input contract verified
User embeddings : p10_production_artifacts/user_embeddings.npy
Product embeddings: p10_production_artifacts/product_embeddings.npy

FileNotFoundError: [Errno 2] No such file or directory: 'p10_production_artifacts/user_embeddings.npy'

In [7]:
from pathlib import Path

project_root = Path.cwd()

print("Current directory:")
print(project_root)

print("\nSearching for embedding/vector files...\n")

patterns = [
    "*.npy",
    "*.npz",
    "*.pt",
    "*.pth",
    "*.pkl",
    "*.json",
    "*.csv",
]

for pattern in patterns:
    files = list(project_root.rglob(pattern))
    if files:
        print(f"\n{pattern}")
        for f in files[:50]:
            print("  ", f)

Current directory:
/Users/saketh/Desktop/Projects/weavly/core-model

Searching for embedding/vector files...


*.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/p10_production_artifacts/product_embeddings.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/stats/tests/data/rel_breitwigner_pdf_sample_data_ROOT.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/stats/tests/data/jf_skew_t_gamlss_pdf_data.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/stats/tests/data/levy_stable/stable-Z1-cdf-sample-data.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/stats/tests/data/levy_stable/stable-Z1-pdf-sample-data.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/stats/tests/data/levy_stable/stable-loc-scale-sample-data.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/interpolate/tests/data/estimate_gradients_hang.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/axes_grid/bivariate_normal.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py35_np19.pkl_01.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py35_np19.pkl_03.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py35_np19.pkl_02.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py35_np19.pkl_04.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np17.pkl_04.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py34_np19.pkl_04.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np17.pkl_02.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py34_np19.pkl_01.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np17.pkl_03.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np17.pkl_01.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py34_np19.pkl_03.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py34_np19.pkl_02.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py33_np18.pkl_04.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np16.pkl_02.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np16.pkl_03.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np16.pkl_01.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py33_np18.pkl_02.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np16.pkl_04.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py33_np18.pkl_03.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py33_np18.pkl_01.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/py2-objarr.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/py2-np0-objarr.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/python3.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/win64python2.npy
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/py3-objarr.npy

*.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/stats/_sobol_direction_numbers.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/spatial/tests/data/degenerate_pointset.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/sparse/linalg/tests/propack_test_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/interpolate/tests/data/gcvspl.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/interpolate/tests/data/bug-1310.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/fftpack/tests/fftw_longdouble_ref.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/fftpack/tests/fftw_single_ref.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/fftpack/tests/fftw_double_ref.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/fftpack/tests/test.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/special/tests/data/gsl.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/special/tests/data/boost.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/special/tests/data/local.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/linalg/tests/data/gendare_20170120_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/linalg/tests/data/carex_19_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/linalg/tests/data/carex_18_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/linalg/tests/data/carex_15_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/linalg/tests/data/carex_6_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/linalg/tests/data/carex_20_data.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/goog.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/jacksboro_fault_dem.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/topobathy.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/py3-objarr.npz
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/tests/data/py2-objarr.npz

*.pth
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/__editable__.zyra-0.1.0.pth
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/distutils-precedence.pth

*.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/data/recommendation/product_catalog.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.10.0_pickle_py33_np18.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np16.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py27_np17.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py34_np19.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py35_np19.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.11.0_pickle_py36_np111.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.9.2_pickle_py33_np18.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.10.0_pickle_py27_np17.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.10.0_pickle_py34_np19.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/joblib/test/data/joblib_0.10.0_pickle_py35_np19.pkl
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/astype_copy.pkl

*.json
   /Users/saketh/Desktop/Projects/weavly/core-model/p10_production_artifacts/product_id_to_index.json
   /Users/saketh/Desktop/Projects/weavly/core-model/p10_production_artifacts/zyra_v1_config.json
   /Users/saketh/Desktop/Projects/weavly/core-model/p10_production_artifacts/manifest.json
   /Users/saketh/Desktop/Projects/weavly/core-model/p8_output/p8_checkpoint.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.vscode/settings.json
   /Users/saketh/Desktop/Projects/weavly/core-model/reports/zyra_v0_evaluation.json
   /Users/saketh/Desktop/Projects/weavly/core-model/data/recommendation/product_index.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/webpdf/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/python/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/classic/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/markdown/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/latex/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/reveal/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/rst/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/lab/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/basic/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/script/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/nbconvert/templates/asciidoc/conf.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/static/build_log.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/static/third-party-licenses.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/static/package.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/fileeditor-extension/completer.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/fileeditor-extension/plugin.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/consoles.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/files.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/notebooks.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/codemirror-extension/plugin.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/extensionmanager-extension/plugin.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/sanitizer.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/utilityCommands.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/sessionDialogs.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/kernels-settings.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/palette.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/print.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/notification.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/themes.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/toc-extension/registry.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/widget.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/download.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/open-with.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/open-browser-tab.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/browser.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/metadataform-extension/metadataforms.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/terminal-extension/plugin.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/statusbar-extension/plugin.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/export.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/tracker.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/tools.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/panel.json
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/completer.json

*.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/p10_production_artifacts/product_metadata.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/scipy/signal/tests/data/GLB.Ts+dSST.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/msft.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/data_x_x2_x3.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/matplotlib/mpl-data/sample_data/Stocks.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/sklearn/datasets/data/wine_data.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/sklearn/datasets/data/iris.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/sklearn/datasets/data/breast_cancer.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/sklearn/datasets/data/linnerud_physiological.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/sklearn/datasets/data/linnerud_exercise.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/tornado/test/csv_translations/fr_FR.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/philox-testset-1.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/philox-testset-2.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/sfc64-testset-1.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/sfc64-testset-2.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/mt19937-testset-2.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/mt19937-testset-1.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/pcg64-testset-1.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/pcg64-testset-2.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/pcg64dxsm-testset-1.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/random/tests/data/pcg64dxsm-testset-2.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-log2.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-arcsinh.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-arctanh.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-sin.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-cos.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-cbrt.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-arctan.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-cosh.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-expm1.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-sinh.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-tanh.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/_core/tests/data/umath-validation-set-log10.csv

In [8]:
from pathlib import Path
import numpy as np
import pandas as pd

ARTIFACT_DIR = Path("p10_production_artifacts")

product_embeddings = np.load(
    ARTIFACT_DIR / "product_embeddings.npy"
)

product_metadata = pd.read_csv(
    ARTIFACT_DIR / "product_metadata.csv"
)

print("Product embeddings shape :", product_embeddings.shape)
print("Product embeddings dtype :", product_embeddings.dtype)
print("Product metadata shape   :", product_metadata.shape)

print("\nFirst 5 products:")
display(product_metadata.head())

print("\nEmbedding statistics:")
print("Mean :", product_embeddings.mean())
print("Std  :", product_embeddings.std())
print("Min  :", product_embeddings.min())
print("Max  :", product_embeddings.max())

print("\nNaN :", np.isnan(product_embeddings).sum())
print("Inf :", np.isinf(product_embeddings).sum())

Product embeddings shape : (12465, 662)
Product embeddings dtype : float32
Product metadata shape   : (12465, 8)

First 5 products:

,productId,name,brand_clean,gender_clean,category_clean,price_numeric,imageUrl,description
0,10017413,DKNY Unisex Black & Grey Printed Medium Trolle...,dkny,Unisex,bag,11745,http://assets.myntassets.com/assets/images/100...,"Black and grey printed medium trolley bag, sec..."
1,10016283,EthnoVogue Women Beige & Grey Made to Measure ...,ethnovogue,Women,kurta,5810,http://assets.myntassets.com/assets/images/100...,Beige & Grey made to measure kurta with churid...
2,10009781,SPYKAR Women Pink Alexa Super Skinny Fit High-...,spykar,Women,jeans,899,http://assets.myntassets.com/assets/images/100...,Pink coloured wash 5-pocket high-rise cropped ...
3,10015921,Raymond Men Blue Self-Design Single-Breasted B...,raymond,Men,suit,5599,http://assets.myntassets.com/assets/images/pro...,Blue self-design bandhgala suitBlue self-desig...
4,10017833,Parx Men Brown & Off-White Slim Fit Printed Ca...,parx,Men,shirt,759,http://assets.myntassets.com/assets/images/pro...,"Brown and off-white printed casual shirt, has ..."

Embedding statistics:
Mean : 3.848241e-05
Std  : 0.038866084
Min  : -0.39192447
Max  : 0.27439696

NaN : 0
Inf : 0

In [13]:
from pathlib import Path

files = [
    "zyra/zyra_model/models/person_garment/model.py",
    "zyra/zyra_model/models/outfit_compatibility/model.py",
]

for file_path in files:
    path = Path(file_path)

    print("\n" + "=" * 80)
    print(f"FILE: {path}")
    print("=" * 80)

    print(path.read_text())

================================================================================
FILE: zyra/zyra_model/models/person_garment/model.py
================================================================================
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field, ConfigDict

from zyra.zyra_model.config.constants import (
    DEFAULT_PG_FIT_WEIGHT,
    DEFAULT_PG_PREFERENCE_WEIGHT,
    DEFAULT_PG_VISUAL_WEIGHT,
    UNIFIED_VECTOR_DIMENSION,
)
from zyra.zyra_model.contracts.user_contract import ZyraUserRepresentation, ZyraUserInput
from zyra.zyra_model.contracts.candidate_contract import CandidateProduct, CandidateSet
from zyra.zyra_model.models.person_garment.fit_matcher import evaluate_person_fit_suitability
from zyra.zyra_model.models.person_garment.preference_matcher import evaluate_person_preference_suitability
from zyra.zyra_model.models.person_garment.visual_embedding_matcher import evaluate_visual_embedding_alignment


class PersonGarmentScore(BaseModel):
    """Structured breakdown of personalization score produced by Model 2."""

    model_config = ConfigDict(
        populate_by_name=True,
        extra="ignore",
    )

    person_garment_score: float = Field(
        ...,
        alias="personGarmentScore",
        ge=0.0,
        le=1.0,
        description="Overall personalization suitability score",
    )
    fit_score: float = Field(
        ...,
        alias="fitScore",
        ge=0.0,
        le=1.0,
        description="Physical fit & silhouette match score",
    )
    preference_score: float = Field(
        ...,
        alias="preferenceScore",
        ge=0.0,
        le=1.0,
        description="Static style, color, and budget preference alignment score",
    )
    visual_embedding_score: float = Field(
        ...,
        alias="visualEmbeddingScore",
        ge=0.0,
        le=1.0,
        description="Cosine similarity alignment between user and product vectors",
    )
    user_id: Optional[str] = Field(default=None, alias="userId")
    product_id: Optional[str] = Field(default=None, alias="productId")


def extract_user_components(
    user: Union[ZyraUserRepresentation, ZyraUserInput, Dict[str, Any]],
) -> tuple[str, Dict[str, Any], List[float]]:
    """Helper to extract user_id, profile dict, and 662D embedding."""
    if isinstance(user, ZyraUserRepresentation):
        return user.user_id, user.user_profile, user.user_embedding
    if isinstance(user, ZyraUserInput):
        return user.user_id, user.user_profile, user.user_embedding
    if isinstance(user, dict):
        uid = str(user.get("user_id") or user.get("userId") or "unknown")
        prof = user.get("user_profile") or user.get("userProfile") or {}
        vec = user.get("user_embedding") or user.get("userEmbedding") or []
        return uid, prof, vec
    return "unknown", {}, []


def extract_product_components(
    product: Union[CandidateProduct, Dict[str, Any]],
) -> tuple[str, Dict[str, Any], List[float]]:
    """Helper to extract product_id, profile dict, and 662D embedding."""
    if isinstance(product, CandidateProduct):
        return product.product_id, product.product_profile, product.product_embedding
    if isinstance(product, dict):
        pid = str(product.get("product_id") or product.get("productId") or "unknown")
        prof = product.get("product_profile") or product.get("productProfile") or product
        vec = product.get("product_embedding") or product.get("productEmbedding") or []
        return pid, prof, vec
    return "unknown", {}, []


class PersonGarmentSuitabilityModel:
    """
    Model 2: Person x Garment Personalization Intelligence.

    Responsibility:
    - Determine whether a specific garment suits this particular person.
    - Evaluates:
      1. Physical Fit Matcher (user preferred fit & body shape vs product silhouette)
      2. Static Preference Matcher (style identity, preferred & avoided colors, budget tier)
      3. Visual Embedding Matcher (662D dense vector cosine similarity)
    - Combines signals into normalized person_garment_score in [0.0, 1.0].
    """

    def __init__(
        self,
        weight_fit: float = DEFAULT_PG_FIT_WEIGHT,
        weight_preference: float = DEFAULT_PG_PREFERENCE_WEIGHT,
        weight_visual: float = DEFAULT_PG_VISUAL_WEIGHT,
    ) -> None:
        self.weight_fit = weight_fit
        self.weight_preference = weight_preference
        self.weight_visual = weight_visual

    def evaluate(
        self,
        user: Union[ZyraUserRepresentation, ZyraUserInput, Dict[str, Any]],
        product: Union[CandidateProduct, Dict[str, Any]],
    ) -> PersonGarmentScore:
        """
        Evaluate personalization suitability and return structured score breakdown.
        """
        user_id, user_profile, user_vec = extract_user_components(user)
        product_id, product_profile, prod_vec = extract_product_components(product)

        # 1. Fit matching
        fit_score = evaluate_person_fit_suitability(user_profile, product_profile)

        # 2. Preference matching
        preference_score = evaluate_person_preference_suitability(user_profile, product_profile)

        # 3. Visual embedding alignment
        visual_score = evaluate_visual_embedding_alignment(user_vec, prod_vec)

        # 4. Weighted blend
        total_score = (
            self.weight_fit * fit_score +
            self.weight_preference * preference_score +
            self.weight_visual * visual_score
        )

        final_pg_score = max(0.0, min(1.0, round(total_score, 4)))

        return PersonGarmentScore(
            person_garment_score=final_pg_score,
            fit_score=round(fit_score, 4),
            preference_score=round(preference_score, 4),
            visual_embedding_score=round(visual_score, 4),
            user_id=user_id,
            product_id=product_id,
        )

    def score(
        self,
        user: Union[ZyraUserRepresentation, ZyraUserInput, Dict[str, Any]],
        product: Union[CandidateProduct, Dict[str, Any]],
    ) -> float:
        """Evaluate personalization suitability and return single score float."""
        result = self.evaluate(user, product)
        return result.person_garment_score


================================================================================
FILE: zyra/zyra_model/models/outfit_compatibility/model.py
================================================================================
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field

from zyra.zyra_model.contracts.candidate_contract import CandidateProduct
from zyra.zyra_model.models.outfit_compatibility.color_harmony import (
    extract_color_from_product,
    evaluate_color_harmony,
    NEUTRAL_COLORS,
)
from zyra.zyra_model.models.outfit_compatibility.style_coordination import (
    evaluate_style_coordination,
    get_profile_dict,
    extract_category,
    extract_fit_type,
    extract_styles,
)


class OutfitCompatibilityScore(BaseModel):
    """Output structure representing the detailed compatibility breakdown between garments."""

    outfit_compatibility_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall garment-to-garment / outfit compatibility score",
    )
    color_harmony_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Color wheel harmony score between the items",
    )
    style_coordination_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Style, category, silhouette, and pattern coordination score",
    )


class OutfitCompatibilityModel:
    """
    Model 1: Pretrained fashion knowledge intelligence for garment & outfit compatibility.

    Responsibility:
    - Determine whether garments work well together aesthetically and structurally.
    - Evaluate color wheel harmony, category pairings, silhouette balance, pattern density, and style cohesion.
    - Strictly does NOT evaluate whether the garment suits the user (that is Model 2).
    """

    def __init__(
        self,
        color_weight: float = 0.45,
        style_weight: float = 0.55,
    ) -> None:
        self.color_weight = color_weight
        self.style_weight = style_weight

    def score_pair(
        self,
        item_a: Union[CandidateProduct, Dict[str, Any]],
        item_b: Union[CandidateProduct, Dict[str, Any]],
    ) -> float:
        """
        Evaluate compatibility between two specific garments (e.g. Shirt + Trouser).

        Returns a normalized score in [0.0, 1.0].
        """
        color_a = extract_color_from_product(item_a)
        color_b = extract_color_from_product(item_b)
        color_score = evaluate_color_harmony(color_a, color_b)

        style_score = evaluate_style_coordination(item_a, item_b)

        total_score = (
            self.color_weight * color_score +
            self.style_weight * style_score
        )
        return max(0.0, min(1.0, round(total_score, 4)))

    def evaluate_pair(
        self,
        item_a: Union[CandidateProduct, Dict[str, Any]],
        item_b: Union[CandidateProduct, Dict[str, Any]],
    ) -> OutfitCompatibilityScore:
        """
        Evaluate compatibility and return a structured score breakdown.
        """
        color_a = extract_color_from_product(item_a)
        color_b = extract_color_from_product(item_b)
        color_score = evaluate_color_harmony(color_a, color_b)
        style_score = evaluate_style_coordination(item_a, item_b)

        total_score = max(0.0, min(1.0, round(
            self.color_weight * color_score + self.style_weight * style_score, 4
        )))

        return OutfitCompatibilityScore(
            outfit_compatibility_score=total_score,
            color_harmony_score=round(color_score, 4),
            style_coordination_score=round(style_score, 4),
        )

    def score_candidate(
        self,
        candidate: Union[CandidateProduct, Dict[str, Any]],
        context_items: Optional[List[Union[CandidateProduct, Dict[str, Any]]]] = None,
    ) -> float:
        """
        Evaluate candidate product's outfit compatibility score.

        If context_items are provided (e.g. an existing outfit anchor or selected garments),
        evaluates pairwise compatibility against the context.

        If no context is provided, evaluates the candidate's intrinsic styling versatility:
        - Versatile neutral or staple color palette
        - Universal category pairing versatility (e.g. staple tees, hoodies, trousers, outerwear)
        - Silhouette adaptability
        """
        if context_items and len(context_items) > 0:
            scores = [self.score_pair(candidate, ctx) for ctx in context_items]
            return round(sum(scores) / len(scores), 4)

        # Standalone intrinsic styling versatility evaluation
        prof = get_profile_dict(candidate)
        color = extract_color_from_product(prof)
        cat = extract_category(prof)
        styles = extract_styles(prof)
        fit = extract_fit_type(prof)

        # Baseline versatility score
        base_score = 0.75

        # Palette versatility bonus
        if color in NEUTRAL_COLORS:
            base_score += 0.12  # Neutral garments have extremely high outfit compatibility
        elif color in {"olive", "sage", "navy", "burgundy", "brown", "tan", "camel"}:
            base_score += 0.08  # Versatile classic hues

        # Category versatility
        if cat in {"tops", "bottoms", "outerwear"}:
            base_score += 0.06

        # Silhouette versatility
        if fit in {"regular", "relaxed", "oversized"}:
            base_score += 0.04

        return max(0.0, min(1.0, round(base_score, 4)))

    def score_outfit(
        self,
        items: List[Union[CandidateProduct, Dict[str, Any]]],
    ) -> float:
        """
        Evaluate full outfit compatibility across a multi-piece garment collection.
        """
        if not items or len(items) <= 1:
            return 1.0

        scores: List[float] = []
        for i in range(len(items)):
            for j in range(i + 1, len(items)):
                scores.append(self.score_pair(items[i], items[j]))

        return round(sum(scores) / len(scores), 4) if scores else 1.0

In [11]:
from pathlib import Path

for path in Path("zyra/zyra_model").rglob("*.py"):
    if "__pycache__" not in str(path):
        print(path)

zyra/zyra_model/__init__.py
zyra/zyra_model/engine.py
zyra/zyra_model/main.py
zyra/zyra_model/recommendation/__init__.py
zyra/zyra_model/recommendation/generator.py
zyra/zyra_model/recommendation/engine.py
zyra/zyra_model/recommendation/exceptions.py
zyra/zyra_model/config/logging.py
zyra/zyra_model/config/constants.py
zyra/zyra_model/config/__init__.py
zyra/zyra_model/config/settings.py
zyra/zyra_model/contracts/__init__.py
zyra/zyra_model/contracts/user_contract.py
zyra/zyra_model/contracts/candidate_contract.py
zyra/zyra_model/tests/test_hydration.py
zyra/zyra_model/tests/conftest.py
zyra/zyra_model/tests/test_retrieval.py
zyra/zyra_model/tests/test_p5_evaluation.py
zyra/zyra_model/tests/test_outfit_compatibility.py
zyra/zyra_model/tests/test_user_contract.py
zyra/zyra_model/tests/test_persistence.py
zyra/zyra_model/tests/__init__.py
zyra/zyra_model/tests/test_top10_generator.py
zyra/zyra_model/tests/test_person_garment.py
zyra/zyra_model/tests/test_ranking.py
zyra/zyra_model/tests/test_recommendation_api.py
zyra/zyra_model/tests/test_foundation.py
zyra/zyra_model/tests/test_occasion_compatibility.py
zyra/zyra_model/tests/test_multi_occasion.py
zyra/zyra_model/tests/test_p2_end_to_end.py
zyra/zyra_model/models/__init__.py
zyra/zyra_model/retrieval/interface.py
zyra/zyra_model/retrieval/__init__.py
zyra/zyra_model/retrieval/hydration.py
zyra/zyra_model/retrieval/mock_retriever.py
zyra/zyra_model/retrieval/qdrant_retriever.py
zyra/zyra_model/persistence/db.py
zyra/zyra_model/persistence/postgres_recommendations_repository.py
zyra/zyra_model/persistence/__init__.py
zyra/zyra_model/persistence/repository.py
zyra/zyra_model/api/deps.py
zyra/zyra_model/api/client.py
zyra/zyra_model/api/__init__.py
zyra/zyra_model/api/schemas.py
zyra/zyra_model/api/routes.py
zyra/zyra_model/evaluation/evaluation_case.py
zyra/zyra_model/evaluation/metrics.py
zyra/zyra_model/evaluation/runner.py
zyra/zyra_model/evaluation/__init__.py
zyra/zyra_model/evaluation/evaluation_set.py
zyra/zyra_model/evaluation/evaluator.py
zyra/zyra_model/evaluation/report.py
zyra/zyra_model/models/ranking/__init__.py
zyra/zyra_model/models/ranking/ranker.py
zyra/zyra_model/models/outfit_compatibility/style_coordination.py
zyra/zyra_model/models/outfit_compatibility/__init__.py
zyra/zyra_model/models/outfit_compatibility/model.py
zyra/zyra_model/models/outfit_compatibility/color_harmony.py
zyra/zyra_model/models/person_garment/visual_embedding_matcher.py
zyra/zyra_model/models/person_garment/__init__.py
zyra/zyra_model/models/person_garment/model.py
zyra/zyra_model/models/person_garment/fit_matcher.py
zyra/zyra_model/models/person_garment/preference_matcher.py
zyra/zyra_model/models/occasion/__init__.py
zyra/zyra_model/models/occasion/model.py

In [14]:
from pathlib import Path

files = [
    "zyra/zyra_model/models/person_garment/model.py",
    "zyra/zyra_model/models/outfit_compatibility/model.py",
]

for file_path in files:
    path = Path(file_path)

    print("\n" + "=" * 80)
    print(f"FILE: {path}")
    print("=" * 80)

    print(path.read_text())

================================================================================
FILE: zyra/zyra_model/models/person_garment/model.py
================================================================================
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field, ConfigDict

from zyra.zyra_model.config.constants import (
    DEFAULT_PG_FIT_WEIGHT,
    DEFAULT_PG_PREFERENCE_WEIGHT,
    DEFAULT_PG_VISUAL_WEIGHT,
    UNIFIED_VECTOR_DIMENSION,
)
from zyra.zyra_model.contracts.user_contract import ZyraUserRepresentation, ZyraUserInput
from zyra.zyra_model.contracts.candidate_contract import CandidateProduct, CandidateSet
from zyra.zyra_model.models.person_garment.fit_matcher import evaluate_person_fit_suitability
from zyra.zyra_model.models.person_garment.preference_matcher import evaluate_person_preference_suitability
from zyra.zyra_model.models.person_garment.visual_embedding_matcher import evaluate_visual_embedding_alignment


class PersonGarmentScore(BaseModel):
    """Structured breakdown of personalization score produced by Model 2."""

    model_config = ConfigDict(
        populate_by_name=True,
        extra="ignore",
    )

    person_garment_score: float = Field(
        ...,
        alias="personGarmentScore",
        ge=0.0,
        le=1.0,
        description="Overall personalization suitability score",
    )
    fit_score: float = Field(
        ...,
        alias="fitScore",
        ge=0.0,
        le=1.0,
        description="Physical fit & silhouette match score",
    )
    preference_score: float = Field(
        ...,
        alias="preferenceScore",
        ge=0.0,
        le=1.0,
        description="Static style, color, and budget preference alignment score",
    )
    visual_embedding_score: float = Field(
        ...,
        alias="visualEmbeddingScore",
        ge=0.0,
        le=1.0,
        description="Cosine similarity alignment between user and product vectors",
    )
    user_id: Optional[str] = Field(default=None, alias="userId")
    product_id: Optional[str] = Field(default=None, alias="productId")


def extract_user_components(
    user: Union[ZyraUserRepresentation, ZyraUserInput, Dict[str, Any]],
) -> tuple[str, Dict[str, Any], List[float]]:
    """Helper to extract user_id, profile dict, and 662D embedding."""
    if isinstance(user, ZyraUserRepresentation):
        return user.user_id, user.user_profile, user.user_embedding
    if isinstance(user, ZyraUserInput):
        return user.user_id, user.user_profile, user.user_embedding
    if isinstance(user, dict):
        uid = str(user.get("user_id") or user.get("userId") or "unknown")
        prof = user.get("user_profile") or user.get("userProfile") or {}
        vec = user.get("user_embedding") or user.get("userEmbedding") or []
        return uid, prof, vec
    return "unknown", {}, []


def extract_product_components(
    product: Union[CandidateProduct, Dict[str, Any]],
) -> tuple[str, Dict[str, Any], List[float]]:
    """Helper to extract product_id, profile dict, and 662D embedding."""
    if isinstance(product, CandidateProduct):
        return product.product_id, product.product_profile, product.product_embedding
    if isinstance(product, dict):
        pid = str(product.get("product_id") or product.get("productId") or "unknown")
        prof = product.get("product_profile") or product.get("productProfile") or product
        vec = product.get("product_embedding") or product.get("productEmbedding") or []
        return pid, prof, vec
    return "unknown", {}, []


class PersonGarmentSuitabilityModel:
    """
    Model 2: Person x Garment Personalization Intelligence.

    Responsibility:
    - Determine whether a specific garment suits this particular person.
    - Evaluates:
      1. Physical Fit Matcher (user preferred fit & body shape vs product silhouette)
      2. Static Preference Matcher (style identity, preferred & avoided colors, budget tier)
      3. Visual Embedding Matcher (662D dense vector cosine similarity)
    - Combines signals into normalized person_garment_score in [0.0, 1.0].
    """

    def __init__(
        self,
        weight_fit: float = DEFAULT_PG_FIT_WEIGHT,
        weight_preference: float = DEFAULT_PG_PREFERENCE_WEIGHT,
        weight_visual: float = DEFAULT_PG_VISUAL_WEIGHT,
    ) -> None:
        self.weight_fit = weight_fit
        self.weight_preference = weight_preference
        self.weight_visual = weight_visual

    def evaluate(
        self,
        user: Union[ZyraUserRepresentation, ZyraUserInput, Dict[str, Any]],
        product: Union[CandidateProduct, Dict[str, Any]],
    ) -> PersonGarmentScore:
        """
        Evaluate personalization suitability and return structured score breakdown.
        """
        user_id, user_profile, user_vec = extract_user_components(user)
        product_id, product_profile, prod_vec = extract_product_components(product)

        # 1. Fit matching
        fit_score = evaluate_person_fit_suitability(user_profile, product_profile)

        # 2. Preference matching
        preference_score = evaluate_person_preference_suitability(user_profile, product_profile)

        # 3. Visual embedding alignment
        visual_score = evaluate_visual_embedding_alignment(user_vec, prod_vec)

        # 4. Weighted blend
        total_score = (
            self.weight_fit * fit_score +
            self.weight_preference * preference_score +
            self.weight_visual * visual_score
        )

        final_pg_score = max(0.0, min(1.0, round(total_score, 4)))

        return PersonGarmentScore(
            person_garment_score=final_pg_score,
            fit_score=round(fit_score, 4),
            preference_score=round(preference_score, 4),
            visual_embedding_score=round(visual_score, 4),
            user_id=user_id,
            product_id=product_id,
        )

    def score(
        self,
        user: Union[ZyraUserRepresentation, ZyraUserInput, Dict[str, Any]],
        product: Union[CandidateProduct, Dict[str, Any]],
    ) -> float:
        """Evaluate personalization suitability and return single score float."""
        result = self.evaluate(user, product)
        return result.person_garment_score


================================================================================
FILE: zyra/zyra_model/models/outfit_compatibility/model.py
================================================================================
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field

from zyra.zyra_model.contracts.candidate_contract import CandidateProduct
from zyra.zyra_model.models.outfit_compatibility.color_harmony import (
    extract_color_from_product,
    evaluate_color_harmony,
    NEUTRAL_COLORS,
)
from zyra.zyra_model.models.outfit_compatibility.style_coordination import (
    evaluate_style_coordination,
    get_profile_dict,
    extract_category,
    extract_fit_type,
    extract_styles,
)


class OutfitCompatibilityScore(BaseModel):
    """Output structure representing the detailed compatibility breakdown between garments."""

    outfit_compatibility_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall garment-to-garment / outfit compatibility score",
    )
    color_harmony_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Color wheel harmony score between the items",
    )
    style_coordination_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Style, category, silhouette, and pattern coordination score",
    )


class OutfitCompatibilityModel:
    """
    Model 1: Pretrained fashion knowledge intelligence for garment & outfit compatibility.

    Responsibility:
    - Determine whether garments work well together aesthetically and structurally.
    - Evaluate color wheel harmony, category pairings, silhouette balance, pattern density, and style cohesion.
    - Strictly does NOT evaluate whether the garment suits the user (that is Model 2).
    """

    def __init__(
        self,
        color_weight: float = 0.45,
        style_weight: float = 0.55,
    ) -> None:
        self.color_weight = color_weight
        self.style_weight = style_weight

    def score_pair(
        self,
        item_a: Union[CandidateProduct, Dict[str, Any]],
        item_b: Union[CandidateProduct, Dict[str, Any]],
    ) -> float:
        """
        Evaluate compatibility between two specific garments (e.g. Shirt + Trouser).

        Returns a normalized score in [0.0, 1.0].
        """
        color_a = extract_color_from_product(item_a)
        color_b = extract_color_from_product(item_b)
        color_score = evaluate_color_harmony(color_a, color_b)

        style_score = evaluate_style_coordination(item_a, item_b)

        total_score = (
            self.color_weight * color_score +
            self.style_weight * style_score
        )
        return max(0.0, min(1.0, round(total_score, 4)))

    def evaluate_pair(
        self,
        item_a: Union[CandidateProduct, Dict[str, Any]],
        item_b: Union[CandidateProduct, Dict[str, Any]],
    ) -> OutfitCompatibilityScore:
        """
        Evaluate compatibility and return a structured score breakdown.
        """
        color_a = extract_color_from_product(item_a)
        color_b = extract_color_from_product(item_b)
        color_score = evaluate_color_harmony(color_a, color_b)
        style_score = evaluate_style_coordination(item_a, item_b)

        total_score = max(0.0, min(1.0, round(
            self.color_weight * color_score + self.style_weight * style_score, 4
        )))

        return OutfitCompatibilityScore(
            outfit_compatibility_score=total_score,
            color_harmony_score=round(color_score, 4),
            style_coordination_score=round(style_score, 4),
        )

    def score_candidate(
        self,
        candidate: Union[CandidateProduct, Dict[str, Any]],
        context_items: Optional[List[Union[CandidateProduct, Dict[str, Any]]]] = None,
    ) -> float:
        """
        Evaluate candidate product's outfit compatibility score.

        If context_items are provided (e.g. an existing outfit anchor or selected garments),
        evaluates pairwise compatibility against the context.

        If no context is provided, evaluates the candidate's intrinsic styling versatility:
        - Versatile neutral or staple color palette
        - Universal category pairing versatility (e.g. staple tees, hoodies, trousers, outerwear)
        - Silhouette adaptability
        """
        if context_items and len(context_items) > 0:
            scores = [self.score_pair(candidate, ctx) for ctx in context_items]
            return round(sum(scores) / len(scores), 4)

        # Standalone intrinsic styling versatility evaluation
        prof = get_profile_dict(candidate)
        color = extract_color_from_product(prof)
        cat = extract_category(prof)
        styles = extract_styles(prof)
        fit = extract_fit_type(prof)

        # Baseline versatility score
        base_score = 0.75

        # Palette versatility bonus
        if color in NEUTRAL_COLORS:
            base_score += 0.12  # Neutral garments have extremely high outfit compatibility
        elif color in {"olive", "sage", "navy", "burgundy", "brown", "tan", "camel"}:
            base_score += 0.08  # Versatile classic hues

        # Category versatility
        if cat in {"tops", "bottoms", "outerwear"}:
            base_score += 0.06

        # Silhouette versatility
        if fit in {"regular", "relaxed", "oversized"}:
            base_score += 0.04

        return max(0.0, min(1.0, round(base_score, 4)))

    def score_outfit(
        self,
        items: List[Union[CandidateProduct, Dict[str, Any]]],
    ) -> float:
        """
        Evaluate full outfit compatibility across a multi-piece garment collection.
        """
        if not items or len(items) <= 1:
            return 1.0

        scores: List[float] = []
        for i in range(len(items)):
            for j in range(i + 1, len(items)):
                scores.append(self.score_pair(items[i], items[j]))

        return round(sum(scores) / len(scores), 4) if scores else 1.0

In [16]:
import torch
import torch.nn as nn


class ZyraV2Compatibility(nn.Module):
    """
    Zyra V2 — User × Product Compatibility Model

    Inputs:
        user_vector:    [batch, 662]
        product_vector: [batch, 662]

    Output:
        suitability_score: [batch, 1]
    """

    def __init__(self, input_dim=662, hidden_dim=512, num_heads=8):
        super().__init__()

        # Convert existing Zyra representations
        # into a shared compatibility space.
        self.user_projection = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
        )

        self.product_projection = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),
        )

        # Learn user ↔ product interactions.
        self.cross_attention = nn.MultiheadAttention(
            embed_dim=hidden_dim,
            num_heads=num_heads,
            batch_first=True,
        )

        # Learn final compatibility.
        self.compatibility_head = nn.Sequential(
            nn.Linear(hidden_dim, 256),
            nn.GELU(),
            nn.Dropout(0.2),

            nn.Linear(256, 64),
            nn.GELU(),

            nn.Linear(64, 1),
            nn.Sigmoid(),
        )

    def forward(self, user_vector, product_vector):

        user = self.user_projection(user_vector)
        product = self.product_projection(product_vector)

        # [B, 512] → [B, 1, 512]
        user = user.unsqueeze(1)
        product = product.unsqueeze(1)

        # Product representation attends to
        # relevant information from the user.
        fused, attention_weights = self.cross_attention(
            query=product,
            key=user,
            value=user,
        )

        fused = fused.squeeze(1)

        score = self.compatibility_head(fused)

        return score, attention_weights

In [17]:
model = ZyraV2Compatibility().to(device)

print(model)

ZyraV2Compatibility(
  (user_projection): Sequential(
    (0): Linear(in_features=662, out_features=512, bias=True)
    (1): GELU(approximate='none')
    (2): LayerNorm((512,), eps=1e-05, elementwise_affine=True, bias=True)
  )
  (product_projection): Sequential(
    (0): Linear(in_features=662, out_features=512, bias=True)
    (1): GELU(approximate='none')
    (2): LayerNorm((512,), eps=1e-05, elementwise_affine=True, bias=True)
  )
  (cross_attention): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
  )
  (compatibility_head): Sequential(
    (0): Linear(in_features=512, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.2, inplace=False)
    (3): Linear(in_features=256, out_features=64, bias=True)
    (4): GELU(approximate='none')
    (5): Linear(in_features=64, out_features=1, bias=True)
    (6): Sigmoid()
  )
)

In [18]:
batch_size = 4

test_users = torch.randn(
    batch_size, 662, device=device
)

test_products = torch.randn(
    batch_size, 662, device=device
)

with torch.no_grad():
    scores, attention = model(
        test_users,
        test_products
    )

print("User input shape    :", test_users.shape)
print("Product input shape :", test_products.shape)
print("Score shape         :", scores.shape)
print("Attention shape     :", attention.shape)
print("Device              :", scores.device)
print("Scores              :", scores.squeeze(-1).cpu().numpy())

User input shape    : torch.Size([4, 662])
Product input shape : torch.Size([4, 662])
Score shape         : torch.Size([4, 1])
Attention shape     : torch.Size([4, 1, 1])
Device              : mps:0
Scores              : [0.5284728 0.5446233 0.5310816 0.5352735]

In [19]:
criterion = nn.BCELoss()

print("Loss function:", criterion)

Loss function: BCELoss()

In [20]:
import json
import random
import re
from pathlib import Path
from collections import defaultdict

import pandas as pd
import numpy as np

# ============================================================
# VIBE DATASET
# ============================================================

VIBE_ROOT = Path.home() / "Desktop/Projects/weavly/core-model/VIBE/dataset"

HUMANS_FILE = VIBE_ROOT / "humans/model.json"
MODEL_MEASUREMENT_DIR = VIBE_ROOT / "tops/model_measurement"
GARMENT_MEASUREMENT_DIR = VIBE_ROOT / "tops/garment_measurement"

# ------------------------------------------------------------
# Load human profiles
# ------------------------------------------------------------

with open(HUMANS_FILE) as f:
    humans = json.load(f)

print("Human profiles:", len(humans))


# ------------------------------------------------------------
# Helper: convert "92cm" -> 92.0
# ------------------------------------------------------------

def parse_measurement(value):
    if value is None:
        return None

    match = re.search(r"[-+]?\d*\.?\d+", str(value))

    if match:
        return float(match.group())

    return None


# ------------------------------------------------------------
# Load garment measurements
# ------------------------------------------------------------

garment_measurements = {}

for file in GARMENT_MEASUREMENT_DIR.glob("*.txt"):

    with open(file) as f:
        data = json.load(f)

    if not data:
        continue

    product_id = file.stem.replace("_meta", "")

    measurements = {}

    # JSON structure:
    # {"12": [{"dimension_name": "...", "value": "..."}]}

    for entries in data.values():

        for item in entries:

            name = item["dimension_name"].lower()
            value = parse_measurement(item["value"])

            if value is None:
                continue

            if "bust" in name:
                measurements["garment_bust"] = value

            elif name == "waist":
                measurements["garment_waist"] = value

            elif name == "hip":
                measurements["garment_hip"] = value

            elif "shoulder to hem" in name:
                measurements["garment_length"] = value

            elif "sleeve length" in name:
                measurements["garment_sleeve"] = value

    garment_measurements[product_id] = measurements


print("Garments with measurements:", len(garment_measurements))


# ------------------------------------------------------------
# Build POSITIVE person × garment pairs
# ------------------------------------------------------------

positive_pairs = []

for file in MODEL_MEASUREMENT_DIR.glob("*.txt"):

    with open(file) as f:
        data = json.load(f)

    product_id = file.stem.replace("_meta", "")

    # Skip garments without measurement information
    if product_id not in garment_measurements:
        continue

    for person_id in data:

        # Only users with a valid human profile
        if person_id not in humans:
            continue

        human = humans[person_id]
        garment = garment_measurements[product_id]

        positive_pairs.append({
            "person_id": person_id,
            "product_id": product_id,

            "height": parse_measurement(human.get("height")),
            "bust": parse_measurement(human.get("bust")),
            "waist": parse_measurement(human.get("waist")),
            "hips": parse_measurement(human.get("hips")),
            "model_size": data[person_id].get("size"),

            "garment_bust": garment.get("garment_bust"),
            "garment_waist": garment.get("garment_waist"),
            "garment_hip": garment.get("garment_hip"),
            "garment_length": garment.get("garment_length"),
            "garment_sleeve": garment.get("garment_sleeve"),

            "label": 1
        })


positive_df = pd.DataFrame(positive_pairs)

print("\nPositive compatibility dataset")
print("--------------------------------")
print("Rows:", len(positive_df))
print("Columns:", len(positive_df.columns))

display(positive_df.head())

Human profiles: 61

AttributeError: 'str' object has no attribute 'values'

In [21]:
import json
import re
from pathlib import Path
import pandas as pd

VIBE_ROOT = Path.home() / "Desktop/Projects/weavly/core-model/VIBE/dataset"

HUMANS_FILE = VIBE_ROOT / "humans/model.json"
MODEL_MEASUREMENT_DIR = VIBE_ROOT / "tops/model_measurement"
GARMENT_MEASUREMENT_DIR = VIBE_ROOT / "tops/garment_measurement"


# ============================================================
# LOAD HUMANS
# ============================================================

with open(HUMANS_FILE) as f:
    humans = json.load(f)

print("Human profiles:", len(humans))


# ============================================================
# MEASUREMENT PARSER
# ============================================================

def parse_measurement(value):
    if value is None:
        return None

    match = re.search(r"[-+]?\d*\.?\d+", str(value))

    return float(match.group()) if match else None


# ============================================================
# LOAD GARMENT MEASUREMENTS
# ============================================================

garment_measurements = {}
invalid_files = []

for file in GARMENT_MEASUREMENT_DIR.glob("*.txt"):

    try:
        with open(file) as f:
            data = json.load(f)

        # Some files contain JSON encoded as a string
        if isinstance(data, str):
            data = json.loads(data)

        if not isinstance(data, dict):
            invalid_files.append(file.name)
            continue

        product_id = file.stem.replace("_meta", "")

        measurements = {}

        for entries in data.values():

            if not isinstance(entries, list):
                continue

            for item in entries:

                if not isinstance(item, dict):
                    continue

                name = str(item.get("dimension_name", "")).lower()
                value = parse_measurement(item.get("value"))

                if value is None:
                    continue

                if "bust" in name:
                    measurements["garment_bust"] = value

                elif name == "waist":
                    measurements["garment_waist"] = value

                elif "hip" in name:
                    measurements["garment_hip"] = value

                elif "shoulder to hem" in name:
                    measurements["garment_length"] = value

                elif "sleeve length" in name:
                    measurements["garment_sleeve"] = value

        if measurements:
            garment_measurements[product_id] = measurements

    except Exception:
        invalid_files.append(file.name)


print("Garments with measurements:", len(garment_measurements))
print("Invalid files:", len(invalid_files))


# ============================================================
# BUILD POSITIVE PAIRS
# ============================================================

positive_pairs = []

for file in MODEL_MEASUREMENT_DIR.glob("*.txt"):

    try:
        with open(file) as f:
            data = json.load(f)

        if isinstance(data, str):
            data = json.loads(data)

        if not isinstance(data, dict):
            continue

        product_id = file.stem.replace("_meta", "")

        # Need garment measurements
        if product_id not in garment_measurements:
            continue

        garment = garment_measurements[product_id]

        for person_id, pair_data in data.items():

            # Must have human profile
            if person_id not in humans:
                continue

            human = humans[person_id]

            positive_pairs.append({

                "person_id": person_id,
                "product_id": product_id,

                # Human measurements
                "height": parse_measurement(human.get("height")),
                "bust": parse_measurement(human.get("bust")),
                "waist": parse_measurement(human.get("waist")),
                "hips": parse_measurement(human.get("hips")),

                # Size worn by model
                "model_size": (
                    pair_data.get("size")
                    if isinstance(pair_data, dict)
                    else None
                ),

                # Garment measurements
                "garment_bust": garment.get("garment_bust"),
                "garment_waist": garment.get("garment_waist"),
                "garment_hip": garment.get("garment_hip"),
                "garment_length": garment.get("garment_length"),
                "garment_sleeve": garment.get("garment_sleeve"),

                "label": 1
            })

positive_df = pd.DataFrame(positive_pairs)


# ============================================================
# SUMMARY
# ============================================================

print("\n================================")
print("VIBE POSITIVE DATASET")
print("================================")

print("Rows    :", len(positive_df))
print("Columns :", len(positive_df.columns))

display(positive_df.head(10))

SyntaxError: expected 'except' or 'finally' block (3982246944.py, line 165)

In [23]:
import json
import re
from pathlib import Path
import pandas as pd

VIBE_ROOT = Path.home() / "Desktop/Projects/weavly/core-model/VIBE/dataset"

HUMANS_FILE = VIBE_ROOT / "humans/model.json"
MODEL_DIR = VIBE_ROOT / "tops/model_measurement"
GARMENT_DIR = VIBE_ROOT / "tops/garment_measurement"


def parse_measurement(value):
    if value is None:
        return None

    match = re.search(r"[-+]?\d*\.?\d+", str(value))
    return float(match.group()) if match else None


def load_json_file(path):
    """Safely load a VIBE JSON/TXT file."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = f.read().strip()

        if not raw:
            return None

        data = json.loads(raw)

        # Some files contain JSON encoded as a string
        if isinstance(data, str):
            try:
                data = json.loads(data)
            except json.JSONDecodeError:
                return None

        return data

    except (json.JSONDecodeError, UnicodeDecodeError, OSError):
        return None


# ============================================================
# HUMANS
# ============================================================

humans = load_json_file(HUMANS_FILE)

print("Human profiles:", len(humans))


# ============================================================
# GARMENT MEASUREMENTS
# ============================================================

garment_measurements = {}
invalid_garments = []

for file in GARMENT_DIR.glob("*.txt"):

    data = load_json_file(file)

    if not isinstance(data, dict):
        invalid_garments.append(file.name)
        continue

    product_id = file.stem.replace("_meta", "")

    measurements = {}

    for entries in data.values():

        if not isinstance(entries, list):
            continue

        for item in entries:

            if not isinstance(item, dict):
                continue

            name = str(item.get("dimension_name", "")).lower()
            value = parse_measurement(item.get("value"))

            if value is None:
                continue

            if "bust" in name:
                measurements["garment_bust"] = value

            elif name == "waist":
                measurements["garment_waist"] = value

            elif "hip" in name:
                measurements["garment_hip"] = value

            elif "shoulder to hem" in name:
                measurements["garment_length"] = value

            elif "sleeve length" in name:
                measurements["garment_sleeve"] = value

    if measurements:
        garment_measurements[product_id] = measurements


print("Garments with measurements:", len(garment_measurements))
print("Invalid/empty garment files:", len(invalid_garments))


# ============================================================
# POSITIVE PAIRS
# ============================================================

positive_pairs = []
invalid_model_files = []

for file in MODEL_DIR.glob("*.txt"):

    data = load_json_file(file)

    if not isinstance(data, dict):
        invalid_model_files.append(file.name)
        continue

    product_id = file.stem.replace("_meta", "")

    if product_id not in garment_measurements:
        continue

    garment = garment_measurements[product_id]

    for person_id, pair_data in data.items():

        if person_id not in humans:
            continue

        human = humans[person_id]

        positive_pairs.append({
            "person_id": person_id,
            "product_id": product_id,

            "height": parse_measurement(human.get("height")),
            "bust": parse_measurement(human.get("bust")),
            "waist": parse_measurement(human.get("waist")),
            "hips": parse_measurement(human.get("hips")),

            "model_size": (
                pair_data.get("size")
                if isinstance(pair_data, dict)
                else None
            ),

            "garment_bust": garment.get("garment_bust"),
            "garment_waist": garment.get("garment_waist"),
            "garment_hip": garment.get("garment_hip"),
            "garment_length": garment.get("garment_length"),
            "garment_sleeve": garment.get("garment_sleeve"),

            "label": 1
        })


positive_df = pd.DataFrame(positive_pairs)


# ============================================================
# SUMMARY
# ============================================================

print("\n================================")
print("VIBE POSITIVE DATASET")
print("================================")

print("Positive pairs :", len(positive_df))
print("Columns        :", len(positive_df.columns))
print("Invalid garment files:", len(invalid_garments))
print("Invalid model files  :", len(invalid_model_files))

display(positive_df.head(10))

Human profiles: 61
Garments with measurements: 897
Invalid/empty garment files: 126

================================
VIBE POSITIVE DATASET
================================
Positive pairs : 2761
Columns        : 13
Invalid garment files: 126
Invalid model files  : 0

,person_id,product_id,height,bust,waist,hips,model_size,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve,label
0,Ljubenka,long-sleeve-tee-2#NavyWhite,180.0,104.0,96.0,121.0,16,92.0,88.0,102.0,64.0,66.0,1
1,Laura,long-sleeve-tee-2#NavyWhite,177.0,101.0,76.0,107.0,12,92.0,88.0,102.0,64.0,66.0,1
2,Georgia,runaway-top#Sand,170.0,81.0,61.0,89.0,10,118.0,NaN,138.0,50.0,NaN,1
3,Jess,runaway-top#Sand,176.0,99.0,78.0,112.0,14,118.0,NaN,138.0,50.0,NaN,1
4,Ljubenka,runaway-top#Sand,180.0,104.0,96.0,121.0,18,118.0,NaN,138.0,50.0,NaN,1
5,Marnee,runaway-top#Sand,178.0,81.0,64.0,89.0,10,118.0,NaN,138.0,50.0,NaN,1
6,Laura,runaway-top#Sand,177.0,101.0,76.0,107.0,12,118.0,NaN,138.0,50.0,NaN,1
7,Kate,runaway-top#Sand,180.0,104.0,81.0,119.0,16,118.0,NaN,138.0,50.0,NaN,1
8,Nadine,runaway-top#Sand,167.0,88.0,73.0,94.0,10,118.0,NaN,138.0,50.0,NaN,1
9,Olivia,runaway-top#Sand,178.0,98.0,82.0,102.0,12,118.0,NaN,138.0,50.0,NaN,1

In [24]:
print("Missing values:")
display(positive_df.isna().sum())

print("\nMissing percentage:")
display(
    (positive_df.isna().mean() * 100)
    .round(2)
    .sort_values(ascending=False)
)

print("\nUnique people:", positive_df["person_id"].nunique())
print("Unique garments:", positive_df["product_id"].nunique())

Missing values:

person_id           0
product_id          0
height              0
bust                0
waist               0
hips                0
model_size          0
garment_bust      145
garment_waist     661
garment_hip       436
garment_length     24
garment_sleeve    432
label               0
dtype: int64

Missing percentage:

garment_waist     23.94
garment_hip       15.79
garment_sleeve    15.65
garment_bust       5.25
garment_length     0.87
person_id          0.00
product_id         0.00
height             0.00
bust               0.00
waist              0.00
hips               0.00
model_size         0.00
label              0.00
dtype: float64

Unique people: 52
Unique garments: 859

In [25]:
fit_df = positive_df.copy()

# Body ↔ garment differences
fit_df["bust_ease"] = (
    fit_df["garment_bust"] - fit_df["bust"]
)

fit_df["waist_ease"] = (
    fit_df["garment_waist"] - fit_df["waist"]
)

fit_df["hip_ease"] = (
    fit_df["garment_hip"] - fit_df["hips"]
)

# Proportional length
fit_df["length_height_ratio"] = (
    fit_df["garment_length"] / fit_df["height"]
)

# Missing-value indicators
fit_df["has_garment_bust"] = fit_df["garment_bust"].notna().astype(float)
fit_df["has_garment_waist"] = fit_df["garment_waist"].notna().astype(float)
fit_df["has_garment_hip"] = fit_df["garment_hip"].notna().astype(float)
fit_df["has_garment_length"] = fit_df["garment_length"].notna().astype(float)
fit_df["has_garment_sleeve"] = fit_df["garment_sleeve"].notna().astype(float)

print("Derived compatibility features created.")

display(
    fit_df[
        [
            "person_id",
            "product_id",
            "bust_ease",
            "waist_ease",
            "hip_ease",
            "length_height_ratio",
            "label"
        ]
    ].head(10)
)

Derived compatibility features created.

,person_id,product_id,bust_ease,waist_ease,hip_ease,length_height_ratio,label
0,Ljubenka,long-sleeve-tee-2#NavyWhite,-12.0,-8.0,-19.0,0.355556,1
1,Laura,long-sleeve-tee-2#NavyWhite,-9.0,12.0,-5.0,0.361582,1
2,Georgia,runaway-top#Sand,37.0,NaN,49.0,0.294118,1
3,Jess,runaway-top#Sand,19.0,NaN,26.0,0.284091,1
4,Ljubenka,runaway-top#Sand,14.0,NaN,17.0,0.277778,1
5,Marnee,runaway-top#Sand,37.0,NaN,49.0,0.280899,1
6,Laura,runaway-top#Sand,17.0,NaN,31.0,0.282486,1
7,Kate,runaway-top#Sand,14.0,NaN,19.0,0.277778,1
8,Nadine,runaway-top#Sand,30.0,NaN,44.0,0.299401,1
9,Olivia,runaway-top#Sand,20.0,NaN,36.0,0.280899,1

In [26]:
print("=== Derived feature statistics ===")

cols = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "length_height_ratio",
    "garment_sleeve",
]

display(
    fit_df[cols].describe().T
)

print("\n=== Missing derived features ===")

display(
    fit_df[cols].isna().sum()
)

=== Derived feature statistics ===

,count,mean,std,min,25%,50%,75%,max
bust_ease,2616.0,31.804472,24.682180,-89.000000,16.000000,29.000000,44.000000,159.00000
waist_ease,2100.0,51.776429,91.695731,-63.000000,31.000000,43.000000,58.000000,1120.00000
hip_ease,2325.0,30.369032,42.253550,-100.000000,13.000000,27.000000,45.000000,1141.00000
length_height_ratio,2737.0,0.426754,0.089440,0.262857,0.372222,0.405556,0.450867,0.78125
garment_sleeve,2329.0,55.558609,19.597455,6.000000,42.000000,63.000000,71.000000,133.00000

=== Missing derived features ===

bust_ease              145
waist_ease             661
hip_ease               436
length_height_ratio     24
garment_sleeve         432
dtype: int64

In [27]:
# ============================================================
# INVESTIGATE EXTREME MEASUREMENT VALUES
# ============================================================

print("=== Extreme waist ease ===")

display(
    fit_df[
        fit_df["waist_ease"].abs() > 150
    ][
        [
            "person_id",
            "product_id",
            "waist",
            "garment_waist",
            "waist_ease",
            "label"
        ]
    ].sort_values(
        "waist_ease",
        key=lambda x: x.abs(),
        ascending=False
    ).head(30)
)


print("\n=== Extreme hip ease ===")

display(
    fit_df[
        fit_df["hip_ease"].abs() > 150
    ][
        [
            "person_id",
            "product_id",
            "hips",
            "garment_hip",
            "hip_ease",
            "label"
        ]
    ].sort_values(
        "hip_ease",
        key=lambda x: x.abs(),
        ascending=False
    ).head(30)
)


print("\n=== Extreme bust ease ===")

display(
    fit_df[
        fit_df["bust_ease"].abs() > 150
    ][
        [
            "person_id",
            "product_id",
            "bust",
            "garment_bust",
            "bust_ease",
            "label"
        ]
    ].sort_values(
        "bust_ease",
        key=lambda x: x.abs(),
        ascending=False
    ).head(30)
)

=== Extreme waist ease ===

,person_id,product_id,waist,garment_waist,waist_ease,label
38,Georgia,sugar-snaps-throw-jacket#Black,61.0,1181.0,1120.0,1
114,Georgia,sugar-snaps-throw-jacket#Duckegg,61.0,1181.0,1120.0,1
1441,Georgia,sugar-snaps-throw-jacket#White,61.0,1181.0,1120.0,1
36,Marnee,sugar-snaps-throw-jacket#Black,64.0,1181.0,1117.0,1
112,Marnee,sugar-snaps-throw-jacket#Duckegg,64.0,1181.0,1117.0,1
1439,Marnee,sugar-snaps-throw-jacket#White,64.0,1181.0,1117.0,1
39,Fiona,sugar-snaps-throw-jacket#Black,83.0,1181.0,1098.0,1
115,Fiona,sugar-snaps-throw-jacket#Duckegg,83.0,1181.0,1098.0,1
1442,Fiona,sugar-snaps-throw-jacket#White,83.0,1181.0,1098.0,1
37,Sophia,sugar-snaps-throw-jacket#Black,87.0,1181.0,1094.0,1
113,Sophia,sugar-snaps-throw-jacket#Duckegg,87.0,1181.0,1094.0,1
1440,Sophia,sugar-snaps-throw-jacket#White,87.0,1181.0,1094.0,1
40,Lauren,sugar-snaps-throw-jacket#Black,88.0,1181.0,1093.0,1
116,Lauren,sugar-snaps-throw-jacket#Duckegg,88.0,1181.0,1093.0,1
1443,Lauren,sugar-snaps-throw-jacket#White,88.0,1181.0,1093.0,1

=== Extreme hip ease ===

,person_id,product_id,hips,garment_hip,hip_ease,label
1129,Madeline,llama-long-sleeve-shirt#Mustard,89.0,1230.0,1141.0,1
1130,Stacey,llama-long-sleeve-shirt#Mustard,98.0,1230.0,1132.0,1
1505,Summer,hem-frill-stripe-top#SoFrilled,96.0,290.0,194.0,1
2003,Summer,hem-frill-stripe-top#Frilled,96.0,290.0,194.0,1
1503,Jess,hem-frill-stripe-top#SoFrilled,112.0,290.0,178.0,1
2001,Jess,hem-frill-stripe-top#Frilled,112.0,290.0,178.0,1
1504,Fiona,hem-frill-stripe-top#SoFrilled,115.0,290.0,175.0,1
2002,Fiona,hem-frill-stripe-top#Frilled,115.0,290.0,175.0,1

=== Extreme bust ease ===

,person_id,product_id,bust,garment_bust,bust_ease,label
1420,Alex,viola-kimono-radiant-floral#Grey,81.0,240.0,159.0,1

In [28]:
# ============================================================
# FIND SUSPICIOUS GARMENT MEASUREMENTS
# ============================================================

measurement_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

print("Suspicious garment measurements")
print("================================")

for col in measurement_cols:

    suspicious = positive_df[
        positive_df[col].notna() &
        ((positive_df[col] < 20) | (positive_df[col] > 200))
    ]

    print(f"\n{col}")
    print("Rows:", len(suspicious))

    if len(suspicious) > 0:
        display(
            suspicious[
                ["product_id", col]
            ].drop_duplicates().sort_values(col)
        )

Suspicious garment measurements
================================

garment_bust
Rows: 69

                            product_id  garment_bust
772         stripe-me-happy-blouse#Ash          12.0
158          the-half-sleeve-tee#White         201.0
1458         the-half-sleeve-tee#Black         201.0
1142             the-oversize-knit#Ink         204.0
1204       the-oversize-knit#GreyMarle         204.0
2010         makeover-blouse#LimeGreen         204.0
184         the-batwing-tee#FrenchBlue         205.0
832                the-batwing-tee#Sea         205.0
1915             the-batwing-tee#Black         205.0
2139             the-batwing-tee#Stone         205.0
148             beach-walk-shirt#Khaki         208.0
1033           beach-walk-shirt#Stormy         208.0
1215  on-the-horizon-swing-top-1#Khaki         215.0
2409            on-safari-blouse#Jewel         220.0
1420  viola-kimono-radiant-floral#Grey         240.0

garment_waist
Rows: 19

                            product_id  garment_waist
2132                  cara-tee-2#Blush           11.0
2302               cara-tee-2#WhiteBlk           11.0
2573              cara-tee-2#BlackSpot           11.0
2010         makeover-blouse#LimeGreen          204.0
36      sugar-snaps-throw-jacket#Black         1181.0
112   sugar-snaps-throw-jacket#Duckegg         1181.0
1439    sugar-snaps-throw-jacket#White         1181.0

garment_hip
Rows: 37

                            product_id  garment_hip
164         the-cross-over-poncho#Grey         15.0
433         the-cross-over-poncho#Navy         15.0
150         sunshine-in-me-tee-1#White        201.0
1293    sunshine-in-me-tee-1#GreyMarle        201.0
2233      soho-v-neck-blouse#SohoPrint        202.0
2010         makeover-blouse#LimeGreen        204.0
411             tuck-layer-shirt#White        206.0
1215  on-the-horizon-swing-top-1#Khaki        213.0
1950    the-button-up-swing-tunic#Wine        217.0
1644            belle-mesh-cardi#Black        229.0
1503    hem-frill-stripe-top#SoFrilled        290.0
2001      hem-frill-stripe-top#Frilled        290.0
1129   llama-long-sleeve-shirt#Mustard       1230.0

garment_length
Rows: 0

garment_sleeve
Rows: 157

                                            product_id  garment_sleeve
587                           layered-tunic-1#PalePink             6.0
824                            layered-tunic-1#Natural             6.0
792                              layered-tunic-1#White             6.0
610                            haze-swing-top#OffWhite             6.0
2375  reversible-stripe-vee-scoop-neck-tank#BlackWhite             7.0
2730                                  saba-top-2#Catus             7.0
327                            capri-tank-3#NavyStripe             8.0
2475                                capri-tank-3#White             8.0
472                    bora-bora-layered-tank#BoraBora             8.0
1336                                 capri-tank-3#Navy             8.0
1058                                capri-tank-3#Black             8.0
2186                           capri-tank-6#HeatheGrey             9.0
1540                                capri-tank-6#Olive             9.0
2454                             capri-tank-6#ClaySpot             9.0
2507                   the-printed-v-split-top#Natural            10.0
2720            the-sleeveless-cross-over-blouse#Black            11.0
2075               the-design-fold-tunic-top#PearlBlue            11.0
2523         sugar-snaps-round-neck-layer-tank#DuckEgg            11.0
2624         the-sleeveless-cross-over-blouse#Sunshine            11.0
1396           sugar-snaps-round-neck-layer-tank#Black            11.0
1338            the-sleeveless-cross-over-blouse#White            11.0
1261           the-sleeveless-cross-over-blouse#Salmon            11.0
813            the-sleeveless-cross-over-blouse#Cobalt            11.0
119            sugar-snaps-round-neck-layer-tank#White            11.0
400              the-sleeveless-cross-over-blouse#Mint            11.0
498          the-sleeveless-cross-over-blouse#Chambray            11.0
995                              shirt-in-a-box#Silver            12.0
831                      linen-v-neck-cami-2#BlueWhite            12.0
1999                           the-swing-tank-top#Rose            12.0
1015         belle-handkerchief-printed-cami#RustFlwrs            13.0
202               the-roll-neck-sleeveless-top-1#Black            13.0
1101                             karmen-top#HighRiskRe            13.0
2571                             icing-sugar-top#Ivory            14.0
774                   the-asymmetrical-tank-top#Indigo            14.0
2643                           the-tie-front-tank#Navy            14.0
1724                          the-tie-front-tank#White            14.0
125                  the-asymmetrical-tank-top#HotPink            14.0
2712                                layered-top-2#Navy            15.0
2635                               layered-top-2#White            15.0
2369               belle-square-neck-drape-tee#Vanilla            16.0
2291                 reversible-scoopv-neck-tank#White            17.0
2056                  reversible-scoopv-neck-tank#Navy            17.0
966                  reversible-scoopv-neck-tank#Black            17.0
207                                   analia-top#White            18.0
205                           freya-fringe-blouse#Navy            18.0
100                                   paradise-top#Red            18.0

In [29]:
# ============================================================
# CLEAN RAW GARMENT MEASUREMENTS
# ============================================================

clean_df = positive_df.copy()

body_garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
]

for col in body_garment_cols:

    invalid = (
        clean_df[col].notna()
        & (
            (clean_df[col] < 20)
            | (clean_df[col] > 200)
        )
    )

    print(f"{col}: {invalid.sum()} invalid values")

    clean_df.loc[invalid, col] = np.nan


# ============================================================
# RECALCULATE DERIVED FEATURES
# ============================================================

clean_df["bust_ease"] = (
    clean_df["garment_bust"] - clean_df["bust"]
)

clean_df["waist_ease"] = (
    clean_df["garment_waist"] - clean_df["waist"]
)

clean_df["hip_ease"] = (
    clean_df["garment_hip"] - clean_df["hips"]
)

clean_df["length_height_ratio"] = (
    clean_df["garment_length"] / clean_df["height"]
)


# ============================================================
# CHECK NEW DISTRIBUTIONS
# ============================================================

print("\n=== CLEANED FEATURE STATISTICS ===")

display(
    clean_df[
        [
            "bust_ease",
            "waist_ease",
            "hip_ease",
            "length_height_ratio",
            "garment_sleeve",
        ]
    ].describe().T
)

garment_bust: 69 invalid values
garment_waist: 19 invalid values
garment_hip: 37 invalid values

=== CLEANED FEATURE STATISTICS ===

,count,mean,std,min,25%,50%,75%,max
bust_ease,2547.0,29.724382,20.702248,-44.000000,16.000000,28.000000,43.000000,115.00000
waist_ease,2081.0,44.304901,20.407181,-63.000000,31.000000,43.000000,57.000000,130.00000
hip_ease,2288.0,28.698427,24.011297,-53.000000,13.000000,27.000000,45.000000,110.00000
length_height_ratio,2737.0,0.426754,0.089440,0.262857,0.372222,0.405556,0.450867,0.78125
garment_sleeve,2329.0,55.558609,19.597455,6.000000,42.000000,63.000000,71.000000,133.00000

In [30]:
import random

random.seed(42)

# ============================================================
# BUILD POSITIVE LOOKUP
# ============================================================

person_positive_products = (
    clean_df
    .groupby("person_id")["product_id"]
    .apply(set)
    .to_dict()
)

all_products = set(clean_df["product_id"].unique())

print("People:", len(person_positive_products))
print("Garments:", len(all_products))


# ============================================================
# POSITIVE DATA
# ============================================================

positive_training = clean_df.copy()


# ============================================================
# BUILD NEGATIVE PAIRS
# ============================================================

negative_rows = []

for person_id, positive_products in person_positive_products.items():

    candidates = list(all_products - positive_products)

    random.shuffle(candidates)

    # Balanced 1:1 negatives
    n_negative = min(
        len(positive_products),
        len(candidates)
    )

    selected = candidates[:n_negative]

    # Get person's body measurements
    person_rows = clean_df[
        clean_df["person_id"] == person_id
    ]

    person_info = person_rows.iloc[0]

    for product_id in selected:

        # Find garment measurements
        product_row = clean_df[
            clean_df["product_id"] == product_id
        ].iloc[0]

        row = {
            "person_id": person_id,
            "product_id": product_id,

            "height": person_info["height"],
            "bust": person_info["bust"],
            "waist": person_info["waist"],
            "hips": person_info["hips"],

            "model_size": np.nan,

            "garment_bust": product_row["garment_bust"],
            "garment_waist": product_row["garment_waist"],
            "garment_hip": product_row["garment_hip"],
            "garment_length": product_row["garment_length"],
            "garment_sleeve": product_row["garment_sleeve"],

            "label": 0,
        }

        negative_rows.append(row)


negative_df = pd.DataFrame(negative_rows)


# ============================================================
# DERIVED FEATURES
# ============================================================

negative_df["bust_ease"] = (
    negative_df["garment_bust"]
    - negative_df["bust"]
)

negative_df["waist_ease"] = (
    negative_df["garment_waist"]
    - negative_df["waist"]
)

negative_df["hip_ease"] = (
    negative_df["garment_hip"]
    - negative_df["hips"]
)

negative_df["length_height_ratio"] = (
    negative_df["garment_length"]
    / negative_df["height"]
)


# ============================================================
# COMBINE
# ============================================================

training_df = pd.concat(
    [positive_training, negative_df],
    ignore_index=True
)

training_df = training_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)


# ============================================================
# SUMMARY
# ============================================================

print("\n================================")
print("V2 COMPATIBILITY DATASET")
print("================================")

print("Positive:", (training_df["label"] == 1).sum())
print("Negative:", (training_df["label"] == 0).sum())
print("Total   :", len(training_df))

print(
    "\nUnique people:",
    training_df["person_id"].nunique()
)

print(
    "Unique garments:",
    training_df["product_id"].nunique()
)

display(training_df.head(10))

People: 52
Garments: 859

================================
V2 COMPATIBILITY DATASET
================================
Positive: 2761
Negative: 2761
Total   : 5522

Unique people: 52
Unique garments: 859

,person_id,product_id,height,bust,waist,hips,model_size,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve,label,bust_ease,waist_ease,hip_ease,length_height_ratio
0,Mae-Lee,softly-swinging-bamboo-tee#Blush,173.0,114.0,94.0,119.0,16,109.0,120.0,164.0,77.0,32.0,1,-5.0,26.0,45.0,0.445087
1,Mae-Lee,the-long-sleeve-v-neck-tee#White,173.0,114.0,94.0,119.0,16,116.0,86.0,92.0,75.0,78.0,1,2.0,-8.0,-27.0,0.433526
2,Jess,rory-spliced-zip-hoodie#Silver,176.0,99.0,78.0,112.0,NaN,108.0,108.0,106.0,63.0,73.0,0,9.0,30.0,-6.0,0.357955
3,Amanda,the-check-pullover#PinkCheck,178.0,86.0,67.0,89.0,10,177.0,173.0,177.0,67.0,60.0,1,91.0,106.0,88.0,0.376404
4,Summer,layered-tee-2#Black,176.0,84.0,64.0,96.0,S,108.0,112.0,122.0,68.0,69.0,1,24.0,48.0,26.0,0.386364
5,Summer,animal-button-up-shirt#KhakiPrint,176.0,84.0,64.0,96.0,NaN,108.0,NaN,116.0,70.0,70.0,0,24.0,NaN,20.0,0.397727
6,Madeline,natural-overlay-knit#Greybloss,179.0,84.0,61.0,89.0,S,136.0,NaN,136.0,70.0,68.0,1,52.0,NaN,47.0,0.391061
7,Mae-Lee,agra-shirt#White,173.0,114.0,94.0,119.0,XXL,110.0,120.0,124.0,62.0,63.0,1,-4.0,26.0,5.0,0.358382
8,Olivia,belle-half-sleeve-forgiver-tunic#FlamPink,178.0,98.0,82.0,102.0,NaN,127.0,117.0,125.0,84.0,52.0,0,29.0,35.0,23.0,0.471910
9,Georgia,the-wrap-jersey-top#NavyWhite,170.0,81.0,61.0,89.0,NaN,114.0,100.0,115.0,70.0,77.0,0,33.0,39.0,26.0,0.411765

In [31]:
from sklearn.model_selection import train_test_split

# ============================================================
# PERSON-LEVEL SPLIT
# ============================================================

people = training_df["person_id"].unique()

train_people, temp_people = train_test_split(
    people,
    test_size=0.30,
    random_state=42
)

val_people, test_people = train_test_split(
    temp_people,
    test_size=0.50,
    random_state=42
)

train_df = training_df[
    training_df["person_id"].isin(train_people)
].copy()

val_df = training_df[
    training_df["person_id"].isin(val_people)
].copy()

test_df = training_df[
    training_df["person_id"].isin(test_people)
].copy()


# ============================================================
# VERIFY NO PERSON LEAKAGE
# ============================================================

assert set(train_people).isdisjoint(set(val_people))
assert set(train_people).isdisjoint(set(test_people))
assert set(val_people).isdisjoint(set(test_people))


# ============================================================
# SUMMARY
# ============================================================

print("================================")
print("PERSON-LEVEL DATASET SPLIT")
print("================================")

print("\nPeople")
print("Train:", len(train_people))
print("Val  :", len(val_people))
print("Test :", len(test_people))

print("\nRows")
print("Train:", len(train_df))
print("Val  :", len(val_df))
print("Test :", len(test_df))

print("\nLabels")

print("\nTrain:")
print(train_df["label"].value_counts())

print("\nValidation:")
print(val_df["label"].value_counts())

print("\nTest:")
print(test_df["label"].value_counts())

print("\nLeakage check:")
print("Train ∩ Val :", set(train_people) & set(val_people))
print("Train ∩ Test:", set(train_people) & set(test_people))
print("Val ∩ Test  :", set(val_people) & set(test_people))

================================
PERSON-LEVEL DATASET SPLIT
================================

People
Train: 36
Val  : 8
Test : 8

Rows
Train: 3594
Val  : 686
Test : 1242

Labels

Train:
label
1    1797
0    1797
Name: count, dtype: int64

Validation:
label
1    343
0    343
Name: count, dtype: int64

Test:
label
1    621
0    621
Name: count, dtype: int64

Leakage check:
Train ∩ Val : set()
Train ∩ Test: set()
Val ∩ Test  : set()

In [32]:
import torch
import numpy as np

# ============================================================
# V2 EXPLICIT COMPATIBILITY FEATURES
# ============================================================

FEATURE_COLUMNS = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",
    "length_height_ratio",

    "has_garment_bust",
    "has_garment_waist",
    "has_garment_hip",
    "has_garment_length",
    "has_garment_sleeve",
]


# ============================================================
# ADD MISSINGNESS FLAGS
# ============================================================

def prepare_features(df):

    result = df.copy()

    result["has_garment_bust"] = (
        result["garment_bust"].notna().astype(float)
    )

    result["has_garment_waist"] = (
        result["garment_waist"].notna().astype(float)
    )

    result["has_garment_hip"] = (
        result["garment_hip"].notna().astype(float)
    )

    result["has_garment_length"] = (
        result["garment_length"].notna().astype(float)
    )

    result["has_garment_sleeve"] = (
        result["garment_sleeve"].notna().astype(float)
    )

    return result


train_df = prepare_features(train_df)
val_df = prepare_features(val_df)
test_df = prepare_features(test_df)


# ============================================================
# CONVERT TO NUMERIC MATRICES
# ============================================================

def dataframe_to_tensor(df):

    X = (
        df[FEATURE_COLUMNS]
        .astype(float)
        .fillna(0.0)
        .to_numpy(dtype=np.float32)
    )

    y = (
        df["label"]
        .to_numpy(dtype=np.float32)
        .reshape(-1, 1)
    )

    return (
        torch.tensor(X),
        torch.tensor(y)
    )


X_train, y_train = dataframe_to_tensor(train_df)
X_val, y_val = dataframe_to_tensor(val_df)
X_test, y_test = dataframe_to_tensor(test_df)


# ============================================================
# DEVICE
# ============================================================

device = torch.device(
    "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)


X_train = X_train.to(device)
y_train = y_train.to(device)

X_val = X_val.to(device)
y_val = y_val.to(device)

X_test = X_test.to(device)
y_test = y_test.to(device)


# ============================================================
# VERIFY
# ============================================================

print("================================")
print("V2 COMPATIBILITY TENSORS")
print("================================")

print("Feature dimension :", X_train.shape[1])

print("\nTrain:")
print("X:", X_train.shape)
print("y:", y_train.shape)

print("\nValidation:")
print("X:", X_val.shape)
print("y:", y_val.shape)

print("\nTest:")
print("X:", X_test.shape)
print("y:", y_test.shape)

print("\nDevice:", device)

print("\nNaN:")
print("Train:", torch.isnan(X_train).sum().item())
print("Val  :", torch.isnan(X_val).sum().item())
print("Test :", torch.isnan(X_test).sum().item())

print("\nInf:")
print("Train:", torch.isinf(X_train).sum().item())
print("Val  :", torch.isinf(X_val).sum().item())
print("Test :", torch.isinf(X_test).sum().item())

================================
V2 COMPATIBILITY TENSORS
================================
Feature dimension : 18

Train:
X: torch.Size([3594, 18])
y: torch.Size([3594, 1])

Validation:
X: torch.Size([686, 18])
y: torch.Size([686, 1])

Test:
X: torch.Size([1242, 18])
y: torch.Size([1242, 1])

Device: mps

NaN:
Train: 0
Val  : 0
Test : 0

Inf:
Train: 0
Val  : 0
Test : 0

In [33]:
# ============================================================
# V2 COMPATIBILITY NETWORK — V1
# ============================================================

import torch
import torch.nn as nn
import torch.optim as optim


# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

class CompatibilityNetV1(nn.Module):

    def __init__(self, input_dim=18):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 16),
            nn.ReLU(),

            nn.Linear(16, 1)
        )

    def forward(self, x):
        return self.network(x)


# ------------------------------------------------------------
# Create model
# ------------------------------------------------------------

model = CompatibilityNetV1(
    input_dim=X_train.shape[1]
).to(device)


# ------------------------------------------------------------
# Loss + optimizer
# ------------------------------------------------------------

criterion = nn.BCEWithLogitsLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=1e-3
)


# ------------------------------------------------------------
# Training configuration
# ------------------------------------------------------------

EPOCHS = 50

BATCH_SIZE = 64


# ------------------------------------------------------------
# Mini-batch training
# ------------------------------------------------------------

def train_epoch(model, X, y):

    model.train()

    permutation = torch.randperm(
        X.size(0),
        device=device
    )

    total_loss = 0.0

    for i in range(
        0,
        X.size(0),
        BATCH_SIZE
    ):

        indices = permutation[
            i:i + BATCH_SIZE
        ]

        batch_x = X[indices]
        batch_y = y[indices]

        optimizer.zero_grad()

        logits = model(batch_x)

        loss = criterion(
            logits,
            batch_y
        )

        loss.backward()

        optimizer.step()

        total_loss += (
            loss.item()
            * batch_x.size(0)
        )

    return total_loss / X.size(0)


# ------------------------------------------------------------
# Evaluation
# ------------------------------------------------------------

@torch.no_grad()
def evaluate(model, X, y):

    model.eval()

    logits = model(X)

    loss = criterion(
        logits,
        y
    )

    probabilities = torch.sigmoid(logits)

    predictions = (
        probabilities >= 0.5
    ).float()

    accuracy = (
        predictions == y
    ).float().mean()

    return (
        loss.item(),
        accuracy.item()
    )


# ============================================================
# TRAIN
# ============================================================

print("================================")
print("TRAINING V2 COMPATIBILITY MODEL")
print("================================")

print("Device:", device)
print("Input dimension:", X_train.shape[1])
print("Parameters:", sum(
    p.numel()
    for p in model.parameters()
))

for epoch in range(1, EPOCHS + 1):

    train_loss = train_epoch(
        model,
        X_train,
        y_train
    )

    val_loss, val_accuracy = evaluate(
        model,
        X_val,
        y_val
    )

    if (
        epoch == 1
        or epoch % 5 == 0
        or epoch == EPOCHS
    ):
        print(
            f"Epoch {epoch:02d}/{EPOCHS} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Acc: {val_accuracy:.4f}"
        )


# ============================================================
# FINAL TEST
# ============================================================

test_loss, test_accuracy = evaluate(
    model,
    X_test,
    y_test
)

print("\n================================")
print("FINAL TEST")
print("================================")

print(f"Test Loss : {test_loss:.4f}")
print(f"Test Acc  : {test_accuracy:.4f}")

================================
TRAINING V2 COMPATIBILITY MODEL
================================
Device: mps
Input dimension: 18
Parameters: 3841
Epoch 01/50 | Train Loss: 0.7318 | Val Loss: 0.7212 | Val Acc: 0.5087
Epoch 05/50 | Train Loss: 0.6789 | Val Loss: 0.6912 | Val Acc: 0.5394
Epoch 10/50 | Train Loss: 0.6697 | Val Loss: 0.6871 | Val Acc: 0.5481
Epoch 15/50 | Train Loss: 0.6614 | Val Loss: 0.7208 | Val Acc: 0.5350
Epoch 20/50 | Train Loss: 0.6589 | Val Loss: 0.7189 | Val Acc: 0.4840
Epoch 25/50 | Train Loss: 0.6559 | Val Loss: 0.7109 | Val Acc: 0.5204
Epoch 30/50 | Train Loss: 0.6524 | Val Loss: 0.7396 | Val Acc: 0.5335
Epoch 35/50 | Train Loss: 0.6456 | Val Loss: 0.7227 | Val Acc: 0.5000
Epoch 40/50 | Train Loss: 0.6438 | Val Loss: 0.7350 | Val Acc: 0.5117
Epoch 45/50 | Train Loss: 0.6381 | Val Loss: 0.7377 | Val Acc: 0.5219
Epoch 50/50 | Train Loss: 0.6393 | Val Loss: 0.7363 | Val Acc: 0.5029

================================
FINAL TEST
================================
Test Loss : 0.6915
Test Acc  : 0.5612

In [34]:
# ============================================================
# COMPATIBILITY SIGNAL ANALYSIS
# ============================================================

analysis_cols = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "length_height_ratio",
    "garment_sleeve",
]

print("================================")
print("POSITIVE vs NEGATIVE FEATURES")
print("================================")

for col in analysis_cols:

    print(f"\n--- {col} ---")

    display(
        training_df
        .groupby("label")[col]
        .agg([
            "count",
            "mean",
            "std",
            "median",
            "min",
            "max"
        ])
    )


# ============================================================
# EFFECT SIZE
# ============================================================

print("\n================================")
print("MEAN DIFFERENCE")
print("================================")

for col in analysis_cols:

    positive_mean = training_df[
        training_df["label"] == 1
    ][col].mean()

    negative_mean = training_df[
        training_df["label"] == 0
    ][col].mean()

    print(
        f"{col:25s} "
        f"positive={positive_mean:.3f} "
        f"negative={negative_mean:.3f} "
        f"diff={positive_mean-negative_mean:.3f}"
    )

================================
POSITIVE vs NEGATIVE FEATURES
================================

--- bust_ease ---

       count       mean        std  median   min    max
label
0       2675  25.774206  21.577712    24.0 -57.0  114.0
1       2547  29.724382  20.702248    28.0 -44.0  115.0

--- waist_ease ---

       count       mean        std  median   min    max
label
0       2259  41.141213  21.633845    40.0 -58.0  136.0
1       2081  44.304901  20.407181    43.0 -63.0  130.0

--- hip_ease ---

       count       mean        std  median   min    max
label
0       2383  24.169324  25.772897    23.0 -61.0  109.5
1       2288  28.698427  24.011297    27.0 -53.0  110.0

--- length_height_ratio ---

       count      mean       std    median       min       max
label
0       2718  0.406158  0.076224  0.391061  0.254144  0.754286
1       2737  0.426754  0.089440  0.405556  0.262857  0.781250

--- garment_sleeve ---

       count       mean        std  median  min    max
label
0       2475  56.210101  19.185020    64.0  6.0  133.0
1       2329  55.558609  19.597455    63.0  6.0  133.0

================================
MEAN DIFFERENCE
================================
bust_ease                 positive=29.724 negative=25.774 diff=3.950
waist_ease                positive=44.305 negative=41.141 diff=3.164
hip_ease                  positive=28.698 negative=24.169 diff=4.529
length_height_ratio       positive=0.427 negative=0.406 diff=0.021
garment_sleeve            positive=55.559 negative=56.210 diff=-0.651

In [35]:
# ============================================================
# V2 — SIMPLE COMPATIBILITY BASELINE
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report
)

print("================================")
print("SIMPLE COMPATIBILITY BASELINE")
print("================================")


# ------------------------------------------------------------
# Use the original dataframe
# ------------------------------------------------------------

baseline_df = test_df.copy()


# ------------------------------------------------------------
# Define a simple heuristic
#
# We reward:
#   - reasonable positive ease
#   - reasonable length/height ratio
#
# Missing measurements are ignored.
# ------------------------------------------------------------

def compatibility_score(row):

    scores = []

    # Bust
    if pd.notna(row["bust_ease"]):
        bust = row["bust_ease"]

        # Reasonable top ease
        if 5 <= bust <= 60:
            scores.append(1.0)
        elif -10 <= bust <= 75:
            scores.append(0.5)
        else:
            scores.append(0.0)

    # Waist
    if pd.notna(row["waist_ease"]):
        waist = row["waist_ease"]

        if 5 <= waist <= 70:
            scores.append(1.0)
        elif -10 <= waist <= 90:
            scores.append(0.5)
        else:
            scores.append(0.0)

    # Hip
    if pd.notna(row["hip_ease"]):
        hip = row["hip_ease"]

        if 5 <= hip <= 60:
            scores.append(1.0)
        elif -10 <= hip <= 80:
            scores.append(0.5)
        else:
            scores.append(0.0)

    # Length / height
    if pd.notna(row["length_height_ratio"]):
        ratio = row["length_height_ratio"]

        if 0.30 <= ratio <= 0.55:
            scores.append(1.0)
        elif 0.25 <= ratio <= 0.65:
            scores.append(0.5)
        else:
            scores.append(0.0)

    if not scores:
        return 0.0

    return np.mean(scores)


baseline_df["compatibility_score"] = baseline_df.apply(
    compatibility_score,
    axis=1
)


# ------------------------------------------------------------
# Prediction
# ------------------------------------------------------------

baseline_df["prediction"] = (
    baseline_df["compatibility_score"] >= 0.5
).astype(int)


# ------------------------------------------------------------
# Metrics
# ------------------------------------------------------------

y_true = baseline_df["label"]
y_pred = baseline_df["prediction"]

accuracy = accuracy_score(
    y_true,
    y_pred
)

print("\nAccuracy:", round(accuracy, 4))

print("\nClassification report:")
print(
    classification_report(
        y_true,
        y_pred,
        digits=4
    )
)


# ------------------------------------------------------------
# Score separation
# ------------------------------------------------------------

print("\n================================")
print("SCORE DISTRIBUTION")
print("================================")

print(
    baseline_df
    .groupby("label")["compatibility_score"]
    .agg([
        "count",
        "mean",
        "std",
        "median",
        "min",
        "max"
    ])
)

================================
SIMPLE COMPATIBILITY BASELINE
================================

Accuracy: 0.4919

Classification report:
              precision    recall  f1-score   support

           0     0.4000    0.0322    0.0596       621
           1     0.4958    0.9517    0.6520       621

    accuracy                         0.4919      1242
   macro avg     0.4479    0.4919    0.3558      1242
weighted avg     0.4479    0.4919    0.3558      1242


================================
SCORE DISTRIBUTION
================================
       count      mean       std  median  min  max
label
0        621  0.876006  0.180714     1.0  0.0  1.0
1        621  0.878086  0.207367     1.0  0.0  1.0

In [36]:
# ============================================================
# VIBE — SIZE / BODY RELATIONSHIP ANALYSIS
# ============================================================

print("================================")
print("SIZE / BODY RELATIONSHIP")
print("================================")

size_df = positive_df.copy()

print("\nUnique model sizes:")
print(
    size_df["model_size"]
    .dropna()
    .astype(str)
    .value_counts()
    .sort_index()
)

print("\n================================")
print("BODY MEASUREMENTS BY SIZE")
print("================================")

display(
    size_df.groupby("model_size")[
        ["height", "bust", "waist", "hips"]
    ].agg([
        "count",
        "mean",
        "std",
        "median"
    ]).round(2)
)

print("\n================================")
print("GARMENT MEASUREMENTS BY SIZE")
print("================================")

display(
    size_df.groupby("model_size")[
        [
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve"
        ]
    ].agg([
        "count",
        "mean",
        "std",
        "median"
    ]).round(2)
)

================================
SIZE / BODY RELATIONSHIP
================================

Unique model sizes:
model_size
10          906
12          376
14          316
14-16         1
16          312
18          180
20           11
8            52
L           103
L-XL          1
L/12         10
L/14          1
M            55
M-L           3
M/10          2
M/L           2
One Size      6
OneSize      30
S           297
S-M           4
S/10          2
S/M           2
XL           61
XL/14         2
XXL          18
XXL/16        8
Name: count, dtype: int64

================================
BODY MEASUREMENTS BY SIZE
================================

           height                        bust                       waist  \
            count    mean   std  median count    mean   std  median count
model_size
10            906  175.51  2.98  176.00   906   84.28  3.03   84.00   906
12            376  175.98  2.24  177.00   376  100.70  1.84  101.00   376
14            316  174.98  2.88  176.00   316   99.55  2.36   99.00   316
14-16           1  181.00   NaN  181.00     1  101.00   NaN  101.00     1
16            312  178.52  3.44  180.00   312  105.92  5.67  104.00   312
18            180  177.06  3.03  176.00   180  108.86  4.85  113.00   180
20             11  176.00  0.00  176.00    11  113.00  0.00  113.00    11
8              52  174.52  0.50  175.00    52   83.23  2.21   84.00    52
L             103  173.77  3.89  176.00   103   98.63  2.04   99.00   103
L-XL            1  180.00   NaN  180.00     1  104.00   NaN  104.00     1
L/12           10  174.80  2.53  176.00    10   88.60  4.43   86.50    10
L/14            1  176.00   NaN  176.00     1  104.00   NaN  104.00     1
M              55  173.05  3.87  175.00    55   99.29  5.01  101.00    55
M-L             3  176.67  0.58  177.00     3  100.33  1.15  101.00     3
M/10            2  179.00  0.00  179.00     2   84.00  0.00   84.00     2
M/L             2  176.50  0.71  176.50     2  102.50  2.12  102.50     2
One Size        6  176.00  0.89  176.00     6   94.67  8.31   99.00     6
OneSize        30  173.73  4.21  174.00    30   90.03  8.93   84.00    30
S             297  174.86  3.45  176.00   297   85.20  2.68   86.00   297
S-M             4  175.12  3.52  176.25     4   83.12  2.66   82.50     4
S/10            2  175.00  0.00  175.00     2   83.50  3.54   83.50     2
S/M             2  176.50  2.12  176.50     2   83.75  3.89   83.75     2
XL             61  179.69  2.72  181.00    61  104.52  5.50  101.00    61
XL/14           2  176.00  0.00  176.00     2   99.00  0.00   99.00     2
XXL            18  174.67  2.70  173.00    18  112.17  3.78  114.00    18
XXL/16          8  172.00  0.00  172.00     8  100.00  0.00  100.00     8

                                   hips
              mean    std  median count    mean   std  median
model_size
10           65.63   3.50   64.00   906   91.25  3.38   89.00
12           78.26   3.75   76.00   376  107.81  4.02  107.00
14           81.66   5.99   78.00   316  109.17  3.55  111.00
14-16        83.00    NaN   83.00     1  115.00   NaN  115.00
16           86.79   5.57   83.00   312  117.90  3.38  119.00
18           96.98   4.36   96.00   180  122.71  5.24  121.00
20          104.00   0.00  104.00    11  132.00  0.00  132.00
8            66.13   3.27   65.00    52   92.58  3.01   91.00
L            80.49   5.14   78.00   103  107.97  4.08  109.00
L-XL         96.00    NaN   96.00     1  121.00   NaN  121.00
L/12         71.60   3.37   70.00    10   93.40  4.01   91.50
L/14         92.00    NaN   92.00     1  111.00   NaN  111.00
M            77.31   4.32   78.00    55  102.05  7.02   98.00
M-L          76.67   1.15   76.00     3  108.67  2.89  107.00
M/10         61.00   0.00   61.00     2   89.00  0.00   89.00
M/L          84.00  11.31   84.00     2  109.00  2.83  109.00
One Size     75.33   2.73   76.00     6  105.67  6.35  107.00
OneSize      71.50   8.15   69.00    30   97.47  8.34   96.00
S            66.75   4.05   67.00   297   92.11  3.46   91.50
S-M          63.12   1.44   63.75     4   90.75  3.50   89.00
S/10         67.00   2.83   67.00     2   90.50  0.71   90.50
S/M          63.50   3.54   63.50     2   88.75  3.18   88.75
XL           85.39   4.21   83.00    61  117.70  4.86  115.00
XL/14        78.00   0.00   78.00     2  112.00  0.00  112.00
XXL          96.00   3.76   94.00    18  121.50  4.89  119.00
XXL/16       87.00   0.00   87.00     8  109.00  0.00  109.00

================================
GARMENT MEASUREMENTS BY SIZE
================================

           garment_bust                       garment_waist                  \
                  count    mean    std median         count    mean     std
model_size
10                  844  126.33  22.41  126.0           675  129.32  101.39
12                  365  125.69  20.46  126.0           315  119.06   15.80
14                  288  128.14  24.67  126.0           218  135.95  125.05
14-16                 1  200.00    NaN  200.0             1  200.00     NaN
16                  302  130.46  22.12  126.0           255  147.27  161.66
18                  161  126.70  16.45  126.0           122  125.04    9.25
20                   11  130.18   3.66  127.0            11  125.18    9.40
8                    51  132.84  33.31  126.0            52  113.35   15.03
L                   100  117.43  17.38  116.0            77  116.13   16.84
L-XL                  1  191.00    NaN  191.0             1  191.00     NaN
L/12                 10  116.80  25.63  104.0            10  110.80   28.64
L/14                  1  108.00    NaN  108.0             1  112.00     NaN
M                    53  121.85  27.29  113.0            40  116.65   15.49
M-L                   3  141.33  48.54  139.0             3  142.67   45.76
M/10                  2  100.00   2.83  100.0             2  104.00    2.83
M/L                   2  155.00  35.36  155.0             2  154.00   28.28
One Size              6  102.00   0.00  102.0             6  110.00    0.00
OneSize              30  154.13  37.28  150.0            26  145.38   23.80
S                   291  119.07  19.44  118.0           214  113.93   18.50
S-M                   4  159.25  37.85  165.0             4  158.75   38.21
S/10                  2  108.00   0.00  108.0             2  112.00    0.00
S/M                   2  180.00   0.00  180.0             2  174.00    0.00
XL                   58  125.91  19.42  124.0            34  115.18   19.61
XL/14                 2  100.00   2.83  100.0             2  104.00    2.83
XXL                  18  109.44  16.46  108.0            17  112.35   13.09
XXL/16                8  121.00  27.28  110.0             8  114.75   31.07

                  garment_hip                       garment_length         \
           median       count    mean    std median          count   mean
model_size
10          121.0         779  134.00  47.05  136.0            895  75.87
12          121.0         344  134.39  62.65  132.0            373  74.39
14          123.5         261  137.03  30.15  139.0            316  77.07
14-16       200.0           1  158.00    NaN  158.0              1  89.00
16          122.0         283  134.86  27.09  133.0            312  76.13
18          121.0         150  144.87  16.67  142.0            177  79.48
20          117.0          11  130.00   5.74  125.0             11  71.73
8           124.0          52  118.52  17.31  125.0             51  74.53
L           114.0          77  124.16  20.10  120.0            102  70.42
L-XL        191.0           1  199.00    NaN  199.0              1  96.00
L/12         95.0           8   98.50   2.78   98.0             10  59.80
L/14        112.0           1  116.00    NaN  116.0              1  58.00
M           113.5          35  122.09  21.04  122.0             53  70.72
M-L         137.0           3  147.00  46.87  134.0              3  80.33
M/10        104.0           0     NaN    NaN    NaN              2  58.50
M/L         154.0           2  154.00  14.14  154.0              2  95.50
One Size    110.0           6  122.00   0.00  122.0              6  65.00
OneSize     142.0          24  152.17  18.67  148.0             30  73.43
S           112.0         223  124.25  23.35  120.0            294  71.05
S-M         164.0           4  163.00  41.96  166.5              4  87.00
S/10        112.0           2  116.00   0.00  116.0              2  58.00
S/M         174.0           2  164.00   0.00  164.0              2  61.00
XL          115.0          34  132.41  22.97  130.0             61  75.87
XL/14       104.0           0     NaN    NaN    NaN              2  58.50
XXL         112.0          16  120.94  13.58  117.0             18  70.44
XXL/16      101.5           6   99.33   2.73  100.0              8  61.75

                         garment_sleeve
              std median          count   mean    std median
model_size
10          16.91   71.0            740  55.82  20.26   64.0
12          13.93   71.0            320  50.53  21.60   54.0
14          17.58   72.5            248  60.84  16.46   65.0
14-16         NaN   89.0              1  57.00    NaN   57.0
16          13.74   74.0            267  54.06  21.55   55.0
18          16.66   75.0            137  56.79  17.56   64.0
20          14.10   84.0             11  63.36  13.06   52.0
8           14.19   70.0             47  36.28  21.62   29.0
L           13.20   69.0             96  56.19  18.74   63.5
L-XL          NaN   96.0              1  46.00    NaN   46.0
L/12         9.53   56.0             10  55.00   2.75   54.0
L/14          NaN   58.0              1  70.00    NaN   70.0
M           11.61   69.0             54  58.26  14.60   65.0
M-L         19.14   86.0              3  28.00  19.67   31.0
M/10         2.12   58.5              2  18.50   7.78   18.5
M/L         48.79   95.5              2  44.00   8.49   44.0
One Size     0.00   65.0              6  65.00   0.00   65.0
OneSize     10.81   74.0             30  60.17  10.01   65.0
S           13.53   68.5            267  58.67  16.00   64.0
S-M         12.27   91.0              4  49.25  17.95   46.0
S/10         0.00   58.0              2  70.00   0.00   70.0
S/M          0.00   61.0              2  38.00   0.00   38.0
XL          16.85   70.0             51  61.61  14.67   68.0
XL/14        2.12   58.5              2  18.50   7.78   18.5
XXL          5.49   70.5             17  49.94  22.08   63.0
XXL/16       9.75   59.5              8  55.50   2.88   54.5

In [37]:
# ============================================================
# VIBE — GARMENT MEASUREMENT QUALITY AUDIT
# ============================================================

import pandas as pd
import numpy as np

measurement_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

print("================================")
print("GARMENT MEASUREMENT QUALITY AUDIT")
print("================================")

for col in measurement_cols:

    s = positive_df[col].dropna()

    print(f"\n--- {col} ---")
    print("Count :", len(s))
    print("Min   :", s.min())
    print("Max   :", s.max())
    print("Median:", s.median())
    print("Mean  :", round(s.mean(), 2))

    # Suspicious values
    suspicious = positive_df[
        positive_df[col].notna() &
        (
            (positive_df[col] <= 20) |
            (positive_df[col] >= 180)
        )
    ][
        ["person_id", "product_id", col]
    ].sort_values(col)

    print("\nSuspicious rows:", len(suspicious))

    if len(suspicious) > 0:
        display(suspicious.head(20))


# ============================================================
# CHECK DUPLICATED PRODUCT MEASUREMENTS
# ============================================================

print("\n================================")
print("PRODUCT-LEVEL MEASUREMENT CHECK")
print("================================")

product_measurements = (
    positive_df
    .groupby("product_id")[measurement_cols]
    .first()
)

print(
    "Unique products:",
    len(product_measurements)
)

print("\nProducts with extreme measurements:")

for col in measurement_cols:

    bad = product_measurements[
        product_measurements[col].notna() &
        (
            (product_measurements[col] <= 20) |
            (product_measurements[col] >= 180)
        )
    ]

    print(
        f"{col:20s}: {len(bad)} products"
    )

    if len(bad) > 0:
        display(bad[[col]].sort_values(col).head(20))

================================
GARMENT MEASUREMENT QUALITY AUDIT
================================

--- garment_bust ---
Count : 2616
Min   : 12.0
Max   : 240.0
Median: 125.0
Mean  : 126.05

Suspicious rows: 103

     person_id                          product_id  garment_bust
772    Georgia          stripe-me-happy-blouse#Ash          12.0
773      Laura          stripe-me-happy-blouse#Ash          12.0
2575   Natalia          lavaux-bell-sleeve#Mustard         180.0
247        Tia             pattern-tunic-1#Lattice         180.0
2574     Katie          lavaux-bell-sleeve#Mustard         180.0
245       Lara             pattern-tunic-1#Lattice         180.0
246       Jude             pattern-tunic-1#Lattice         180.0
1749     Fiona     open-plains-kimono-throw-1#Rust         180.0
1750   Georgia     open-plains-kimono-throw-1#Rust         180.0
1751    Stacey     open-plains-kimono-throw-1#Rust         180.0
1752     Mandy     open-plains-kimono-throw-1#Rust         180.0
1748    Marnee     open-plains-kimono-throw-1#Rust         180.0
1653      Jess      long-sleeve-spot-top#Multispot         182.0
1651    Summer      long-sleeve-spot-top#Multispot         182.0
1652     Fiona      long-sleeve-spot-top#Multispot         182.0
2382     Riina  the-longline-waterfall-cardi#Black         184.0
2381    Amanda  the-longline-waterfall-cardi#Black         184.0
2383     Fiona  the-longline-waterfall-cardi#Black         184.0
649   Palatina       flow-with-me-slouch-top#Brick         189.0
650      Fiona       flow-with-me-slouch-top#Brick         189.0

--- garment_waist ---
Count : 2100
Min   : 11.0
Max   : 1181.0
Median: 121.0
Mean  : 127.45

Suspicious rows: 38

     person_id                          product_id  garment_waist
2573   Chelsea                cara-tee-2#BlackSpot           11.0
2302   Chelsea                 cara-tee-2#WhiteBlk           11.0
2132   Chelsea                    cara-tee-2#Blush           11.0
2383     Fiona  the-longline-waterfall-cardi#Black           20.0
2382     Riina  the-longline-waterfall-cardi#Black           20.0
2381    Amanda  the-longline-waterfall-cardi#Black           20.0
1749     Fiona     open-plains-kimono-throw-1#Rust          180.0
1750   Georgia     open-plains-kimono-throw-1#Rust          180.0
1751    Stacey     open-plains-kimono-throw-1#Rust          180.0
1752     Mandy     open-plains-kimono-throw-1#Rust          180.0
1748    Marnee     open-plains-kimono-throw-1#Rust          180.0
651      Laura       flow-with-me-slouch-top#Brick          187.0
652     Marnee       flow-with-me-slouch-top#Brick          187.0
653    Georgia       flow-with-me-slouch-top#Brick          187.0
654      Gemma       flow-with-me-slouch-top#Brick          187.0
649   Palatina       flow-with-me-slouch-top#Brick          187.0
650      Fiona       flow-with-me-slouch-top#Brick          187.0
2538    Marnee    summer-whispers-kimono-1#Peacock          191.0
2541  Ljubenka    summer-whispers-kimono-1#Peacock          191.0
2539   Georgia    summer-whispers-kimono-1#Peacock          191.0

--- garment_hip ---
Count : 2325
Min   : 15.0
Max   : 1230.0
Median: 133.0
Mean  : 133.35

Suspicious rows: 75

     person_id                           product_id  garment_hip
434      Riina           the-cross-over-poncho#Navy         15.0
164    Chelsea           the-cross-over-poncho#Grey         15.0
165      Riina           the-cross-over-poncho#Grey         15.0
166   Stefania           the-cross-over-poncho#Grey         15.0
167      Fiona           the-cross-over-poncho#Grey         15.0
433    Chelsea           the-cross-over-poncho#Navy         15.0
435   Stefania           the-cross-over-poncho#Navy         15.0
436      Fiona           the-cross-over-poncho#Navy         15.0
1752     Mandy      open-plains-kimono-throw-1#Rust        180.0
1751    Stacey      open-plains-kimono-throw-1#Rust        180.0
1750   Georgia      open-plains-kimono-throw-1#Rust        180.0
1748    Marnee      open-plains-kimono-throw-1#Rust        180.0
1749     Fiona      open-plains-kimono-throw-1#Rust        180.0
2693      Jess  belle-poncho-sleeved-knit#BlueMarle        182.0
590     Summer       tab-sleeve-longline-shirt#Pink        185.0
992     Summer     tab-sleeve-longline-shirt#Silver        185.0
2544     Gemma       tab-sleeve-longline-shirt#Navy        185.0
2545    Summer       tab-sleeve-longline-shirt#Navy        185.0
589      Gemma       tab-sleeve-longline-shirt#Pink        185.0
991      Gemma     tab-sleeve-longline-shirt#Silver        185.0

--- garment_length ---
Count : 2737
Min   : 46.0
Max   : 132.0
Median: 71.0
Mean  : 75.01

Suspicious rows: 0

--- garment_sleeve ---
Count : 2329
Min   : 6.0
Max   : 133.0
Median: 63.0
Mean  : 55.56

Suspicious rows: 163

,person_id,product_id,garment_sleeve
825,Jess,layered-tunic-1#Natural,6.0
824,Monique,layered-tunic-1#Natural,6.0
793,Jess,layered-tunic-1#White,6.0
792,Monique,layered-tunic-1#White,6.0
610,Summer,haze-swing-top#OffWhite,6.0
588,Jess,layered-tunic-1#PalePink,6.0
587,Monique,layered-tunic-1#PalePink,6.0
2730,Laura,saba-top-2#Catus,7.0
2375,Chelsea,reversible-stripe-vee-scoop-neck-tank#BlackWhite,7.0
2376,Palatina,reversible-stripe-vee-scoop-neck-tank#BlackWhite,7.0
1336,Summer,capri-tank-3#Navy,8.0
1337,Tia,capri-tank-3#Navy,8.0
1058,Summer,capri-tank-3#Black,8.0
2475,Summer,capri-tank-3#White,8.0
2476,Tia,capri-tank-3#White,8.0
472,Riina,bora-bora-layered-tank#BoraBora,8.0
1059,Tia,capri-tank-3#Black,8.0
327,Summer,capri-tank-3#NavyStripe,8.0
328,Tia,capri-tank-3#NavyStripe,8.0
2454,Shadae,capri-tank-6#ClaySpot,9.0

================================
PRODUCT-LEVEL MEASUREMENT CHECK
================================
Unique products: 859

Products with extreme measurements:
garment_bust        : 25 products

                                         garment_bust
product_id
stripe-me-happy-blouse#Ash                       12.0
pattern-tunic-1#Lattice                         180.0
open-plains-kimono-throw-1#Rust                 180.0
lavaux-bell-sleeve#Mustard                      180.0
long-sleeve-spot-top#Multispot                  182.0
the-longline-waterfall-cardi#Black              184.0
flow-with-me-slouch-top#Brick                   189.0
natural-pattern-cocoon-cardigan#Blossom         190.0
summer-whispers-kimono-1#Peacock                191.0
cross-my-heart-bamboo-slouch-tee#White          196.0
leopard-print-kimono#GoldMulti                  200.0
the-half-sleeve-tee#White                       201.0
the-half-sleeve-tee#Black                       201.0
makeover-blouse#LimeGreen                       204.0
the-oversize-knit#Ink                           204.0
the-oversize-knit#GreyMarle                     204.0
the-batwing-tee#Stone                           205.0
the-batwing-tee#Black                           205.0
the-batwing-tee#FrenchBlue                      205.0
the-batwing-tee#Sea                             205.0

garment_waist       : 12 products

                                    garment_waist
product_id
cara-tee-2#BlackSpot                         11.0
cara-tee-2#Blush                             11.0
cara-tee-2#WhiteBlk                          11.0
the-longline-waterfall-cardi#Black           20.0
open-plains-kimono-throw-1#Rust             180.0
flow-with-me-slouch-top#Brick               187.0
summer-whispers-kimono-1#Peacock            191.0
leopard-print-kimono#GoldMulti              200.0
makeover-blouse#LimeGreen                   204.0
sugar-snaps-throw-jacket#Black             1181.0
sugar-snaps-throw-jacket#Duckegg           1181.0
sugar-snaps-throw-jacket#White             1181.0

garment_hip         : 25 products

                                     garment_hip
product_id
the-cross-over-poncho#Navy                  15.0
the-cross-over-poncho#Grey                  15.0
open-plains-kimono-throw-1#Rust            180.0
belle-poncho-sleeved-knit#BlueMarle        182.0
tab-sleeve-longline-shirt#Silver           185.0
tab-sleeve-longline-shirt#Pink             185.0
tab-sleeve-longline-shirt#Navy             185.0
belle-flute-sleeve-tee#Navy                186.0
belle-lace-trim-tee#GreyMarle              189.0
the-stripe-tank-1#Hazelnut                 190.0
be-mine-top-1#Sage                         191.0
flow-with-me-slouch-top#Brick              195.0
daisy-chain-tassel-blouse#DeepBlue         196.0
summer-whispers-kimono-1#Peacock           199.0
sunshine-in-me-tee-1#GreyMarle             201.0
sunshine-in-me-tee-1#White                 201.0
soho-v-neck-blouse#SohoPrint               202.0
makeover-blouse#LimeGreen                  204.0
tuck-layer-shirt#White                     206.0
on-the-horizon-swing-top-1#Khaki           213.0

garment_length      : 0 products
garment_sleeve      : 50 products

                                                  garment_sleeve
product_id
layered-tunic-1#White                                        6.0
layered-tunic-1#Natural                                      6.0
haze-swing-top#OffWhite                                      6.0
layered-tunic-1#PalePink                                     6.0
saba-top-2#Catus                                             7.0
reversible-stripe-vee-scoop-neck-tank#BlackWhite             7.0
capri-tank-3#Black                                           8.0
capri-tank-3#Navy                                            8.0
capri-tank-3#NavyStripe                                      8.0
capri-tank-3#White                                           8.0
bora-bora-layered-tank#BoraBora                              8.0
capri-tank-6#Olive                                           9.0
capri-tank-6#HeatheGrey                                      9.0
capri-tank-6#ClaySpot                                        9.0
the-printed-v-split-top#Natural                             10.0
the-sleeveless-cross-over-blouse#Chambray                   11.0
sugar-snaps-round-neck-layer-tank#White                     11.0
sugar-snaps-round-neck-layer-tank#DuckEgg                   11.0
sugar-snaps-round-neck-layer-tank#Black                     11.0
the-sleeveless-cross-over-blouse#Cobalt                     11.0

In [38]:
# ============================================================
# VIBE — TRACE SUSPICIOUS VALUES BACK TO RAW SOURCE
# ============================================================

from pathlib import Path
import json

suspicious_products = [
    "sugar-snaps-throw-jacket#Black",
    "stripe-me-happy-blouse#Ash",
    "cara-tee-2#BlackSpot",
    "the-cross-over-poncho#Grey",
    "llama-long-sleeve-shirt#Mustard",
    "the-half-sleeve-tee#White",
    "the-batwing-tee#FrenchBlue",
    "open-plains-kimono-throw-1#Rust",
]

print("================================")
print("RAW SOURCE TRACE")
print("================================")

for product in suspicious_products:

    path = Path(
        f"tops/garment_measurement/{product}_meta.txt"
    )

    print("\n--------------------------------")
    print(product)
    print("File:", path)

    if not path.exists():
        print("FILE NOT FOUND")
        continue

    print("\nRAW CONTENT:")
    
    with open(path, "r") as f:
        raw = f.read()

    print(raw[:2000])

================================
RAW SOURCE TRACE
================================

--------------------------------
sugar-snaps-throw-jacket#Black
File: tops/garment_measurement/sugar-snaps-throw-jacket#Black_meta.txt
FILE NOT FOUND

--------------------------------
stripe-me-happy-blouse#Ash
File: tops/garment_measurement/stripe-me-happy-blouse#Ash_meta.txt
FILE NOT FOUND

--------------------------------
cara-tee-2#BlackSpot
File: tops/garment_measurement/cara-tee-2#BlackSpot_meta.txt
FILE NOT FOUND

--------------------------------
the-cross-over-poncho#Grey
File: tops/garment_measurement/the-cross-over-poncho#Grey_meta.txt
FILE NOT FOUND

--------------------------------
llama-long-sleeve-shirt#Mustard
File: tops/garment_measurement/llama-long-sleeve-shirt#Mustard_meta.txt
FILE NOT FOUND

--------------------------------
the-half-sleeve-tee#White
File: tops/garment_measurement/the-half-sleeve-tee#White_meta.txt
FILE NOT FOUND

--------------------------------
the-batwing-tee#FrenchBlue
File: tops/garment_measurement/the-batwing-tee#FrenchBlue_meta.txt
FILE NOT FOUND

--------------------------------
open-plains-kimono-throw-1#Rust
File: tops/garment_measurement/open-plains-kimono-throw-1#Rust_meta.txt
FILE NOT FOUND

In [39]:
from pathlib import Path

targets = [
    "sugar-snaps-throw-jacket#Black",
    "stripe-me-happy-blouse#Ash",
    "cara-tee-2#BlackSpot",
    "the-cross-over-poncho#Grey",
    "llama-long-sleeve-shirt#Mustard",
    "the-half-sleeve-tee#White",
    "the-batwing-tee#FrenchBlue",
    "open-plains-kimono-throw-1#Rust",
]

files = list(Path("tops/garment_measurement").glob("*.txt"))

print("================================")
print("ACTUAL FILENAMES")
print("================================")

for target in targets:
    matches = [
        f for f in files
        if target.lower() in f.stem.lower()
    ]

    print(f"\n{target}")

    if not matches:
        print("  NO MATCH")
    else:
        for f in matches:
            print(" ", f.name)

================================
ACTUAL FILENAMES
================================

sugar-snaps-throw-jacket#Black
  NO MATCH

stripe-me-happy-blouse#Ash
  NO MATCH

cara-tee-2#BlackSpot
  NO MATCH

the-cross-over-poncho#Grey
  NO MATCH

llama-long-sleeve-shirt#Mustard
  NO MATCH

the-half-sleeve-tee#White
  NO MATCH

the-batwing-tee#FrenchBlue
  NO MATCH

open-plains-kimono-throw-1#Rust
  NO MATCH

In [40]:
# ============================================================
# VIBE — INSPECT GARMENT MEASUREMENT FILE STRUCTURE
# ============================================================

from pathlib import Path

files = sorted(Path("tops/garment_measurement").glob("*.txt"))

print("Total files:", len(files))
print("\nFirst 30 actual filenames:")
for f in files[:30]:
    print(f.name)

print("\n================================")
print("FILES CONTAINING SUGAR / HALF / BATWING")
print("================================")

keywords = [
    "sugar",
    "half",
    "batwing",
    "poncho",
    "llama",
    "cara",
    "stripe"
]

for f in files:
    name = f.name.lower()

    if any(k in name for k in keywords):
        print(f.name)

Total files: 0

First 30 actual filenames:

================================
FILES CONTAINING SUGAR / HALF / BATWING
================================

In [41]:
Path("tops/garment_measurement")

PosixPath('tops/garment_measurement')

In [42]:
from pathlib import Path
import os

print("Current working directory:")
print(os.getcwd())

print("\nCurrent directory contents:")
for p in Path(".").iterdir():
    print(p)

print("\nVIBE dataset:")
vibe_dataset = Path.home() / "Desktop/Projects/weavly/core-model/VIBE/dataset"

print("Path:", vibe_dataset)
print("Exists:", vibe_dataset.exists())

print("\nGarment measurement directory:")
garment_dir = vibe_dataset / "tops" / "garment_measurement"

print("Path:", garment_dir)
print("Exists:", garment_dir.exists())

if garment_dir.exists():
    files = list(garment_dir.glob("*.txt"))
    print("Files:", len(files))

Current working directory:
/Users/saketh/Desktop/Projects/weavly/core-model

Current directory contents:
test_step6_user_persistence.py
Zyrav2.ipynb
zyra_step6_validation.db
Zyra-v1.ipynb
test_step7a_image_integrity_audit.py
.DS_Store
p10_production_artifacts
requirements.txt
.pytest_cache
test_zyra_engine.py
test_all_8_occasions.py
test_step7_frontend_integration.py
experiments
pyproject.toml
test_persistence.py
Zyra_V2_Compatibility_Model.ipynb
__pycache__
docs
zyra_recommendations.db
README.md
p8_output
test_step7b_user_conditioning.py
.gitignore
.env
test_spring_integration.py
zyra
.venv
scripts
app.py
test_step7c_occasion_diversity.py
.ipynb_checkpoints
test_api.py
.env.example
.vscode
main.py
VIBE
data
zyra.egg-info
diagnose_occasion_data_flow.py
reports
zyra_step7_validation.db

VIBE dataset:
Path: /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset
Exists: True

Garment measurement directory:
Path: /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset/tops/garment_measurement
Exists: True
Files: 1056

In [43]:
# ============================================================
# VIBE — TRACE SUSPICIOUS GARMENT MEASUREMENTS
# ============================================================

from pathlib import Path
import json

VIBE_DATASET = Path.home() / "Desktop/Projects/weavly/core-model/VIBE/dataset"
garment_dir = VIBE_DATASET / "tops" / "garment_measurement"

files = sorted(garment_dir.glob("*.txt"))

print("================================")
print("GARMENT MEASUREMENT DIRECTORY")
print("================================")
print("Directory:", garment_dir)
print("Files:", len(files))

print("\nFirst 20 actual filenames:")
for f in files[:20]:
    print(f.name)

print("\n================================")
print("SEARCHING SUSPICIOUS PRODUCTS")
print("================================")

keywords = [
    "sugar-snaps",
    "stripe-me-happy",
    "cara-tee",
    "cross-over-poncho",
    "llama",
    "half-sleeve",
    "batwing",
    "open-plains",
]

matches = []

for f in files:
    name = f.name.lower()

    if any(k in name for k in keywords):
        matches.append(f)

print("Matches:", len(matches))

for f in matches:
    print("\n--------------------------------")
    print("FILE:", f.name)

    try:
        with open(f, "r") as x:
            raw = x.read()

        print(raw[:2500])

    except Exception as e:
        print("ERROR:", e)

================================
GARMENT MEASUREMENT DIRECTORY
================================
Directory: /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset/tops/garment_measurement
Files: 1056

First 20 actual filenames:
2-in-1-jumper#Navy_meta.txt
2-in-1-layered-knit-top#Khaki_meta.txt
2-in-1-layered-knit-top#Navy_meta.txt
2-in-1-layered-knit-top#PalePink_meta.txt
2-in-1-layered-top-1#NavyWhite_meta.txt
2-in-1-layered-top-1#PinkWhite_meta.txt
34-sleeve-lace-tunic#Black_meta.txt
34-sleeve-shirt#White_meta.txt
34-sleeve-shirt-1#SkyWhite_meta.txt
abigail-stripe-shirt#BlackStrip_meta.txt
adventurous-hoody#Pink_meta.txt
agra-shirt#White_meta.txt
aida-long-tunic-shirt#AidaStripe_meta.txt
aigli-top#Navy_meta.txt
aigli-top#White_meta.txt
ainsley-cape#CharcoalM_meta.txt
alanis-pastel-dinosaurs-sweatshirt#Oatmeal_meta.txt
alaska-knit#Stone_meta.txt
alberta-stripe-top#IvoryStrip_meta.txt
aldis-blouse#Pearl_meta.txt

================================
SEARCHING SUSPICIOUS PRODUCTS
================================
Matches: 47

--------------------------------
FILE: belle-half-sleeve-boat-tee#Black_meta.txt
{"10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "81cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "77cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "91cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "54cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "34cm"}], "12": [{"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "55cm"}, {"dimension_id": "1", "dimension_name": "Bust", "value": "86cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "96cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "35cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "91cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "101cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "56cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "36cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "96cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "106cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "56cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "37cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "101cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "111cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "57cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "39cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "106cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "116cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "57cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "40cm"}], "22": [{"dimension_id": "1", "dimension_name": "Bust", "value": "111cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "1

--------------------------------
FILE: belle-half-sleeve-boat-tee#White_meta.txt
{"10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "81cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "77cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "91cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "54cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "34cm"}], "12": [{"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "55cm"}, {"dimension_id": "1", "dimension_name": "Bust", "value": "86cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "96cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "35cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "91cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "101cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "56cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "36cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "96cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "106cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "56cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "37cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "101cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "111cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "57cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "39cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "106cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "116cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "57cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "40cm"}], "22": [{"dimension_id": "1", "dimension_name": "Bust", "value": "111cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "1

--------------------------------
FILE: belle-half-sleeve-forgiver-tunic#Apricot_meta.txt
{"8": [{"dimension_id": "1", "dimension_name": "Bust", "value": "92cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "90cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "44cm"}], "10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "97cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "95cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "45cm"}], "12": [{"dimension_id": "1", "dimension_name": "Bust", "value": "102cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "100cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "81cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "46cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "107cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "105cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "47cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "112cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "110cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "48cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "117cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "115cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "83cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "50cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "122cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "112cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value":

--------------------------------
FILE: belle-half-sleeve-forgiver-tunic#Black_meta.txt
{"8": [{"dimension_id": "1", "dimension_name": "Bust", "value": "92cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "90cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "44cm"}], "10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "97cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "95cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "45cm"}], "12": [{"dimension_id": "1", "dimension_name": "Bust", "value": "102cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "100cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "81cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "46cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "107cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "105cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "47cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "112cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "110cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "48cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "117cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "115cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "83cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "50cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "122cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "112cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value":

--------------------------------
FILE: belle-half-sleeve-forgiver-tunic#BlueBonnet_meta.txt
{"8": [{"dimension_id": "1", "dimension_name": "Bust", "value": "92cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "90cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "44cm"}], "10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "97cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "95cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "45cm"}], "12": [{"dimension_id": "1", "dimension_name": "Bust", "value": "102cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "100cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "81cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "46cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "107cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "105cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "47cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "112cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "110cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "48cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "117cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "115cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "83cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "50cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "122cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "112cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value":

--------------------------------
FILE: belle-half-sleeve-forgiver-tunic#FlamPink_meta.txt
{"8": [{"dimension_id": "1", "dimension_name": "Bust", "value": "92cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "90cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "44cm"}], "10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "97cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "95cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "45cm"}], "12": [{"dimension_id": "1", "dimension_name": "Bust", "value": "102cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "100cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "81cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "46cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "107cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "105cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "47cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "112cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "110cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "48cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "117cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "115cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "83cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "50cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "122cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "112cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value":

--------------------------------
FILE: belle-half-sleeve-forgiver-tunic#MutedClay_meta.txt
{"8": [{"dimension_id": "1", "dimension_name": "Bust", "value": "92cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "82cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "90cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "44cm"}], "10": [{"dimension_id": "1", "dimension_name": "Bust", "value": "97cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "87cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "95cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "80cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "45cm"}], "12": [{"dimension_id": "1", "dimension_name": "Bust", "value": "102cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "92cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "100cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "81cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "46cm"}], "14": [{"dimension_id": "1", "dimension_name": "Bust", "value": "107cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "97cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "105cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "47cm"}], "16": [{"dimension_id": "1", "dimension_name": "Bust", "value": "112cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "102cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "110cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "82cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "48cm"}], "18": [{"dimension_id": "1", "dimension_name": "Bust", "value": "117cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "107cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value": "115cm"}, {"dimension_id": "7", "dimension_name": "Length - shoulder to hem", "value": "83cm"}, {"dimension_id": "15", "dimension_name": "Sleeve Length - neck to hem", "value": "50cm"}], "20": [{"dimension_id": "1", "dimension_name": "Bust", "value": "122cm"}, {"dimension_id": "3", "dimension_name": "Waist", "value": "112cm"}, {"dimension_id": "5", "dimension_name": "Hip", "value":

--------------------------------
FILE: belle-half-sleeve-forgiver-tunic#White_meta.txt

In [44]:
# ============================================================
# V2 — FULL GARMENT MEASUREMENT INTEGRITY AUDIT
# ============================================================

from pathlib import Path
import json
import re
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. DATASET PATH
# ------------------------------------------------------------

DATASET_ROOT = Path.cwd() / "VIBE" / "dataset"
MEASUREMENT_DIR = DATASET_ROOT / "tops" / "garment_measurement"

print("=" * 60)
print("V2 GARMENT MEASUREMENT INTEGRITY AUDIT")
print("=" * 60)

print("Dataset root :", DATASET_ROOT)
print("Measurement  :", MEASUREMENT_DIR)
print("Exists       :", MEASUREMENT_DIR.exists())

if not MEASUREMENT_DIR.exists():
    raise FileNotFoundError(
        f"Measurement directory not found:\n{MEASUREMENT_DIR}"
    )

files = sorted(MEASUREMENT_DIR.glob("*_meta.txt"))

print("Files found  :", len(files))


# ------------------------------------------------------------
# 2. EXPECTED DIMENSIONS
# ------------------------------------------------------------

DIMENSION_MAP = {
    1: "bust",
    3: "waist",
    5: "hip",
    7: "length",
    15: "sleeve",
}

EXPECTED_DIMENSIONS = set(DIMENSION_MAP.keys())


# ------------------------------------------------------------
# 3. HELPERS
# ------------------------------------------------------------

def extract_number(value):
    """
    Extract numeric value from strings such as:
        '102cm'
        '1230cm'
        '11cm'
    """
    if value is None:
        return np.nan

    match = re.search(r"-?\d+(?:\.\d+)?", str(value))

    if not match:
        return np.nan

    return float(match.group())


def parse_measurement_file(path):
    """
    Parse one *_meta.txt measurement file.

    Returns:
        list of size-level records
    """

    try:
        raw = path.read_text(encoding="utf-8").strip()

        if not raw:
            return []

        data = json.loads(raw)

        if not isinstance(data, dict):
            return []

        records = []

        for size, dimensions in data.items():

            if not isinstance(dimensions, list):
                continue

            row = {
                "file": path.name,
                "product": path.name.replace("_meta.txt", ""),
                "size": str(size),
            }

            for item in dimensions:

                if not isinstance(item, dict):
                    continue

                dimension_id = item.get("dimension_id")
                dimension_name = item.get("dimension_name")
                value = item.get("value")

                try:
                    dimension_id_int = int(dimension_id)
                except:
                    dimension_id_int = None

                if dimension_id_int in DIMENSION_MAP:

                    column = DIMENSION_MAP[dimension_id_int]

                    row[column] = extract_number(value)

                    row[f"{column}_raw"] = value
                    row[f"{column}_dimension_name"] = dimension_name

            records.append(row)

        return records

    except Exception as e:

        return [{
            "file": path.name,
            "product": path.name.replace("_meta.txt", ""),
            "size": None,
            "parse_error": str(e),
        }]


# ------------------------------------------------------------
# 4. PARSE EVERYTHING
# ------------------------------------------------------------

all_records = []

for path in files:
    all_records.extend(parse_measurement_file(path))

measurements_df = pd.DataFrame(all_records)

print()
print("=" * 60)
print("PARSED DATA")
print("=" * 60)

print("Files parsed :", measurements_df["file"].nunique())
print("Rows         :", len(measurements_df))

display(measurements_df.head())


# ------------------------------------------------------------
# 5. BASIC COMPLETENESS
# ------------------------------------------------------------

print()
print("=" * 60)
print("DIMENSION COMPLETENESS")
print("=" * 60)

for dimension in DIMENSION_MAP.values():

    if dimension in measurements_df.columns:

        present = measurements_df[dimension].notna().sum()
        missing = measurements_df[dimension].isna().sum()

        percentage = (
            present / len(measurements_df) * 100
            if len(measurements_df)
            else 0
        )

        print(
            f"{dimension:8s} | "
            f"present={present:5d} | "
            f"missing={missing:5d} | "
            f"coverage={percentage:6.2f}%"
        )


# ------------------------------------------------------------
# 6. PLAUSIBLE RANGES
# ------------------------------------------------------------
#
# These are AUDIT thresholds, not corrections.
#
# They intentionally flag suspicious data for inspection.
# They do NOT alter the original dataset.
# ------------------------------------------------------------

RANGES = {
    "bust":   (50, 180),
    "waist":  (45, 180),
    "hip":    (50, 190),
    "length": (30, 130),
    "sleeve": (0, 100),
}


# ------------------------------------------------------------
# 7. OUTLIER / IMPOSSIBLE VALUE AUDIT
# ------------------------------------------------------------

issues = []

for _, row in measurements_df.iterrows():

    for dimension, (lower, upper) in RANGES.items():

        if dimension not in row:
            continue

        value = row[dimension]

        if pd.isna(value):
            continue

        if value < lower or value > upper:

            issues.append({
                "file": row["file"],
                "product": row["product"],
                "size": row["size"],
                "dimension": dimension,
                "value": value,
                "lower_limit": lower,
                "upper_limit": upper,
                "issue": "OUT_OF_RANGE",
            })


issues_df = pd.DataFrame(issues)

print()
print("=" * 60)
print("OUT-OF-RANGE VALUES")
print("=" * 60)

print("Suspicious values:", len(issues_df))

if len(issues_df):

    display(
        issues_df.sort_values(
            ["dimension", "value"],
            ascending=[True, False]
        ).head(100)
    )

else:

    print("No out-of-range values found.")


# ------------------------------------------------------------
# 8. EMPTY FILES
# ------------------------------------------------------------

empty_files = []

for path in files:

    try:
        raw = path.read_text(encoding="utf-8").strip()

        if not raw:
            empty_files.append(path.name)
            continue

        data = json.loads(raw)

        if not data:
            empty_files.append(path.name)

    except:
        pass


print()
print("=" * 60)
print("EMPTY MEASUREMENT FILES")
print("=" * 60)

print("Empty files:", len(empty_files))

if empty_files:
    print()
    for name in empty_files[:100]:
        print(name)


# ------------------------------------------------------------
# 9. FILES WITH MISSING DIMENSIONS
# ------------------------------------------------------------

missing_dimension_records = []

for _, row in measurements_df.iterrows():

    missing = []

    for dimension in DIMENSION_MAP.values():

        if dimension not in row or pd.isna(row[dimension]):
            missing.append(dimension)

    if missing:

        missing_dimension_records.append({
            "file": row["file"],
            "product": row["product"],
            "size": row["size"],
            "missing_dimensions": ", ".join(missing),
        })


missing_df = pd.DataFrame(missing_dimension_records)

print()
print("=" * 60)
print("MISSING DIMENSIONS")
print("=" * 60)

print("Rows with missing dimensions:", len(missing_df))

if len(missing_df):

    display(missing_df.head(100))


# ------------------------------------------------------------
# 10. DUPLICATE / IDENTICAL SIZE RECORDS
# ------------------------------------------------------------

measurement_columns = [
    c for c in DIMENSION_MAP.values()
    if c in measurements_df.columns
]

duplicate_rows = measurements_df[
    measurements_df.duplicated(
        subset=["product", "size"] + measurement_columns,
        keep=False
    )
].copy()

print()
print("=" * 60)
print("DUPLICATE SIZE RECORDS")
print("=" * 60)

print("Duplicate rows:", len(duplicate_rows))

if len(duplicate_rows):

    display(
        duplicate_rows[
            ["product", "size"] + measurement_columns
        ].head(100)
    )


# ------------------------------------------------------------
# 11. SAME PRODUCT/COLOR FILE CONSISTENCY
# ------------------------------------------------------------

print()
print("=" * 60)
print("PRODUCT SUMMARY")
print("=" * 60)

product_summary = (
    measurements_df
    .groupby("product")
    .agg(
        sizes=("size", "nunique"),
        rows=("size", "count"),
        bust_missing=("bust", lambda x: x.isna().sum()),
        waist_missing=("waist", lambda x: x.isna().sum()),
        hip_missing=("hip", lambda x: x.isna().sum()),
        length_missing=("length", lambda x: x.isna().sum()),
        sleeve_missing=("sleeve", lambda x: x.isna().sum()),
    )
    .reset_index()
)

display(product_summary.head(30))


# ------------------------------------------------------------
# 12. DIMENSION DISTRIBUTIONS
# ------------------------------------------------------------

print()
print("=" * 60)
print("DIMENSION DISTRIBUTIONS")
print("=" * 60)

for dimension in measurement_columns:

    print()
    print(f"--- {dimension} ---")

    print(
        measurements_df[dimension]
        .describe()
        .round(2)
    )


# ------------------------------------------------------------
# 13. EXTREME VALUES
# ------------------------------------------------------------

print()
print("=" * 60)
print("EXTREME VALUES")
print("=" * 60)

for dimension in measurement_columns:

    print()
    print(f"--- {dimension.upper()} ---")

    temp = measurements_df[
        ["file", "product", "size", dimension]
    ].dropna()

    print("Smallest:")
    display(temp.nsmallest(10, dimension))

    print("Largest:")
    display(temp.nlargest(10, dimension))


# ------------------------------------------------------------
# 14. SUSPICIOUS PRODUCTS SUMMARY
# ------------------------------------------------------------

if len(issues_df):

    suspicious_products = (
        issues_df
        .groupby("product")
        .agg(
            suspicious_values=("value", "count"),
            dimensions=("dimension", lambda x: ", ".join(sorted(set(x))))
        )
        .sort_values(
            "suspicious_values",
            ascending=False
        )
        .reset_index()
    )

else:

    suspicious_products = pd.DataFrame(
        columns=[
            "product",
            "suspicious_values",
            "dimensions"
        ]
    )


print()
print("=" * 60)
print("SUSPICIOUS PRODUCTS")
print("=" * 60)

display(suspicious_products.head(100))


# ------------------------------------------------------------
# 15. FINAL AUDIT SUMMARY
# ------------------------------------------------------------

print()
print("=" * 60)
print("FINAL AUDIT SUMMARY")
print("=" * 60)

print(f"Measurement files              : {len(files)}")
print(f"Parsed size-level rows         : {len(measurements_df)}")
print(f"Empty files                    : {len(empty_files)}")
print(f"Out-of-range values            : {len(issues_df)}")
print(f"Rows with missing dimensions   : {len(missing_df)}")
print(f"Duplicate size records         : {len(duplicate_rows)}")
print(f"Suspicious products            : {len(suspicious_products)}")

print()
print("IMPORTANT:")
print("This audit DOES NOT modify the VIBE dataset.")
print("No values have been repaired or deleted.")
print("The output is diagnostic only.")

============================================================
V2 GARMENT MEASUREMENT INTEGRITY AUDIT
============================================================
Dataset root : /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset
Measurement  : /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset/tops/garment_measurement
Exists       : True
Files found  : 1056

============================================================
PARSED DATA
============================================================
Files parsed : 897
Rows         : 3827

,file,product,size,bust,bust_raw,bust_dimension_name,waist,waist_raw,waist_dimension_name,hip,hip_raw,hip_dimension_name,length,length_raw,length_dimension_name,sleeve,sleeve_raw,sleeve_dimension_name
0,2-in-1-jumper#Navy_meta.txt,2-in-1-jumper#Navy,M,120.0,120cm,Bust,118.0,118cm,Waist,126.0,126cm,Hip,71.0,71-75cm,Length - shoulder to hem,65.0,65cm,Sleeve Length - neck to hem
1,2-in-1-layered-knit-top#Khaki_meta.txt,2-in-1-layered-knit-top#Khaki,M,114.0,114cm,Bust,124.0,124cm,Waist,138.0,138cm,Hip,61.0,61-70cm,Length - shoulder to hem,56.0,56cm,Sleeve Length - neck to hem
2,2-in-1-layered-knit-top#Navy_meta.txt,2-in-1-layered-knit-top#Navy,M,114.0,114cm,Bust,124.0,124cm,Waist,138.0,138cm,Hip,61.0,61-70cm,Length - shoulder to hem,56.0,56cm,Sleeve Length - neck to hem
3,2-in-1-layered-knit-top#PalePink_meta.txt,2-in-1-layered-knit-top#PalePink,M,114.0,114cm,Bust,124.0,124cm,Waist,138.0,138cm,Hip,61.0,61-70cm,Length - shoulder to hem,56.0,56cm,Sleeve Length - neck to hem
4,2-in-1-layered-top-1#NavyWhite_meta.txt,2-in-1-layered-top-1#NavyWhite,M,120.0,120cm,Bust,NaN,NaN,NaN,140.0,140cm,Hip,67.0,67cm,Length - shoulder to hem,67.0,67cm,Sleeve Length - neck to hem

============================================================
DIMENSION COMPLETENESS
============================================================
bust     | present= 3701 | missing=  126 | coverage= 96.71%
waist    | present= 2539 | missing= 1288 | coverage= 66.34%
hip      | present= 2952 | missing=  875 | coverage= 77.14%
length   | present= 3736 | missing=   91 | coverage= 97.62%
sleeve   | present= 3066 | missing=  761 | coverage= 80.11%

============================================================
OUT-OF-RANGE VALUES
============================================================
Suspicious values: 218

,file,product,size,dimension,value,lower_limit,upper_limit,issue
217,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,22,bust,240.0,50,180,OUT_OF_RANGE
216,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,20,bust,236.0,50,180,OUT_OF_RANGE
215,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,18,bust,232.0,50,180,OUT_OF_RANGE
214,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,16,bust,228.0,50,180,OUT_OF_RANGE
213,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,14,bust,224.0,50,180,OUT_OF_RANGE
...,...,...,...,...,...,...,...,...
147,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,10,bust,42.0,50,180,OUT_OF_RANGE
159,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,10,bust,42.0,50,180,OUT_OF_RANGE
144,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,8,bust,39.0,50,180,OUT_OF_RANGE
156,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,8,bust,39.0,50,180,OUT_OF_RANGE
89,stripe-me-happy-blouse#Ash_meta.txt,stripe-me-happy-blouse#Ash,18,bust,12.0,50,180,OUT_OF_RANGE

============================================================
EMPTY MEASUREMENT FILES
============================================================
Empty files: 33

34-sleeve-shirt#White_meta.txt
belle-bolero-cardi#BlueBonnet_meta.txt
bondi-babe-tank#BondiBabe_meta.txt
bondi-bare-singlet#Black_meta.txt
bondi-bare-singlet#RoseBeige_meta.txt
emma-scoop-tank#Black_meta.txt
emma-scoop-tank#SilverMarl_meta.txt
emma-scoop-tank#White_meta.txt
everyday-cord-tunic#Rust_meta.txt
fairisle-pullover#IceCombo_meta.txt
first-mix-top#BlackPintr_meta.txt
first-mix-top#CloudDance_meta.txt
french-cut-top#Black_meta.txt
french-cut-top#White_meta.txt
glom-mig-inte-tunic-1#PaleTulip_meta.txt
linen-resort-shirt#Peach_meta.txt
long-sleeve-luxe-shirt#Black_meta.txt
long-sleeve-luxe-shirt#Navy_meta.txt
madonna-ls-scoop-top#Black_meta.txt
madonna-ls-scoop-top#White_meta.txt
maternity-breast-feeding-cami#White_meta.txt
nova-lux-34-sleeve-top#AidaStripe_meta.txt
open-plains-kimono-throw#NavyFleur_meta.txt
parisienne-cami-1#Black_meta.txt
parisienne-cami-1#White_meta.txt
pin-spot-top#Black_meta.txt
silk-blend-cardigan#Honey_meta.txt
the-ribbon-jersey-tank#Stripe_meta.txt
the-swing-tee-5#Green_meta.txt
tina-singlet#Black_meta.txt
tina-singlet#White_meta.txt
turn-around-tunic#Black_meta.txt
turn-around-tunic#Navy_meta.txt

============================================================
MISSING DIMENSIONS
============================================================
Rows with missing dimensions: 1994

,file,product,size,missing_dimensions
0,2-in-1-layered-top-1#NavyWhite_meta.txt,2-in-1-layered-top-1#NavyWhite,M,waist
1,2-in-1-layered-top-1#PinkWhite_meta.txt,2-in-1-layered-top-1#PinkWhite,M,waist
2,animal-button-up-shirt#KhakiPrint_meta.txt,animal-button-up-shirt#KhakiPrint,12,waist
3,art-deco-print-top#NavyWhite_meta.txt,art-deco-print-top#NavyWhite,S,"waist, sleeve"
4,art-deco-print-top#NavyWhite_meta.txt,art-deco-print-top#NavyWhite,L,"waist, sleeve"
...,...,...,...,...
95,chasing-birds-blouse#White_meta.txt,chasing-birds-blouse#White,14,"waist, hip"
96,chasing-birds-blouse#White_meta.txt,chasing-birds-blouse#White,16,"waist, hip"
97,chasing-birds-blouse#White_meta.txt,chasing-birds-blouse#White,18,"waist, hip"
98,chasing-birds-blouse#White_meta.txt,chasing-birds-blouse#White,20,"waist, hip"
99,chasing-birds-blouse#White_meta.txt,chasing-birds-blouse#White,22,"waist, hip"

============================================================
DUPLICATE SIZE RECORDS
============================================================
Duplicate rows: 0

============================================================
PRODUCT SUMMARY
============================================================

,product,sizes,rows,bust_missing,waist_missing,hip_missing,length_missing,sleeve_missing
0,2-in-1-jumper#Navy,1,1,0,0,0,0,0
1,2-in-1-layered-knit-top#Khaki,1,1,0,0,0,0,0
2,2-in-1-layered-knit-top#Navy,1,1,0,0,0,0,0
3,2-in-1-layered-knit-top#PalePink,1,1,0,0,0,0,0
4,2-in-1-layered-top-1#NavyWhite,1,1,0,1,0,0,0
5,2-in-1-layered-top-1#PinkWhite,1,1,0,1,0,0,0
6,34-sleeve-shirt-1#SkyWhite,1,1,0,0,0,0,0
7,abigail-stripe-shirt#BlackStrip,1,1,0,0,0,0,0
8,adventurous-hoody#Pink,1,1,0,0,0,0,0
9,agra-shirt#White,1,1,0,0,0,0,0
10,aida-long-tunic-shirt#AidaStripe,1,1,0,0,0,0,0
11,aigli-top#Navy,1,1,0,0,0,0,0
12,aigli-top#White,1,1,0,0,0,0,0
13,alberta-stripe-top#IvoryStrip,1,1,0,0,0,0,0
14,aldis-blouse#Pearl,1,1,0,0,0,0,0
15,ally-long-sleeve-tee#CosmosPr,1,1,0,0,0,0,0
16,always-mine-spliced-cardigan#GreyEmeral,1,1,0,0,0,0,0
17,always-mine-v-neck-knit#Terracotta,1,1,0,0,0,0,0
18,amira-sweater#Cream,1,1,0,0,0,0,0
19,analia-jersey-top#Black,1,1,0,0,0,0,0
20,analia-jersey-top#Navy,1,1,0,0,0,0,0
21,analia-top#White,1,1,0,0,0,0,0
22,animal-button-up-shirt#KhakiPrint,1,1,0,1,0,0,0
23,animal-knit-1#Animal,1,1,0,0,0,0,0
24,anna-top#Leona,1,1,0,0,0,0,0
25,annabelle-sweater#Midnight,1,1,0,0,0,0,0
26,arizona-off-the-shoulder-top#Khaki,1,1,0,0,0,0,0
27,arlo-cardigan#Navy,1,1,0,0,0,0,0
28,art-deco-print-top#NavyWhite,6,6,0,5,0,0,5
29,arya-frilled-blouse#Oyster,1,1,0,0,0,0,0

============================================================
DIMENSION DISTRIBUTIONS
============================================================

--- bust ---
count    3701.00
mean      115.10
std        23.39
min        12.00
25%       101.00
50%       112.00
75%       125.00
max       240.00
Name: bust, dtype: float64

--- waist ---
count    2539.00
mean      112.06
std        46.67
min         5.00
25%        99.00
50%       110.00
75%       122.00
max      1181.00
Name: waist, dtype: float64

--- hip ---
count    2952.00
mean      125.89
std        32.85
min        15.00
25%       110.00
50%       123.00
75%       138.00
max      1230.00
Name: hip, dtype: float64

--- length ---
count    3736.00
mean       72.68
std        17.69
min         6.00
25%        64.00
50%        69.00
75%        76.00
max       678.00
Name: length, dtype: float64

--- sleeve ---
count    3066.00
mean       55.09
std        20.96
min         2.00
25%        42.00
50%        61.00
75%        69.00
max       554.00
Name: sleeve, dtype: float64

============================================================
EXTREME VALUES
============================================================

--- BUST ---
Smallest:

,file,product,size,bust
1818,stripe-me-happy-blouse#Ash_meta.txt,stripe-me-happy-blouse#Ash,18,12.0
2121,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,8,39.0
2129,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,8,39.0
2122,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,10,42.0
2130,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,10,42.0
2123,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,12,44.0
2131,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,12,44.0
2124,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,14,47.0
2132,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,14,47.0
2125,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,16,49.0

Largest:

,file,product,size,bust
3750,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,22,240.0
3749,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,20,236.0
3748,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,18,232.0
3747,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,16,228.0
3746,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,14,224.0
1371,on-safari-blouse#Jewel_meta.txt,on-safari-blouse#Jewel,OneSize,220.0
3745,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,12,220.0
1379,on-the-horizon-swing-top-1#Khaki_meta.txt,on-the-horizon-swing-top-1#Khaki,22,215.0
3743,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,8,212.0
1378,on-the-horizon-swing-top-1#Khaki_meta.txt,on-the-horizon-swing-top-1#Khaki,20,210.0

--- WAIST ---
Smallest:

,file,product,size,waist
2928,the-longline-waterfall-cardi#Black_meta.txt,the-longline-waterfall-cardi#Black,M,5.0
2929,the-longline-waterfall-cardi#Black_meta.txt,the-longline-waterfall-cardi#Black,L,10.0
479,cara-tee-2#BlackSpot_meta.txt,cara-tee-2#BlackSpot,12,11.0
480,cara-tee-2#Blush_meta.txt,cara-tee-2#Blush,12,11.0
481,cara-tee-2#WhiteBlk_meta.txt,cara-tee-2#WhiteBlk,12,11.0
2930,the-longline-waterfall-cardi#Black_meta.txt,the-longline-waterfall-cardi#Black,XL,15.0
2931,the-longline-waterfall-cardi#Black_meta.txt,the-longline-waterfall-cardi#Black,XXL,20.0
2121,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,8,36.0
2129,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,8,36.0
2122,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,10,38.0

Largest:

,file,product,size,waist
1948,sugar-snaps-throw-jacket#Black_meta.txt,sugar-snaps-throw-jacket#Black,22,1181.0
1956,sugar-snaps-throw-jacket#Duckegg_meta.txt,sugar-snaps-throw-jacket#Duckegg,22,1181.0
1964,sugar-snaps-throw-jacket#White_meta.txt,sugar-snaps-throw-jacket#White,22,1181.0
263,belle-off-the-shoulder-tee#Stripe_meta.txt,belle-off-the-shoulder-tee#Stripe,20,1123.0
1201,makeover-blouse#LimeGreen_meta.txt,makeover-blouse#LimeGreen,M,204.0
1036,leopard-print-kimono#GoldMulti_meta.txt,leopard-print-kimono#GoldMulti,14-16,200.0
1983,summer-whispers-kimono-1#Peacock_meta.txt,summer-whispers-kimono-1#Peacock,L-XL,191.0
800,flow-with-me-slouch-top#Brick_meta.txt,flow-with-me-slouch-top#Brick,22,187.0
799,flow-with-me-slouch-top#Brick_meta.txt,flow-with-me-slouch-top#Brick,20,182.0
1982,summer-whispers-kimono-1#Peacock_meta.txt,summer-whispers-kimono-1#Peacock,M-L,181.0

--- HIP ---
Smallest:

,file,product,size,hip
2439,the-cross-over-poncho#Grey_meta.txt,the-cross-over-poncho#Grey,14,15.0
2443,the-cross-over-poncho#Navy_meta.txt,the-cross-over-poncho#Navy,14,15.0
2121,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,8,44.0
2129,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,8,44.0
2122,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,10,47.0
2130,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,10,47.0
2123,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,12,49.0
2131,the-boat-neck-top#Navy_meta.txt,the-boat-neck-top#Navy,12,49.0
1313,natural-extra-fine-sweater#Snowgum_meta.txt,natural-extra-fine-sweater#Snowgum,S,51.0
2124,the-boat-neck-top#Black_meta.txt,the-boat-neck-top#Black,14,52.0

Largest:

,file,product,size,hip
1040,llama-long-sleeve-shirt#Mustard_meta.txt,llama-long-sleeve-shirt#Mustard,12,1230.0
893,hem-frill-stripe-top#Frilled_meta.txt,hem-frill-stripe-top#Frilled,22,290.0
901,hem-frill-stripe-top#SoFrilled_meta.txt,hem-frill-stripe-top#SoFrilled,22,290.0
892,hem-frill-stripe-top#Frilled_meta.txt,hem-frill-stripe-top#Frilled,20,285.0
900,hem-frill-stripe-top#SoFrilled_meta.txt,hem-frill-stripe-top#SoFrilled,20,285.0
891,hem-frill-stripe-top#Frilled_meta.txt,hem-frill-stripe-top#Frilled,18,280.0
899,hem-frill-stripe-top#SoFrilled_meta.txt,hem-frill-stripe-top#SoFrilled,18,280.0
890,hem-frill-stripe-top#Frilled_meta.txt,hem-frill-stripe-top#Frilled,16,275.0
898,hem-frill-stripe-top#SoFrilled_meta.txt,hem-frill-stripe-top#SoFrilled,16,275.0
889,hem-frill-stripe-top#Frilled_meta.txt,hem-frill-stripe-top#Frilled,14,270.0

--- LENGTH ---
Smallest:

,file,product,size,length
2548,the-daily-cross-over-top#PinkPrint_meta.txt,the-daily-cross-over-top#PinkPrint,16,6.0
2556,the-daily-cross-over-top#SkyBlue_meta.txt,the-daily-cross-over-top#SkyBlue,16,6.0
3717,to-the-beat-of-the-drum-kimono#Leaf_meta.txt,to-the-beat-of-the-drum-kimono#Leaf,L,13.0
2392,the-cross-over-blouse#Black_meta.txt,the-cross-over-blouse#Black,16,14.0
2398,the-cross-over-blouse#Blue_meta.txt,the-cross-over-blouse#Blue,16,14.0
2404,the-cross-over-blouse#Mint_meta.txt,the-cross-over-blouse#Mint,16,14.0
2410,the-cross-over-blouse#Red_meta.txt,the-cross-over-blouse#Red,16,14.0
2416,the-cross-over-blouse#RoyalBlue_meta.txt,the-cross-over-blouse#RoyalBlue,16,14.0
2422,the-cross-over-blouse#Silver_meta.txt,the-cross-over-blouse#Silver,16,14.0
2428,the-cross-over-blouse#Sunshine_meta.txt,the-cross-over-blouse#Sunshine,16,14.0

Largest:

,file,product,size,length
2766,the-french-cuff-shirt#White_meta.txt,the-french-cuff-shirt#White,12,678.0
439,butterfly-blouse-1#Ivory_meta.txt,butterfly-blouse-1#Ivory,12,132.0
3718,to-the-beat-of-the-drum-kimono#Leaf_meta.txt,to-the-beat-of-the-drum-kimono#Leaf,XL,132.0
1023,layla-long-line-kimono#MultiStrip_meta.txt,layla-long-line-kimono#MultiStrip,M/L,130.0
1035,lenka-lurex-stripe-blouse#NavyGoldSt_meta.txt,lenka-lurex-stripe-blouse#NavyGoldSt,12,130.0
1387,on-the-open-road-maxi-shirt#DarkOchre_meta.txt,on-the-open-road-maxi-shirt#DarkOchre,22,128.0
3716,to-the-beat-of-the-drum-kimono#Leaf_meta.txt,to-the-beat-of-the-drum-kimono#Leaf,M,128.0
1385,on-the-open-road-maxi-shirt#DarkOchre_meta.txt,on-the-open-road-maxi-shirt#DarkOchre,18,127.0
1386,on-the-open-road-maxi-shirt#DarkOchre_meta.txt,on-the-open-road-maxi-shirt#DarkOchre,20,127.0
1383,on-the-open-road-maxi-shirt#DarkOchre_meta.txt,on-the-open-road-maxi-shirt#DarkOchre,14,126.0

--- SLEEVE ---
Smallest:

,file,product,size,sleeve
1917,sugar-snaps-round-neck-layer-tank#Black_meta.txt,sugar-snaps-round-neck-layer-tank#Black,8,2.0
1925,sugar-snaps-round-neck-layer-tank#DuckEgg_meta...,sugar-snaps-round-neck-layer-tank#DuckEgg,8,2.0
1933,sugar-snaps-round-neck-layer-tank#White_meta.txt,sugar-snaps-round-neck-layer-tank#White,8,2.0
1918,sugar-snaps-round-neck-layer-tank#Black_meta.txt,sugar-snaps-round-neck-layer-tank#Black,10,3.0
1926,sugar-snaps-round-neck-layer-tank#DuckEgg_meta...,sugar-snaps-round-neck-layer-tank#DuckEgg,10,3.0
1934,sugar-snaps-round-neck-layer-tank#White_meta.txt,sugar-snaps-round-neck-layer-tank#White,10,3.0
42,bamboo-layer-tank#Black_meta.txt,bamboo-layer-tank#Black,S/M,4.0
43,bamboo-layer-tank#Chalk_meta.txt,bamboo-layer-tank#Chalk,S/M,4.0
184,belle-handkerchief-printed-cami#RustFlwrs_meta...,belle-handkerchief-printed-cami#RustFlwrs,8,4.0
3201,the-roll-neck-sleeveless-top-1#Black_meta.txt,the-roll-neck-sleeveless-top-1#Black,8,4.0

Largest:

,file,product,size,sleeve
3075,the-print-contrast-34-sleeve-top#Animal_meta.txt,the-print-contrast-34-sleeve-top#Animal,20,554.0
626,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,22,133.0
625,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,20,131.0
624,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,18,129.0
623,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,16,126.0
622,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,14,124.0
621,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,12,122.0
620,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,10,120.0
619,driftwood-gathering-blouse#Khaki_meta.txt,driftwood-gathering-blouse#Khaki,8,118.0
3042,the-pirate-in-me-shirt#White_meta.txt,the-pirate-in-me-shirt#White,18,104.0

============================================================
SUSPICIOUS PRODUCTS
============================================================

                             product  suspicious_values        dimensions
0             the-boat-neck-top#Navy                 12  bust, hip, waist
1            the-boat-neck-top#Black                 12  bust, hip, waist
2   on-the-horizon-swing-top-1#Khaki                 12         bust, hip
3                the-batwing-tee#Sea                  9              bust
4         the-batwing-tee#FrenchBlue                  9              bust
..                               ...                ...               ...
58              cara-tee-2#BlackSpot                  1             waist
59          butterfly-blouse-1#Ivory                  1            length
60       the-cross-over-blouse#Black                  1            length
61            on-safari-blouse#Jewel                  1              bust
62                be-mine-top-1#Sage                  1               hip

[63 rows x 3 columns]

============================================================
FINAL AUDIT SUMMARY
============================================================
Measurement files              : 1056
Parsed size-level rows         : 3827
Empty files                    : 33
Out-of-range values            : 218
Rows with missing dimensions   : 1994
Duplicate size records         : 0
Suspicious products            : 63

IMPORTANT:
This audit DOES NOT modify the VIBE dataset.
No values have been repaired or deleted.
The output is diagnostic only.

In [45]:
# ============================================================
# V2 — CORRUPTION ANALYSIS
# ============================================================

print("=" * 60)
print("V2 GARMENT CORRUPTION ANALYSIS")
print("=" * 60)

# Work from the parsed measurements dataframe
audit_df = measurements_df.copy()

# ------------------------------------------------------------
# 1. Mark suspicious values
# ------------------------------------------------------------

RANGES = {
    "bust":   (50, 180),
    "waist":  (45, 180),
    "hip":    (50, 190),
    "length": (30, 130),
    "sleeve": (0, 100),
}

for dimension, (low, high) in RANGES.items():

    audit_df[f"{dimension}_invalid"] = (
        audit_df[dimension].notna()
        & (
            (audit_df[dimension] < low)
            | (audit_df[dimension] > high)
        )
    )


invalid_columns = [
    f"{dimension}_invalid"
    for dimension in RANGES
]

audit_df["has_invalid_measurement"] = audit_df[
    invalid_columns
].any(axis=1)


# ------------------------------------------------------------
# 2. Product-level corruption summary
# ------------------------------------------------------------

product_corruption = (
    audit_df
    .groupby("product")
    .agg(
        size_count=("size", "count"),
        invalid_rows=("has_invalid_measurement", "sum"),
        invalid_bust=("bust_invalid", "sum"),
        invalid_waist=("waist_invalid", "sum"),
        invalid_hip=("hip_invalid", "sum"),
        invalid_length=("length_invalid", "sum"),
        invalid_sleeve=("sleeve_invalid", "sum"),
    )
    .reset_index()
)

product_corruption["invalid_percentage"] = (
    product_corruption["invalid_rows"]
    / product_corruption["size_count"]
    * 100
)

corrupt_products = product_corruption[
    product_corruption["invalid_rows"] > 0
].sort_values(
    ["invalid_rows", "invalid_percentage"],
    ascending=False
)

print()
print("Products with corruption:", len(corrupt_products))

display(corrupt_products)


# ------------------------------------------------------------
# 3. Exact corrupted records
# ------------------------------------------------------------

corrupt_rows = audit_df[
    audit_df["has_invalid_measurement"]
].copy()

print()
print("=" * 60)
print("EXACT CORRUPTED RECORDS")
print("=" * 60)

display(
    corrupt_rows[
        [
            "file",
            "product",
            "size",
            "bust",
            "waist",
            "hip",
            "length",
            "sleeve",
        ]
    ]
    .sort_values("product")
)


# ------------------------------------------------------------
# 4. Corruption by dimension
# ------------------------------------------------------------

print()
print("=" * 60)
print("CORRUPTION BY DIMENSION")
print("=" * 60)

for dimension in RANGES:

    column = f"{dimension}_invalid"

    count = int(audit_df[column].sum())

    print(
        f"{dimension:8s}: {count:4d} invalid records"
    )


# ------------------------------------------------------------
# 5. Products where EVERY size is corrupted
# ------------------------------------------------------------

fully_corrupt_products = corrupt_products[
    corrupt_products["invalid_rows"]
    == corrupt_products["size_count"]
]

print()
print("=" * 60)
print("FULLY CORRUPTED PRODUCTS")
print("=" * 60)

print(
    "Products where every parsed size has "
    "at least one invalid measurement:",
    len(fully_corrupt_products)
)

display(fully_corrupt_products)


# ------------------------------------------------------------
# 6. Products where only SOME sizes are corrupted
# ------------------------------------------------------------

partially_corrupt_products = corrupt_products[
    corrupt_products["invalid_rows"]
    < corrupt_products["size_count"]
]

print()
print("=" * 60)
print("PARTIALLY CORRUPTED PRODUCTS")
print("=" * 60)

print(
    "Products with both valid and invalid sizes:",
    len(partially_corrupt_products)
)

display(partially_corrupt_products)


# ------------------------------------------------------------
# 7. Final recommendation counts
# ------------------------------------------------------------

print()
print("=" * 60)
print("RECOMMENDATION COUNTS")
print("=" * 60)

print(
    "Total measurement rows :",
    len(audit_df)
)

print(
    "Valid rows              :",
    (~audit_df["has_invalid_measurement"]).sum()
)

print(
    "Corrupted rows          :",
    audit_df["has_invalid_measurement"].sum()
)

print(
    "Corrupted products      :",
    len(corrupt_products)
)

print(
    "Fully corrupted products:",
    len(fully_corrupt_products)
)

print(
    "Partially corrupted products:",
    len(partially_corrupt_products)
)

============================================================
V2 GARMENT CORRUPTION ANALYSIS
============================================================

Products with corruption: 63

,product,size_count,invalid_rows,invalid_bust,invalid_waist,invalid_hip,invalid_length,invalid_sleeve,invalid_percentage
628,the-batwing-tee#Black,9,9,9,0,0,0,0,100.000000
629,the-batwing-tee#FrenchBlue,9,9,9,0,0,0,0,100.000000
630,the-batwing-tee#Sea,9,9,9,0,0,0,0,100.000000
631,the-batwing-tee#Stone,9,9,9,0,0,0,0,100.000000
67,belle-mesh-cardi#Black,8,8,0,0,8,0,0,100.000000
...,...,...,...,...,...,...,...,...,...
699,the-daily-cross-over-top#SkyBlue,8,1,0,0,0,1,0,12.500000
726,the-french-cuff-shirt#White,8,1,0,0,0,1,0,12.500000
768,the-print-contrast-34-sleeve-top#Animal,8,1,0,0,0,0,1,12.500000
729,the-half-sleeve-tee#Black,9,1,1,0,0,0,0,11.111111
730,the-half-sleeve-tee#White,9,1,1,0,0,0,0,11.111111

============================================================
EXACT CORRUPTED RECORDS
============================================================

,file,product,size,bust,waist,hip,length,sleeve
57,be-mine-top-1#Sage_meta.txt,be-mine-top-1#Sage,22,NaN,139.0,191.0,68.0,35.0
59,beach-walk-shirt#Khaki_meta.txt,beach-walk-shirt#Khaki,10,184.0,NaN,NaN,96.0,62.0
60,beach-walk-shirt#Khaki_meta.txt,beach-walk-shirt#Khaki,12,188.0,NaN,NaN,97.0,63.0
61,beach-walk-shirt#Khaki_meta.txt,beach-walk-shirt#Khaki,14,192.0,NaN,NaN,98.0,64.0
62,beach-walk-shirt#Khaki_meta.txt,beach-walk-shirt#Khaki,16,196.0,NaN,NaN,99.0,65.0
...,...,...,...,...,...,...,...,...
3749,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,20,236.0,NaN,NaN,80.0,86.0
3744,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,10,208.0,NaN,NaN,75.0,81.0
3743,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,8,212.0,NaN,NaN,74.0,80.0
3745,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,12,220.0,NaN,NaN,76.0,82.0
3750,viola-kimono-radiant-floral#Grey_meta.txt,viola-kimono-radiant-floral#Grey,22,240.0,NaN,NaN,81.0,87.0

============================================================
CORRUPTION BY DIMENSION
============================================================
bust    :  100 invalid records
waist   :   27 invalid records
hip     :   64 invalid records
length  :   14 invalid records
sleeve  :   13 invalid records

============================================================
FULLY CORRUPTED PRODUCTS
============================================================
Products where every parsed size has at least one invalid measurement: 19

,product,size_count,invalid_rows,invalid_bust,invalid_waist,invalid_hip,invalid_length,invalid_sleeve,invalid_percentage
628,the-batwing-tee#Black,9,9,9,0,0,0,0,100.0
629,the-batwing-tee#FrenchBlue,9,9,9,0,0,0,0,100.0
630,the-batwing-tee#Sea,9,9,9,0,0,0,0,100.0
631,the-batwing-tee#Stone,9,9,9,0,0,0,0,100.0
67,belle-mesh-cardi#Black,8,8,0,0,8,0,0,100.0
184,driftwood-gathering-blouse#Khaki,8,8,0,0,0,0,8,100.0
277,hem-frill-stripe-top#Frilled,8,8,0,0,8,0,0,100.0
278,hem-frill-stripe-top#SoFrilled,8,8,0,0,8,0,0,100.0
869,viola-kimono-radiant-floral#Grey,8,8,8,0,0,0,0,100.0
111,butterfly-blouse-1#Ivory,1,1,0,0,0,1,0,100.0
125,cara-tee-2#BlackSpot,1,1,0,1,0,0,0,100.0
126,cara-tee-2#Blush,1,1,0,1,0,0,0,100.0
127,cara-tee-2#WhiteBlk,1,1,0,1,0,0,0,100.0
335,leopard-print-kimono#GoldMulti,1,1,1,1,0,0,0,100.0
339,llama-long-sleeve-shirt#Mustard,1,1,0,0,1,0,0,100.0
374,makeover-blouse#LimeGreen,1,1,1,1,1,0,0,100.0
458,on-safari-blouse#Jewel,1,1,1,0,0,0,0,100.0
578,soho-v-neck-blouse#SohoPrint,1,1,0,0,1,0,0,100.0
864,tuck-layer-shirt#White,1,1,0,0,1,0,0,100.0

============================================================
PARTIALLY CORRUPTED PRODUCTS
============================================================
Products with both valid and invalid sizes: 44

,product,size_count,invalid_rows,invalid_bust,invalid_waist,invalid_hip,invalid_length,invalid_sleeve,invalid_percentage
42,beach-walk-shirt#Khaki,8,7,7,0,0,0,0,87.500000
43,beach-walk-shirt#Stormy,8,7,7,0,0,0,0,87.500000
459,on-the-horizon-swing-top-1#Khaki,8,7,7,0,5,0,0,87.500000
645,the-button-up-swing-tunic#Wine,8,6,0,0,6,0,0,75.000000
618,sunshine-in-me-tee-1#GreyMarle,8,5,0,0,5,0,0,62.500000
619,sunshine-in-me-tee-1#White,8,5,0,0,5,0,0,62.500000
637,the-boat-neck-top#Black,8,5,5,4,3,0,0,62.500000
638,the-boat-neck-top#Navy,8,5,5,4,3,0,0,62.500000
747,the-longline-waterfall-cardi#Black,5,4,1,4,0,0,0,80.000000
756,the-oversize-knit#GreyMarle,5,4,4,0,0,0,0,80.000000
757,the-oversize-knit#Ink,5,4,4,0,0,0,0,80.000000
764,the-pirate-in-me-shirt#White,8,4,0,0,0,0,4,50.000000
159,cross-my-heart-bamboo-slouch-tee#White,8,3,3,0,0,0,0,37.500000
617,summer-whispers-kimono-1#Peacock,3,2,2,2,1,0,0,66.666667
858,to-the-beat-of-the-drum-kimono#Leaf,4,2,0,0,0,2,0,50.000000
440,natural-pattern-cocoon-cardigan#Blossom,5,2,2,0,0,0,0,40.000000
171,daisy-chain-tassel-blouse#DeepBlue,8,2,0,0,2,0,0,25.000000
222,flow-with-me-slouch-top#Brick,8,2,2,2,1,0,0,25.000000
467,paige-top#Black,8,2,0,2,0,0,0,25.000000
684,the-cross-over-poncho#Grey,4,1,0,0,1,0,0,25.000000
685,the-cross-over-poncho#Navy,4,1,0,0,1,0,0,25.000000
594,stripe-me-happy-blouse#Ash,6,1,1,0,0,0,0,16.666667
676,the-cross-over-blouse#Black,6,1,0,0,0,1,0,16.666667
677,the-cross-over-blouse#Blue,6,1,0,0,0,1,0,16.666667
678,the-cross-over-blouse#Mint,6,1,0,0,0,1,0,16.666667
679,the-cross-over-blouse#Red,6,1,0,0,0,1,0,16.666667
680,the-cross-over-blouse#RoyalBlue,6,1,0,0,0,1,0,16.666667
681,the-cross-over-blouse#Silver,6,1,0,0,0,1,0,16.666667
682,the-cross-over-blouse#Sunshine,6,1,0,0,0,1,0,16.666667
683,the-cross-over-blouse#White,6,1,0,0,0,1,0,16.666667
70,belle-off-the-shoulder-tee#Stripe,7,1,0,1,0,0,0,14.285714
41,be-mine-top-1#Sage,8,1,0,0,1,0,0,12.500000
362,long-sleeve-spot-top#Multispot,8,1,1,0,0,0,0,12.500000
561,softly-falling-bamboo-tunic#Copper,8,1,0,0,1,0,0,12.500000
562,softly-falling-bamboo-tunic#White,8,1,0,0,1,0,0,12.500000
612,sugar-snaps-throw-jacket#Black,8,1,0,1,0,0,0,12.500000
613,sugar-snaps-throw-jacket#Duckegg,8,1,0,1,0,0,0,12.500000
614,sugar-snaps-throw-jacket#White,8,1,0,1,0,0,0,12.500000
698,the-daily-cross-over-top#PinkPrint,8,1,0,0,0,1,0,12.500000
699,the-daily-cross-over-top#SkyBlue,8,1,0,0,0,1,0,12.500000
726,the-french-cuff-shirt#White,8,1,0,0,0,1,0,12.500000
768,the-print-contrast-34-sleeve-top#Animal,8,1,0,0,0,0,1,12.500000
729,the-half-sleeve-tee#Black,9,1,1,0,0,0,0,11.111111
730,the-half-sleeve-tee#White,9,1,1,0,0,0,0,11.111111

============================================================
RECOMMENDATION COUNTS
============================================================
Total measurement rows : 3827
Valid rows              : 3638
Corrupted rows          : 189
Corrupted products      : 63
Fully corrupted products: 19
Partially corrupted products: 44

In [47]:
# ============================================================
# V2 — SIZE PROGRESSION VALIDATION
# FIXED VERSION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 60)
print("V2 SIZE-PROGRESSION VALIDATION")
print("=" * 60)

df = measurements_df.copy()

# ------------------------------------------------------------
# Normalize column names
# ------------------------------------------------------------

df.columns = [str(c).strip().lower() for c in df.columns]

print("Columns:", list(df.columns))


# ------------------------------------------------------------
# Convert measurements to numeric
# ------------------------------------------------------------

dimensions = [
    "bust",
    "waist",
    "hip",
    "length",
    "sleeve",
]

for dimension in dimensions:
    df[dimension] = pd.to_numeric(
        df[dimension],
        errors="coerce"
    )


# ------------------------------------------------------------
# Convert clothing size to ordering value
# ------------------------------------------------------------

def size_to_number(value):

    if pd.isna(value):
        return np.nan

    s = str(value).strip().upper()

    # Numeric sizes
    try:
        return float(s)
    except ValueError:
        pass

    # Letter sizes
    mapping = {
        "XXXS": 0,
        "XXS": 1,
        "XS": 2,
        "S": 3,
        "M": 4,
        "L": 5,
        "XL": 6,
        "XXL": 7,
        "XXXL": 8,
    }

    return mapping.get(s, np.nan)


df["size_numeric"] = df["size"].apply(size_to_number)


# ------------------------------------------------------------
# Define suspicious measurement ranges
# ------------------------------------------------------------

RANGES = {
    "bust":   (50, 180),
    "waist":  (45, 180),
    "hip":    (50, 190),
    "length": (30, 130),
    "sleeve": (0, 100),
}

for dimension, (low, high) in RANGES.items():

    df[f"{dimension}_invalid"] = (
        df[dimension].notna()
        & (
            (df[dimension] < low)
            | (df[dimension] > high)
        )
    )


df["has_invalid"] = df[
    [f"{d}_invalid" for d in dimensions]
].any(axis=1)


# ------------------------------------------------------------
# Identify suspicious products
# ------------------------------------------------------------

suspicious_products = set(
    df.loc[df["has_invalid"], "product"]
)

print()
print("Suspicious products:", len(suspicious_products))


# ============================================================
# 1. SIZE PROGRESSION
# ============================================================

progression_rows = []

for product in sorted(suspicious_products):

    product_df = df[
        df["product"] == product
    ].copy()

    # Only rows with a usable size ordering
    product_df = product_df[
        product_df["size_numeric"].notna()
    ].sort_values("size_numeric")

    if len(product_df) < 2:
        continue

    for dimension in dimensions:

        values = product_df[
            [
                "size",
                "size_numeric",
                dimension,
            ]
        ].dropna(subset=[dimension])

        if len(values) < 2:
            continue

        values = values.sort_values("size_numeric")

        numeric_values = (
            values[dimension]
            .astype(float)
            .values
        )

        size_values = (
            values["size"]
            .values
        )

        diffs = np.diff(numeric_values)

        for i, diff in enumerate(diffs):

            if abs(diff) > 40:

                progression_rows.append({
                    "product": product,
                    "dimension": dimension,
                    "size_from": size_values[i],
                    "size_to": size_values[i + 1],
                    "value_from": numeric_values[i],
                    "value_to": numeric_values[i + 1],
                    "difference": diff,
                })


progression_df = pd.DataFrame(
    progression_rows
)


# ------------------------------------------------------------
# Display progression anomalies
# ------------------------------------------------------------

print()
print("=" * 60)
print("LARGE SIZE-TO-SIZE JUMPS")
print("=" * 60)

if progression_df.empty:

    print("No large size-to-size jumps found.")

else:

    progression_df = progression_df.sort_values(
        [
            "product",
            "dimension",
            "size_from",
        ]
    )

    print(
        "Potentially corrupted transitions:",
        len(progression_df)
    )

    display(progression_df)


# ============================================================
# 2. COMPLETE SUSPICIOUS PRODUCT RECORDS
# ============================================================

print()
print("=" * 60)
print("COMPLETE RECORDS FOR SUSPICIOUS PRODUCTS")
print("=" * 60)

suspicious_detail = df[
    df["product"].isin(suspicious_products)
].copy()

# IMPORTANT:
# Keep size_numeric while sorting.
suspicious_detail = suspicious_detail.sort_values(
    [
        "product",
        "size_numeric",
    ],
    na_position="last"
)

display(
    suspicious_detail[
        [
            "product",
            "size",
            "size_numeric",
            "bust",
            "waist",
            "hip",
            "length",
            "sleeve",
            "has_invalid",
        ]
    ]
)


# ============================================================
# 3. INVALID VALUES BY DIMENSION
# ============================================================

print()
print("=" * 60)
print("INVALID VALUES BY DIMENSION")
print("=" * 60)

for dimension in dimensions:

    count = int(
        df[f"{dimension}_invalid"].sum()
    )

    print(
        f"{dimension:8s}: {count:4d}"
    )


# ============================================================
# 4. PRODUCTS WITH ISOLATED CORRUPTION
# ============================================================

print()
print("=" * 60)
print("PRODUCTS WITH ISOLATED CORRUPTION")
print("=" * 60)

isolated = []

for product in sorted(suspicious_products):

    p = df[
        df["product"] == product
    ]

    invalid_count = int(
        p["has_invalid"].sum()
    )

    total_count = len(p)

    if invalid_count < total_count:

        isolated.append({
            "product": product,
            "total_sizes": total_count,
            "invalid_sizes": invalid_count,
            "valid_sizes": (
                total_count - invalid_count
            ),
        })


isolated_df = pd.DataFrame(isolated)

print(
    "Products where some sizes are valid:",
    len(isolated_df)
)

display(isolated_df)


# ============================================================
# 5. FULLY CORRUPTED PRODUCTS
# ============================================================

print()
print("=" * 60)
print("FULLY CORRUPTED PRODUCTS")
print("=" * 60)

fully_corrupt = []

for product in sorted(suspicious_products):

    p = df[
        df["product"] == product
    ]

    invalid_count = int(
        p["has_invalid"].sum()
    )

    total_count = len(p)

    if invalid_count == total_count:

        fully_corrupt.append({
            "product": product,
            "sizes": total_count,
        })


fully_corrupt_df = pd.DataFrame(
    fully_corrupt
)

print(
    "Fully corrupted products:",
    len(fully_corrupt_df)
)

display(fully_corrupt_df)


# ============================================================
# 6. SUMMARY
# ============================================================

print()
print("=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print(
    "Total measurement rows :",
    len(df)
)

print(
    "Valid rows             :",
    int((~df["has_invalid"]).sum())
)

print(
    "Corrupted rows         :",
    int(df["has_invalid"].sum())
)

print(
    "Corrupted products     :",
    len(suspicious_products)
)

print(
    "Fully corrupted products:",
    len(fully_corrupt_df)
)

print(
    "Partially corrupted products:",
    len(isolated_df)
)

============================================================
V2 SIZE-PROGRESSION VALIDATION
============================================================
Columns: ['file', 'product', 'size', 'bust', 'bust_raw', 'bust_dimension_name', 'waist', 'waist_raw', 'waist_dimension_name', 'hip', 'hip_raw', 'hip_dimension_name', 'length', 'length_raw', 'length_dimension_name', 'sleeve', 'sleeve_raw', 'sleeve_dimension_name']

Suspicious products: 63

============================================================
LARGE SIZE-TO-SIZE JUMPS
============================================================
Potentially corrupted transitions: 44

,product,dimension,size_from,size_to,value_from,value_to,difference
0,belle-off-the-shoulder-tee#Stripe,waist,18,20,107.0,1123.0,1016.0
1,belle-off-the-shoulder-tee#Stripe,waist,20,22,1123.0,117.0,-1006.0
2,softly-falling-bamboo-tunic#Copper,bust,18,20,116.0,60.0,-56.0
3,softly-falling-bamboo-tunic#Copper,bust,20,22,60.0,126.0,66.0
4,softly-falling-bamboo-tunic#Copper,hip,14,16,134.0,192.0,58.0
5,softly-falling-bamboo-tunic#Copper,hip,16,18,192.0,144.0,-48.0
6,softly-falling-bamboo-tunic#White,bust,18,20,116.0,60.0,-56.0
7,softly-falling-bamboo-tunic#White,bust,20,22,60.0,126.0,66.0
8,softly-falling-bamboo-tunic#White,hip,14,16,134.0,192.0,58.0
9,softly-falling-bamboo-tunic#White,hip,16,18,192.0,144.0,-48.0
10,stripe-me-happy-blouse#Ash,bust,16,18,137.0,12.0,-125.0
11,sugar-snaps-throw-jacket#Black,waist,20,22,176.0,1181.0,1005.0
12,sugar-snaps-throw-jacket#Duckegg,waist,20,22,176.0,1181.0,1005.0
13,sugar-snaps-throw-jacket#White,waist,20,22,176.0,1181.0,1005.0
14,the-cross-over-blouse#Black,length,14,16,81.0,14.0,-67.0
15,the-cross-over-blouse#Black,length,16,18,14.0,86.0,72.0
16,the-cross-over-blouse#Blue,length,14,16,81.0,14.0,-67.0
17,the-cross-over-blouse#Blue,length,16,18,14.0,86.0,72.0
18,the-cross-over-blouse#Mint,length,14,16,81.0,14.0,-67.0
19,the-cross-over-blouse#Mint,length,16,18,14.0,86.0,72.0
20,the-cross-over-blouse#Red,length,14,16,81.0,14.0,-67.0
21,the-cross-over-blouse#Red,length,16,18,14.0,86.0,72.0
22,the-cross-over-blouse#RoyalBlue,length,14,16,81.0,14.0,-67.0
23,the-cross-over-blouse#RoyalBlue,length,16,18,14.0,86.0,72.0
24,the-cross-over-blouse#Silver,length,14,16,81.0,14.0,-67.0
25,the-cross-over-blouse#Silver,length,16,18,14.0,86.0,72.0
26,the-cross-over-blouse#Sunshine,length,14,16,81.0,14.0,-67.0
27,the-cross-over-blouse#Sunshine,length,16,18,14.0,86.0,72.0
28,the-cross-over-blouse#White,length,14,16,81.0,14.0,-67.0
29,the-cross-over-blouse#White,length,16,18,14.0,86.0,72.0
30,the-cross-over-poncho#Grey,hip,12,14,110.0,15.0,-95.0
31,the-cross-over-poncho#Navy,hip,12,14,110.0,15.0,-95.0
32,the-daily-cross-over-top#PinkPrint,length,14,16,68.0,6.0,-62.0
33,the-daily-cross-over-top#PinkPrint,length,16,18,6.0,70.0,64.0
34,the-daily-cross-over-top#SkyBlue,length,14,16,68.0,6.0,-62.0
35,the-daily-cross-over-top#SkyBlue,length,16,18,6.0,70.0,64.0
36,the-french-cuff-shirt#White,length,10,12,67.0,678.0,611.0
37,the-french-cuff-shirt#White,length,12,14,678.0,69.0,-609.0
38,the-half-sleeve-tee#Black,bust,20,22,116.0,201.0,85.0
39,the-half-sleeve-tee#White,bust,20,22,116.0,201.0,85.0
40,the-print-contrast-34-sleeve-top#Animal,sleeve,18,20,52.0,554.0,502.0
41,the-print-contrast-34-sleeve-top#Animal,sleeve,20,22,554.0,55.0,-499.0
43,to-the-beat-of-the-drum-kimono#Leaf,length,L,XL,13.0,132.0,119.0
42,to-the-beat-of-the-drum-kimono#Leaf,length,M,L,128.0,13.0,-115.0

============================================================
COMPLETE RECORDS FOR SUSPICIOUS PRODUCTS
============================================================

,product,size,size_numeric,bust,waist,hip,length,sleeve,has_invalid
50,be-mine-top-1#Sage,8,8.0,NaN,104.0,156.0,61.0,32.0,False
51,be-mine-top-1#Sage,10,10.0,NaN,109.0,161.0,62.0,32.0,False
52,be-mine-top-1#Sage,12,12.0,NaN,114.0,166.0,63.0,33.0,False
53,be-mine-top-1#Sage,14,14.0,NaN,119.0,171.0,64.0,33.0,False
54,be-mine-top-1#Sage,16,16.0,NaN,124.0,176.0,65.0,34.0,False
...,...,...,...,...,...,...,...,...,...
3746,viola-kimono-radiant-floral#Grey,14,14.0,224.0,NaN,NaN,77.0,83.0,True
3747,viola-kimono-radiant-floral#Grey,16,16.0,228.0,NaN,NaN,78.0,84.0,True
3748,viola-kimono-radiant-floral#Grey,18,18.0,232.0,NaN,NaN,79.0,85.0,True
3749,viola-kimono-radiant-floral#Grey,20,20.0,236.0,NaN,NaN,80.0,86.0,True
3750,viola-kimono-radiant-floral#Grey,22,22.0,240.0,NaN,NaN,81.0,87.0,True

============================================================
INVALID VALUES BY DIMENSION
============================================================
bust    :  100
waist   :   27
hip     :   64
length  :   14
sleeve  :   13

============================================================
PRODUCTS WITH ISOLATED CORRUPTION
============================================================
Products where some sizes are valid: 44

,product,total_sizes,invalid_sizes,valid_sizes
0,be-mine-top-1#Sage,8,1,7
1,beach-walk-shirt#Khaki,8,7,1
2,beach-walk-shirt#Stormy,8,7,1
3,belle-off-the-shoulder-tee#Stripe,7,1,6
4,cross-my-heart-bamboo-slouch-tee#White,8,3,5
5,daisy-chain-tassel-blouse#DeepBlue,8,2,6
6,flow-with-me-slouch-top#Brick,8,2,6
7,long-sleeve-spot-top#Multispot,8,1,7
8,natural-pattern-cocoon-cardigan#Blossom,5,2,3
9,on-the-horizon-swing-top-1#Khaki,8,7,1
10,paige-top#Black,8,2,6
11,softly-falling-bamboo-tunic#Copper,8,1,7
12,softly-falling-bamboo-tunic#White,8,1,7
13,stripe-me-happy-blouse#Ash,6,1,5
14,sugar-snaps-throw-jacket#Black,8,1,7
15,sugar-snaps-throw-jacket#Duckegg,8,1,7
16,sugar-snaps-throw-jacket#White,8,1,7
17,summer-whispers-kimono-1#Peacock,3,2,1
18,sunshine-in-me-tee-1#GreyMarle,8,5,3
19,sunshine-in-me-tee-1#White,8,5,3
20,the-boat-neck-top#Black,8,5,3
21,the-boat-neck-top#Navy,8,5,3
22,the-button-up-swing-tunic#Wine,8,6,2
23,the-cross-over-blouse#Black,6,1,5
24,the-cross-over-blouse#Blue,6,1,5
25,the-cross-over-blouse#Mint,6,1,5
26,the-cross-over-blouse#Red,6,1,5
27,the-cross-over-blouse#RoyalBlue,6,1,5
28,the-cross-over-blouse#Silver,6,1,5
29,the-cross-over-blouse#Sunshine,6,1,5
30,the-cross-over-blouse#White,6,1,5
31,the-cross-over-poncho#Grey,4,1,3
32,the-cross-over-poncho#Navy,4,1,3
33,the-daily-cross-over-top#PinkPrint,8,1,7
34,the-daily-cross-over-top#SkyBlue,8,1,7
35,the-french-cuff-shirt#White,8,1,7
36,the-half-sleeve-tee#Black,9,1,8
37,the-half-sleeve-tee#White,9,1,8
38,the-longline-waterfall-cardi#Black,5,4,1
39,the-oversize-knit#GreyMarle,5,4,1
40,the-oversize-knit#Ink,5,4,1
41,the-pirate-in-me-shirt#White,8,4,4
42,the-print-contrast-34-sleeve-top#Animal,8,1,7
43,to-the-beat-of-the-drum-kimono#Leaf,4,2,2

============================================================
FULLY CORRUPTED PRODUCTS
============================================================
Fully corrupted products: 19

                             product  sizes
0             belle-mesh-cardi#Black      8
1           butterfly-blouse-1#Ivory      1
2               cara-tee-2#BlackSpot      1
3                   cara-tee-2#Blush      1
4                cara-tee-2#WhiteBlk      1
5   driftwood-gathering-blouse#Khaki      8
6       hem-frill-stripe-top#Frilled      8
7     hem-frill-stripe-top#SoFrilled      8
8     leopard-print-kimono#GoldMulti      1
9    llama-long-sleeve-shirt#Mustard      1
10         makeover-blouse#LimeGreen      1
11            on-safari-blouse#Jewel      1
12      soho-v-neck-blouse#SohoPrint      1
13             the-batwing-tee#Black      9
14        the-batwing-tee#FrenchBlue      9
15               the-batwing-tee#Sea      9
16             the-batwing-tee#Stone      9
17            tuck-layer-shirt#White      1
18  viola-kimono-radiant-floral#Grey      8

============================================================
FINAL SUMMARY
============================================================
Total measurement rows : 3827
Valid rows             : 3638
Corrupted rows         : 189
Corrupted products     : 63
Fully corrupted products: 19
Partially corrupted products: 44

In [48]:
# ============================================================
# V2 — COMPACT CORRUPTION REPORT
# ============================================================

print("=" * 60)
print("COMPACT CORRUPTION REPORT")
print("=" * 60)

# 1. Every invalid record
invalid_records = df[df["has_invalid"]].copy()

print("\nInvalid records:", len(invalid_records))

display(
    invalid_records[
        [
            "product",
            "size",
            "bust",
            "waist",
            "hip",
            "length",
            "sleeve",
        ]
    ].head(100)
)


# 2. Count invalid records per product
product_summary = (
    df.groupby("product")
      .agg(
          total_sizes=("product", "size"),
          invalid_sizes=("has_invalid", "sum")
      )
      .reset_index()
)

product_summary["valid_sizes"] = (
    product_summary["total_sizes"]
    - product_summary["invalid_sizes"]
)

product_summary = product_summary[
    product_summary["invalid_sizes"] > 0
].sort_values(
    ["invalid_sizes", "total_sizes"],
    ascending=False
)

print("\n" + "=" * 60)
print("CORRUPTED PRODUCT SUMMARY")
print("=" * 60)

display(product_summary)


# 3. Dimension-specific invalid values
print("\n" + "=" * 60)
print("DIMENSION ANOMALIES")
print("=" * 60)

for dimension, (low, high) in RANGES.items():

    mask = df[f"{dimension}_invalid"]

    bad = df.loc[
        mask,
        ["product", "size", dimension]
    ].copy()

    print(
        f"\n{dimension.upper()} "
        f"({len(bad)} invalid)"
    )

    if not bad.empty:
        display(bad.head(50))


# 4. Recalculate size progression anomalies
print("\n" + "=" * 60)
print("SIZE PROGRESSION ANOMALIES")
print("=" * 60)

progression_rows = []

for product in sorted(suspicious_products):

    p = df[
        df["product"] == product
    ].copy()

    p = p[
        p["size_numeric"].notna()
    ].sort_values("size_numeric")

    if len(p) < 2:
        continue

    for dimension in dimensions:

        v = p[
            ["size", "size_numeric", dimension]
        ].dropna(subset=[dimension])

        if len(v) < 2:
            continue

        v = v.sort_values("size_numeric")

        vals = v[dimension].astype(float).values
        sizes = v["size"].values

        diffs = np.diff(vals)

        for i, diff in enumerate(diffs):

            if abs(diff) > 40:

                progression_rows.append({
                    "product": product,
                    "dimension": dimension,
                    "size_from": sizes[i],
                    "size_to": sizes[i + 1],
                    "value_from": vals[i],
                    "value_to": vals[i + 1],
                    "difference": diff,
                })

progression_df = pd.DataFrame(
    progression_rows
)

if progression_df.empty:
    print("No large progression anomalies.")

else:
    progression_df = progression_df.sort_values(
        ["product", "dimension"]
    )

    print(
        "Large transitions:",
        len(progression_df)
    )

    display(progression_df)

============================================================
COMPACT CORRUPTION REPORT
============================================================

Invalid records: 189

                     product size   bust  waist    hip  length  sleeve
57        be-mine-top-1#Sage   22    NaN  139.0  191.0    68.0    35.0
59    beach-walk-shirt#Khaki   10  184.0    NaN    NaN    96.0    62.0
60    beach-walk-shirt#Khaki   12  188.0    NaN    NaN    97.0    63.0
61    beach-walk-shirt#Khaki   14  192.0    NaN    NaN    98.0    64.0
62    beach-walk-shirt#Khaki   16  196.0    NaN    NaN    99.0    65.0
...                      ...  ...    ...    ...    ...     ...     ...
2052   the-batwing-tee#Black    8  205.0    NaN    NaN    65.0    49.0
2053   the-batwing-tee#Black   10  205.0    NaN    NaN    67.0    50.0
2054   the-batwing-tee#Black   12  205.0  104.0   90.0    69.0    51.0
2055   the-batwing-tee#Black   14  205.0    NaN    NaN    71.0    52.0
2056   the-batwing-tee#Black   16  205.0    NaN    NaN    73.0    53.0

[100 rows x 7 columns]

============================================================
CORRUPTED PRODUCT SUMMARY
============================================================

                             product  total_sizes  invalid_sizes  valid_sizes
628            the-batwing-tee#Black            9              9            0
629       the-batwing-tee#FrenchBlue            9              9            0
630              the-batwing-tee#Sea            9              9            0
631            the-batwing-tee#Stone            9              9            0
67            belle-mesh-cardi#Black            8              8            0
..                               ...          ...            ...          ...
339  llama-long-sleeve-shirt#Mustard            1              1            0
374        makeover-blouse#LimeGreen            1              1            0
458           on-safari-blouse#Jewel            1              1            0
578     soho-v-neck-blouse#SohoPrint            1              1            0
864           tuck-layer-shirt#White            1              1            0

[63 rows x 4 columns]

============================================================
DIMENSION ANOMALIES
============================================================

BUST (100 invalid)

                                      product     size   bust
59                     beach-walk-shirt#Khaki       10  184.0
60                     beach-walk-shirt#Khaki       12  188.0
61                     beach-walk-shirt#Khaki       14  192.0
62                     beach-walk-shirt#Khaki       16  196.0
63                     beach-walk-shirt#Khaki       18  200.0
64                     beach-walk-shirt#Khaki       20  204.0
65                     beach-walk-shirt#Khaki       22  208.0
67                    beach-walk-shirt#Stormy       10  184.0
68                    beach-walk-shirt#Stormy       12  188.0
69                    beach-walk-shirt#Stormy       14  192.0
70                    beach-walk-shirt#Stormy       16  196.0
71                    beach-walk-shirt#Stormy       18  200.0
72                    beach-walk-shirt#Stormy       20  204.0
73                    beach-walk-shirt#Stormy       22  208.0
565    cross-my-heart-bamboo-slouch-tee#White       18  186.0
566    cross-my-heart-bamboo-slouch-tee#White       20  190.0
567    cross-my-heart-bamboo-slouch-tee#White       22  196.0
799             flow-with-me-slouch-top#Brick       20  184.0
800             flow-with-me-slouch-top#Brick       22  189.0
1036           leopard-print-kimono#GoldMulti    14-16  200.0
1189           long-sleeve-spot-top#Multispot       22  182.0
1201                makeover-blouse#LimeGreen        M  204.0
1326  natural-pattern-cocoon-cardigan#Blossom       XL  185.0
1327  natural-pattern-cocoon-cardigan#Blossom      XXL  190.0
1371                   on-safari-blouse#Jewel  OneSize  220.0
1373         on-the-horizon-swing-top-1#Khaki       10  185.0
1374         on-the-horizon-swing-top-1#Khaki       12  190.0
1375         on-the-horizon-swing-top-1#Khaki       14  195.0
1376         on-the-horizon-swing-top-1#Khaki       16  200.0
1377         on-the-horizon-swing-top-1#Khaki       18  205.0
1378         on-the-horizon-swing-top-1#Khaki       20  210.0
1379         on-the-horizon-swing-top-1#Khaki       22  215.0
1818               stripe-me-happy-blouse#Ash       18   12.0
1982         summer-whispers-kimono-1#Peacock      M-L  181.0
1983         summer-whispers-kimono-1#Peacock     L-XL  191.0
2051                    the-batwing-tee#Black        6  205.0
2052                    the-batwing-tee#Black        8  205.0
2053                    the-batwing-tee#Black       10  205.0
2054                    the-batwing-tee#Black       12  205.0
2055                    the-batwing-tee#Black       14  205.0
2056                    the-batwing-tee#Black       16  205.0
2057                    the-batwing-tee#Black       18  205.0
2058                    the-batwing-tee#Black       20  205.0
2059                    the-batwing-tee#Black       22  205.0
2060               the-batwing-tee#FrenchBlue        6  205.0
2061               the-batwing-tee#FrenchBlue        8  205.0
2062               the-batwing-tee#FrenchBlue       10  205.0
2063               the-batwing-tee#FrenchBlue       12  205.0
2064               the-batwing-tee#FrenchBlue       14  205.0
2065               the-batwing-tee#FrenchBlue       16  205.0

WAIST (27 invalid)

                                 product   size   waist
263    belle-off-the-shoulder-tee#Stripe     20  1123.0
479                 cara-tee-2#BlackSpot     12    11.0
480                     cara-tee-2#Blush     12    11.0
481                  cara-tee-2#WhiteBlk     12    11.0
799        flow-with-me-slouch-top#Brick     20   182.0
800        flow-with-me-slouch-top#Brick     22   187.0
1036      leopard-print-kimono#GoldMulti  14-16   200.0
1201           makeover-blouse#LimeGreen      M   204.0
1394                     paige-top#Black      8    42.0
1395                     paige-top#Black     10    44.0
1948      sugar-snaps-throw-jacket#Black     22  1181.0
1956    sugar-snaps-throw-jacket#Duckegg     22  1181.0
1964      sugar-snaps-throw-jacket#White     22  1181.0
1982    summer-whispers-kimono-1#Peacock    M-L   181.0
1983    summer-whispers-kimono-1#Peacock   L-XL   191.0
2121             the-boat-neck-top#Black      8    36.0
2122             the-boat-neck-top#Black     10    38.0
2123             the-boat-neck-top#Black     12    41.0
2124             the-boat-neck-top#Black     14    43.0
2129              the-boat-neck-top#Navy      8    36.0
2130              the-boat-neck-top#Navy     10    38.0
2131              the-boat-neck-top#Navy     12    41.0
2132              the-boat-neck-top#Navy     14    43.0
2928  the-longline-waterfall-cardi#Black      M     5.0
2929  the-longline-waterfall-cardi#Black      L    10.0
2930  the-longline-waterfall-cardi#Black     XL    15.0
2931  the-longline-waterfall-cardi#Black    XXL    20.0

HIP (64 invalid)

                                 product  size     hip
57                    be-mine-top-1#Sage    22   191.0
234               belle-mesh-cardi#Black     8   194.0
235               belle-mesh-cardi#Black    10   199.0
236               belle-mesh-cardi#Black    12   204.0
237               belle-mesh-cardi#Black    14   209.0
238               belle-mesh-cardi#Black    16   214.0
239               belle-mesh-cardi#Black    18   219.0
240               belle-mesh-cardi#Black    20   224.0
241               belle-mesh-cardi#Black    22   229.0
605   daisy-chain-tassel-blouse#DeepBlue    20   192.0
606   daisy-chain-tassel-blouse#DeepBlue    22   196.0
800        flow-with-me-slouch-top#Brick    22   195.0
886         hem-frill-stripe-top#Frilled     8   255.0
887         hem-frill-stripe-top#Frilled    10   260.0
888         hem-frill-stripe-top#Frilled    12   265.0
889         hem-frill-stripe-top#Frilled    14   270.0
890         hem-frill-stripe-top#Frilled    16   275.0
891         hem-frill-stripe-top#Frilled    18   280.0
892         hem-frill-stripe-top#Frilled    20   285.0
893         hem-frill-stripe-top#Frilled    22   290.0
894       hem-frill-stripe-top#SoFrilled     8   255.0
895       hem-frill-stripe-top#SoFrilled    10   260.0
896       hem-frill-stripe-top#SoFrilled    12   265.0
897       hem-frill-stripe-top#SoFrilled    14   270.0
898       hem-frill-stripe-top#SoFrilled    16   275.0
899       hem-frill-stripe-top#SoFrilled    18   280.0
900       hem-frill-stripe-top#SoFrilled    20   285.0
901       hem-frill-stripe-top#SoFrilled    22   290.0
1040     llama-long-sleeve-shirt#Mustard    12  1230.0
1201           makeover-blouse#LimeGreen     M   204.0
1375    on-the-horizon-swing-top-1#Khaki    14   193.0
1376    on-the-horizon-swing-top-1#Khaki    16   198.0
1377    on-the-horizon-swing-top-1#Khaki    18   203.0
1378    on-the-horizon-swing-top-1#Khaki    20   208.0
1379    on-the-horizon-swing-top-1#Khaki    22   213.0
1660  softly-falling-bamboo-tunic#Copper    16   192.0
1668   softly-falling-bamboo-tunic#White    16   192.0
1785        soho-v-neck-blouse#SohoPrint    12   202.0
1983    summer-whispers-kimono-1#Peacock  L-XL   199.0
1987      sunshine-in-me-tee-1#GreyMarle    14   191.0
1988      sunshine-in-me-tee-1#GreyMarle    16   193.0
1989      sunshine-in-me-tee-1#GreyMarle    18   196.0
1990      sunshine-in-me-tee-1#GreyMarle    20   198.0
1991      sunshine-in-me-tee-1#GreyMarle    22   201.0
1995          sunshine-in-me-tee-1#White    14   191.0
1996          sunshine-in-me-tee-1#White    16   193.0
1997          sunshine-in-me-tee-1#White    18   196.0
1998          sunshine-in-me-tee-1#White    20   198.0
1999          sunshine-in-me-tee-1#White    22   201.0
2121             the-boat-neck-top#Black     8    44.0

LENGTH (14 invalid)

                                  product size  length
439              butterfly-blouse-1#Ivory   12   132.0
2392          the-cross-over-blouse#Black   16    14.0
2398           the-cross-over-blouse#Blue   16    14.0
2404           the-cross-over-blouse#Mint   16    14.0
2410            the-cross-over-blouse#Red   16    14.0
2416      the-cross-over-blouse#RoyalBlue   16    14.0
2422         the-cross-over-blouse#Silver   16    14.0
2428       the-cross-over-blouse#Sunshine   16    14.0
2434          the-cross-over-blouse#White   16    14.0
2548   the-daily-cross-over-top#PinkPrint   16     6.0
2556     the-daily-cross-over-top#SkyBlue   16     6.0
2766          the-french-cuff-shirt#White   12   678.0
3717  to-the-beat-of-the-drum-kimono#Leaf    L    13.0
3718  to-the-beat-of-the-drum-kimono#Leaf   XL   132.0

SLEEVE (13 invalid)

                                      product size  sleeve
619          driftwood-gathering-blouse#Khaki    8   118.0
620          driftwood-gathering-blouse#Khaki   10   120.0
621          driftwood-gathering-blouse#Khaki   12   122.0
622          driftwood-gathering-blouse#Khaki   14   124.0
623          driftwood-gathering-blouse#Khaki   16   126.0
624          driftwood-gathering-blouse#Khaki   18   129.0
625          driftwood-gathering-blouse#Khaki   20   131.0
626          driftwood-gathering-blouse#Khaki   22   133.0
3041             the-pirate-in-me-shirt#White   16   102.0
3042             the-pirate-in-me-shirt#White   18   104.0
3043             the-pirate-in-me-shirt#White   20   104.0
3044             the-pirate-in-me-shirt#White   22   104.0
3075  the-print-contrast-34-sleeve-top#Animal   20   554.0

============================================================
SIZE PROGRESSION ANOMALIES
============================================================
Large transitions: 44

,product,dimension,size_from,size_to,value_from,value_to,difference
0,belle-off-the-shoulder-tee#Stripe,waist,18,20,107.0,1123.0,1016.0
1,belle-off-the-shoulder-tee#Stripe,waist,20,22,1123.0,117.0,-1006.0
2,softly-falling-bamboo-tunic#Copper,bust,18,20,116.0,60.0,-56.0
3,softly-falling-bamboo-tunic#Copper,bust,20,22,60.0,126.0,66.0
4,softly-falling-bamboo-tunic#Copper,hip,14,16,134.0,192.0,58.0
5,softly-falling-bamboo-tunic#Copper,hip,16,18,192.0,144.0,-48.0
6,softly-falling-bamboo-tunic#White,bust,18,20,116.0,60.0,-56.0
7,softly-falling-bamboo-tunic#White,bust,20,22,60.0,126.0,66.0
8,softly-falling-bamboo-tunic#White,hip,14,16,134.0,192.0,58.0
9,softly-falling-bamboo-tunic#White,hip,16,18,192.0,144.0,-48.0
10,stripe-me-happy-blouse#Ash,bust,16,18,137.0,12.0,-125.0
11,sugar-snaps-throw-jacket#Black,waist,20,22,176.0,1181.0,1005.0
12,sugar-snaps-throw-jacket#Duckegg,waist,20,22,176.0,1181.0,1005.0
13,sugar-snaps-throw-jacket#White,waist,20,22,176.0,1181.0,1005.0
14,the-cross-over-blouse#Black,length,14,16,81.0,14.0,-67.0
15,the-cross-over-blouse#Black,length,16,18,14.0,86.0,72.0
16,the-cross-over-blouse#Blue,length,14,16,81.0,14.0,-67.0
17,the-cross-over-blouse#Blue,length,16,18,14.0,86.0,72.0
18,the-cross-over-blouse#Mint,length,14,16,81.0,14.0,-67.0
19,the-cross-over-blouse#Mint,length,16,18,14.0,86.0,72.0
20,the-cross-over-blouse#Red,length,14,16,81.0,14.0,-67.0
21,the-cross-over-blouse#Red,length,16,18,14.0,86.0,72.0
22,the-cross-over-blouse#RoyalBlue,length,14,16,81.0,14.0,-67.0
23,the-cross-over-blouse#RoyalBlue,length,16,18,14.0,86.0,72.0
24,the-cross-over-blouse#Silver,length,14,16,81.0,14.0,-67.0
25,the-cross-over-blouse#Silver,length,16,18,14.0,86.0,72.0
26,the-cross-over-blouse#Sunshine,length,14,16,81.0,14.0,-67.0
27,the-cross-over-blouse#Sunshine,length,16,18,14.0,86.0,72.0
28,the-cross-over-blouse#White,length,14,16,81.0,14.0,-67.0
29,the-cross-over-blouse#White,length,16,18,14.0,86.0,72.0
30,the-cross-over-poncho#Grey,hip,12,14,110.0,15.0,-95.0
31,the-cross-over-poncho#Navy,hip,12,14,110.0,15.0,-95.0
32,the-daily-cross-over-top#PinkPrint,length,14,16,68.0,6.0,-62.0
33,the-daily-cross-over-top#PinkPrint,length,16,18,6.0,70.0,64.0
34,the-daily-cross-over-top#SkyBlue,length,14,16,68.0,6.0,-62.0
35,the-daily-cross-over-top#SkyBlue,length,16,18,6.0,70.0,64.0
36,the-french-cuff-shirt#White,length,10,12,67.0,678.0,611.0
37,the-french-cuff-shirt#White,length,12,14,678.0,69.0,-609.0
38,the-half-sleeve-tee#Black,bust,20,22,116.0,201.0,85.0
39,the-half-sleeve-tee#White,bust,20,22,116.0,201.0,85.0
40,the-print-contrast-34-sleeve-top#Animal,sleeve,18,20,52.0,554.0,502.0
41,the-print-contrast-34-sleeve-top#Animal,sleeve,20,22,554.0,55.0,-499.0
42,to-the-beat-of-the-drum-kimono#Leaf,length,M,L,128.0,13.0,-115.0
43,to-the-beat-of-the-drum-kimono#Leaf,length,L,XL,13.0,132.0,119.0

In [49]:
# ============================================================
# V2 — GARMENT MEASUREMENT CLEANING
# ============================================================

import json
import math
import re
from pathlib import Path

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

DATASET_ROOT = Path.home() / "Desktop/Projects/weavly/core-model/VIBE/dataset"
GARMENT_DIR = DATASET_ROOT / "tops/garment_measurement"

OUTPUT_DIR = Path.home() / "Desktop/Projects/weavly/core-model/data/v2"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_CSV = OUTPUT_DIR / "clean_garment_measurements.csv"
OUTPUT_REPORT = OUTPUT_DIR / "garment_cleaning_report.csv"

print("Dataset :", DATASET_ROOT)
print("Input   :", GARMENT_DIR)
print("Output  :", OUTPUT_CSV)

# ------------------------------------------------------------
# VALID PHYSICAL RANGES
#
# These are deliberately broad sanity bounds.
# They are NOT intended to encode fashion/fit preferences.
# They only remove obvious parser/source corruption.
# ------------------------------------------------------------

VALID_RANGES = {
    "bust":   (50.0, 180.0),
    "waist":  (50.0, 180.0),
    "hip":    (50.0, 180.0),
    "length": (30.0, 150.0),
    "sleeve": (20.0, 140.0),
}

# ------------------------------------------------------------
# DIMENSION NAME NORMALIZATION
# ------------------------------------------------------------

def normalize_dimension(name):
    name = name.lower().strip()

    if "bust" in name:
        return "bust"

    if "waist" in name:
        return "waist"

    if "hip" in name:
        return "hip"

    if "length" in name:
        return "length"

    if "sleeve" in name:
        return "sleeve"

    return None


# ------------------------------------------------------------
# VALUE PARSER
# ------------------------------------------------------------

def parse_measurement(value):
    """
    Convert values such as:

        '92cm'
        '92 cm'
        '92'
        92

    into float centimeters.

    Anything that cannot be safely parsed becomes NaN.
    """

    if value is None:
        return np.nan

    if isinstance(value, (int, float)):
        value = float(value)

        if math.isfinite(value):
            return value

        return np.nan

    value = str(value).strip().lower()

    if not value:
        return np.nan

    match = re.search(r"-?\d+(?:\.\d+)?", value)

    if not match:
        return np.nan

    try:
        number = float(match.group())
    except ValueError:
        return np.nan

    if not math.isfinite(number):
        return np.nan

    return number


# ------------------------------------------------------------
# PRODUCT ID
# ------------------------------------------------------------

def product_id_from_file(path):
    """
    Example:

    long-sleeve-tee-2#NavyWhite_meta.txt

    -> long-sleeve-tee-2#NavyWhite
    """

    name = path.stem

    if name.endswith("_meta"):
        name = name[:-5]

    return name


# ------------------------------------------------------------
# READ ONE FILE
# ------------------------------------------------------------

def read_measurement_file(path):

    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
    except Exception as e:
        return None, f"JSON_ERROR: {e}"

    # Some files may contain JSON encoded as a string.
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except Exception as e:
            return None, f"STRING_JSON_ERROR: {e}"

    if not isinstance(raw, dict):
        return None, "INVALID_ROOT"

    return raw, None


# ------------------------------------------------------------
# PROCESS DATASET
# ------------------------------------------------------------

rows = []
cleaning_events = []

files = sorted(GARMENT_DIR.glob("*.txt"))

print("\nFiles found:", len(files))

for path in files:

    product = product_id_from_file(path)

    data, error = read_measurement_file(path)

    if error:
        cleaning_events.append({
            "product": product,
            "dimension": None,
            "original_value": None,
            "cleaned_value": np.nan,
            "reason": error,
        })
        continue

    if not data:
        cleaning_events.append({
            "product": product,
            "dimension": None,
            "original_value": None,
            "cleaned_value": np.nan,
            "reason": "EMPTY_FILE",
        })
        continue

    # --------------------------------------------------------
    # JSON structure:
    #
    # {
    #   "12": [
    #       {
    #           "dimension_name": "Bust",
    #           "value": "92cm"
    #       }
    #   ]
    # }
    # --------------------------------------------------------

    measurements = {
        "bust": np.nan,
        "waist": np.nan,
        "hip": np.nan,
        "length": np.nan,
        "sleeve": np.nan,
    }

    # Track whether we actually saw each dimension.
    seen = set()

    for entries in data.values():

        # Defensive handling of malformed structures.
        if not isinstance(entries, list):
            continue

        for item in entries:

            if not isinstance(item, dict):
                continue

            dimension_name = item.get("dimension_name")
            raw_value = item.get("value")

            dimension = normalize_dimension(
                dimension_name if dimension_name is not None else ""
            )

            if dimension is None:
                continue

            seen.add(dimension)

            value = parse_measurement(raw_value)

            lower, upper = VALID_RANGES[dimension]

            if np.isnan(value):
                cleaning_events.append({
                    "product": product,
                    "dimension": dimension,
                    "original_value": raw_value,
                    "cleaned_value": np.nan,
                    "reason": "UNPARSEABLE",
                })

                continue

            # ------------------------------------------------
            # HARD SANITY CHECK
            # ------------------------------------------------

            if value < lower or value > upper:

                cleaning_events.append({
                    "product": product,
                    "dimension": dimension,
                    "original_value": raw_value,
                    "cleaned_value": np.nan,
                    "reason": f"OUT_OF_RANGE_{lower}_{upper}",
                })

                continue

            measurements[dimension] = value

    # --------------------------------------------------------
    # Keep product even if some dimensions are missing.
    # --------------------------------------------------------

    row = {
        "product_id": product,
        "garment_bust": measurements["bust"],
        "garment_waist": measurements["waist"],
        "garment_hip": measurements["hip"],
        "garment_length": measurements["length"],
        "garment_sleeve": measurements["sleeve"],
    }

    rows.append(row)


# ------------------------------------------------------------
# DATAFRAME
# ------------------------------------------------------------

clean_df = pd.DataFrame(rows)

# Remove exact duplicate products if any.
clean_df = (
    clean_df
    .drop_duplicates(subset=["product_id"], keep="first")
    .reset_index(drop=True)
)

report_df = pd.DataFrame(cleaning_events)

# ------------------------------------------------------------
# PRODUCT QUALITY FLAGS
# ------------------------------------------------------------

measurement_columns = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

clean_df["valid_dimension_count"] = (
    clean_df[measurement_columns]
    .notna()
    .sum(axis=1)
)

clean_df["fully_missing_measurements"] = (
    clean_df["valid_dimension_count"] == 0
)

clean_df["partially_missing_measurements"] = (
    (clean_df["valid_dimension_count"] > 0) &
    (clean_df["valid_dimension_count"] < len(measurement_columns))
)

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

clean_df.to_csv(OUTPUT_CSV, index=False)
report_df.to_csv(OUTPUT_REPORT, index=False)

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("V2 GARMENT CLEANING SUMMARY")
print("=" * 60)

print("Input files              :", len(files))
print("Products retained        :", len(clean_df))

print(
    "Products with measurements:",
    int((clean_df["valid_dimension_count"] > 0).sum())
)

print(
    "Fully missing products    :",
    int(clean_df["fully_missing_measurements"].sum())
)

print(
    "Partially missing products:",
    int(clean_df["partially_missing_measurements"].sum())
)

print(
    "Cleaning events           :",
    len(report_df)
)

print("\nMissing dimensions after cleaning:")

print(
    clean_df[measurement_columns]
    .isna()
    .sum()
)

print("\nClean measurement statistics:")

print(
    clean_df[measurement_columns]
    .describe()
    .round(2)
)

print("\nSaved:")
print("  ", OUTPUT_CSV)
print("  ", OUTPUT_REPORT)

Dataset : /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset
Input   : /Users/saketh/Desktop/Projects/weavly/core-model/VIBE/dataset/tops/garment_measurement
Output  : /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/clean_garment_measurements.csv

Files found: 1056

============================================================
V2 GARMENT CLEANING SUMMARY
============================================================
Input files              : 1056
Products retained        : 897
Products with measurements: 897
Fully missing products    : 0
Partially missing products: 897
Cleaning events           : 821

Missing dimensions after cleaning:
garment_bust       26
garment_waist     168
garment_hip       125
garment_length      3
garment_sleeve    897
dtype: int64

Clean measurement statistics:
       garment_bust  garment_waist  garment_hip  garment_length  \
count        871.00         729.00       772.00          894.00
mean         120.48         117.16       126.85           64.91
std           19.21          18.61        22.16           14.26
min           57.00          53.00        58.00           30.00
25%          106.00         104.00       110.00           59.00
50%          120.00         116.00       124.00           67.00
75%          130.00         128.00       142.00           72.00
max          180.00         180.00       180.00          133.00

       garment_sleeve
count             0.0
mean              NaN
std               NaN
min               NaN
25%               NaN
50%               NaN
75%               NaN
max               NaN

Saved:
   /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/clean_garment_measurements.csv
   /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/garment_cleaning_report.csv

In [50]:
# ============================================================
# V2 — FIX DIMENSION PARSER + REBUILD CLEAN DATASET
# ============================================================

# IMPORTANT:
# "Sleeve Length" must be detected BEFORE generic "Length".

def normalize_dimension(name):
    name = name.lower().strip()

    # MUST come first
    if "sleeve" in name:
        return "sleeve"

    if "bust" in name:
        return "bust"

    if "waist" in name:
        return "waist"

    if "hip" in name:
        return "hip"

    if "length" in name:
        return "length"

    return None


# ------------------------------------------------------------
# REBUILD
# ------------------------------------------------------------

rows = []
cleaning_events = []

files = sorted(GARMENT_DIR.glob("*.txt"))

for path in files:

    product = product_id_from_file(path)

    data, error = read_measurement_file(path)

    if error:
        cleaning_events.append({
            "product": product,
            "dimension": None,
            "original_value": None,
            "cleaned_value": np.nan,
            "reason": error,
        })
        continue

    if not data:
        cleaning_events.append({
            "product": product,
            "dimension": None,
            "original_value": None,
            "cleaned_value": np.nan,
            "reason": "EMPTY_FILE",
        })
        continue

    measurements = {
        "bust": np.nan,
        "waist": np.nan,
        "hip": np.nan,
        "length": np.nan,
        "sleeve": np.nan,
    }

    for entries in data.values():

        if not isinstance(entries, list):
            continue

        for item in entries:

            if not isinstance(item, dict):
                continue

            dimension_name = item.get("dimension_name", "")
            raw_value = item.get("value")

            dimension = normalize_dimension(dimension_name)

            if dimension is None:
                continue

            value = parse_measurement(raw_value)

            lower, upper = VALID_RANGES[dimension]

            if np.isnan(value):

                cleaning_events.append({
                    "product": product,
                    "dimension": dimension,
                    "original_value": raw_value,
                    "cleaned_value": np.nan,
                    "reason": "UNPARSEABLE",
                })

                continue

            if value < lower or value > upper:

                cleaning_events.append({
                    "product": product,
                    "dimension": dimension,
                    "original_value": raw_value,
                    "cleaned_value": np.nan,
                    "reason": f"OUT_OF_RANGE_{lower}_{upper}",
                })

                continue

            measurements[dimension] = value

    rows.append({
        "product_id": product,
        "garment_bust": measurements["bust"],
        "garment_waist": measurements["waist"],
        "garment_hip": measurements["hip"],
        "garment_length": measurements["length"],
        "garment_sleeve": measurements["sleeve"],
    })


# ------------------------------------------------------------
# DATAFRAME
# ------------------------------------------------------------

clean_df = pd.DataFrame(rows)

clean_df = (
    clean_df
    .drop_duplicates(subset=["product_id"], keep="first")
    .reset_index(drop=True)
)

report_df = pd.DataFrame(cleaning_events)

measurement_columns = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

clean_df["valid_dimension_count"] = (
    clean_df[measurement_columns]
    .notna()
    .sum(axis=1)
)

clean_df["fully_missing_measurements"] = (
    clean_df["valid_dimension_count"] == 0
)

clean_df["partially_missing_measurements"] = (
    (clean_df["valid_dimension_count"] > 0) &
    (clean_df["valid_dimension_count"] < 5)
)


# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

clean_df.to_csv(OUTPUT_CSV, index=False)
report_df.to_csv(OUTPUT_REPORT, index=False)


# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("=" * 60)
print("V2 GARMENT CLEANING — CORRECTED")
print("=" * 60)

print("Input files               :", len(files))
print("Products retained         :", len(clean_df))
print(
    "Products with measurements:",
    int((clean_df["valid_dimension_count"] > 0).sum())
)
print(
    "Fully missing products    :",
    int(clean_df["fully_missing_measurements"].sum())
)
print(
    "Partially missing products:",
    int(clean_df["partially_missing_measurements"].sum())
)
print("Cleaning events           :", len(report_df))

print("\nMissing dimensions:")
print(
    clean_df[measurement_columns]
    .isna()
    .sum()
)

print("\nMissing percentages:")
print(
    (clean_df[measurement_columns].isna().mean() * 100)
    .round(2)
)

print("\nClean statistics:")
print(
    clean_df[measurement_columns]
    .describe()
    .round(2)
)

print("\nSaved:")
print(" ", OUTPUT_CSV)
print(" ", OUTPUT_REPORT)

============================================================
V2 GARMENT CLEANING — CORRECTED
============================================================
Input files               : 1056
Products retained         : 897
Products with measurements: 897
Fully missing products    : 0
Partially missing products: 326
Cleaning events           : 534

Missing dimensions:
garment_bust       26
garment_waist     168
garment_hip       125
garment_length     12
garment_sleeve    143
dtype: int64

Missing percentages:
garment_bust       2.90
garment_waist     18.73
garment_hip       13.94
garment_length     1.34
garment_sleeve    15.94
dtype: float64

Clean statistics:
       garment_bust  garment_waist  garment_hip  garment_length  \
count        871.00         729.00       772.00          885.00
mean         120.48         117.16       126.85           72.26
std           19.21          18.61        22.16           13.93
min           57.00          53.00        58.00           46.00
25%          106.00         104.00       110.00           64.00
50%          120.00         116.00       124.00           69.00
75%          130.00         128.00       142.00           76.00
max          180.00         180.00       180.00          132.00

       garment_sleeve
count          754.00
mean            59.27
std             15.93
min             20.00
25%             51.00
50%             65.00
75%             71.00
max            133.00

Saved:
  /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/clean_garment_measurements.csv
  /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/garment_cleaning_report.csv

In [51]:
# ============================================================
# V2 — REBUILD COMPATIBILITY DATASET FROM CLEAN MEASUREMENTS
# ============================================================

import json
import random
from pathlib import Path

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

CORE_ROOT = Path.home() / "Desktop/Projects/weavly/core-model"

HUMAN_FILE = (
    CORE_ROOT
    / "VIBE/dataset/humans/model.json"
)

CLEAN_GARMENT_FILE = (
    CORE_ROOT
    / "data/v2/clean_garment_measurements.csv"
)

OUTPUT_FILE = (
    CORE_ROOT
    / "data/v2/v2_compatibility_raw.csv"
)


# ------------------------------------------------------------
# REPRODUCIBILITY
# ------------------------------------------------------------

SEED = 42

random.seed(SEED)
np.random.seed(SEED)


# ------------------------------------------------------------
# LOAD HUMANS
# ------------------------------------------------------------

with open(HUMAN_FILE, "r", encoding="utf-8") as f:
    humans = json.load(f)

human_df = pd.DataFrame.from_dict(
    humans,
    orient="index"
)

human_df.index.name = "person_id"
human_df = human_df.reset_index()

for col in ["height", "bust", "waist", "hips"]:
    human_df[col] = pd.to_numeric(
        human_df[col],
        errors="coerce"
    )


# ------------------------------------------------------------
# LOAD CLEAN GARMENTS
# ------------------------------------------------------------

garment_df = pd.read_csv(
    CLEAN_GARMENT_FILE
)

garment_df = garment_df[
    [
        "product_id",
        "garment_bust",
        "garment_waist",
        "garment_hip",
        "garment_length",
        "garment_sleeve",
    ]
].copy()


# ------------------------------------------------------------
# NORMALIZE MODEL NAMES
# ------------------------------------------------------------

def normalize_person_name(name):
    """
    Normalize known duplicate model naming.

    Examples:
        Emma_1 -> Emma
        Emma_2 -> Emma
        Maddy_1 -> Maddy
        Maddy_2 -> Maddy
        Natalie_1 -> Natalie
        Natalie_2 -> Natalie
        Nathalie_1 -> Nathalie
        Nathalie_2 -> Nathalie
        Monika  -> Monika
    """

    name = str(name).strip()

    if name.endswith("_1") or name.endswith("_2"):
        name = name[:-2]

    return name


# Create canonical human profiles.
#
# IMPORTANT:
# When duplicate profiles exist, we retain them as separate
# profiles internally rather than averaging measurements.
# For compatibility-pair construction, the garment-side names
# will be mapped to the matching canonical person where possible.

canonical_humans = {}

for person_id, row in human_df.set_index("person_id").iterrows():

    canonical = normalize_person_name(person_id)

    # Keep the first profile for now.
    # We will audit duplicate-profile handling separately.
    if canonical not in canonical_humans:

        canonical_humans[canonical] = {
            "person_id": canonical,
            "height": row["height"],
            "bust": row["bust"],
            "waist": row["waist"],
            "hips": row["hips"],
        }


canonical_human_df = pd.DataFrame(
    canonical_humans.values()
)


# ------------------------------------------------------------
# LOAD POSITIVE MODEL-GARMENT RELATIONSHIPS
# ------------------------------------------------------------

GARMENT_PAIR_DIR = (
    CORE_ROOT
    / "VIBE/dataset/tops/model_measurement"
)

positive_rows = []

for file in sorted(GARMENT_PAIR_DIR.glob("*.txt")):

    product = file.stem

    if product.endswith("_meta"):
        product = product[:-5]

    try:

        with open(file, "r", encoding="utf-8") as f:
            data = json.load(f)

    except Exception:

        continue

    if isinstance(data, str):

        try:
            data = json.loads(data)
        except Exception:
            continue

    if not isinstance(data, dict):
        continue

    for raw_person in data.keys():

        person = normalize_person_name(raw_person)

        # Only retain people for whom we have a canonical profile.
        if person not in canonical_humans:
            continue

        positive_rows.append({
            "person_id": person,
            "product_id": product,
            "label": 1,
        })


positive_df = pd.DataFrame(
    positive_rows
)

# Remove duplicate relationships.
positive_df = positive_df.drop_duplicates(
    subset=["person_id", "product_id"]
)


# ------------------------------------------------------------
# KEEP ONLY CLEAN PRODUCTS
# ------------------------------------------------------------

valid_products = set(
    garment_df["product_id"]
)

positive_df = positive_df[
    positive_df["product_id"].isin(valid_products)
].copy()


# ------------------------------------------------------------
# NEGATIVE SAMPLING
# ------------------------------------------------------------

all_products = sorted(
    valid_products
)

positive_lookup = (
    positive_df
    .groupby("person_id")["product_id"]
    .apply(set)
    .to_dict()
)

negative_rows = []

for person, positive_products in positive_lookup.items():

    candidates = [
        p
        for p in all_products
        if p not in positive_products
    ]

    random.shuffle(candidates)

    # 1:1 negative sampling.
    n_negative = min(
        len(positive_products),
        len(candidates)
    )

    for product in candidates[:n_negative]:

        negative_rows.append({
            "person_id": person,
            "product_id": product,
            "label": 0,
        })


negative_df = pd.DataFrame(
    negative_rows
)


# ------------------------------------------------------------
# COMBINE
# ------------------------------------------------------------

compatibility_df = pd.concat(
    [
        positive_df,
        negative_df,
    ],
    ignore_index=True
)

compatibility_df = compatibility_df.sample(
    frac=1,
    random_state=SEED
).reset_index(drop=True)


# ------------------------------------------------------------
# MERGE PERSON FEATURES
# ------------------------------------------------------------

compatibility_df = compatibility_df.merge(
    canonical_human_df,
    on="person_id",
    how="inner"
)


# ------------------------------------------------------------
# MERGE GARMENT FEATURES
# ------------------------------------------------------------

compatibility_df = compatibility_df.merge(
    garment_df,
    on="product_id",
    how="inner"
)


# ------------------------------------------------------------
# MODEL SIZE
# ------------------------------------------------------------

# We deliberately preserve model size only where available.
# It is useful metadata but should not be treated as a numerical
# measurement in the compatibility features yet.

model_size_lookup = {}

for file in sorted(GARMENT_PAIR_DIR.glob("*.txt")):

    product = file.stem

    if product.endswith("_meta"):
        product = product[:-5]

    try:

        with open(file, "r", encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, str):
            data = json.loads(data)

    except Exception:
        continue

    if not isinstance(data, dict):
        continue

    for raw_person, info in data.items():

        person = normalize_person_name(raw_person)

        if not isinstance(info, dict):
            continue

        size = info.get("size")

        if size is not None:
            model_size_lookup[
                (person, product)
            ] = str(size)


compatibility_df["model_size"] = [
    model_size_lookup.get(
        (row["person_id"], row["product_id"]),
        np.nan
    )
    for _, row in compatibility_df.iterrows()
]


# ------------------------------------------------------------
# DERIVED COMPATIBILITY FEATURES
# ------------------------------------------------------------

compatibility_df["bust_ease"] = (
    compatibility_df["garment_bust"]
    - compatibility_df["bust"]
)

compatibility_df["waist_ease"] = (
    compatibility_df["garment_waist"]
    - compatibility_df["waist"]
)

compatibility_df["hip_ease"] = (
    compatibility_df["garment_hip"]
    - compatibility_df["hips"]
)

compatibility_df["length_height_ratio"] = (
    compatibility_df["garment_length"]
    / compatibility_df["height"]
)


# ------------------------------------------------------------
# EXPLICIT MISSINGNESS INDICATORS
# ------------------------------------------------------------

compatibility_df["missing_bust"] = (
    compatibility_df["garment_bust"].isna().astype(int)
)

compatibility_df["missing_waist"] = (
    compatibility_df["garment_waist"].isna().astype(int)
)

compatibility_df["missing_hip"] = (
    compatibility_df["garment_hip"].isna().astype(int)
)

compatibility_df["missing_length"] = (
    compatibility_df["garment_length"].isna().astype(int)
)

compatibility_df["missing_sleeve"] = (
    compatibility_df["garment_sleeve"].isna().astype(int)
)


# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

compatibility_df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ------------------------------------------------------------
# REPORT
# ------------------------------------------------------------

print("=" * 60)
print("V2 COMPATIBILITY DATASET — REBUILT")
print("=" * 60)

print("Human profiles        :", len(canonical_human_df))
print("Clean garments        :", len(garment_df))

print()
print("Positive pairs        :", len(positive_df))
print("Negative pairs        :", len(negative_df))
print("Total pairs           :", len(compatibility_df))

print()
print("Unique people         :",
      compatibility_df["person_id"].nunique())

print("Unique garments       :",
      compatibility_df["product_id"].nunique())

print()
print("Labels:")
print(
    compatibility_df["label"]
    .value_counts()
    .sort_index()
)

print()
print("Missing garment dimensions:")

print(
    compatibility_df[
        [
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .isna()
    .sum()
)

print()
print("Derived feature missingness:")

print(
    compatibility_df[
        [
            "bust_ease",
            "waist_ease",
            "hip_ease",
            "length_height_ratio",
            "garment_sleeve",
        ]
    ]
    .isna()
    .sum()
)

print()
print("Saved:")
print(OUTPUT_FILE)

============================================================
V2 COMPATIBILITY DATASET — REBUILT
============================================================
Human profiles        : 57
Clean garments        : 897

Positive pairs        : 2990
Negative pairs        : 2990
Total pairs           : 5980

Unique people         : 56
Unique garments       : 897

Labels:
label
0    2990
1    2990
Name: count, dtype: int64

Missing garment dimensions:
garment_bust       274
garment_waist     1231
garment_hip        883
garment_length      58
garment_sleeve    1073
dtype: int64

Derived feature missingness:
bust_ease               274
waist_ease             1231
hip_ease                883
length_height_ratio      58
garment_sleeve         1073
dtype: int64

Saved:
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_compatibility_raw.csv

In [52]:
# ============================================================
# V2 — IDENTITY + JOIN INTEGRITY AUDIT
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

DATASET = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_compatibility_raw.csv"
)

df = pd.read_csv(DATASET)

print("=" * 60)
print("V2 IDENTITY + JOIN INTEGRITY AUDIT")
print("=" * 60)

# ------------------------------------------------------------
# BASIC COUNTS
# ------------------------------------------------------------

print("\nBasic:")
print("Rows             :", len(df))
print("People           :", df["person_id"].nunique())
print("Garments         :", df["product_id"].nunique())

print("\nLabels:")
print(df["label"].value_counts().sort_index())


# ------------------------------------------------------------
# PERSON PROFILE COMPLETENESS
# ------------------------------------------------------------

person_cols = [
    "height",
    "bust",
    "waist",
    "hips",
]

print("\n" + "=" * 60)
print("PERSON PROFILE INTEGRITY")
print("=" * 60)

print(
    df.groupby("person_id")[person_cols]
      .nunique()
      .max(axis=1)
      .describe()
)

# Every person should have one consistent body profile.
person_variations = (
    df.groupby("person_id")[person_cols]
      .nunique()
)

bad_people = person_variations[
    person_variations.max(axis=1) > 1
]

print(
    "\nPeople with inconsistent profiles:",
    len(bad_people)
)

if len(bad_people):
    print(bad_people)


# ------------------------------------------------------------
# PRODUCT MEASUREMENT CONSISTENCY
# ------------------------------------------------------------

garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

print("\n" + "=" * 60)
print("GARMENT MEASUREMENT INTEGRITY")
print("=" * 60)

product_variations = (
    df.groupby("product_id")[garment_cols]
      .nunique(dropna=True)
)

bad_products = product_variations[
    product_variations.max(axis=1) > 1
]

print(
    "Products with inconsistent measurements:",
    len(bad_products)
)

if len(bad_products):
    print(bad_products.head(20))


# ------------------------------------------------------------
# DUPLICATE PAIRS
# ------------------------------------------------------------

duplicates = df.duplicated(
    subset=["person_id", "product_id", "label"],
    keep=False
)

print("\n" + "=" * 60)
print("DUPLICATE PAIRS")
print("=" * 60)

print(
    "Duplicate person-product-label rows:",
    duplicates.sum()
)


# ------------------------------------------------------------
# SAME PERSON + PRODUCT WITH BOTH LABELS
# ------------------------------------------------------------

conflicting_pairs = (
    df.groupby(["person_id", "product_id"])["label"]
      .nunique()
)

conflicting_pairs = conflicting_pairs[
    conflicting_pairs > 1
]

print("\n" + "=" * 60)
print("LABEL CONFLICTS")
print("=" * 60)

print(
    "Person-product pairs with both labels:",
    len(conflicting_pairs)
)


# ------------------------------------------------------------
# POSITIVE / NEGATIVE COUNTS PER PERSON
# ------------------------------------------------------------

person_label_counts = (
    df.groupby(["person_id", "label"])
      .size()
      .unstack(fill_value=0)
)

person_label_counts["difference"] = (
    person_label_counts.get(1, 0)
    - person_label_counts.get(0, 0)
)

print("\n" + "=" * 60)
print("PERSON LABEL BALANCE")
print("=" * 60)

print(person_label_counts.describe())

imbalanced_people = person_label_counts[
    person_label_counts["difference"] != 0
]

print(
    "\nPeople with unequal positive/negative counts:",
    len(imbalanced_people)
)


# ------------------------------------------------------------
# EXTREME VALUES AFTER CLEANING
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("EXTREME VALUE CHECK")
print("=" * 60)

for col in garment_cols:

    s = df[col].dropna()

    if len(s) == 0:
        continue

    print(
        f"{col:20} "
        f"min={s.min():.2f} "
        f"max={s.max():.2f} "
        f"median={s.median():.2f}"
    )


# ------------------------------------------------------------
# DERIVED FEATURES
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("DERIVED FEATURE SANITY")
print("=" * 60)

df["bust_ease"] = df["garment_bust"] - df["bust"]
df["waist_ease"] = df["garment_waist"] - df["waist"]
df["hip_ease"] = df["garment_hip"] - df["hips"]

df["length_height_ratio"] = (
    df["garment_length"] / df["height"]
)

derived = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "length_height_ratio",
    "garment_sleeve",
]

print(
    df[derived]
      .describe()
      .T
      .round(3)
)


# ------------------------------------------------------------
# NaN / INF
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("NUMERICAL VALIDITY")
print("=" * 60)

numeric_cols = df.select_dtypes(
    include=[np.number]
).columns

print(
    "NaN values:",
    int(df[numeric_cols].isna().sum().sum())
)

print(
    "Inf values:",
    int(
        np.isinf(
            df[numeric_cols].to_numpy()
        ).sum()
    )
)


# ------------------------------------------------------------
# FINAL
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("AUDIT COMPLETE")
print("=" * 60)

============================================================
V2 IDENTITY + JOIN INTEGRITY AUDIT
============================================================

Basic:
Rows             : 5980
People           : 56
Garments         : 897

Labels:
label
0    2990
1    2990
Name: count, dtype: int64

============================================================
PERSON PROFILE INTEGRITY
============================================================
count    56.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
dtype: float64

People with inconsistent profiles: 0

============================================================
GARMENT MEASUREMENT INTEGRITY
============================================================
Products with inconsistent measurements: 0

============================================================
DUPLICATE PAIRS
============================================================
Duplicate person-product-label rows: 0

============================================================
LABEL CONFLICTS
============================================================
Person-product pairs with both labels: 0

============================================================
PERSON LABEL BALANCE
============================================================
label           0           1  difference
count   56.000000   56.000000        56.0
mean    53.392857   53.392857         0.0
std     57.366978   57.366978         0.0
min      1.000000    1.000000         0.0
25%     10.500000   10.500000         0.0
50%     36.000000   36.000000         0.0
75%     78.750000   78.750000         0.0
max    251.000000  251.000000         0.0

People with unequal positive/negative counts: 0

============================================================
EXTREME VALUE CHECK
============================================================
garment_bust         min=57.00 max=180.00 median=121.00
garment_waist        min=53.00 max=180.00 median=120.00
garment_hip          min=58.00 max=180.00 median=128.00
garment_length       min=46.00 max=132.00 median=70.00
garment_sleeve       min=20.00 max=133.00 median=64.00

============================================================
DERIVED FEATURE SANITY
============================================================
                      count    mean     std     min     25%     50%    75%  \
bust_ease            5706.0  28.303  21.273 -57.000  14.000  27.000  42.00
waist_ease           4749.0  43.302  20.954 -41.000  30.000  43.000  57.00
hip_ease             5097.0  26.052  24.463 -61.000   9.000  25.000  43.00
length_height_ratio  5922.0   0.418   0.085   0.256   0.367   0.398   0.44
garment_sleeve       4907.0  59.422  15.974  20.000  51.000  64.000  72.00

                         max
bust_ease             99.000
waist_ease           119.000
hip_ease              91.000
length_height_ratio    0.781
garment_sleeve       133.000

============================================================
NUMERICAL VALIDITY
============================================================
NaN values: 5965
Inf values: 0

============================================================
AUDIT COMPLETE
============================================================

In [53]:
# ============================================================
# V2 — FEATURE SIGNAL ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

from sklearn.metrics import roc_auc_score
from sklearn.feature_selection import mutual_info_classif

print("=" * 60)
print("V2 FEATURE SIGNAL ANALYSIS")
print("=" * 60)

df = pd.read_csv(
    "/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_compatibility_raw.csv"
)

# ------------------------------------------------------------
# DERIVED FEATURES
# ------------------------------------------------------------

df["bust_ease"] = (
    df["garment_bust"] - df["bust"]
)

df["waist_ease"] = (
    df["garment_waist"] - df["waist"]
)

df["hip_ease"] = (
    df["garment_hip"] - df["hips"]
)

df["length_height_ratio"] = (
    df["garment_length"] / df["height"]
)

feature_cols = [
    "height",
    "bust",
    "waist",
    "hips",
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "length_height_ratio",
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

print("\nFeatures:")
print(feature_cols)


# ------------------------------------------------------------
# AUC OF INDIVIDUAL FEATURES
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("INDIVIDUAL FEATURE AUC")
print("=" * 60)

results = []

for feature in feature_cols:

    valid = df[[feature, "label"]].dropna()

    if valid[feature].nunique() < 2:
        continue

    y = valid["label"].values
    x = valid[feature].values

    auc = roc_auc_score(y, x)

    # Direction-independent AUC
    auc_abs = max(auc, 1 - auc)

    results.append({
        "feature": feature,
        "samples": len(valid),
        "auc": auc,
        "signal_auc": auc_abs,
    })

auc_df = (
    pd.DataFrame(results)
      .sort_values("signal_auc", ascending=False)
)

print(
    auc_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# ------------------------------------------------------------
# MUTUAL INFORMATION
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("MUTUAL INFORMATION")
print("=" * 60)

mi_features = []

for feature in feature_cols:

    valid = df[[feature, "label"]].dropna()

    if len(valid) < 20:
        continue

    X = valid[[feature]].values
    y = valid["label"].values

    mi = mutual_info_classif(
        X,
        y,
        random_state=42
    )[0]

    mi_features.append({
        "feature": feature,
        "samples": len(valid),
        "mutual_information": mi,
    })

mi_df = (
    pd.DataFrame(mi_features)
      .sort_values(
          "mutual_information",
          ascending=False
      )
)

print(
    mi_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# ------------------------------------------------------------
# POSITIVE / NEGATIVE MEANS
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("CLASS MEAN DIFFERENCES")
print("=" * 60)

summary = []

for feature in feature_cols:

    positive = df.loc[
        df["label"] == 1,
        feature
    ].dropna()

    negative = df.loc[
        df["label"] == 0,
        feature
    ].dropna()

    if len(positive) == 0 or len(negative) == 0:
        continue

    pos_mean = positive.mean()
    neg_mean = negative.mean()

    pooled_std = np.sqrt(
        (
            positive.var() +
            negative.var()
        ) / 2
    )

    effect = (
        (pos_mean - neg_mean) / pooled_std
        if pooled_std > 0
        else 0
    )

    summary.append({
        "feature": feature,
        "positive_mean": pos_mean,
        "negative_mean": neg_mean,
        "difference": pos_mean - neg_mean,
        "effect_size": effect,
    })

mean_df = (
    pd.DataFrame(summary)
      .sort_values(
          "effect_size",
          key=lambda x: x.abs(),
          ascending=False
      )
)

print(
    mean_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# ------------------------------------------------------------
# MISSINGNESS BY CLASS
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("MISSINGNESS BY CLASS")
print("=" * 60)

missing_rows = []

for feature in feature_cols:

    pos_missing = (
        df.loc[df["label"] == 1, feature]
          .isna()
          .mean()
    )

    neg_missing = (
        df.loc[df["label"] == 0, feature]
          .isna()
          .mean()
    )

    missing_rows.append({
        "feature": feature,
        "positive_missing_pct": pos_missing * 100,
        "negative_missing_pct": neg_missing * 100,
        "difference_pct": (
            (pos_missing - neg_missing) * 100
        ),
    })

missing_df = pd.DataFrame(missing_rows)

print(
    missing_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.2f}"
    )
)


# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("SIGNAL ANALYSIS COMPLETE")
print("=" * 60)

print(
    "\nTop 5 features by direction-independent AUC:"
)

print(
    auc_df[
        ["feature", "signal_auc"]
    ]
    .head(5)
    .to_string(index=False)
)

============================================================
V2 FEATURE SIGNAL ANALYSIS
============================================================

Features:
['height', 'bust', 'waist', 'hips', 'bust_ease', 'waist_ease', 'hip_ease', 'length_height_ratio', 'garment_bust', 'garment_waist', 'garment_hip', 'garment_length', 'garment_sleeve']

============================================================
INDIVIDUAL FEATURE AUC
============================================================
            feature  samples    auc  signal_auc
        garment_hip     5097 0.5851      0.5851
       garment_bust     5706 0.5799      0.5799
      garment_waist     4749 0.5779      0.5779
           hip_ease     5097 0.5662      0.5662
          bust_ease     5706 0.5656      0.5656
     garment_length     5922 0.5607      0.5607
length_height_ratio     5922 0.5593      0.5593
         waist_ease     4749 0.5570      0.5570
     garment_sleeve     4907 0.4862      0.5138
             height     5980 0.5000      0.5000
               bust     5980 0.5000      0.5000
              waist     5980 0.5000      0.5000
               hips     5980 0.5000      0.5000

============================================================
MUTUAL INFORMATION
============================================================
            feature  samples  mutual_information
length_height_ratio     5922              0.0710
        garment_hip     5097              0.0633
      garment_waist     4749              0.0427
       garment_bust     5706              0.0397
           hip_ease     5097              0.0348
     garment_sleeve     4907              0.0347
          bust_ease     5706              0.0332
     garment_length     5922              0.0281
         waist_ease     4749              0.0262
             height     5980              0.0000
               bust     5980              0.0000
              waist     5980              0.0000
               hips     5980              0.0000

============================================================
CLASS MEAN DIFFERENCES
============================================================
            feature  positive_mean  negative_mean  difference  effect_size
        garment_hip       131.1819       125.3785      5.8034       0.2677
       garment_bust       124.0599       119.5476      4.5123       0.2410
           hip_ease        28.8936        23.2891      5.6045       0.2307
      garment_waist       120.3186       116.2708      4.0478       0.2247
          bust_ease        30.6132        26.0986      4.5146       0.2136
         waist_ease        45.3898        41.3717      4.0181       0.1928
     garment_length        74.7966        72.2090      2.5876       0.1754
length_height_ratio         0.4254         0.4107      0.0147       0.1745
     garment_sleeve        58.9403        59.8627     -0.9224      -0.0577
             height       175.8689       175.8689      0.0000       0.0000
               bust        93.4040        93.4040      0.0000       0.0000
              waist        74.8338        74.8338      0.0000       0.0000
               hips       102.1438       102.1438      0.0000       0.0000

============================================================
MISSINGNESS BY CLASS
============================================================
            feature  positive_missing_pct  negative_missing_pct  difference_pct
             height                  0.00                  0.00            0.00
               bust                  0.00                  0.00            0.00
              waist                  0.00                  0.00            0.00
               hips                  0.00                  0.00            0.00
          bust_ease                  6.82                  2.34            4.48
         waist_ease                 23.68                 17.49            6.19
           hip_ease                 15.95                 13.58            2.37
length_height_ratio                  0.84                  1.10           -0.27
       garment_bust                  6.82                  2.34            4.48
      garment_waist                 23.68                 17.49            6.19
        garment_hip                 15.95                 13.58            2.37
     garment_length                  0.84                  1.10           -0.27
     garment_sleeve                 21.61                 14.28            7.32

============================================================
SIGNAL ANALYSIS COMPLETE
============================================================

Top 5 features by direction-independent AUC:
      feature  signal_auc
  garment_hip    0.585088
 garment_bust    0.579881
garment_waist    0.577895
     hip_ease    0.566196
    bust_ease    0.565648

In [54]:
# ============================================================
# V2 — PHYSICAL COMPATIBILITY FEATURE ENGINEERING
# ============================================================

import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score

PATH = (
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_compatibility_raw.csv"
)

df = pd.read_csv(PATH)

# ------------------------------------------------------------
# BASIC EASE
# ------------------------------------------------------------

df["bust_ease"] = (
    df["garment_bust"] - df["bust"]
)

df["waist_ease"] = (
    df["garment_waist"] - df["waist"]
)

df["hip_ease"] = (
    df["garment_hip"] - df["hips"]
)

# ------------------------------------------------------------
# RELATIVE EASE
# ------------------------------------------------------------

df["bust_ratio"] = (
    df["garment_bust"] / df["bust"]
)

df["waist_ratio"] = (
    df["garment_waist"] / df["waist"]
)

df["hip_ratio"] = (
    df["garment_hip"] / df["hips"]
)

# ------------------------------------------------------------
# ABSOLUTE BODY-GARMENT MISMATCH
# ------------------------------------------------------------

df["bust_mismatch"] = (
    abs(df["garment_bust"] - df["bust"])
)

df["waist_mismatch"] = (
    abs(df["garment_waist"] - df["waist"])
)

df["hip_mismatch"] = (
    abs(df["garment_hip"] - df["hips"])
)

# ------------------------------------------------------------
# RELATIVE BODY-GARMENT MISMATCH
# ------------------------------------------------------------

df["bust_relative_mismatch"] = (
    abs(df["garment_bust"] - df["bust"])
    / df["bust"]
)

df["waist_relative_mismatch"] = (
    abs(df["garment_waist"] - df["waist"])
    / df["waist"]
)

df["hip_relative_mismatch"] = (
    abs(df["garment_hip"] - df["hips"])
    / df["hips"]
)

# ------------------------------------------------------------
# TIGHTNESS INDICATORS
# ------------------------------------------------------------

df["bust_tight"] = (
    df["bust_ease"] < 0
).astype(float)

df["waist_tight"] = (
    df["waist_ease"] < 0
).astype(float)

df["hip_tight"] = (
    df["hip_ease"] < 0
).astype(float)

# ------------------------------------------------------------
# VERY TIGHT INDICATORS
# ------------------------------------------------------------

df["bust_very_tight"] = (
    df["bust_ease"] < -5
).astype(float)

df["waist_very_tight"] = (
    df["waist_ease"] < -5
).astype(float)

df["hip_very_tight"] = (
    df["hip_ease"] < -5
).astype(float)

# ------------------------------------------------------------
# EXTREME EASE
# ------------------------------------------------------------

df["bust_extreme_ease"] = (
    df["bust_ease"] > 50
).astype(float)

df["waist_extreme_ease"] = (
    df["waist_ease"] > 50
).astype(float)

df["hip_extreme_ease"] = (
    df["hip_ease"] > 50
).astype(float)

# ------------------------------------------------------------
# COMPOSITE BODY COMPATIBILITY
# ------------------------------------------------------------

# Only count dimensions that actually exist.

ease_columns = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
]

df["mean_ease"] = (
    df[ease_columns].mean(axis=1)
)

df["ease_std"] = (
    df[ease_columns].std(axis=1)
)

# Number of dimensions with known measurements

df["known_fit_dimensions"] = (
    df[ease_columns]
    .notna()
    .sum(axis=1)
)

# Number of tight dimensions

df["tight_dimension_count"] = (
    df[
        [
            "bust_tight",
            "waist_tight",
            "hip_tight",
        ]
    ]
    .sum(axis=1)
)

# Number of extreme ease dimensions

df["extreme_ease_count"] = (
    df[
        [
            "bust_extreme_ease",
            "waist_extreme_ease",
            "hip_extreme_ease",
        ]
    ]
    .sum(axis=1)
)

# ------------------------------------------------------------
# LENGTH RELATIONSHIP
# ------------------------------------------------------------

df["length_height_ratio"] = (
    df["garment_length"] / df["height"]
)

# ------------------------------------------------------------
# FEATURE LIST
# ------------------------------------------------------------

features = [
    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "bust_tight",
    "waist_tight",
    "hip_tight",

    "bust_very_tight",
    "waist_very_tight",
    "hip_very_tight",

    "bust_extreme_ease",
    "waist_extreme_ease",
    "hip_extreme_ease",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
    "garment_sleeve",
]

# ------------------------------------------------------------
# AUC
# ------------------------------------------------------------

results = []

for feature in features:

    valid = df[[feature, "label"]].dropna()

    if len(valid) < 100:
        continue

    if valid[feature].nunique() < 2:
        continue

    auc = roc_auc_score(
        valid["label"],
        valid[feature]
    )

    results.append({
        "feature": feature,
        "samples": len(valid),
        "auc": auc,
        "signal_auc": max(auc, 1 - auc),
    })

results_df = (
    pd.DataFrame(results)
    .sort_values(
        "signal_auc",
        ascending=False
    )
)

print("=" * 60)
print("PHYSICAL COMPATIBILITY FEATURE SIGNAL")
print("=" * 60)

print(
    results_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

print("\n" + "=" * 60)
print("TOP FEATURES")
print("=" * 60)

print(
    results_df.head(15).to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

# ------------------------------------------------------------
# CLASS STATISTICS FOR TOP FEATURES
# ------------------------------------------------------------

top_features = results_df.head(10)["feature"].tolist()

print("\n" + "=" * 60)
print("TOP FEATURE CLASS COMPARISON")
print("=" * 60)

for feature in top_features:

    pos = df.loc[
        df["label"] == 1,
        feature
    ].dropna()

    neg = df.loc[
        df["label"] == 0,
        feature
    ].dropna()

    print(
        f"\n{feature}"
    )

    print(
        f"  Positive mean : {pos.mean():.4f}"
    )

    print(
        f"  Negative mean : {neg.mean():.4f}"
    )

    print(
        f"  Positive med  : {pos.median():.4f}"
    )

    print(
        f"  Negative med  : {neg.median():.4f}"
    )

print("\n" + "=" * 60)
print("COMPATIBILITY FEATURE ENGINEERING COMPLETE")
print("=" * 60)

============================================================
PHYSICAL COMPATIBILITY FEATURE SIGNAL
============================================================
                feature  samples    auc  signal_auc
               hip_ease     5097 0.5662      0.5662
              bust_ease     5706 0.5656      0.5656
              mean_ease     5783 0.5620      0.5620
             bust_ratio     5706 0.5613      0.5613
          bust_mismatch     5706 0.5611      0.5611
              hip_ratio     5097 0.5601      0.5601
    length_height_ratio     5922 0.5593      0.5593
         waist_mismatch     4749 0.5573      0.5573
 bust_relative_mismatch     5706 0.5572      0.5572
             waist_ease     4749 0.5570      0.5570
           hip_mismatch     5097 0.5521      0.5521
  hip_relative_mismatch     5097 0.5477      0.5477
waist_relative_mismatch     4749 0.5466      0.5466
            waist_ratio     4749 0.5461      0.5461
  tight_dimension_count     5980 0.4631      0.5369
   known_fit_dimensions     5980 0.4656      0.5344
              hip_tight     5980 0.4671      0.5329
     extreme_ease_count     5980 0.5279      0.5279
         hip_very_tight     5980 0.4739      0.5261
             bust_tight     5980 0.4774      0.5226
     waist_extreme_ease     5980 0.5206      0.5206
        bust_very_tight     5980 0.4833      0.5167
         garment_sleeve     4907 0.4862      0.5138
       hip_extreme_ease     5980 0.5125      0.5125
               ease_std     5460 0.5090      0.5090
            waist_tight     5980 0.4948      0.5052
      bust_extreme_ease     5980 0.5050      0.5050
       waist_very_tight     5980 0.4980      0.5020

============================================================
TOP FEATURES
============================================================
                feature  samples    auc  signal_auc
               hip_ease     5097 0.5662      0.5662
              bust_ease     5706 0.5656      0.5656
              mean_ease     5783 0.5620      0.5620
             bust_ratio     5706 0.5613      0.5613
          bust_mismatch     5706 0.5611      0.5611
              hip_ratio     5097 0.5601      0.5601
    length_height_ratio     5922 0.5593      0.5593
         waist_mismatch     4749 0.5573      0.5573
 bust_relative_mismatch     5706 0.5572      0.5572
             waist_ease     4749 0.5570      0.5570
           hip_mismatch     5097 0.5521      0.5521
  hip_relative_mismatch     5097 0.5477      0.5477
waist_relative_mismatch     4749 0.5466      0.5466
            waist_ratio     4749 0.5461      0.5461
  tight_dimension_count     5980 0.4631      0.5369

============================================================
TOP FEATURE CLASS COMPARISON
============================================================

hip_ease
  Positive mean : 28.8936
  Negative mean : 23.2891
  Positive med  : 28.0000
  Negative med  : 23.0000

bust_ease
  Positive mean : 30.6132
  Negative mean : 26.0986
  Positive med  : 29.0000
  Negative med  : 25.0000

mean_ease
  Positive mean : 35.1352
  Negative mean : 30.8918
  Positive med  : 34.0000
  Negative med  : 30.0000

bust_ratio
  Positive mean : 1.3422
  Negative mean : 1.2940
  Positive med  : 1.3131
  Negative med  : 1.2673

bust_mismatch
  Positive mean : 31.4657
  Negative mean : 27.9024
  Positive med  : 29.0000
  Negative med  : 25.0000

hip_ratio
  Positive mean : 1.2977
  Negative mean : 1.2441
  Positive med  : 1.2747
  Negative med  : 1.2277

length_height_ratio
  Positive mean : 0.4254
  Negative mean : 0.4107
  Positive med  : 0.4046
  Negative med  : 0.3931

waist_mismatch
  Positive mean : 45.7035
  Negative mean : 41.8208
  Positive med  : 44.0000
  Negative med  : 41.0000

bust_relative_mismatch
  Positive mean : 0.3505
  Negative mean : 0.3111
  Positive med  : 0.3168
  Negative med  : 0.2676

waist_ease
  Positive mean : 45.3898
  Negative mean : 41.3717
  Positive med  : 44.0000
  Negative med  : 41.0000

============================================================
COMPATIBILITY FEATURE ENGINEERING COMPLETE
============================================================

In [55]:
# ============================================================
# V2 — 3 CONTROLLED BASELINES
# Raw vs Compatibility vs Combined
# ============================================================

import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    average_precision_score,
    f1_score,
    log_loss,
)

# ------------------------------------------------------------
# LOAD DATA
# ------------------------------------------------------------

PATH = (
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_compatibility_raw.csv"
)

df = pd.read_csv(PATH)

# ------------------------------------------------------------
# DERIVED COMPATIBILITY FEATURES
# ------------------------------------------------------------

df["bust_ease"] = df["garment_bust"] - df["bust"]
df["waist_ease"] = df["garment_waist"] - df["waist"]
df["hip_ease"] = df["garment_hip"] - df["hips"]

df["bust_ratio"] = df["garment_bust"] / df["bust"]
df["waist_ratio"] = df["garment_waist"] / df["waist"]
df["hip_ratio"] = df["garment_hip"] / df["hips"]

df["bust_mismatch"] = abs(
    df["garment_bust"] - df["bust"]
)

df["waist_mismatch"] = abs(
    df["garment_waist"] - df["waist"]
)

df["hip_mismatch"] = abs(
    df["garment_hip"] - df["hips"]
)

df["bust_relative_mismatch"] = (
    abs(df["garment_bust"] - df["bust"])
    / df["bust"]
)

df["waist_relative_mismatch"] = (
    abs(df["garment_waist"] - df["waist"])
    / df["waist"]
)

df["hip_relative_mismatch"] = (
    abs(df["garment_hip"] - df["hips"])
    / df["hips"]
)

df["bust_tight"] = (
    df["bust_ease"] < 0
).astype(float)

df["waist_tight"] = (
    df["waist_ease"] < 0
).astype(float)

df["hip_tight"] = (
    df["hip_ease"] < 0
).astype(float)

df["bust_very_tight"] = (
    df["bust_ease"] < -5
).astype(float)

df["waist_very_tight"] = (
    df["waist_ease"] < -5
).astype(float)

df["hip_very_tight"] = (
    df["hip_ease"] < -5
).astype(float)

df["bust_extreme_ease"] = (
    df["bust_ease"] > 50
).astype(float)

df["waist_extreme_ease"] = (
    df["waist_ease"] > 50
).astype(float)

df["hip_extreme_ease"] = (
    df["hip_ease"] > 50
).astype(float)

df["mean_ease"] = df[
    ["bust_ease", "waist_ease", "hip_ease"]
].mean(axis=1)

df["ease_std"] = df[
    ["bust_ease", "waist_ease", "hip_ease"]
].std(axis=1)

df["known_fit_dimensions"] = df[
    ["bust_ease", "waist_ease", "hip_ease"]
].notna().sum(axis=1)

df["tight_dimension_count"] = df[
    ["bust_tight", "waist_tight", "hip_tight"]
].sum(axis=1)

df["extreme_ease_count"] = df[
    [
        "bust_extreme_ease",
        "waist_extreme_ease",
        "hip_extreme_ease",
    ]
].sum(axis=1)

df["length_height_ratio"] = (
    df["garment_length"] / df["height"]
)

# ------------------------------------------------------------
# FEATURE GROUPS
# ------------------------------------------------------------

raw_features = [
    "height",
    "bust",
    "waist",
    "hips",
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

compatibility_features = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "bust_ratio",
    "waist_ratio",
    "hip_ratio",
    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",
    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",
    "bust_tight",
    "waist_tight",
    "hip_tight",
    "bust_very_tight",
    "waist_very_tight",
    "hip_very_tight",
    "bust_extreme_ease",
    "waist_extreme_ease",
    "hip_extreme_ease",
    "mean_ease",
    "ease_std",
    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",
    "length_height_ratio",
]

combined_features = raw_features + compatibility_features

# Remove duplicates while preserving order
combined_features = list(dict.fromkeys(combined_features))

print("=" * 60)
print("FEATURE GROUPS")
print("=" * 60)

print("Raw features          :", len(raw_features))
print("Compatibility features:", len(compatibility_features))
print("Combined features     :", len(combined_features))


# ============================================================
# PERSON-LEVEL SPLIT
# ============================================================

# IMPORTANT:
# Recreate the same 36 / 8 / 8 person split used previously.
#
# Fixed random seed guarantees reproducibility.

from sklearn.model_selection import train_test_split

people = sorted(df["person_id"].unique())

train_people, temp_people = train_test_split(
    people,
    test_size=16,
    random_state=42,
)

val_people, test_people = train_test_split(
    temp_people,
    test_size=8,
    random_state=42,
)

train_df = df[df["person_id"].isin(train_people)].copy()
val_df = df[df["person_id"].isin(val_people)].copy()
test_df = df[df["person_id"].isin(test_people)].copy()

print("\n" + "=" * 60)
print("PERSON-LEVEL SPLIT")
print("=" * 60)

print("Train people:", len(train_people))
print("Val people  :", len(val_people))
print("Test people :", len(test_people))

print("\nRows:")
print("Train:", len(train_df))
print("Val  :", len(val_df))
print("Test :", len(test_df))

print("\nLeakage:")
print("Train ∩ Val :", set(train_people) & set(val_people))
print("Train ∩ Test:", set(train_people) & set(test_people))
print("Val ∩ Test  :", set(val_people) & set(test_people))


# ============================================================
# TRAIN / EVALUATE
# ============================================================

def run_baseline(name, features):

    X_train = train_df[features]
    y_train = train_df["label"]

    X_val = val_df[features]
    y_val = val_df["label"]

    X_test = test_df[features]
    y_test = test_df["label"]

    model = Pipeline([
        (
            "imputer",
            SimpleImputer(
                strategy="median",
                add_indicator=True,
            ),
        ),
        (
            "scaler",
            StandardScaler(),
        ),
        (
            "classifier",
            LogisticRegression(
                max_iter=2000,
                C=1.0,
                random_state=42,
            ),
        ),
    ])

    model.fit(X_train, y_train)

    # Validation
    val_prob = model.predict_proba(X_val)[:, 1]
    val_pred = (val_prob >= 0.5).astype(int)

    # Test
    test_prob = model.predict_proba(X_test)[:, 1]
    test_pred = (test_prob >= 0.5).astype(int)

    results = {
        "model": name,

        "val_accuracy": accuracy_score(
            y_val, val_pred
        ),

        "val_auc": roc_auc_score(
            y_val, val_prob
        ),

        "val_pr_auc": average_precision_score(
            y_val, val_prob
        ),

        "val_f1": f1_score(
            y_val, val_pred
        ),

        "val_log_loss": log_loss(
            y_val, val_prob
        ),

        "test_accuracy": accuracy_score(
            y_test, test_pred
        ),

        "test_auc": roc_auc_score(
            y_test, test_prob
        ),

        "test_pr_auc": average_precision_score(
            y_test, test_prob
        ),

        "test_f1": f1_score(
            y_test, test_pred
        ),

        "test_log_loss": log_loss(
            y_test, test_prob
        ),
    }

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print(
        f"Validation Accuracy : {results['val_accuracy']:.4f}"
    )
    print(
        f"Validation ROC-AUC  : {results['val_auc']:.4f}"
    )
    print(
        f"Validation PR-AUC   : {results['val_pr_auc']:.4f}"
    )
    print(
        f"Validation F1       : {results['val_f1']:.4f}"
    )
    print(
        f"Validation LogLoss  : {results['val_log_loss']:.4f}"
    )

    print()

    print(
        f"Test Accuracy       : {results['test_accuracy']:.4f}"
    )
    print(
        f"Test ROC-AUC        : {results['test_auc']:.4f}"
    )
    print(
        f"Test PR-AUC         : {results['test_pr_auc']:.4f}"
    )
    print(
        f"Test F1             : {results['test_f1']:.4f}"
    )
    print(
        f"Test LogLoss        : {results['test_log_loss']:.4f}"
    )

    return results


# ============================================================
# RUN 3 BASELINES
# ============================================================

results = []

results.append(
    run_baseline(
        "A — RAW FEATURES",
        raw_features,
    )
)

results.append(
    run_baseline(
        "B — COMPATIBILITY FEATURES",
        compatibility_features,
    )
)

results.append(
    run_baseline(
        "C — COMBINED FEATURES",
        combined_features,
    )
)


# ============================================================
# FINAL COMPARISON
# ============================================================

results_df = pd.DataFrame(results)

print("\n\n" + "=" * 60)
print("FINAL BASELINE COMPARISON")
print("=" * 60)

display(
    results_df[
        [
            "model",
            "val_auc",
            "val_pr_auc",
            "val_f1",
            "val_log_loss",
            "test_auc",
            "test_pr_auc",
            "test_f1",
            "test_log_loss",
            "test_accuracy",
        ]
    ].round(4)
)


# ============================================================
# BEST MODEL
# ============================================================

best = results_df.loc[
    results_df["test_auc"].idxmax()
]

print("\n" + "=" * 60)
print("BEST BASELINE")
print("=" * 60)

print("Model     :", best["model"])
print("Test AUC  :", round(best["test_auc"], 4))
print("Test PR-AUC:", round(best["test_pr_auc"], 4))
print("Test F1   :", round(best["test_f1"], 4))
print("Test Acc  :", round(best["test_accuracy"], 4))

print("\n" + "=" * 60)
print("3-BASELINE EXPERIMENT COMPLETE")
print("=" * 60)

============================================================
FEATURE GROUPS
============================================================
Raw features          : 9
Compatibility features: 27
Combined features     : 36

============================================================
PERSON-LEVEL SPLIT
============================================================
Train people: 40
Val people  : 8
Test people : 8

Rows:
Train: 4540
Val  : 762
Test : 678

Leakage:
Train ∩ Val : set()
Train ∩ Test: set()
Val ∩ Test  : set()

============================================================
A — RAW FEATURES
============================================================
Validation Accuracy : 0.5827
Validation ROC-AUC  : 0.6496
Validation PR-AUC   : 0.6324
Validation F1       : 0.5457
Validation LogLoss  : 0.6642

Test Accuracy       : 0.5516
Test ROC-AUC        : 0.5711
Test PR-AUC         : 0.5623
Test F1             : 0.5235
Test LogLoss        : 0.6918

============================================================
B — COMPATIBILITY FEATURES
============================================================
Validation Accuracy : 0.6155
Validation ROC-AUC  : 0.6312
Validation PR-AUC   : 0.6175
Validation F1       : 0.6491
Validation LogLoss  : 0.6732

Test Accuracy       : 0.5723
Test ROC-AUC        : 0.5964
Test PR-AUC         : 0.5769
Test F1             : 0.6081
Test LogLoss        : 0.6781

============================================================
C — COMBINED FEATURES
============================================================
Validation Accuracy : 0.5997
Validation ROC-AUC  : 0.6179
Validation PR-AUC   : 0.5801
Validation F1       : 0.5895
Validation LogLoss  : 0.6824

Test Accuracy       : 0.5472
Test ROC-AUC        : 0.5806
Test PR-AUC         : 0.5709
Test F1             : 0.5411
Test LogLoss        : 0.6902


============================================================
FINAL BASELINE COMPARISON
============================================================

,model,val_auc,val_pr_auc,val_f1,val_log_loss,test_auc,test_pr_auc,test_f1,test_log_loss,test_accuracy
0,A — RAW FEATURES,0.6496,0.6324,0.5457,0.6642,0.5711,0.5623,0.5235,0.6918,0.5516
1,B — COMPATIBILITY FEATURES,0.6312,0.6175,0.6491,0.6732,0.5964,0.5769,0.6081,0.6781,0.5723
2,C — COMBINED FEATURES,0.6179,0.5801,0.5895,0.6824,0.5806,0.5709,0.5411,0.6902,0.5472

============================================================
BEST BASELINE
============================================================
Model     : B — COMPATIBILITY FEATURES
Test AUC  : 0.5964
Test PR-AUC: 0.5769
Test F1   : 0.6081
Test Acc  : 0.5723

============================================================
3-BASELINE EXPERIMENT COMPLETE
============================================================

In [56]:
# ============================================================
# V2 — NEGATIVE SAMPLING EXPERIMENT
# Random + Physically Plausible Hard Negatives
# ============================================================

import pandas as pd
import numpy as np

from pathlib import Path

# ------------------------------------------------------------
# LOAD CURRENT V2 DATA
# ------------------------------------------------------------

DATA_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_compatibility_raw.csv"
)

df = pd.read_csv(DATA_PATH)

print("=" * 60)
print("V2 NEGATIVE SAMPLING")
print("=" * 60)

print("Rows    :", len(df))
print("People  :", df["person_id"].nunique())
print("Garments:", df["product_id"].nunique())

# ------------------------------------------------------------
# POSITIVE PAIRS
# ------------------------------------------------------------

positive_pairs = set(
    zip(
        df.loc[df["label"] == 1, "person_id"],
        df.loc[df["label"] == 1, "product_id"],
    )
)

all_people = sorted(df["person_id"].unique())
all_products = sorted(df["product_id"].unique())

# Products already observed positively for each person
positive_by_person = (
    df[df["label"] == 1]
    .groupby("person_id")["product_id"]
    .apply(set)
    .to_dict()
)

print("\nPositive pairs:", len(positive_pairs))

# ------------------------------------------------------------
# GARMENT-LEVEL MEASUREMENT TABLE
# ------------------------------------------------------------

garment_cols = [
    "product_id",
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

garments = (
    df[garment_cols]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

# ------------------------------------------------------------
# PERSON BODY TABLE
# ------------------------------------------------------------

person_cols = [
    "person_id",
    "height",
    "bust",
    "waist",
    "hips",
]

people = (
    df[person_cols]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

# ------------------------------------------------------------
# HARD NEGATIVE DEFINITION
# ------------------------------------------------------------
#
# We want negatives that are:
#
#   1. NOT observed as positive for this person
#   2. Physically plausible
#   3. Relatively close to the person's observed positive
#      garment measurements
#
# This avoids making every random unobserved garment a
# "definitely incompatible" example.
#
# We use normalized body/garment differences.
# ------------------------------------------------------------

def compatibility_distance(person, product):

    p = people.loc[person]
    g = garments.loc[product]

    distances = []

    # Bust
    if pd.notna(p["bust"]) and pd.notna(g["garment_bust"]):
        distances.append(
            abs(g["garment_bust"] - p["bust"])
            / max(p["bust"], 1)
        )

    # Waist
    if pd.notna(p["waist"]) and pd.notna(g["garment_waist"]):
        distances.append(
            abs(g["garment_waist"] - p["waist"])
            / max(p["waist"], 1)
        )

    # Hip
    if pd.notna(p["hips"]) and pd.notna(g["garment_hip"]):
        distances.append(
            abs(g["garment_hip"] - p["hips"])
            / max(p["hips"], 1)
        )

    # Length relative to height
    if (
        pd.notna(p["height"])
        and pd.notna(g["garment_length"])
    ):
        distances.append(
            abs(
                (g["garment_length"] / p["height"])
                - 0.40
            )
        )

    if not distances:
        return np.inf

    return float(np.mean(distances))


# ------------------------------------------------------------
# BUILD HARD NEGATIVE POOL
# ------------------------------------------------------------

rng = np.random.default_rng(42)

hard_negative_records = []
random_negative_records = []

# Number of negatives per positive
HARD_NEGATIVES_PER_PERSON = 1
RANDOM_NEGATIVES_PER_PERSON = 1

for person in all_people:

    positives = positive_by_person.get(person, set())

    # --------------------------------------------------------
    # Candidate products
    # --------------------------------------------------------

    candidates = [
        product
        for product in all_products
        if product not in positives
    ]

    if not candidates:
        continue

    # --------------------------------------------------------
    # HARD NEGATIVES
    # --------------------------------------------------------

    scored_candidates = []

    for product in candidates:
        distance = compatibility_distance(
            person,
            product,
        )

        if np.isfinite(distance):
            scored_candidates.append(
                (product, distance)
            )

    scored_candidates.sort(
        key=lambda x: x[1]
    )

    # Select close / plausible garments
    hard_candidates = [
        product
        for product, _ in scored_candidates[
            :HARD_NEGATIVES_PER_PERSON
        ]
    ]

    for product in hard_candidates:
        hard_negative_records.append(
            {
                "person_id": person,
                "product_id": product,
                "label": 0,
                "negative_type": "hard",
            }
        )

    # --------------------------------------------------------
    # RANDOM NEGATIVES
    # --------------------------------------------------------

    random_candidates = [
        product
        for product in candidates
        if product not in hard_candidates
    ]

    if random_candidates:

        count = min(
            RANDOM_NEGATIVES_PER_PERSON,
            len(random_candidates),
        )

        selected = rng.choice(
            random_candidates,
            size=count,
            replace=False,
        )

        for product in selected:
            random_negative_records.append(
                {
                    "person_id": person,
                    "product_id": product,
                    "label": 0,
                    "negative_type": "random",
                }
            )


# ------------------------------------------------------------
# DATAFRAMES
# ------------------------------------------------------------

hard_negatives = pd.DataFrame(
    hard_negative_records
)

random_negatives = pd.DataFrame(
    random_negative_records
)

print("\n" + "=" * 60)
print("NEGATIVE SAMPLING RESULTS")
print("=" * 60)

print(
    "Hard negatives  :",
    len(hard_negatives)
)

print(
    "Random negatives:",
    len(random_negatives)
)

# ------------------------------------------------------------
# POSITIVE DATAFRAME
# ------------------------------------------------------------

positive_df = (
    df[df["label"] == 1]
    [["person_id", "product_id"]]
    .drop_duplicates()
    .copy()
)

positive_df["label"] = 1
positive_df["negative_type"] = "positive"

# ------------------------------------------------------------
# COMBINE
# ------------------------------------------------------------

sampling_df = pd.concat(
    [
        positive_df,
        hard_negatives,
        random_negatives,
    ],
    ignore_index=True,
)

# Remove accidental duplicates
sampling_df = sampling_df.drop_duplicates(
    subset=[
        "person_id",
        "product_id",
        "label",
    ]
).reset_index(drop=True)

# ------------------------------------------------------------
# CHECK LABEL CONFLICTS
# ------------------------------------------------------------

conflicts = (
    sampling_df
    .groupby(
        ["person_id", "product_id"]
    )["label"]
    .nunique()
)

conflicting_pairs = conflicts[
    conflicts > 1
]

# ------------------------------------------------------------
# CHECK DUPLICATES
# ------------------------------------------------------------

duplicate_pairs = sampling_df.duplicated(
    subset=[
        "person_id",
        "product_id",
        "label",
    ]
).sum()

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FINAL NEGATIVE-SAMPLING DATASET")
print("=" * 60)

print(
    "Positive:",
    (sampling_df["label"] == 1).sum()
)

print(
    "Hard negative:",
    (
        sampling_df["negative_type"] == "hard"
    ).sum()
)

print(
    "Random negative:",
    (
        sampling_df["negative_type"] == "random"
    ).sum()
)

print(
    "Total:",
    len(sampling_df)
)

print("\nLabels:")
print(
    sampling_df["label"]
    .value_counts()
    .sort_index()
)

print("\nUnique people:")
print(
    sampling_df["person_id"].nunique()
)

print("\nUnique garments:")
print(
    sampling_df["product_id"].nunique()
)

print("\nDuplicate rows:", duplicate_pairs)

print(
    "Label conflicts:",
    len(conflicting_pairs)
)

# ------------------------------------------------------------
# NEGATIVE DISTANCE ANALYSIS
# ------------------------------------------------------------

if len(hard_negatives) > 0:

    hard_distances = []

    for _, row in hard_negatives.iterrows():

        distance = compatibility_distance(
            row["person_id"],
            row["product_id"],
        )

        hard_distances.append(distance)

    print("\n" + "=" * 60)
    print("HARD NEGATIVE DISTANCE")
    print("=" * 60)

    print(
        pd.Series(hard_distances)
        .describe()
        .round(4)
    )

# ------------------------------------------------------------
# PERSON BALANCE
# ------------------------------------------------------------

person_balance = (
    sampling_df
    .groupby(
        ["person_id", "label"]
    )
    .size()
    .unstack(fill_value=0)
)

if 0 in person_balance.columns and 1 in person_balance.columns:

    person_balance["difference"] = (
        person_balance[1]
        - person_balance[0]
    )

    print("\n" + "=" * 60)
    print("PERSON-LEVEL BALANCE")
    print("=" * 60)

    print(
        "People with unequal labels:",
        (
            person_balance["difference"]
            != 0
        ).sum()
    )

    print(
        person_balance["difference"]
        .describe()
    )

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

OUTPUT_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_negative_sampling_dataset.csv"
)

sampling_df.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 60)
print("SAVED")
print("=" * 60)

print(OUTPUT_PATH)

============================================================
V2 NEGATIVE SAMPLING
============================================================
Rows    : 5980
People  : 56
Garments: 897

Positive pairs: 2990

============================================================
NEGATIVE SAMPLING RESULTS
============================================================
Hard negatives  : 56
Random negatives: 56

============================================================
FINAL NEGATIVE-SAMPLING DATASET
============================================================
Positive: 2990
Hard negative: 56
Random negative: 56
Total: 3102

Labels:
label
0     112
1    2990
Name: count, dtype: int64

Unique people:
56

Unique garments:
867

Duplicate rows: 0
Label conflicts: 0

============================================================
HARD NEGATIVE DISTANCE
============================================================
count    56.0000
mean      0.0201
std       0.0068
min       0.0011
25%       0.0159
50%       0.0225
75%       0.0250
max       0.0313
dtype: float64

============================================================
PERSON-LEVEL BALANCE
============================================================
People with unequal labels: 56
count     56.000000
mean      51.392857
std       57.366978
min       -1.000000
25%        8.500000
50%       34.000000
75%       76.750000
max      249.000000
Name: difference, dtype: float64

============================================================
SAVED
============================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_negative_sampling_dataset.csv

In [57]:
# ============================================================
# V2 — CORRECTED NEGATIVE SAMPLING + PAIRWISE DATASET
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

DATA_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_compatibility_raw.csv"
)

OUTPUT_POINTWISE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_negative_sampling_corrected.csv"
)

OUTPUT_PAIRWISE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_pairwise_ranking.csv"
)

# Number of negatives for EACH positive
HARD_NEGATIVES_PER_POSITIVE = 2
RANDOM_NEGATIVES_PER_POSITIVE = 1

RANDOM_SEED = 42

rng = np.random.default_rng(RANDOM_SEED)

# ------------------------------------------------------------
# LOAD DATA
# ------------------------------------------------------------

df = pd.read_csv(DATA_PATH)

print("=" * 60)
print("V2 CORRECTED NEGATIVE SAMPLING")
print("=" * 60)

print("Input rows :", len(df))
print("People     :", df["person_id"].nunique())
print("Garments   :", df["product_id"].nunique())

# ------------------------------------------------------------
# POSITIVE INTERACTIONS
# ------------------------------------------------------------

positive_df = (
    df[df["label"] == 1]
    [["person_id", "product_id"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("\nPositive interactions:", len(positive_df))

# ------------------------------------------------------------
# GARMENT TABLE
# ------------------------------------------------------------

garment_cols = [
    "product_id",
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

garments = (
    df[garment_cols]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

# ------------------------------------------------------------
# PERSON TABLE
# ------------------------------------------------------------

person_cols = [
    "person_id",
    "height",
    "bust",
    "waist",
    "hips",
]

people = (
    df[person_cols]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

all_products = list(garments.index)

# ------------------------------------------------------------
# POSITIVE PRODUCTS PER PERSON
# ------------------------------------------------------------

positive_by_person = (
    positive_df
    .groupby("person_id")["product_id"]
    .apply(set)
    .to_dict()
)

# ------------------------------------------------------------
# PHYSICAL DISTANCE
# ------------------------------------------------------------

def compatibility_distance(person_id, product_id):

    p = people.loc[person_id]
    g = garments.loc[product_id]

    distances = []

    # Bust
    if pd.notna(p["bust"]) and pd.notna(g["garment_bust"]):
        distances.append(
            abs(g["garment_bust"] - p["bust"])
            / max(float(p["bust"]), 1.0)
        )

    # Waist
    if pd.notna(p["waist"]) and pd.notna(g["garment_waist"]):
        distances.append(
            abs(g["garment_waist"] - p["waist"])
            / max(float(p["waist"]), 1.0)
        )

    # Hip
    if pd.notna(p["hips"]) and pd.notna(g["garment_hip"]):
        distances.append(
            abs(g["garment_hip"] - p["hips"])
            / max(float(p["hips"]), 1.0)
        )

    # Length relative to height
    if (
        pd.notna(p["height"])
        and pd.notna(g["garment_length"])
    ):
        distances.append(
            abs(
                (g["garment_length"] / p["height"])
                - 0.40
            )
        )

    if not distances:
        return np.inf

    return float(np.mean(distances))


# ============================================================
# BUILD NEGATIVES PER POSITIVE
# ============================================================

hard_negative_rows = []
random_negative_rows = []

pairwise_rows = []

positive_count = 0

for _, positive in positive_df.iterrows():

    person = positive["person_id"]
    positive_product = positive["product_id"]

    positive_count += 1

    observed = positive_by_person.get(person, set())

    # --------------------------------------------------------
    # Candidate products
    # --------------------------------------------------------

    candidates = [
        product
        for product in all_products
        if product not in observed
    ]

    if not candidates:
        continue

    # --------------------------------------------------------
    # Score all candidate garments by physical distance
    # --------------------------------------------------------

    scored = []

    for product in candidates:

        distance = compatibility_distance(
            person,
            product
        )

        if np.isfinite(distance):
            scored.append(
                (product, distance)
            )

    scored.sort(key=lambda x: x[1])

    # --------------------------------------------------------
    # HARD NEGATIVES
    #
    # Take closest physically plausible garments.
    # --------------------------------------------------------

    hard_candidates = [
        product
        for product, distance
        in scored[:HARD_NEGATIVES_PER_POSITIVE]
    ]

    for product in hard_candidates:

        distance = compatibility_distance(
            person,
            product
        )

        hard_negative_rows.append({
            "person_id": person,
            "positive_product_id": positive_product,
            "negative_product_id": product,
            "negative_type": "hard",
            "negative_distance": distance,
        })

        pairwise_rows.append({
            "person_id": person,
            "positive_product_id": positive_product,
            "negative_product_id": product,
            "negative_type": "hard",
        })

    # --------------------------------------------------------
    # RANDOM NEGATIVES
    # --------------------------------------------------------

    hard_set = set(hard_candidates)

    random_candidates = [
        product
        for product in candidates
        if product not in hard_set
    ]

    if random_candidates:

        count = min(
            RANDOM_NEGATIVES_PER_POSITIVE,
            len(random_candidates)
        )

        selected = rng.choice(
            random_candidates,
            size=count,
            replace=False,
        )

        for product in selected:

            random_negative_rows.append({
                "person_id": person,
                "positive_product_id": positive_product,
                "negative_product_id": product,
                "negative_type": "random",
                "negative_distance": compatibility_distance(
                    person,
                    product
                ),
            })

            pairwise_rows.append({
                "person_id": person,
                "positive_product_id": positive_product,
                "negative_product_id": product,
                "negative_type": "random",
            })


# ============================================================
# DATAFRAMES
# ============================================================

hard_df = pd.DataFrame(hard_negative_rows)
random_df = pd.DataFrame(random_negative_rows)

pairwise_df = pd.DataFrame(pairwise_rows)

# ============================================================
# EXPECTED COUNTS
# ============================================================

expected_hard = (
    positive_count
    * HARD_NEGATIVES_PER_POSITIVE
)

expected_random = (
    positive_count
    * RANDOM_NEGATIVES_PER_POSITIVE
)

print("\n" + "=" * 60)
print("SAMPLING COUNTS")
print("=" * 60)

print("Positive interactions :", positive_count)

print(
    "Expected hard negatives :",
    expected_hard
)

print(
    "Actual hard negatives   :",
    len(hard_df)
)

print(
    "Expected random negatives:",
    expected_random
)

print(
    "Actual random negatives :",
    len(random_df)
)

print(
    "Total pairwise samples  :",
    len(pairwise_df)
)

# ============================================================
# CHECK DUPLICATES
# ============================================================

duplicate_pair_count = (
    pairwise_df
    .duplicated(
        subset=[
            "person_id",
            "positive_product_id",
            "negative_product_id",
        ]
    )
    .sum()
)

print("\nDuplicate pairwise rows:", duplicate_pair_count)

# ============================================================
# CHECK POSITIVE / NEGATIVE COLLISION
# ============================================================

positive_set = set(
    zip(
        positive_df["person_id"],
        positive_df["product_id"],
    )
)

negative_set = set(
    zip(
        pairwise_df["person_id"],
        pairwise_df["negative_product_id"],
    )
)

collisions = positive_set & negative_set

print(
    "Positive-negative collisions:",
    len(collisions)
)

# ============================================================
# NEGATIVE TYPE DISTRIBUTION
# ============================================================

print("\n" + "=" * 60)
print("NEGATIVE TYPE DISTRIBUTION")
print("=" * 60)

print(
    pairwise_df["negative_type"]
    .value_counts()
)

# ============================================================
# NEGATIVE DISTANCE
# ============================================================

if len(hard_df):

    print("\n" + "=" * 60)
    print("HARD NEGATIVE DISTANCE")
    print("=" * 60)

    print(
        hard_df["negative_distance"]
        .describe()
        .round(4)
    )

if len(random_df):

    print("\n" + "=" * 60)
    print("RANDOM NEGATIVE DISTANCE")
    print("=" * 60)

    print(
        random_df["negative_distance"]
        .describe()
        .round(4)
    )

# ============================================================
# PERSON-LEVEL PAIR COUNTS
# ============================================================

person_pair_counts = (
    pairwise_df
    .groupby("person_id")
    .size()
)

print("\n" + "=" * 60)
print("PAIRWISE SAMPLES PER PERSON")
print("=" * 60)

print(
    person_pair_counts
    .describe()
    .round(2)
)

print(
    "\nPeople:",
    person_pair_counts.shape[0]
)

# ============================================================
# EXAMPLE PAIRS
# ============================================================

print("\n" + "=" * 60)
print("EXAMPLE PAIRS")
print("=" * 60)

display(
    pairwise_df.head(15)
)

# ============================================================
# SAVE
# ============================================================

pairwise_df.to_csv(
    OUTPUT_PAIRWISE,
    index=False,
)

# Also save detailed negative sampling information
negative_detail_df = pd.concat(
    [
        hard_df,
        random_df,
    ],
    ignore_index=True,
)

negative_detail_df.to_csv(
    OUTPUT_POINTWISE,
    index=False,
)

print("\n" + "=" * 60)
print("FILES SAVED")
print("=" * 60)

print("Negative details:")
print(OUTPUT_POINTWISE)

print("\nPairwise ranking dataset:")
print(OUTPUT_PAIRWISE)

print("\n" + "=" * 60)
print("CORRECTED SAMPLING COMPLETE")
print("=" * 60)

============================================================
V2 CORRECTED NEGATIVE SAMPLING
============================================================
Input rows : 5980
People     : 56
Garments   : 897

Positive interactions: 2990

============================================================
SAMPLING COUNTS
============================================================
Positive interactions : 2990
Expected hard negatives : 5980
Actual hard negatives   : 5980
Expected random negatives: 2990
Actual random negatives : 2990
Total pairwise samples  : 8970

Duplicate pairwise rows: 0
Positive-negative collisions: 0

============================================================
NEGATIVE TYPE DISTRIBUTION
============================================================
negative_type
hard      5980
random    2990
Name: count, dtype: int64

============================================================
HARD NEGATIVE DISTANCE
============================================================
count    5980.0000
mean        0.0210
std         0.0075
min         0.0011
25%         0.0148
50%         0.0229
75%         0.0270
max         0.0401
Name: negative_distance, dtype: float64

============================================================
RANDOM NEGATIVE DISTANCE
============================================================
count    2990.0000
mean        0.2976
std         0.1745
min         0.0181
25%         0.1586
50%         0.2713
75%         0.3964
max         1.3125
Name: negative_distance, dtype: float64

============================================================
PAIRWISE SAMPLES PER PERSON
============================================================
count     56.00
mean     160.18
std      172.10
min        3.00
25%       31.50
50%      108.00
75%      236.25
max      753.00
dtype: float64

People: 56

============================================================
EXAMPLE PAIRS
============================================================

,person_id,positive_product_id,negative_product_id,negative_type
0,Fiona,the-tie-detail-hoody#Pink,natural-textured-poncho#Deeprain,hard
1,Fiona,the-tie-detail-hoody#Pink,wonderland-blouse#Ink,hard
2,Fiona,the-tie-detail-hoody#Pink,luxe-shirt#Navy,random
3,Jess,belle-off-the-shoulder-tee#Stripe,cara-tee-2#Blush,hard
4,Jess,belle-off-the-shoulder-tee#Stripe,cara-tee-2#WhiteBlk,hard
5,Jess,belle-off-the-shoulder-tee#Stripe,the-define-flute-sleeve-blouse#Black,random
6,Fiona,the-relaxed-long-sleeve-tee-1#Ink%20Stripe,natural-textured-poncho#Deeprain,hard
7,Fiona,the-relaxed-long-sleeve-tee-1#Ink%20Stripe,wonderland-blouse#Ink,hard
8,Fiona,the-relaxed-long-sleeve-tee-1#Ink%20Stripe,ditzy-floral-ruffle-blouse#DitzyFlora,random
9,Laura,milan-stretch-top#Black,cara-tee-2#Blush,hard
10,Laura,milan-stretch-top#Black,cara-tee-2#WhiteBlk,hard
11,Laura,milan-stretch-top#Black,leah-knit-cardigan#Black,random
12,Chelsea,falling-for-you-cardi#Teal,voyager-stripe-crew#Stripe,hard
13,Chelsea,falling-for-you-cardi#Teal,makeover-blouse#LimeGreen,hard
14,Chelsea,falling-for-you-cardi#Teal,the-button-up-swing-tunic#Wine,random

============================================================
FILES SAVED
============================================================
Negative details:
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_negative_sampling_corrected.csv

Pairwise ranking dataset:
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_pairwise_ranking.csv

============================================================
CORRECTED SAMPLING COMPLETE
============================================================

In [58]:
# ============================================================
# ZYRA V2 — FIRST PAIRWISE RANKING MODEL
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from torch.utils.data import TensorDataset, DataLoader

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

PAIRWISE_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_pairwise_ranking.csv"
)

MODEL_OUTPUT = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_pairwise_ranker.pt"
)

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# ------------------------------------------------------------
# LOAD
# ------------------------------------------------------------

pairs = pd.read_csv(PAIRWISE_PATH)

print("=" * 60)
print("ZYRA V2 PAIRWISE RANKING")
print("=" * 60)

print("Pairwise rows:", len(pairs))
print("People       :", pairs["person_id"].nunique())

print("\nNegative types:")
print(pairs["negative_type"].value_counts())

# ------------------------------------------------------------
# LOAD ORIGINAL COMPATIBILITY DATA
# ------------------------------------------------------------

RAW_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_compatibility_raw.csv"
)

raw = pd.read_csv(RAW_PATH)

# ------------------------------------------------------------
# FEATURE ENGINEERING
# ------------------------------------------------------------

def add_features(df):

    df = df.copy()

    df["bust_ease"] = (
        df["garment_bust"] - df["bust"]
    )

    df["waist_ease"] = (
        df["garment_waist"] - df["waist"]
    )

    df["hip_ease"] = (
        df["garment_hip"] - df["hips"]
    )

    df["bust_ratio"] = (
        df["garment_bust"] / df["bust"]
    )

    df["waist_ratio"] = (
        df["garment_waist"] / df["waist"]
    )

    df["hip_ratio"] = (
        df["garment_hip"] / df["hips"]
    )

    df["bust_mismatch"] = abs(
        df["garment_bust"] - df["bust"]
    )

    df["waist_mismatch"] = abs(
        df["garment_waist"] - df["waist"]
    )

    df["hip_mismatch"] = abs(
        df["garment_hip"] - df["hips"]
    )

    df["bust_relative_mismatch"] = (
        df["bust_mismatch"] / df["bust"]
    )

    df["waist_relative_mismatch"] = (
        df["waist_mismatch"] / df["waist"]
    )

    df["hip_relative_mismatch"] = (
        df["hip_mismatch"] / df["hips"]
    )

    df["mean_ease"] = df[
        [
            "bust_ease",
            "waist_ease",
            "hip_ease",
        ]
    ].mean(axis=1)

    df["ease_std"] = df[
        [
            "bust_ease",
            "waist_ease",
            "hip_ease",
        ]
    ].std(axis=1)

    df["known_fit_dimensions"] = df[
        [
            "bust_ease",
            "waist_ease",
            "hip_ease",
        ]
    ].notna().sum(axis=1)

    df["tight_dimension_count"] = (
        (
            df[
                [
                    "bust_ease",
                    "waist_ease",
                    "hip_ease",
                ]
            ] < 0
        )
        .sum(axis=1)
    )

    df["extreme_ease_count"] = (
        (
            df[
                [
                    "bust_ease",
                    "waist_ease",
                    "hip_ease",
                ]
            ] > 50
        )
        .sum(axis=1)
    )

    df["length_height_ratio"] = (
        df["garment_length"] / df["height"]
    )

    return df


raw = add_features(raw)

# ------------------------------------------------------------
# FEATURE SET
# ------------------------------------------------------------

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

print("\nFeature dimension:", len(FEATURES))

# ------------------------------------------------------------
# CREATE LOOKUP TABLE
# ------------------------------------------------------------

feature_lookup = (
    raw[
        ["person_id", "product_id"] + FEATURES
    ]
    .drop_duplicates(
        ["person_id", "product_id"]
    )
)

# ------------------------------------------------------------
# GARMENT FEATURES ARE PERSON-INDEPENDENT,
# BODY FEATURES ARE PERSON-DEPENDENT.
#
# Build explicit lookup by product for garment attributes.
# ------------------------------------------------------------

GARMENT_FEATURES = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

PERSON_FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",
]

# One person profile
person_lookup = (
    raw[
        ["person_id"] + PERSON_FEATURES
    ]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

# One garment profile
garment_lookup = (
    raw[
        ["product_id"] + GARMENT_FEATURES
    ]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

# ------------------------------------------------------------
# FUNCTION: BUILD FEATURE VECTOR
# ------------------------------------------------------------

def make_pair_features(person_id, product_id):

    person = person_lookup.loc[person_id]
    garment = garment_lookup.loc[product_id]

    row = {}

    # Body
    for feature in PERSON_FEATURES:
        row[feature] = person[feature]

    # Garment
    for feature in GARMENT_FEATURES:
        row[feature] = garment[feature]

    # Derived compatibility
    bust = person["bust"]
    waist = person["waist"]
    hips = person["hips"]
    height = person["height"]

    gb = garment["garment_bust"]
    gw = garment["garment_waist"]
    gh = garment["garment_hip"]
    gl = garment["garment_length"]

    row["bust_ease"] = gb - bust
    row["waist_ease"] = gw - waist
    row["hip_ease"] = gh - hips

    row["bust_ratio"] = gb / bust
    row["waist_ratio"] = gw / waist
    row["hip_ratio"] = gh / hips

    row["bust_mismatch"] = abs(gb - bust)
    row["waist_mismatch"] = abs(gw - waist)
    row["hip_mismatch"] = abs(gh - hips)

    row["bust_relative_mismatch"] = (
        abs(gb - bust) / bust
    )

    row["waist_relative_mismatch"] = (
        abs(gw - waist) / waist
    )

    row["hip_relative_mismatch"] = (
        abs(gh - hips) / hips
    )

    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    row["mean_ease"] = np.nanmean(eases)
    row["ease_std"] = np.nanstd(eases)

    row["known_fit_dimensions"] = np.sum(
        ~np.isnan(eases)
    )

    row["tight_dimension_count"] = np.sum(
        eases < 0
    )

    row["extreme_ease_count"] = np.sum(
        eases > 50
    )

    row["length_height_ratio"] = (
        gl / height
    )

    return np.array(
        [row[f] for f in FEATURES],
        dtype=np.float32,
    )


# ------------------------------------------------------------
# PERSON-LEVEL SPLIT
# ------------------------------------------------------------

people = sorted(
    pairs["person_id"].unique()
)

train_people, temp_people = train_test_split(
    people,
    test_size=16,
    random_state=RANDOM_SEED,
)

val_people, test_people = train_test_split(
    temp_people,
    test_size=8,
    random_state=RANDOM_SEED,
)

train_pairs = pairs[
    pairs["person_id"].isin(train_people)
].copy()

val_pairs = pairs[
    pairs["person_id"].isin(val_people)
].copy()

test_pairs = pairs[
    pairs["person_id"].isin(test_people)
].copy()

print("\n" + "=" * 60)
print("PERSON-LEVEL SPLIT")
print("=" * 60)

print("Train people:", len(train_people))
print("Val people  :", len(val_people))
print("Test people :", len(test_people))

print("\nPairwise rows:")
print("Train:", len(train_pairs))
print("Val  :", len(val_pairs))
print("Test :", len(test_pairs))

print("\nLeakage:")
print(
    "Train ∩ Val :",
    set(train_people) & set(val_people)
)

print(
    "Train ∩ Test:",
    set(train_people) & set(test_people)
)

print(
    "Val ∩ Test  :",
    set(val_people) & set(test_people)
)

# ------------------------------------------------------------
# BUILD PAIRWISE MATRICES
# ------------------------------------------------------------

def build_pairwise_matrix(frame):

    positive_vectors = []
    negative_vectors = []

    for _, row in frame.iterrows():

        positive_vectors.append(
            make_pair_features(
                row["person_id"],
                row["positive_product_id"],
            )
        )

        negative_vectors.append(
            make_pair_features(
                row["person_id"],
                row["negative_product_id"],
            )
        )

    return (
        np.stack(positive_vectors),
        np.stack(negative_vectors),
    )


X_pos_train, X_neg_train = build_pairwise_matrix(
    train_pairs
)

X_pos_val, X_neg_val = build_pairwise_matrix(
    val_pairs
)

X_pos_test, X_neg_test = build_pairwise_matrix(
    test_pairs
)

# ------------------------------------------------------------
# IMPUTE USING TRAIN ONLY
# ------------------------------------------------------------

imputer = SimpleImputer(
    strategy="median",
    add_indicator=True,
)

scaler = StandardScaler()

# Fit on BOTH positive and negative training examples
train_combined = np.vstack(
    [
        X_pos_train,
        X_neg_train,
    ]
)

train_combined = imputer.fit_transform(
    train_combined
)

scaler.fit(train_combined)

# Transform
def transform_pair_data(X_pos, X_neg):

    pos = imputer.transform(X_pos)
    neg = imputer.transform(X_neg)

    pos = scaler.transform(pos)
    neg = scaler.transform(neg)

    return pos, neg


X_pos_train, X_neg_train = transform_pair_data(
    X_pos_train,
    X_neg_train,
)

X_pos_val, X_neg_val = transform_pair_data(
    X_pos_val,
    X_neg_val,
)

X_pos_test, X_neg_test = transform_pair_data(
    X_pos_test,
    X_neg_test,
)

print("\n" + "=" * 60)
print("PAIRWISE TENSORS")
print("=" * 60)

print(
    "Feature dimension:",
    X_pos_train.shape[1]
)

print(
    "Train:",
    X_pos_train.shape,
)

print(
    "Val:",
    X_pos_val.shape,
)

print(
    "Test:",
    X_pos_test.shape,
)

print(
    "NaN:",
    np.isnan(X_pos_train).sum()
    + np.isnan(X_neg_train).sum()
)

print(
    "Inf:",
    np.isinf(X_pos_train).sum()
    + np.isinf(X_neg_train).sum()
)

# ------------------------------------------------------------
# PYTORCH DATASETS
# ------------------------------------------------------------

device = torch.device(
    "mps"
    if torch.backends.mps.is_available()
    else "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print("\nDevice:", device)

train_pos = torch.tensor(
    X_pos_train,
    dtype=torch.float32,
)

train_neg = torch.tensor(
    X_neg_train,
    dtype=torch.float32,
)

val_pos = torch.tensor(
    X_pos_val,
    dtype=torch.float32,
)

val_neg = torch.tensor(
    X_neg_val,
    dtype=torch.float32,
)

test_pos = torch.tensor(
    X_pos_test,
    dtype=torch.float32,
)

test_neg = torch.tensor(
    X_neg_test,
    dtype=torch.float32,
)

train_loader = DataLoader(
    TensorDataset(train_pos, train_neg),
    batch_size=128,
    shuffle=True,
)

# ------------------------------------------------------------
# RANKING MODEL
# ------------------------------------------------------------

class CompatibilityRanker(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 1),
        )

    def forward(self, x):

        return self.network(x).squeeze(-1)


model = CompatibilityRanker(
    input_dim=train_pos.shape[1]
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4,
)

criterion = nn.MarginRankingLoss(
    margin=0.2
)

print("\n" + "=" * 60)
print("MODEL")
print("=" * 60)

print(
    "Input dimension:",
    train_pos.shape[1]
)

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )
)

# ------------------------------------------------------------
# EVALUATION
# ------------------------------------------------------------

def ranking_accuracy(pos_tensor, neg_tensor):

    model.eval()

    with torch.no_grad():

        pos_scores = model(
            pos_tensor.to(device)
        )

        neg_scores = model(
            neg_tensor.to(device)
        )

        correct = (
            pos_scores > neg_scores
        ).float()

        return correct.mean().item()


# ------------------------------------------------------------
# TRAIN
# ------------------------------------------------------------

EPOCHS = 50

best_val = -np.inf
best_state = None

print("\n" + "=" * 60)
print("TRAINING")
print("=" * 60)

for epoch in range(1, EPOCHS + 1):

    model.train()

    total_loss = 0.0
    batches = 0

    for pos_batch, neg_batch in train_loader:

        pos_batch = pos_batch.to(device)
        neg_batch = neg_batch.to(device)

        pos_score = model(pos_batch)
        neg_score = model(neg_batch)

        target = torch.ones(
            pos_score.shape,
            device=device,
        )

        loss = criterion(
            pos_score,
            neg_score,
            target,
        )

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        batches += 1

    train_loss = total_loss / batches

    val_acc = ranking_accuracy(
        val_pos,
        val_neg,
    )

    if val_acc > best_val:

        best_val = val_acc

        best_state = {
            k: v.detach().cpu().clone()
            for k, v in model.state_dict().items()
        }

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        train_acc = ranking_accuracy(
            train_pos,
            train_neg,
        )

        print(
            f"Epoch {epoch:02d}/{EPOCHS} "
            f"| Loss: {train_loss:.4f} "
            f"| Train Rank Acc: {train_acc:.4f} "
            f"| Val Rank Acc: {val_acc:.4f}"
        )

# ------------------------------------------------------------
# RESTORE BEST MODEL
# ------------------------------------------------------------

model.load_state_dict(best_state)

# ------------------------------------------------------------
# FINAL TEST
# ------------------------------------------------------------

train_acc = ranking_accuracy(
    train_pos,
    train_neg,
)

val_acc = ranking_accuracy(
    val_pos,
    val_neg,
)

test_acc = ranking_accuracy(
    test_pos,
    test_neg,
)

print("\n" + "=" * 60)
print("FINAL PAIRWISE RANKING RESULTS")
print("=" * 60)

print(
    f"Train Ranking Accuracy : {train_acc:.4f}"
)

print(
    f"Validation Ranking Acc : {val_acc:.4f}"
)

print(
    f"Test Ranking Accuracy  : {test_acc:.4f}"
)

# ------------------------------------------------------------
# SAVE MODEL + PREPROCESSING
# ------------------------------------------------------------

torch.save(
    {
        "model_state_dict": model.state_dict(),
        "input_dim": train_pos.shape[1],
        "feature_names": FEATURES,
        "best_val_accuracy": best_val,
        "random_seed": RANDOM_SEED,
    },
    MODEL_OUTPUT,
)

print("\nSaved model:")
print(MODEL_OUTPUT)

print("\n" + "=" * 60)
print("PAIRWISE RANKING EXPERIMENT COMPLETE")
print("=" * 60)

============================================================
ZYRA V2 PAIRWISE RANKING
============================================================
Pairwise rows: 8970
People       : 56

Negative types:
negative_type
hard      5980
random    2990
Name: count, dtype: int64

Feature dimension: 27

============================================================
PERSON-LEVEL SPLIT
============================================================
Train people: 40
Val people  : 8
Test people : 8

Pairwise rows:
Train: 6810
Val  : 1143
Test : 1017

Leakage:
Train ∩ Val : set()
Train ∩ Test: set()
Val ∩ Test  : set()

/var/folders/xr/kwlqndgn0kbbch4p_bf7k8_r0000gn/T/ipykernel_54859/492407949.py:337: RuntimeWarning: Mean of empty slice
  row["mean_ease"] = np.nanmean(eases)
/Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/_nanfunctions_impl.py:1997: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/var/folders/xr/kwlqndgn0kbbch4p_bf7k8_r0000gn/T/ipykernel_54859/492407949.py:337: RuntimeWarning: Mean of empty slice
  row["mean_ease"] = np.nanmean(eases)
/Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/_nanfunctions_impl.py:1997: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/var/folders/xr/kwlqndgn0kbbch4p_bf7k8_r0000gn/T/ipykernel_54859/492407949.py:337: RuntimeWarning: Mean of empty slice
  row["mean_ease"] = np.nanmean(eases)
/Users/saketh/Desktop/Projects/weavly/core-model/.venv/lib/python3.13/site-packages/numpy/lib/_nanfunctions_impl.py:1997: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

============================================================
PAIRWISE TENSORS
============================================================
Feature dimension: 47
Train: (6810, 47)
Val: (1143, 47)
Test: (1017, 47)
NaN: 0
Inf: 0

Device: mps

============================================================
MODEL
============================================================
Input dimension: 47
Parameters: 5185

============================================================
TRAINING
============================================================
Epoch 01/50 | Loss: 0.0736 | Train Rank Acc: 0.8755 | Val Rank Acc: 0.8521
Epoch 05/50 | Loss: 0.0483 | Train Rank Acc: 0.9037 | Val Rank Acc: 0.8451
Epoch 10/50 | Loss: 0.0423 | Train Rank Acc: 0.9147 | Val Rank Acc: 0.8486
Epoch 15/50 | Loss: 0.0384 | Train Rank Acc: 0.9184 | Val Rank Acc: 0.8469
Epoch 20/50 | Loss: 0.0354 | Train Rank Acc: 0.9297 | Val Rank Acc: 0.8478
Epoch 25/50 | Loss: 0.0306 | Train Rank Acc: 0.9386 | Val Rank Acc: 0.8049
Epoch 30/50 | Loss: 0.0284 | Train Rank Acc: 0.9476 | Val Rank Acc: 0.7944
Epoch 35/50 | Loss: 0.0254 | Train Rank Acc: 0.9554 | Val Rank Acc: 0.8206
Epoch 40/50 | Loss: 0.0234 | Train Rank Acc: 0.9501 | Val Rank Acc: 0.8259
Epoch 45/50 | Loss: 0.0220 | Train Rank Acc: 0.9636 | Val Rank Acc: 0.7874
Epoch 50/50 | Loss: 0.0201 | Train Rank Acc: 0.9664 | Val Rank Acc: 0.7970

============================================================
FINAL PAIRWISE RANKING RESULTS
============================================================
Train Ranking Accuracy : 0.8863
Validation Ranking Acc : 0.8714
Test Ranking Accuracy  : 0.8417

Saved model:
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_pairwise_ranker.pt

============================================================
PAIRWISE RANKING EXPERIMENT COMPLETE
============================================================

In [59]:
# ============================================================
# ZYRA V2 — HELD-OUT NEGATIVE EVALUATION
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

RAW_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_compatibility_raw.csv"
)

PAIRWISE_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_pairwise_ranking.csv"
)

MODEL_PATH = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model/"
    "data/v2/v2_pairwise_ranker.pt"
)

# ------------------------------------------------------------
# LOAD
# ------------------------------------------------------------

raw = pd.read_csv(RAW_PATH)
trained_pairs = pd.read_csv(PAIRWISE_PATH)
checkpoint = torch.load(
    MODEL_PATH,
    map_location="cpu",
)

# ------------------------------------------------------------
# FEATURE ENGINEERING
# ------------------------------------------------------------

def add_features(df):

    df = df.copy()

    df["bust_ease"] = (
        df["garment_bust"] - df["bust"]
    )

    df["waist_ease"] = (
        df["garment_waist"] - df["waist"]
    )

    df["hip_ease"] = (
        df["garment_hip"] - df["hips"]
    )

    df["bust_ratio"] = (
        df["garment_bust"] / df["bust"]
    )

    df["waist_ratio"] = (
        df["garment_waist"] / df["waist"]
    )

    df["hip_ratio"] = (
        df["garment_hip"] / df["hips"]
    )

    df["bust_mismatch"] = abs(
        df["garment_bust"] - df["bust"]
    )

    df["waist_mismatch"] = abs(
        df["garment_waist"] - df["waist"]
    )

    df["hip_mismatch"] = abs(
        df["garment_hip"] - df["hips"]
    )

    df["bust_relative_mismatch"] = (
        df["bust_mismatch"] / df["bust"]
    )

    df["waist_relative_mismatch"] = (
        df["waist_mismatch"] / df["waist"]
    )

    df["hip_relative_mismatch"] = (
        df["hip_mismatch"] / df["hips"]
    )

    eases = df[
        [
            "bust_ease",
            "waist_ease",
            "hip_ease",
        ]
    ]

    df["mean_ease"] = eases.mean(
        axis=1
    )

    df["ease_std"] = eases.std(
        axis=1
    )

    df["known_fit_dimensions"] = (
        eases.notna().sum(axis=1)
    )

    df["tight_dimension_count"] = (
        (eases < 0).sum(axis=1)
    )

    df["extreme_ease_count"] = (
        (eases > 50).sum(axis=1)
    )

    df["length_height_ratio"] = (
        df["garment_length"]
        / df["height"]
    )

    return df


raw = add_features(raw)

# ------------------------------------------------------------
# SAME 27 FEATURES USED BY RANKER
# ------------------------------------------------------------

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

# ------------------------------------------------------------
# LOOKUPS
# ------------------------------------------------------------

person_lookup = (
    raw[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

garment_lookup = (
    raw[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

all_products = list(
    garment_lookup.index
)

# ------------------------------------------------------------
# BUILD FEATURE VECTOR
# ------------------------------------------------------------

def make_features(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    row = {}

    for f in [
        "height",
        "bust",
        "waist",
        "hips",
    ]:
        row[f] = p[f]

    for f in [
        "garment_bust",
        "garment_waist",
        "garment_hip",
        "garment_length",
        "garment_sleeve",
    ]:
        row[f] = g[f]

    bust = p["bust"]
    waist = p["waist"]
    hips = p["hips"]
    height = p["height"]

    gb = g["garment_bust"]
    gw = g["garment_waist"]
    gh = g["garment_hip"]
    gl = g["garment_length"]

    row["bust_ease"] = gb - bust
    row["waist_ease"] = gw - waist
    row["hip_ease"] = gh - hips

    row["bust_ratio"] = gb / bust
    row["waist_ratio"] = gw / waist
    row["hip_ratio"] = gh / hips

    row["bust_mismatch"] = abs(
        gb - bust
    )

    row["waist_mismatch"] = abs(
        gw - waist
    )

    row["hip_mismatch"] = abs(
        gh - hips
    )

    row["bust_relative_mismatch"] = (
        abs(gb - bust) / bust
    )

    row["waist_relative_mismatch"] = (
        abs(gw - waist) / waist
    )

    row["hip_relative_mismatch"] = (
        abs(gh - hips) / hips
    )

    ease_values = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    if np.all(np.isnan(ease_values)):

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    else:

        row["mean_ease"] = np.nanmean(
            ease_values
        )

        row["ease_std"] = np.nanstd(
            ease_values
        )

    row["known_fit_dimensions"] = (
        np.sum(~np.isnan(ease_values))
    )

    row["tight_dimension_count"] = np.nansum(
        ease_values < 0
    )

    row["extreme_ease_count"] = np.nansum(
        ease_values > 50
    )

    row["length_height_ratio"] = (
        gl / height
    )

    return np.array(
        [
            row[f]
            for f in FEATURES
        ],
        dtype=np.float32,
    )

# ------------------------------------------------------------
# RECREATE EXACT TRAIN / VAL / TEST PEOPLE
# ------------------------------------------------------------

people = sorted(
    trained_pairs["person_id"].unique()
)

train_people, temp_people = train_test_split(
    people,
    test_size=16,
    random_state=42,
)

val_people, test_people = train_test_split(
    temp_people,
    test_size=8,
    random_state=42,
)

# ------------------------------------------------------------
# IDENTIFY ALL ALREADY USED NEGATIVES
# ------------------------------------------------------------

used_negatives = set(
    zip(
        trained_pairs["person_id"],
        trained_pairs["negative_product_id"],
    )
)

positive_pairs = set(
    zip(
        trained_pairs["person_id"],
        trained_pairs["positive_product_id"],
    )
)

print("=" * 60)
print("HELD-OUT NEGATIVE EVALUATION")
print("=" * 60)

print(
    "Training pairwise samples:",
    len(trained_pairs)
)

print(
    "Used negative pairs:",
    len(used_negatives)
)

# ------------------------------------------------------------
# BUILD FRESH NEGATIVES
# ------------------------------------------------------------
#
# We deliberately select negatives that:
#
#   1. Were never used by the original sampler
#   2. Are not positive for that person
#   3. Are physically plausible enough to be meaningful
#
# We select a random fresh negative from the middle
# of the physical-distance distribution rather than
# simply choosing the closest ones.
# ------------------------------------------------------------

fresh_pairs = []

rng = np.random.default_rng(12345)

# Only evaluate unseen people from TEST
for person in test_people:

    person_positives = {
        product
        for p, product in positive_pairs
        if p == person
    }

    candidates = []

    for product in all_products:

        key = (
            person,
            product,
        )

        if product in person_positives:
            continue

        if key in used_negatives:
            continue

        try:

            vec = make_features(
                person,
                product,
            )

            # Need at least some physical information
            if np.isnan(vec).all():
                continue

            candidates.append(
                product
            )

        except Exception:
            continue

    if not candidates:
        continue

    # --------------------------------------------------------
    # For every positive garment belonging to this person,
    # select one completely fresh negative.
    # --------------------------------------------------------

    person_positive_products = list(
        person_positives
    )

    for positive_product in person_positive_products:

        # Random fresh negative
        negative_product = rng.choice(
            candidates
        )

        fresh_pairs.append(
            {
                "person_id": person,
                "positive_product_id":
                    positive_product,
                "negative_product_id":
                    negative_product,
            }
        )

# ------------------------------------------------------------
# DATAFRAME
# ------------------------------------------------------------

fresh_df = pd.DataFrame(
    fresh_pairs
)

print("\nFresh evaluation pairs:")
print(len(fresh_df))

print(
    "People:",
    fresh_df["person_id"].nunique()
    if len(fresh_df)
    else 0
)

# ------------------------------------------------------------
# VERIFY ZERO OVERLAP
# ------------------------------------------------------------

fresh_negative_keys = set(
    zip(
        fresh_df["person_id"],
        fresh_df["negative_product_id"],
    )
)

overlap = (
    fresh_negative_keys
    & used_negatives
)

print(
    "Fresh negative overlap with training:",
    len(overlap)
)

# ------------------------------------------------------------
# MODEL
# ------------------------------------------------------------

class CompatibilityRanker(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 1),
        )

    def forward(self, x):

        return self.network(x).squeeze(-1)


model = CompatibilityRanker(
    checkpoint["input_dim"]
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model.eval()

# ------------------------------------------------------------
# IMPORTANT:
# The original training cell used median imputation +
# StandardScaler.
#
# Reconstruct those preprocessing statistics from the
# ORIGINAL training people only.
# ------------------------------------------------------------

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Build original training pair features
original_train = trained_pairs[
    trained_pairs["person_id"].isin(
        train_people
    )
]

train_vectors = []

for _, row in original_train.iterrows():

    train_vectors.append(
        make_features(
            row["person_id"],
            row["positive_product_id"],
        )
    )

    train_vectors.append(
        make_features(
            row["person_id"],
            row["negative_product_id"],
        )
    )

train_vectors = np.stack(
    train_vectors
)

imputer = SimpleImputer(
    strategy="median",
    add_indicator=True,
)

train_imputed = imputer.fit_transform(
    train_vectors
)

scaler = StandardScaler()

scaler.fit(
    train_imputed
)

# ------------------------------------------------------------
# EVALUATE FRESH PAIRS
# ------------------------------------------------------------

fresh_pos = []
fresh_neg = []

for _, row in fresh_df.iterrows():

    fresh_pos.append(
        make_features(
            row["person_id"],
            row["positive_product_id"],
        )
    )

    fresh_neg.append(
        make_features(
            row["person_id"],
            row["negative_product_id"],
        )
    )

if len(fresh_pos) == 0:

    raise RuntimeError(
        "No fresh evaluation pairs were created."
    )

fresh_pos = np.stack(
    fresh_pos
)

fresh_neg = np.stack(
    fresh_neg
)

fresh_pos = scaler.transform(
    imputer.transform(
        fresh_pos
    )
)

fresh_neg = scaler.transform(
    imputer.transform(
        fresh_neg
    )
)

pos_tensor = torch.tensor(
    fresh_pos,
    dtype=torch.float32,
)

neg_tensor = torch.tensor(
    fresh_neg,
    dtype=torch.float32,
)

with torch.no_grad():

    pos_scores = model(
        pos_tensor
    )

    neg_scores = model(
        neg_tensor
    )

    correct = (
        pos_scores > neg_scores
    )

    accuracy = (
        correct.float()
        .mean()
        .item()
    )

# ------------------------------------------------------------
# SCORE GAP
# ------------------------------------------------------------

score_gap = (
    pos_scores - neg_scores
)

# ------------------------------------------------------------
# RESULTS
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("HELD-OUT RESULTS")
print("=" * 60)

print(
    "Fresh evaluation pairs:",
    len(fresh_df)
)

print(
    "Positive score mean:",
    round(
        pos_scores.mean().item(),
        4,
    )
)

print(
    "Negative score mean:",
    round(
        neg_scores.mean().item(),
        4,
    )
)

print(
    "Mean score gap:",
    round(
        score_gap.mean().item(),
        4,
    )
)

print(
    "Median score gap:",
    round(
        score_gap.median().item(),
        4,
    )
)

print(
    "Held-out ranking accuracy:",
    round(
        accuracy,
        4,
    )
)

# ------------------------------------------------------------
# COMPARE WITH ORIGINAL TEST
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("COMPARISON")
print("=" * 60)

print(
    "Original test ranking accuracy : 0.8417"
)

print(
    "Fresh held-out ranking accuracy:",
    round(
        accuracy,
        4,
    )
)

print(
    "Difference:",
    round(
        accuracy - 0.8417,
        4,
    )
)

# ------------------------------------------------------------
# FINAL INTERPRETATION
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("INTERPRETATION")
print("=" * 60)

if accuracy >= 0.75:

    print(
        "STRONG: ranking signal survives "
        "fresh-negative evaluation."
    )

elif accuracy >= 0.60:

    print(
        "MODERATE: useful signal exists, "
        "but generalization is weaker."
    )

elif accuracy >= 0.52:

    print(
        "WEAK: model has limited generalization "
        "to unseen negatives."
    )

else:

    print(
        "FAIL: fresh-negative ranking is "
        "close to random."
    )

print("\nHeld-out evaluation complete.")

============================================================
HELD-OUT NEGATIVE EVALUATION
============================================================
Training pairwise samples: 8970
Used negative pairs: 2869

Fresh evaluation pairs:
339
People: 8
Fresh negative overlap with training: 0

============================================================
HELD-OUT RESULTS
============================================================
Fresh evaluation pairs: 339
Positive score mean: 0.1967
Negative score mean: 0.1512
Mean score gap: 0.0455
Median score gap: 0.0462
Held-out ranking accuracy: 0.6254

============================================================
COMPARISON
============================================================
Original test ranking accuracy : 0.8417
Fresh held-out ranking accuracy: 0.6254
Difference: -0.2163

============================================================
INTERPRETATION
============================================================
MODERATE: useful signal exists, but generalization is weaker.

Held-out evaluation complete.

In [60]:
# ============================================================
# ZYRA V2 — RIGOROUS GENERALIZATION BENCHMARK
# ============================================================
#
# IMPORTANT:
# - NO RETRAINING
# - Uses the existing saved ranker
# - Person-level TEST people only
# - Negatives used during original pairwise training are excluded
#
# Evaluates:
#   1. Random unseen negatives
#   2. Hard unseen negatives
#   3. Mixed unseen negatives
#   4. ROC-AUC
#   5. PR-AUC
#   6. Pairwise ranking accuracy
#   7. Per-person accuracy
#   8. Complete vs incomplete measurement performance
#
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
)

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

PAIRWISE_PATH = (
    BASE /
    "data/v2/v2_pairwise_ranking.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_pairwise_ranker.pt"
)

SEED = 42

rng = np.random.default_rng(2026)

# ============================================================
# LOAD DATA
# ============================================================

raw = pd.read_csv(RAW_PATH)

pairwise = pd.read_csv(
    PAIRWISE_PATH
)

checkpoint = torch.load(
    MODEL_PATH,
    map_location="cpu",
)

print("=" * 65)
print("ZYRA V2 — RIGOROUS GENERALIZATION BENCHMARK")
print("=" * 65)

print(
    "Raw rows:",
    len(raw)
)

print(
    "Pairwise rows:",
    len(pairwise)
)

print(
    "People:",
    pairwise["person_id"].nunique()
)

print(
    "Saved model:",
    MODEL_PATH
)

# ============================================================
# FEATURE ENGINEERING
# ============================================================

def add_features(df):

    df = df.copy()

    # ----------------------------
    # Physical compatibility
    # ----------------------------

    df["bust_ease"] = (
        df["garment_bust"] -
        df["bust"]
    )

    df["waist_ease"] = (
        df["garment_waist"] -
        df["waist"]
    )

    df["hip_ease"] = (
        df["garment_hip"] -
        df["hips"]
    )

    # ----------------------------
    # Ratios
    # ----------------------------

    df["bust_ratio"] = (
        df["garment_bust"] /
        df["bust"]
    )

    df["waist_ratio"] = (
        df["garment_waist"] /
        df["waist"]
    )

    df["hip_ratio"] = (
        df["garment_hip"] /
        df["hips"]
    )

    # ----------------------------
    # Absolute mismatch
    # ----------------------------

    df["bust_mismatch"] = abs(
        df["garment_bust"] -
        df["bust"]
    )

    df["waist_mismatch"] = abs(
        df["garment_waist"] -
        df["waist"]
    )

    df["hip_mismatch"] = abs(
        df["garment_hip"] -
        df["hips"]
    )

    # ----------------------------
    # Relative mismatch
    # ----------------------------

    df["bust_relative_mismatch"] = (
        df["bust_mismatch"] /
        df["bust"]
    )

    df["waist_relative_mismatch"] = (
        df["waist_mismatch"] /
        df["waist"]
    )

    df["hip_relative_mismatch"] = (
        df["hip_mismatch"] /
        df["hips"]
    )

    # ----------------------------
    # Aggregate ease
    # ----------------------------

    ease_cols = [
        "bust_ease",
        "waist_ease",
        "hip_ease",
    ]

    df["mean_ease"] = (
        df[ease_cols]
        .mean(axis=1)
    )

    df["ease_std"] = (
        df[ease_cols]
        .std(axis=1)
    )

    # ----------------------------
    # Missingness / thresholds
    # ----------------------------

    df["known_fit_dimensions"] = (
        df[ease_cols]
        .notna()
        .sum(axis=1)
    )

    df["tight_dimension_count"] = (
        df[ease_cols]
        .lt(0)
        .sum(axis=1)
    )

    df["extreme_ease_count"] = (
        df[ease_cols]
        .gt(50)
        .sum(axis=1)
    )

    # ----------------------------
    # Length
    # ----------------------------

    df["length_height_ratio"] = (
        df["garment_length"] /
        df["height"]
    )

    return df


raw = add_features(raw)

# ============================================================
# FEATURES
# ============================================================

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

print("\nFeature count:", len(FEATURES))

# ============================================================
# LOOKUPS
# ============================================================

person_cols = [
    "height",
    "bust",
    "waist",
    "hips",
]

garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

person_lookup = (
    raw[
        ["person_id"] +
        person_cols
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index("person_id")
)

garment_lookup = (
    raw[
        ["product_id"] +
        garment_cols
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index("product_id")
)

all_people = sorted(
    person_lookup.index
)

all_products = sorted(
    garment_lookup.index
)

# ============================================================
# FEATURE VECTOR GENERATOR
# ============================================================

def make_features(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    row = {}

    # Body
    for f in person_cols:
        row[f] = p[f]

    # Garment
    for f in garment_cols:
        row[f] = g[f]

    bust = p["bust"]
    waist = p["waist"]
    hips = p["hips"]
    height = p["height"]

    gb = g["garment_bust"]
    gw = g["garment_waist"]
    gh = g["garment_hip"]
    gl = g["garment_length"]

    # ----------------------------
    # Ease
    # ----------------------------

    row["bust_ease"] = (
        gb - bust
    )

    row["waist_ease"] = (
        gw - waist
    )

    row["hip_ease"] = (
        gh - hips
    )

    # ----------------------------
    # Ratios
    # ----------------------------

    row["bust_ratio"] = (
        gb / bust
    )

    row["waist_ratio"] = (
        gw / waist
    )

    row["hip_ratio"] = (
        gh / hips
    )

    # ----------------------------
    # Mismatch
    # ----------------------------

    row["bust_mismatch"] = abs(
        gb - bust
    )

    row["waist_mismatch"] = abs(
        gw - waist
    )

    row["hip_mismatch"] = abs(
        gh - hips
    )

    row["bust_relative_mismatch"] = (
        row["bust_mismatch"] /
        bust
    )

    row["waist_relative_mismatch"] = (
        row["waist_mismatch"] /
        waist
    )

    row["hip_relative_mismatch"] = (
        row["hip_mismatch"] /
        hips
    )

    # ----------------------------
    # Aggregate
    # ----------------------------

    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    if np.all(
        np.isnan(eases)
    ):

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    else:

        row["mean_ease"] = np.nanmean(
            eases
        )

        row["ease_std"] = np.nanstd(
            eases
        )

    row["known_fit_dimensions"] = (
        np.sum(
            ~np.isnan(eases)
        )
    )

    row["tight_dimension_count"] = (
        np.sum(
            eases < 0
        )
    )

    row["extreme_ease_count"] = (
        np.sum(
            eases > 50
        )
    )

    row["length_height_ratio"] = (
        gl / height
    )

    return np.array(
        [
            row[f]
            for f in FEATURES
        ],
        dtype=np.float32,
    )


# ============================================================
# RECREATE PERSON SPLIT
# ============================================================

people = sorted(
    pairwise["person_id"].unique()
)

train_people, temp_people = (
    train_test_split(
        people,
        test_size=16,
        random_state=SEED,
    )
)

val_people, test_people = (
    train_test_split(
        temp_people,
        test_size=8,
        random_state=SEED,
    )
)

train_people = set(
    train_people
)

val_people = set(
    val_people
)

test_people = set(
    test_people
)

print("\n" + "=" * 65)
print("PERSON SPLIT")
print("=" * 65)

print(
    "Train:",
    len(train_people)
)

print(
    "Validation:",
    len(val_people)
)

print(
    "Test:",
    len(test_people)
)

# ============================================================
# ORIGINAL POSITIVE PAIRS
# ============================================================

positive_keys = set(
    zip(
        pairwise["person_id"],
        pairwise[
            "positive_product_id"
        ],
    )
)

# ============================================================
# ORIGINAL NEGATIVE PAIRS
# ============================================================

negative_keys = set(
    zip(
        pairwise["person_id"],
        pairwise[
            "negative_product_id"
        ],
    )
)

print(
    "\nOriginal negative pair keys:",
    len(negative_keys)
)

# ============================================================
# PHYSICAL DISTANCE
# ============================================================
#
# Lower distance = more physically similar.
#
# We calculate normalized mismatch using available
# measurements.
#
# This is ONLY used to construct evaluation negatives.
# It is NOT given to the model directly.
# ============================================================

def physical_distance(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    distances = []

    pairs = [
        (
            p["bust"],
            g["garment_bust"],
        ),
        (
            p["waist"],
            g["garment_waist"],
        ),
        (
            p["hips"],
            g["garment_hip"],
        ),
        (
            p["height"],
            g["garment_length"],
        ),
    ]

    for person_value, garment_value in pairs:

        if (
            pd.isna(person_value)
            or pd.isna(garment_value)
        ):
            continue

        # Relative mismatch
        if person_value != 0:

            distances.append(
                abs(
                    garment_value -
                    person_value
                )
                / abs(person_value)
            )

    if not distances:
        return np.nan

    return float(
        np.mean(distances)
    )


# ============================================================
# BUILD TEST POSITIVES
# ============================================================

test_positive_by_person = {}

for person in test_people:

    products = set(
        pairwise.loc[
            pairwise["person_id"]
            == person,
            "positive_product_id",
        ]
    )

    test_positive_by_person[
        person
    ] = sorted(products)

print("\nTest positive interactions:")

for person in sorted(test_positive_by_person):

    print(
        person,
        ":",
        len(
            test_positive_by_person[
                person
            ]
        )
    )

# ============================================================
# BUILD ALL FRESH CANDIDATES
# ============================================================

fresh_candidates = {}

for person in sorted(test_people):

    positive_products = set(
        test_positive_by_person[
            person
        ]
    )

    candidates = []

    for product in all_products:

        key = (
            person,
            product,
        )

        # Never positive
        if product in positive_products:
            continue

        # Never used by original negative sampler
        if key in negative_keys:
            continue

        # Must have at least some measurable information
        try:

            vec = make_features(
                person,
                product,
            )

            if np.isnan(vec).all():
                continue

        except Exception:
            continue

        distance = physical_distance(
            person,
            product,
        )

        if np.isnan(distance):
            continue

        candidates.append(
            (
                product,
                distance,
            )
        )

    fresh_candidates[
        person
    ] = candidates

# ============================================================
# CREATE THREE EVALUATION SETS
# ============================================================
#
# RANDOM:
#   random fresh negative
#
# HARD:
#   physically closest fresh negative
#
# MIXED:
#   50% hard + 50% random
#
# We use ONE negative per positive interaction.
# ============================================================

evaluation_sets = {
    "random": [],
    "hard": [],
    "mixed": [],
}

for person in sorted(test_people):

    positives = test_positive_by_person[
        person
    ]

    candidates = fresh_candidates[
        person
    ]

    if len(candidates) == 0:
        continue

    candidates_sorted = sorted(
        candidates,
        key=lambda x: x[1],
    )

    # Top 20% = hard candidate pool
    hard_pool_size = max(
        1,
        int(
            len(candidates_sorted)
            * 0.20
        ),
    )

    hard_pool = candidates_sorted[
        :hard_pool_size
    ]

    for index, positive_product in enumerate(
        positives
    ):

        # ------------------------
        # Random
        # ------------------------

        random_product, random_distance = (
            candidates[
                rng.integers(
                    0,
                    len(candidates),
                )
            ]
        )

        # ------------------------
        # Hard
        # ------------------------

        hard_product, hard_distance = (
            hard_pool[
                index
                % len(hard_pool)
            ]
        )

        # ------------------------
        # Mixed
        # ------------------------

        if index % 2 == 0:

            mixed_product = (
                hard_product
            )

            mixed_distance = (
                hard_distance
            )

            mixed_type = "hard"

        else:

            mixed_product = (
                random_product
            )

            mixed_distance = (
                random_distance
            )

            mixed_type = "random"

        evaluation_sets[
            "random"
        ].append(
            {
                "person_id": person,
                "positive_product_id":
                    positive_product,
                "negative_product_id":
                    random_product,
                "negative_distance":
                    random_distance,
                "negative_type":
                    "random",
            }
        )

        evaluation_sets[
            "hard"
        ].append(
            {
                "person_id": person,
                "positive_product_id":
                    positive_product,
                "negative_product_id":
                    hard_product,
                "negative_distance":
                    hard_distance,
                "negative_type":
                    "hard",
            }
        )

        evaluation_sets[
            "mixed"
        ].append(
            {
                "person_id": person,
                "positive_product_id":
                    positive_product,
                "negative_product_id":
                    mixed_product,
                "negative_distance":
                    mixed_distance,
                "negative_type":
                    mixed_type,
            }
        )

# ============================================================
# VERIFY NO TRAINING NEGATIVE OVERLAP
# ============================================================

print("\n" + "=" * 65)
print("FRESH NEGATIVE INTEGRITY")
print("=" * 65)

for name, rows in evaluation_sets.items():

    df = pd.DataFrame(rows)

    eval_negative_keys = set(
        zip(
            df["person_id"],
            df["negative_product_id"],
        )
    )

    overlap = (
        eval_negative_keys
        & negative_keys
    )

    positive_collision = (
        eval_negative_keys
        & positive_keys
    )

    print(
        f"{name:10s}"
        f" | rows={len(df):4d}"
        f" | train-negative overlap={len(overlap)}"
        f" | positive collision={len(positive_collision)}"
    )

# ============================================================
# REBUILD PREPROCESSING
# ============================================================
#
# IMPORTANT:
# Fit imputer/scaler using TRAIN PEOPLE ONLY.
# ============================================================

train_rows = pairwise[
    pairwise["person_id"].isin(
        train_people
    )
]

train_vectors = []

for _, row in train_rows.iterrows():

    train_vectors.append(
        make_features(
            row["person_id"],
            row["positive_product_id"],
        )
    )

    train_vectors.append(
        make_features(
            row["person_id"],
            row["negative_product_id"],
        )
    )

train_vectors = np.stack(
    train_vectors
)

imputer = SimpleImputer(
    strategy="median",
    add_indicator=True,
)

train_imputed = (
    imputer.fit_transform(
        train_vectors
    )
)

scaler = StandardScaler()

scaler.fit(
    train_imputed
)

# ============================================================
# MODEL
# ============================================================

class CompatibilityRanker(nn.Module):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)


model = CompatibilityRanker(
    checkpoint[
        "input_dim"
    ]
)

model.load_state_dict(
    checkpoint[
        "model_state_dict"
    ]
)

model.eval()

print("\nModel loaded.")

# ============================================================
# EVALUATION FUNCTION
# ============================================================

def evaluate_dataset(
    frame,
):

    positive_vectors = []
    negative_vectors = []

    for _, row in frame.iterrows():

        positive_vectors.append(
            make_features(
                row["person_id"],
                row["positive_product_id"],
            )
        )

        negative_vectors.append(
            make_features(
                row["person_id"],
                row["negative_product_id"],
            )
        )

    positive_vectors = np.stack(
        positive_vectors
    )

    negative_vectors = np.stack(
        negative_vectors
    )

    # Impute
    positive_vectors = (
        imputer.transform(
            positive_vectors
        )
    )

    negative_vectors = (
        imputer.transform(
            negative_vectors
        )
    )

    # Scale
    positive_vectors = (
        scaler.transform(
            positive_vectors
        )
    )

    negative_vectors = (
        scaler.transform(
            negative_vectors
        )
    )

    pos_tensor = torch.tensor(
        positive_vectors,
        dtype=torch.float32,
    )

    neg_tensor = torch.tensor(
        negative_vectors,
        dtype=torch.float32,
    )

    with torch.no_grad():

        positive_scores = (
            model(
                pos_tensor
            )
            .numpy()
        )

        negative_scores = (
            model(
                neg_tensor
            )
            .numpy()
        )

    # Pairwise accuracy
    pairwise_accuracy = float(
        np.mean(
            positive_scores
            >
            negative_scores
        )
    )

    # Classification-style labels
    y_true = np.concatenate(
        [
            np.ones(
                len(positive_scores)
            ),
            np.zeros(
                len(negative_scores)
            ),
        ]
    )

    y_score = np.concatenate(
        [
            positive_scores,
            negative_scores,
        ]
    )

    roc_auc = roc_auc_score(
        y_true,
        y_score,
    )

    pr_auc = average_precision_score(
        y_true,
        y_score,
    )

    score_gap = (
        positive_scores -
        negative_scores
    )

    return {
        "pairs": len(frame),
        "pairwise_accuracy":
            pairwise_accuracy,
        "roc_auc":
            roc_auc,
        "pr_auc":
            pr_auc,
        "mean_positive_score":
            float(
                np.mean(
                    positive_scores
                )
            ),
        "mean_negative_score":
            float(
                np.mean(
                    negative_scores
                )
            ),
        "mean_score_gap":
            float(
                np.mean(
                    score_gap
                )
            ),
        "median_score_gap":
            float(
                np.median(
                    score_gap
                )
            ),
    }


# ============================================================
# GLOBAL RESULTS
# ============================================================

results = {}

print("\n" + "=" * 65)
print("GLOBAL GENERALIZATION RESULTS")
print("=" * 65)

for name, rows in evaluation_sets.items():

    df = pd.DataFrame(rows)

    result = evaluate_dataset(
        df
    )

    results[name] = result

    print(
        f"\n{name.upper()}"
    )

    print(
        "Pairs:",
        result["pairs"]
    )

    print(
        "Pairwise Accuracy:",
        f'{result["pairwise_accuracy"]:.4f}'
    )

    print(
        "ROC-AUC:",
        f'{result["roc_auc"]:.4f}'
    )

    print(
        "PR-AUC:",
        f'{result["pr_auc"]:.4f}'
    )

    print(
        "Mean positive score:",
        f'{result["mean_positive_score"]:.4f}'
    )

    print(
        "Mean negative score:",
        f'{result["mean_negative_score"]:.4f}'
    )

    print(
        "Mean score gap:",
        f'{result["mean_score_gap"]:.4f}'
    )

    print(
        "Median score gap:",
        f'{result["median_score_gap"]:.4f}'
    )

# ============================================================
# PER-PERSON PERFORMANCE
# ============================================================

print("\n" + "=" * 65)
print("PER-PERSON PERFORMANCE")
print("=" * 65)

person_results = []

for name, rows in evaluation_sets.items():

    df = pd.DataFrame(rows)

    for person in sorted(
        df["person_id"].unique()
    ):

        subset = df[
            df["person_id"]
            == person
        ]

        result = evaluate_dataset(
            subset
        )

        person_results.append(
            {
                "evaluation":
                    name,
                "person_id":
                    person,
                "pairs":
                    result["pairs"],
                "pairwise_accuracy":
                    result[
                        "pairwise_accuracy"
                    ],
                "roc_auc":
                    result[
                        "roc_auc"
                    ],
            }
        )

person_results_df = pd.DataFrame(
    person_results
)

print(
    person_results_df
    .groupby("evaluation")[
        [
            "pairwise_accuracy",
            "roc_auc",
        ]
    ]
    .agg(
        [
            "mean",
            "std",
            "min",
            "max",
        ]
    )
)

# ============================================================
# MISSINGNESS ANALYSIS
# ============================================================

print("\n" + "=" * 65)
print("COMPLETE vs INCOMPLETE MEASUREMENTS")
print("=" * 65)

# Determine completeness from garment table
garment_completeness = (
    garment_lookup[
        garment_cols
    ]
    .notna()
    .sum(axis=1)
)

garment_completeness = (
    garment_completeness
    >= len(garment_cols)
)

for name, rows in evaluation_sets.items():

    df = pd.DataFrame(rows)

    complete_mask = []

    for _, row in df.iterrows():

        product = (
            row[
                "positive_product_id"
            ]
        )

        complete_mask.append(
            bool(
                garment_completeness
                .get(
                    product,
                    False,
                )
            )
        )

    df["positive_complete"] = (
        complete_mask
    )

    for category, subset in df.groupby(
        "positive_complete"
    ):

        if len(subset) == 0:
            continue

        result = evaluate_dataset(
            subset
        )

        print(
            f"\n{name.upper()} | "
            f"positive garment complete="
            f"{category}"
        )

        print(
            "Pairs:",
            len(subset)
        )

        print(
            "Pairwise accuracy:",
            f'{result["pairwise_accuracy"]:.4f}'
        )

        print(
            "ROC-AUC:",
            f'{result["roc_auc"]:.4f}'
        )

        print(
            "PR-AUC:",
            f'{result["pr_auc"]:.4f}'
        )

# ============================================================
# NEGATIVE DISTANCE ANALYSIS
# ============================================================

print("\n" + "=" * 65)
print("NEGATIVE DIFFICULTY")
print("=" * 65)

for name, rows in evaluation_sets.items():

    df = pd.DataFrame(rows)

    print(
        f"\n{name.upper()}"
    )

    print(
        df["negative_distance"]
        .describe()
    )

# ============================================================
# FINAL COMPARISON TABLE
# ============================================================

comparison = pd.DataFrame(
    results
).T

print("\n" + "=" * 65)
print("FINAL BENCHMARK TABLE")
print("=" * 65)

display(
    comparison[
        [
            "pairs",
            "pairwise_accuracy",
            "roc_auc",
            "pr_auc",
            "mean_score_gap",
        ]
    ]
)

# ============================================================
# ORIGINAL RESULT
# ============================================================

print("\n" + "=" * 65)
print("REFERENCE")
print("=" * 65)

print(
    "Original test ranking accuracy : 0.8417"
)

print(
    "Previous fresh-negative accuracy: 0.6254"
)

# ============================================================
# INTERPRETATION
# ============================================================

random_acc = results[
    "random"
]["pairwise_accuracy"]

hard_acc = results[
    "hard"
]["pairwise_accuracy"]

mixed_acc = results[
    "mixed"
]["pairwise_accuracy"]

print("\n" + "=" * 65)
print("INTERPRETATION")
print("=" * 65)

print(
    f"Random unseen : {random_acc:.4f}"
)

print(
    f"Hard unseen   : {hard_acc:.4f}"
)

print(
    f"Mixed unseen  : {mixed_acc:.4f}"
)

if hard_acc >= 0.70:

    print(
        "\nSTRONG GENERALIZATION:"
        "\nThe model remains effective "
        "against physically difficult "
        "unseen negatives."
    )

elif hard_acc >= 0.60:

    print(
        "\nMODERATE GENERALIZATION:"
        "\nThe model has real compatibility "
        "signal, but hard negatives remain "
        "challenging."
    )

else:

    print(
        "\nWEAK GENERALIZATION:"
        "\nThe model struggles against "
        "physically similar unseen garments."
    )

# ============================================================
# SAVE BENCHMARK
# ============================================================

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_generalization_benchmark.csv"
)

comparison.to_csv(
    OUTPUT_PATH
)

print("\n" + "=" * 65)
print("BENCHMARK COMPLETE")
print("=" * 65)

print(
    "Saved:",
    OUTPUT_PATH
)

=================================================================
ZYRA V2 — RIGOROUS GENERALIZATION BENCHMARK
=================================================================
Raw rows: 5980
Pairwise rows: 8970
People: 56
Saved model: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_pairwise_ranker.pt

Feature count: 27

=================================================================
PERSON SPLIT
=================================================================
Train: 40
Validation: 8
Test: 8

Original negative pair keys: 2869

Test positive interactions:
Alex : 37
Anna Maria : 18
Bree : 6
Chesska : 11
Emma : 87
Maddy : 77
Palatina : 49
Sophie : 54

=================================================================
FRESH NEGATIVE INTEGRITY
=================================================================
random     | rows= 339 | train-negative overlap=0 | positive collision=0
hard       | rows= 339 | train-negative overlap=0 | positive collision=0
mixed      | rows= 339 | train-negative overlap=0 | positive collision=0

Model loaded.

=================================================================
GLOBAL GENERALIZATION RESULTS
=================================================================

RANDOM
Pairs: 339
Pairwise Accuracy: 0.5752
ROC-AUC: 0.5741
PR-AUC: 0.5455
Mean positive score: 0.1967
Mean negative score: 0.1715
Mean score gap: 0.0251
Median score gap: 0.0312

HARD
Pairs: 339
Pairwise Accuracy: 0.8466
ROC-AUC: 0.8363
PR-AUC: 0.7981
Mean positive score: 0.1967
Mean negative score: 0.0427
Mean score gap: 0.1540
Median score gap: 0.1717

MIXED
Pairs: 339
Pairwise Accuracy: 0.6903
ROC-AUC: 0.6885
PR-AUC: 0.6227
Mean positive score: 0.1967
Mean negative score: 0.1101
Mean score gap: 0.0866
Median score gap: 0.1017

=================================================================
PER-PERSON PERFORMANCE
=================================================================
           pairwise_accuracy                            roc_auc            \
                        mean       std       min  max      mean       std
evaluation
hard                0.884679  0.131346  0.611111  1.0  0.882145  0.116601
mixed               0.738494  0.151782  0.518519  1.0  0.745328  0.154020
random              0.604982  0.234579  0.181818  1.0  0.616575  0.222858


                 min  max
evaluation
hard        0.636831  1.0
mixed       0.534294  1.0
random      0.280992  1.0

=================================================================
COMPLETE vs INCOMPLETE MEASUREMENTS
=================================================================

RANDOM | positive garment complete=False
Pairs: 155
Pairwise accuracy: 0.7161
ROC-AUC: 0.6852
PR-AUC: 0.6651

RANDOM | positive garment complete=True
Pairs: 184
Pairwise accuracy: 0.4565
ROC-AUC: 0.4849
PR-AUC: 0.4712

HARD | positive garment complete=False
Pairs: 155
Pairwise accuracy: 0.8387
ROC-AUC: 0.8752
PR-AUC: 0.8591

HARD | positive garment complete=True
Pairs: 184
Pairwise accuracy: 0.8533
ROC-AUC: 0.8052
PR-AUC: 0.7354

MIXED | positive garment complete=False
Pairs: 155
Pairwise accuracy: 0.7355
ROC-AUC: 0.7512
PR-AUC: 0.7034

MIXED | positive garment complete=True
Pairs: 184
Pairwise accuracy: 0.6522
ROC-AUC: 0.6446
PR-AUC: 0.5654

=================================================================
NEGATIVE DIFFICULTY
=================================================================

RANDOM
count    339.000000
mean       0.477694
std        0.180655
min        0.146401
25%        0.340909
50%        0.455900
75%        0.597116
max        1.050163
Name: negative_distance, dtype: float64

HARD
count    339.000000
mean       0.256821
std        0.071100
min        0.045052
25%        0.195286
50%        0.264975
75%        0.315966
max        0.384906
Name: negative_distance, dtype: float64

MIXED
count    339.000000
mean       0.367758
std        0.180133
min        0.045052
25%        0.236896
50%        0.327834
75%        0.456482
max        1.050163
Name: negative_distance, dtype: float64

=================================================================
FINAL BENCHMARK TABLE
=================================================================

        pairs  pairwise_accuracy   roc_auc    pr_auc  mean_score_gap
random  339.0           0.575221  0.574147  0.545533        0.025134
hard    339.0           0.846608  0.836274  0.798115        0.153959
mixed   339.0           0.690265  0.688473  0.622658        0.086575

=================================================================
REFERENCE
=================================================================
Original test ranking accuracy : 0.8417
Previous fresh-negative accuracy: 0.6254

=================================================================
INTERPRETATION
=================================================================
Random unseen : 0.5752
Hard unseen   : 0.8466
Mixed unseen  : 0.6903

STRONG GENERALIZATION:
The model remains effective against physically difficult unseen negatives.

=================================================================
BENCHMARK COMPLETE
=================================================================
Saved: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_generalization_benchmark.csv

In [62]:
# ============================================================
# ZYRA V2 — EXPERIMENT #2
# BALANCED HARD / SEMI-HARD / RANDOM NEGATIVE SAMPLING
# ============================================================
#
# Goal:
#   Fix the weakness observed in Experiment #1:
#
#       Random unseen  : ~57.5%
#       Hard unseen    : ~84.7%
#
# We now train with:
#
#   1/3 hard negatives
#   1/3 semi-hard negatives
#   1/3 random negatives
#
# IMPORTANT:
# - Uses only positive interactions from the cleaned dataset
# - Does NOT use labels from the old negative dataset
# - Does NOT create positive collisions
# - Does NOT create duplicate (person, negative garment) pairs
# - Keeps negatives diverse per person
# - Does NOT train the model yet
#
# ============================================================

import pandas as pd
import numpy as np

from pathlib import Path

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_balanced_negative_sampling.csv"
)

SEED = 2026

rng = np.random.default_rng(SEED)

# Number of negatives PER positive
# 3 types -> 3 negatives per positive
NEGATIVES_PER_POSITIVE = 3

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(
    RAW_PATH
)

print("=" * 65)
print("ZYRA V2 — EXPERIMENT #2 NEGATIVE SAMPLING")
print("=" * 65)

print(
    "Input rows:",
    len(df)
)

print(
    "People:",
    df["person_id"].nunique()
)

print(
    "Garments:",
    df["product_id"].nunique()
)

# ============================================================
# KEEP ONLY POSITIVE INTERACTIONS
# ============================================================

positive_df = df[
    df["label"] == 1
].copy()

# Remove accidental duplicates
positive_df = (
    positive_df
    .drop_duplicates(
        [
            "person_id",
            "product_id",
        ]
    )
)

print(
    "\nPositive interactions:",
    len(positive_df)
)

# ============================================================
# BUILD PERSON PROFILES
# ============================================================

person_cols = [
    "height",
    "bust",
    "waist",
    "hips",
]

person_lookup = (
    positive_df[
        [
            "person_id"
        ] + person_cols
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

# ============================================================
# BUILD GARMENT PROFILES
# ============================================================

garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

garment_lookup = (
    df[
        [
            "product_id"
        ] + garment_cols
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

all_products = list(
    garment_lookup.index
)

print(
    "Available garments:",
    len(all_products)
)

# ============================================================
# PHYSICAL DISTANCE
# ============================================================
#
# Smaller = physically closer to person's body dimensions.
#
# Used ONLY for negative selection.
#
# We deliberately do NOT use the model for negative selection.
# ============================================================

def physical_distance(
    person_id,
    product_id,
):

    person = person_lookup.loc[
        person_id
    ]

    garment = garment_lookup.loc[
        product_id
    ]

    values = []

    dimensions = [
        (
            person["bust"],
            garment["garment_bust"],
        ),
        (
            person["waist"],
            garment["garment_waist"],
        ),
        (
            person["hips"],
            garment["garment_hip"],
        ),
        (
            person["height"],
            garment["garment_length"],
        ),
    ]

    for person_value, garment_value in dimensions:

        if (
            pd.isna(person_value)
            or pd.isna(garment_value)
        ):
            continue

        if person_value == 0:
            continue

        values.append(
            abs(
                garment_value -
                person_value
            )
            / abs(person_value)
        )

    if not values:
        return np.nan

    return float(
        np.mean(values)
    )

# ============================================================
# PRECOMPUTE DISTANCES
# ============================================================

print(
    "\nComputing physical candidate distances..."
)

distance_cache = {}

for person_id in person_lookup.index:

    distance_cache[
        person_id
    ] = {}

    for product_id in all_products:

        try:

            distance = physical_distance(
                person_id,
                product_id,
            )

            if not np.isnan(distance):

                distance_cache[
                    person_id
                ][
                    product_id
                ] = distance

        except Exception:

            continue

print(
    "Distance computation complete."
)

# ============================================================
# BUILD POSITIVE PRODUCT SET
# ============================================================

positive_products_by_person = (
    positive_df
    .groupby("person_id")[
        "product_id"
    ]
    .apply(set)
    .to_dict()
)

# ============================================================
# NEGATIVE SAMPLING
# ============================================================
#
# For each positive interaction:
#
# HARD:
#   closest 10% of available negative garments
#
# SEMI-HARD:
#   30%-60% distance percentile
#
# RANDOM:
#   uniformly random from all available negatives
#
# We ensure that the SAME negative pair
# (person, garment) isn't repeated.
#
# ============================================================

output_rows = []

used_negative_pairs = set()

sampling_statistics = []

for person_id in sorted(
    positive_products_by_person
):

    positive_products = (
        positive_products_by_person[
            person_id
        ]
    )

    available = (
        distance_cache
        .get(
            person_id,
            {}
        )
    )

    # Remove positive garments
    candidates = [
        (
            product,
            distance,
        )
        for product, distance
        in available.items()
        if product
        not in positive_products
    ]

    if len(candidates) < 3:

        print(
            f"WARNING: {person_id} "
            f"has only {len(candidates)} "
            f"negative candidates."
        )

        continue

    # Sort by physical distance
    candidates = sorted(
        candidates,
        key=lambda x: x[1]
    )

    n = len(candidates)

    # --------------------------------------------------------
    # Percentile boundaries
    # --------------------------------------------------------

    hard_end = max(
        1,
        int(
            n * 0.10
        )
    )

    semi_start = max(
        hard_end,
        int(
            n * 0.30
        )
    )

    semi_end = max(
        semi_start + 1,
        int(
            n * 0.60
        )
    )

    hard_pool = candidates[
        :hard_end
    ]

    semi_pool = candidates[
        semi_start:semi_end
    ]

    random_pool = candidates

    # Safety
    if not semi_pool:
        semi_pool = candidates

    # --------------------------------------------------------
    # Sample one of each type for every positive
    # --------------------------------------------------------

    person_used = set()

    for positive_product in sorted(
        positive_products
    ):

        selected = []

        # ====================================================
        # HARD
        # ====================================================

        hard_candidates = [
            item
            for item in hard_pool
            if item[0]
            not in person_used
        ]

        if not hard_candidates:

            hard_candidates = [
                item
                for item in hard_pool
            ]

        hard_product, hard_distance = (
            hard_candidates[
                rng.integers(
                    len(
                        hard_candidates
                    )
                )
            ]
        )

        person_used.add(
            hard_product
        )

        selected.append(
            (
                hard_product,
                hard_distance,
                "hard",
            )
        )

        # ====================================================
        # SEMI-HARD
        # ====================================================

        semi_candidates = [
            item
            for item in semi_pool
            if item[0]
            not in person_used
        ]

        if not semi_candidates:

            semi_candidates = [
                item
                for item in semi_pool
            ]

        semi_product, semi_distance = (
            semi_candidates[
                rng.integers(
                    len(
                        semi_candidates
                    )
                )
            ]
        )

        person_used.add(
            semi_product
        )

        selected.append(
            (
                semi_product,
                semi_distance,
                "semi-hard",
            )
        )

        # ====================================================
        # RANDOM
        # ====================================================

        random_candidates = [
            item
            for item in random_pool
            if item[0]
            not in person_used
        ]

        if not random_candidates:

            random_candidates = [
                item
                for item in random_pool
            ]

        random_product, random_distance = (
            random_candidates[
                rng.integers(
                    len(
                        random_candidates
                    )
                )
            ]
        )

        person_used.add(
            random_product
        )

        selected.append(
            (
                random_product,
                random_distance,
                "random",
            )
        )

        # ====================================================
        # STORE
        # ====================================================

        for (
            negative_product,
            distance,
            negative_type,
        ) in selected:

            key = (
                person_id,
                negative_product,
            )

            # ------------------------------------------------
            # Global duplicate protection
            # ------------------------------------------------

            if key in used_negative_pairs:

                # Find an unused fallback
                fallback = [
                    item
                    for item
                    in random_pool
                    if (
                        person_id,
                        item[0],
                    )
                    not in used_negative_pairs
                    and item[0]
                    not in positive_products
                ]

                if fallback:

                    negative_product, distance = (
                        fallback[
                            rng.integers(
                                len(
                                    fallback
                                )
                            )
                        )

                    key = (
                        person_id,
                        negative_product,
                    )

                else:

                    continue

            used_negative_pairs.add(
                key
            )

            output_rows.append(
                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        negative_product,

                    "negative_type":
                        negative_type,

                    "negative_distance":
                        distance,

                    "label_positive":
                        1,

                    "label_negative":
                        0,
                }
            )

# ============================================================
# DATAFRAME
# ============================================================

ranking_df = pd.DataFrame(
    output_rows
)

# ============================================================
# BASIC INTEGRITY
# ============================================================

print("\n" + "=" * 65)
print("SAMPLING RESULTS")
print("=" * 65)

print(
    "Positive interactions:",
    len(positive_df)
)

print(
    "Pairwise ranking rows:",
    len(ranking_df)
)

print(
    "\nNegative type counts:"
)

print(
    ranking_df[
        "negative_type"
    ].value_counts()
)

# ============================================================
# EXPECTED COUNTS
# ============================================================

expected_per_type = len(
    positive_df
)

print(
    "\nExpected hard negatives:",
    expected_per_type
)

print(
    "Actual hard negatives:",
    (
        ranking_df[
            "negative_type"
        ]
        == "hard"
    ).sum()
)

print(
    "Expected semi-hard negatives:",
    expected_per_type
)

print(
    "Actual semi-hard negatives:",
    (
        ranking_df[
            "negative_type"
        ]
        == "semi-hard"
    ).sum()
)

print(
    "Expected random negatives:",
    expected_per_type
)

print(
    "Actual random negatives:",
    (
        ranking_df[
            "negative_type"
        ]
        == "random"
    ).sum()
)

# ============================================================
# DUPLICATE CHECK
# ============================================================

duplicate_pairs = (
    ranking_df[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
        ]
    ]
    .duplicated()
    .sum()
)

duplicate_negative_pairs = (
    ranking_df[
        [
            "person_id",
            "negative_product_id",
        ]
    ]
    .duplicated()
    .sum()
)

print(
    "\nDuplicate full pair rows:",
    duplicate_pairs
)

print(
    "Duplicate person-negative pairs:",
    duplicate_negative_pairs
)

# ============================================================
# POSITIVE COLLISION
# ============================================================

positive_keys = set(
    zip(
        positive_df[
            "person_id"
        ],
        positive_df[
            "product_id"
        ],
    )
)

negative_keys = set(
    zip(
        ranking_df[
            "person_id"
        ],
        ranking_df[
            "negative_product_id"
        ],
    )
)

collision_count = len(
    positive_keys
    &
    negative_keys
)

print(
    "Positive-negative collisions:",
    collision_count
)

# ============================================================
# NEGATIVE DISTANCE DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("NEGATIVE DISTANCE DISTRIBUTION")
print("=" * 65)

distance_summary = (
    ranking_df
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .describe()
)

print(
    distance_summary
)

# ============================================================
# TYPE ORDER CHECK
# ============================================================

print("\n" + "=" * 65)
print("EXPECTED DIFFICULTY ORDER")
print("=" * 65)

mean_distances = (
    ranking_df
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .mean()
    .sort_values()
)

print(
    mean_distances
)

hard_mean = (
    ranking_df.loc[
        ranking_df[
            "negative_type"
        ]
        == "hard",
        "negative_distance",
    ]
    .mean()
)

semi_mean = (
    ranking_df.loc[
        ranking_df[
            "negative_type"
        ]
        == "semi-hard",
        "negative_distance",
    ]
    .mean()
)

random_mean = (
    ranking_df.loc[
        ranking_df[
            "negative_type"
        ]
        == "random",
        "negative_distance",
    ]
    .mean()
)

print(
    "\nHard < Semi-hard < Random:",
    hard_mean < semi_mean < random_mean
)

# ============================================================
# PEOPLE BALANCE
# ============================================================

print("\n" + "=" * 65)
print("PER-PERSON NEGATIVE COUNTS")
print("=" * 65)

person_counts = (
    ranking_df
    .groupby(
        [
            "person_id",
            "negative_type",
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
)

print(
    person_counts
    .describe()
)

# ============================================================
# POSITIVE / NEGATIVE RATIO
# ============================================================

print("\n" + "=" * 65)
print("TRAINING RATIO")
print("=" * 65)

print(
    "Positive interactions:",
    len(positive_df)
)

print(
    "Negative interactions:",
    len(ranking_df)
)

print(
    "Positive : Negative ratio = "
    f"1 : {len(ranking_df) / len(positive_df):.2f}"
)

# ============================================================
# EXAMPLE PAIRS
# ============================================================

print("\n" + "=" * 65)
print("EXAMPLE PAIRS")
print("=" * 65)

display(
    ranking_df[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "negative_type",
            "negative_distance",
        ]
    ]
    .head(20)
)

# ============================================================
# SAVE
# ============================================================

ranking_df.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 65)
print("EXPERIMENT #2 DATASET SAVED")
print("=" * 65)

print(
    OUTPUT_PATH
)

# ============================================================
# FINAL VALIDATION
# ============================================================

print("\n" + "=" * 65)
print("FINAL VALIDATION")
print("=" * 65)

checks = {
    "No duplicate full pairs":
        duplicate_pairs == 0,

    "No duplicate person-negative pairs":
        duplicate_negative_pairs == 0,

    "No positive-negative collisions":
        collision_count == 0,

    "Hard < Semi-hard < Random":
        hard_mean < semi_mean < random_mean,

    "All three negative types exist":
        set(
            ranking_df[
                "negative_type"
            ]
        )
        == {
            "hard",
            "semi-hard",
            "random",
        },
}

for name, passed in checks.items():

    print(
        f"{name}:",
        "PASS" if passed else "FAIL"
    )

all_passed = all(
    checks.values()
)

print(
    "\nOVERALL:",
    "PASS" if all_passed else "FAIL"
)

print("\nExperiment #2 sampling complete.")

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' on line 578 (649365559.py, line 584)

In [63]:
# ============================================================
# ZYRA V2 — EXPERIMENT #2
# BALANCED HARD / SEMI-HARD / RANDOM NEGATIVE SAMPLING
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_balanced_negative_sampling.csv"
)

SEED = 2026
rng = np.random.default_rng(SEED)

# ============================================================
# LOAD DATA
# ============================================================

df = pd.read_csv(RAW_PATH)

print("=" * 65)
print("ZYRA V2 — EXPERIMENT #2 NEGATIVE SAMPLING")
print("=" * 65)

print("Input rows :", len(df))
print("People     :", df["person_id"].nunique())
print("Garments   :", df["product_id"].nunique())

# ============================================================
# POSITIVE INTERACTIONS
# ============================================================

positive_df = (
    df[df["label"] == 1]
    .drop_duplicates(
        ["person_id", "product_id"]
    )
    .copy()
)

print(
    "\nPositive interactions:",
    len(positive_df)
)

# ============================================================
# PERSON LOOKUP
# ============================================================

person_cols = [
    "height",
    "bust",
    "waist",
    "hips",
]

person_lookup = (
    positive_df[
        ["person_id"] + person_cols
    ]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

# ============================================================
# GARMENT LOOKUP
# ============================================================

garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

garment_lookup = (
    df[
        ["product_id"] + garment_cols
    ]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

all_products = list(
    garment_lookup.index
)

print(
    "Available garments:",
    len(all_products)
)

# ============================================================
# PHYSICAL DISTANCE
# ============================================================

def physical_distance(
    person_id,
    product_id,
):

    person = person_lookup.loc[
        person_id
    ]

    garment = garment_lookup.loc[
        product_id
    ]

    values = []

    dimensions = [
        (
            person["bust"],
            garment["garment_bust"],
        ),
        (
            person["waist"],
            garment["garment_waist"],
        ),
        (
            person["hips"],
            garment["garment_hip"],
        ),
        (
            person["height"],
            garment["garment_length"],
        ),
    ]

    for pv, gv in dimensions:

        if pd.isna(pv) or pd.isna(gv):
            continue

        if pv == 0:
            continue

        values.append(
            abs(gv - pv) / abs(pv)
        )

    if not values:
        return np.nan

    return float(
        np.mean(values)
    )

# ============================================================
# PRECOMPUTE DISTANCES
# ============================================================

print(
    "\nComputing physical distances..."
)

distance_cache = {}

for person_id in person_lookup.index:

    distance_cache[person_id] = {}

    for product_id in all_products:

        try:

            distance = physical_distance(
                person_id,
                product_id,
            )

            if not np.isnan(distance):

                distance_cache[
                    person_id
                ][
                    product_id
                ] = distance

        except Exception:
            continue

print(
    "Distance computation complete."
)

# ============================================================
# POSITIVE PRODUCTS BY PERSON
# ============================================================

positive_products_by_person = (
    positive_df
    .groupby("person_id")["product_id"]
    .apply(set)
    .to_dict()
)

# ============================================================
# SAMPLE NEGATIVES
# ============================================================

output_rows = []

used_negative_pairs = set()

for person_id in sorted(
    positive_products_by_person
):

    positive_products = (
        positive_products_by_person[
            person_id
        ]
    )

    available = (
        distance_cache.get(
            person_id,
            {}
        )
    )

    # Remove positive garments
    candidates = [
        (
            product,
            distance
        )
        for product, distance
        in available.items()
        if product not in positive_products
    ]

    if len(candidates) < 3:

        print(
            "WARNING:",
            person_id,
            "has only",
            len(candidates),
            "negative candidates."
        )

        continue

    # --------------------------------------------------------
    # Sort by physical distance
    # --------------------------------------------------------

    candidates = sorted(
        candidates,
        key=lambda x: x[1]
    )

    n = len(candidates)

    # --------------------------------------------------------
    # Define pools
    # --------------------------------------------------------
    #
    # HARD:
    # closest 10%
    #
    # SEMI-HARD:
    # 30th–60th percentile
    #
    # RANDOM:
    # entire candidate pool
    #

    hard_end = max(
        1,
        int(n * 0.10)
    )

    semi_start = max(
        hard_end,
        int(n * 0.30)
    )

    semi_end = max(
        semi_start + 1,
        int(n * 0.60)
    )

    hard_pool = candidates[
        :hard_end
    ]

    semi_pool = candidates[
        semi_start:semi_end
    ]

    random_pool = candidates

    if not semi_pool:
        semi_pool = candidates

    # --------------------------------------------------------
    # One hard + one semi-hard + one random
    # for every positive interaction
    # --------------------------------------------------------

    for positive_product in sorted(
        positive_products
    ):

        # ================================================
        # HARD
        # ================================================

        hard_available = [
            item
            for item in hard_pool
            if (
                person_id,
                item[0],
            )
            not in used_negative_pairs
        ]

        if not hard_available:
            hard_available = hard_pool

        hard_product, hard_distance = (
            hard_available[
                rng.integers(
                    len(hard_available)
                )
            ]
        )

        hard_key = (
            person_id,
            hard_product,
        )

        # ================================================
        # SEMI-HARD
        # ================================================

        semi_available = [
            item
            for item in semi_pool
            if (
                person_id,
                item[0],
            )
            not in used_negative_pairs
            and item[0] != hard_product
        ]

        if not semi_available:
            semi_available = [
                item
                for item in semi_pool
                if item[0] != hard_product
            ]

        semi_product, semi_distance = (
            semi_available[
                rng.integers(
                    len(semi_available)
                )
            ]
        )

        semi_key = (
            person_id,
            semi_product,
        )

        # ================================================
        # RANDOM
        # ================================================

        random_available = [
            item
            for item in random_pool
            if (
                person_id,
                item[0],
            )
            not in used_negative_pairs
            and item[0] != hard_product
            and item[0] != semi_product
        ]

        if not random_available:

            random_available = [
                item
                for item in random_pool
                if item[0] != hard_product
                and item[0] != semi_product
            ]

        random_product, random_distance = (
            random_available[
                rng.integers(
                    len(random_available)
                )
            ]
        )

        random_key = (
            person_id,
            random_product,
        )

        # ================================================
        # STORE HARD
        # ================================================

        if hard_key not in used_negative_pairs:

            used_negative_pairs.add(
                hard_key
            )

            output_rows.append(
                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        hard_product,

                    "negative_type":
                        "hard",

                    "negative_distance":
                        hard_distance,

                    "label_positive":
                        1,

                    "label_negative":
                        0,
                }
            )

        # ================================================
        # STORE SEMI-HARD
        # ================================================

        if semi_key not in used_negative_pairs:

            used_negative_pairs.add(
                semi_key
            )

            output_rows.append(
                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        semi_product,

                    "negative_type":
                        "semi-hard",

                    "negative_distance":
                        semi_distance,

                    "label_positive":
                        1,

                    "label_negative":
                        0,
                }
            )

        # ================================================
        # STORE RANDOM
        # ================================================

        if random_key not in used_negative_pairs:

            used_negative_pairs.add(
                random_key
            )

            output_rows.append(
                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        random_product,

                    "negative_type":
                        "random",

                    "negative_distance":
                        random_distance,

                    "label_positive":
                        1,

                    "label_negative":
                        0,
                }
            )

# ============================================================
# DATAFRAME
# ============================================================

ranking_df = pd.DataFrame(
    output_rows
)

# ============================================================
# BASIC RESULTS
# ============================================================

print("\n" + "=" * 65)
print("SAMPLING RESULTS")
print("=" * 65)

print(
    "Positive interactions :",
    len(positive_df)
)

print(
    "Ranking samples       :",
    len(ranking_df)
)

print(
    "\nNegative type counts:"
)

print(
    ranking_df[
        "negative_type"
    ].value_counts()
)

# ============================================================
# EXPECTED COUNTS
# ============================================================

expected = len(
    positive_df
)

hard_actual = (
    ranking_df[
        "negative_type"
    ]
    .eq("hard")
    .sum()
)

semi_actual = (
    ranking_df[
        "negative_type"
    ]
    .eq("semi-hard")
    .sum()
)

random_actual = (
    ranking_df[
        "negative_type"
    ]
    .eq("random")
    .sum()
)

print(
    "\nExpected hard negatives      :",
    expected
)

print(
    "Actual hard negatives        :",
    hard_actual
)

print(
    "Expected semi-hard negatives :",
    expected
)

print(
    "Actual semi-hard negatives   :",
    semi_actual
)

print(
    "Expected random negatives    :",
    expected
)

print(
    "Actual random negatives      :",
    random_actual
)

# ============================================================
# DUPLICATES
# ============================================================

duplicate_full = (
    ranking_df[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
        ]
    ]
    .duplicated()
    .sum()
)

duplicate_negative = (
    ranking_df[
        [
            "person_id",
            "negative_product_id",
        ]
    ]
    .duplicated()
    .sum()
)

print(
    "\nDuplicate full rows:",
    duplicate_full
)

print(
    "Duplicate person-negative pairs:",
    duplicate_negative
)

# ============================================================
# POSITIVE COLLISIONS
# ============================================================

positive_keys = set(
    zip(
        positive_df[
            "person_id"
        ],
        positive_df[
            "product_id"
        ],
    )
)

negative_keys = set(
    zip(
        ranking_df[
            "person_id"
        ],
        ranking_df[
            "negative_product_id"
        ],
    )
)

collisions = (
    positive_keys
    &
    negative_keys
)

print(
    "Positive-negative collisions:",
    len(collisions)
)

# ============================================================
# DISTANCE STATISTICS
# ============================================================

print("\n" + "=" * 65)
print("NEGATIVE DISTANCE DISTRIBUTION")
print("=" * 65)

distance_summary = (
    ranking_df
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .describe()
)

print(
    distance_summary
)

# ============================================================
# MEAN DISTANCE
# ============================================================

print("\n" + "=" * 65)
print("MEAN NEGATIVE DISTANCE")
print("=" * 65)

mean_distances = (
    ranking_df
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .mean()
)

print(
    mean_distances
)

hard_mean = mean_distances.get(
    "hard",
    np.nan
)

semi_mean = mean_distances.get(
    "semi-hard",
    np.nan
)

random_mean = mean_distances.get(
    "random",
    np.nan
)

difficulty_order = (
    hard_mean
    < semi_mean
    < random_mean
)

print(
    "\nHard < Semi-hard < Random:",
    difficulty_order
)

# ============================================================
# PERSON DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("PER-PERSON SAMPLE COUNTS")
print("=" * 65)

person_counts = (
    ranking_df
    .groupby(
        [
            "person_id",
            "negative_type",
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
)

print(
    person_counts
)

# ============================================================
# EXAMPLES
# ============================================================

print("\n" + "=" * 65)
print("EXAMPLE PAIRS")
print("=" * 65)

display(
    ranking_df[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "negative_type",
            "negative_distance",
        ]
    ]
    .head(20)
)

# ============================================================
# SAVE
# ============================================================

ranking_df.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 65)
print("SAVED")
print("=" * 65)

print(
    OUTPUT_PATH
)

# ============================================================
# FINAL VALIDATION
# ============================================================

print("\n" + "=" * 65)
print("FINAL VALIDATION")
print("=" * 65)

checks = {
    "No duplicate full rows":
        duplicate_full == 0,

    "No duplicate person-negative pairs":
        duplicate_negative == 0,

    "No positive-negative collisions":
        len(collisions) == 0,

    "Hard < Semi-hard < Random":
        difficulty_order,

    "Hard negatives exist":
        hard_actual > 0,

    "Semi-hard negatives exist":
        semi_actual > 0,

    "Random negatives exist":
        random_actual > 0,
}

for name, passed in checks.items():

    print(
        f"{name}:",
        "PASS" if passed else "FAIL"
    )

all_passed = all(
    checks.values()
)

print(
    "\nOVERALL:",
    "PASS" if all_passed else "FAIL"
)

print(
    "\nExperiment #2 sampling complete."
)

=================================================================
ZYRA V2 — EXPERIMENT #2 NEGATIVE SAMPLING
=================================================================
Input rows : 5980
People     : 56
Garments   : 897

Positive interactions: 2990
Available garments: 897

Computing physical distances...
Distance computation complete.

=================================================================
SAMPLING RESULTS
=================================================================
Positive interactions : 2990
Ranking samples       : 7938

Negative type counts:
negative_type
random       2990
semi-hard    2816
hard         2132
Name: count, dtype: int64

Expected hard negatives      : 2990
Actual hard negatives        : 2132
Expected semi-hard negatives : 2990
Actual semi-hard negatives   : 2816
Expected random negatives    : 2990
Actual random negatives      : 2990

Duplicate full rows: 0
Duplicate person-negative pairs: 0
Positive-negative collisions: 0

=================================================================
NEGATIVE DISTANCE DISTRIBUTION
=================================================================
                count      mean       std       min       25%       50%  \
negative_type
hard           2132.0  0.261517  0.065941  0.020032  0.210736  0.259977
random         2990.0  0.466532  0.171279  0.117134  0.335698  0.449268
semi-hard      2816.0  0.424923  0.108627  0.229411  0.324584  0.441152

                    75%       max
negative_type
hard           0.318772  0.418320
random         0.577930  1.312500
semi-hard      0.522087  0.692677

=================================================================
MEAN NEGATIVE DISTANCE
=================================================================
negative_type
hard         0.261517
random       0.466532
semi-hard    0.424923
Name: negative_distance, dtype: float64

Hard < Semi-hard < Random: True

=================================================================
PER-PERSON SAMPLE COUNTS
=================================================================
negative_type  hard  random  semi-hard
person_id
Alex             37      37         37
Amanda           76     108        108
Anna             75      87         87
Anna Maria       18      18         18
Anneliese         3       3          3
Bree              6       6          6
Charlotte        13      13         13
Chelsea          75      88         88
Chesska          11      11         11
Clementine       62      62         62
Denniel          26      26         26
Edith             3       3          3
Emma             78      87         87
Fiona            66     184        182
Gemma            78      84         84
Georgia          73     131        131
Grazi             1       1          1
Helen             8       8          8
Jess             61     251        156
Jira              1       1          1
Jude             14      14         14
Kate             52      52         52
Katie            24      24         24
Lara              3       3          3
Laura            61     244        167
Lauren           30      30         30
Lisa              8       8          8
Ljubenka         75     109        109
Louise            5       5          5
Lucy              4       4          4
Maddy            76      77         77
Madeline         37      37         37
Mae-Lee          70     159        159
Mandy             9       9          9
Marnee           71     141        141
Mercy            24      24         24
Miranda          27      27         27
Monique          29      29         29
Nadine           42      42         42
Natalia          46      46         46
Natalie          51      51         51
Nathalie         14      14         14
Nikki             9       9          9
Olivia           23      23         23
Palatina         49      49         49
Perrie           37      37         37
Riina            78     104        104
Rosaline          4       4          4
Shadae           35      35         35
Sophia           59      59         59
Sophie           54      54         54
Stacey           56      56         56
Stefania         33      33         33
Summer           78      95         95
Thais             3       3          3
Tia              71      71         71

=================================================================
EXAMPLE PAIRS
=================================================================

,person_id,positive_product_id,negative_product_id,negative_type,negative_distance
0,Alex,jade-kimono-kaleidoscope#Blue,the-boat-neck-top#Black,hard,0.357633
1,Alex,jade-kimono-kaleidoscope#Blue,luxe-shirt#Navy,semi-hard,0.503275
2,Alex,jade-kimono-kaleidoscope#Blue,natural-classic-cardigan#Pebble,random,0.312493
3,Alex,jade-kimono-sweet-blossoms#Blue,manhattan-stretch-tee#Black,hard,0.341822
4,Alex,jade-kimono-sweet-blossoms#Blue,always-mine-spliced-cardigan#GreyEmeral,semi-hard,0.527133
5,Alex,jade-kimono-sweet-blossoms#Blue,the-contrast-trim-knit#BlackWhite,random,0.550766
6,Alex,lola-bell-sleeve-top-ditsy-daisies#Blue,pure-merino-fine-rib-polo#BlackStri,hard,0.251497
7,Alex,lola-bell-sleeve-top-ditsy-daisies#Blue,natural-waterfall-cardigan#Fallendust,semi-hard,0.528736
8,Alex,lola-bell-sleeve-top-ditsy-daisies#Blue,long-sleeve-softly-swinging-bamboo-tee#Storm,random,0.629682
9,Alex,lola-bell-sleeve-top-entangled-vines#Gold,mila-knit-cardigan#Clay,hard,0.330992
10,Alex,lola-bell-sleeve-top-entangled-vines#Gold,natural-overlay-knit#Greybloss,semi-hard,0.590406
11,Alex,lola-bell-sleeve-top-entangled-vines#Gold,fundamental-split-hoodie-1#Khaki,random,0.691917
12,Alex,the-batwing-tee#Black,eco-78-long-cardigan#DarkGreyM,hard,0.345893
13,Alex,the-batwing-tee#Black,natural-cosy-sweater#Rosered,semi-hard,0.595892
14,Alex,the-batwing-tee#Black,relaxed-top-1#FloraStrip,random,0.654427
15,Alex,the-batwing-tee#FrenchBlue,the-reversible-cowl-neck-top-2#Ocean,hard,0.275752
16,Alex,the-batwing-tee#FrenchBlue,wellington-tee#HeatheGrey,semi-hard,0.590719
17,Alex,the-batwing-tee#FrenchBlue,the-daily-cross-over-top#PinkPrint,random,0.632184
18,Alex,the-batwing-tee#Sea,holly-rib-long-sleeve-tee#Khaki,hard,0.260726
19,Alex,the-batwing-tee#Sea,panelled-stripe-top#NavyWhite,semi-hard,0.516232

=================================================================
SAVED
=================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_balanced_negative_sampling.csv

=================================================================
FINAL VALIDATION
=================================================================
No duplicate full rows: PASS
No duplicate person-negative pairs: PASS
No positive-negative collisions: PASS
Hard < Semi-hard < Random: PASS
Hard negatives exist: PASS
Semi-hard negatives exist: PASS
Random negatives exist: PASS

OVERALL: PASS

Experiment #2 sampling complete.

In [64]:
# ============================================================
# ZYRA V2 — EXPERIMENT #2 TRAINING
# ============================================================
#
# Dataset:
#   v2_balanced_negative_sampling.csv
#
# Negative mix:
#   hard + semi-hard + random
#
# Model:
#   Same architecture as Experiment #1
#
# IMPORTANT:
#   Person-level split.
#   No model architecture changes.
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

DATA_PATH = (
    BASE /
    "data/v2/v2_balanced_negative_sampling.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

MODEL_OUTPUT = (
    BASE /
    "data/v2/v2_pairwise_ranker_exp2.pt"
)

SEED = 42

np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================
# DEVICE
# ============================================================

if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("=" * 65)
print("ZYRA V2 — EXPERIMENT #2 TRAINING")
print("=" * 65)

print("Device:", device)

# ============================================================
# LOAD DATA
# ============================================================

pairwise = pd.read_csv(
    DATA_PATH
)

raw = pd.read_csv(
    RAW_PATH
)

print(
    "\nPairwise rows:",
    len(pairwise)
)

print(
    "People:",
    pairwise["person_id"].nunique()
)

print(
    "\nNegative types:"
)

print(
    pairwise[
        "negative_type"
    ].value_counts()
)

# ============================================================
# FEATURE ENGINEERING
# ============================================================

def add_features(df):

    df = df.copy()

    df["bust_ease"] = (
        df["garment_bust"]
        - df["bust"]
    )

    df["waist_ease"] = (
        df["garment_waist"]
        - df["waist"]
    )

    df["hip_ease"] = (
        df["garment_hip"]
        - df["hips"]
    )

    df["bust_ratio"] = (
        df["garment_bust"]
        / df["bust"]
    )

    df["waist_ratio"] = (
        df["garment_waist"]
        / df["waist"]
    )

    df["hip_ratio"] = (
        df["garment_hip"]
        / df["hips"]
    )

    df["bust_mismatch"] = abs(
        df["garment_bust"]
        - df["bust"]
    )

    df["waist_mismatch"] = abs(
        df["garment_waist"]
        - df["waist"]
    )

    df["hip_mismatch"] = abs(
        df["garment_hip"]
        - df["hips"]
    )

    df["bust_relative_mismatch"] = (
        df["bust_mismatch"]
        / df["bust"]
    )

    df["waist_relative_mismatch"] = (
        df["waist_mismatch"]
        / df["waist"]
    )

    df["hip_relative_mismatch"] = (
        df["hip_mismatch"]
        / df["hips"]
    )

    ease_cols = [
        "bust_ease",
        "waist_ease",
        "hip_ease",
    ]

    df["mean_ease"] = (
        df[ease_cols]
        .mean(axis=1)
    )

    df["ease_std"] = (
        df[ease_cols]
        .std(axis=1)
    )

    df["known_fit_dimensions"] = (
        df[ease_cols]
        .notna()
        .sum(axis=1)
    )

    df["tight_dimension_count"] = (
        df[ease_cols]
        .lt(0)
        .sum(axis=1)
    )

    df["extreme_ease_count"] = (
        df[ease_cols]
        .gt(50)
        .sum(axis=1)
    )

    df["length_height_ratio"] = (
        df["garment_length"]
        / df["height"]
    )

    return df


raw = add_features(raw)

# ============================================================
# FEATURE LIST
# ============================================================

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

print(
    "\nFeature dimension:",
    len(FEATURES)
)

# ============================================================
# LOOKUPS
# ============================================================

person_cols = [
    "height",
    "bust",
    "waist",
    "hips",
]

garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

person_lookup = (
    raw[
        ["person_id"] + person_cols
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

garment_lookup = (
    raw[
        ["product_id"] + garment_cols
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

# ============================================================
# FEATURE VECTOR
# ============================================================

def make_features(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    row = {}

    # Body
    for f in person_cols:
        row[f] = p[f]

    # Garment
    for f in garment_cols:
        row[f] = g[f]

    # Ease
    row["bust_ease"] = (
        g["garment_bust"]
        - p["bust"]
    )

    row["waist_ease"] = (
        g["garment_waist"]
        - p["waist"]
    )

    row["hip_ease"] = (
        g["garment_hip"]
        - p["hips"]
    )

    # Ratios
    row["bust_ratio"] = (
        g["garment_bust"]
        / p["bust"]
    )

    row["waist_ratio"] = (
        g["garment_waist"]
        / p["waist"]
    )

    row["hip_ratio"] = (
        g["garment_hip"]
        / p["hips"]
    )

    # Mismatch
    row["bust_mismatch"] = abs(
        g["garment_bust"]
        - p["bust"]
    )

    row["waist_mismatch"] = abs(
        g["garment_waist"]
        - p["waist"]
    )

    row["hip_mismatch"] = abs(
        g["garment_hip"]
        - p["hips"]
    )

    # Relative mismatch
    row["bust_relative_mismatch"] = (
        row["bust_mismatch"]
        / p["bust"]
    )

    row["waist_relative_mismatch"] = (
        row["waist_mismatch"]
        / p["waist"]
    )

    row["hip_relative_mismatch"] = (
        row["hip_mismatch"]
        / p["hips"]
    )

    # Aggregate ease
    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    if np.all(
        np.isnan(eases)
    ):

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    else:

        row["mean_ease"] = (
            np.nanmean(eases)
        )

        row["ease_std"] = (
            np.nanstd(eases)
        )

    row["known_fit_dimensions"] = (
        np.sum(
            ~np.isnan(eases)
        )
    )

    row["tight_dimension_count"] = (
        np.sum(
            eases < 0
        )
    )

    row["extreme_ease_count"] = (
        np.sum(
            eases > 50
        )
    )

    row["length_height_ratio"] = (
        g["garment_length"]
        / p["height"]
    )

    return np.array(
        [
            row[f]
            for f in FEATURES
        ],
        dtype=np.float32,
    )

# ============================================================
# PERSON-LEVEL SPLIT
# ============================================================

people = sorted(
    pairwise["person_id"]
    .unique()
)

train_people, temp_people = (
    train_test_split(
        people,
        test_size=16,
        random_state=SEED,
    )
)

val_people, test_people = (
    train_test_split(
        temp_people,
        test_size=8,
        random_state=SEED,
    )
)

train_people = set(
    train_people
)

val_people = set(
    val_people
)

test_people = set(
    test_people
)

print("\n" + "=" * 65)
print("PERSON-LEVEL SPLIT")
print("=" * 65)

print(
    "Train people:",
    len(train_people)
)

print(
    "Val people:",
    len(val_people)
)

print(
    "Test people:",
    len(test_people)
)

# ============================================================
# BUILD PAIRWISE FEATURES
# ============================================================

def build_pairwise_features(
    frame
):

    X = []
    y = []

    for _, row in frame.iterrows():

        positive = make_features(
            row["person_id"],
            row["positive_product_id"],
        )

        negative = make_features(
            row["person_id"],
            row["negative_product_id"],
        )

        # Difference representation
        #
        # positive
        # negative
        # positive - negative
        #
        # 27 + 27 + 27 = 81 normally.
        #
        # BUT Experiment #1's actual ranker
        # used 47 dimensions.
        #
        # Therefore we use:
        #
        # positive features
        # negative features
        # first  - 20 dimensions difference
        #
        # 27 + 20 = 47
        #
        # This preserves the original architecture.
        # ----------------------------------------------------

        difference = (
            positive[:20]
            - negative[:20]
        )

        features = np.concatenate(
            [
                positive,
                difference,
            ]
        )

        X.append(
            features
        )

        y.append(
            1.0
        )

    return (
        np.asarray(
            X,
            dtype=np.float32,
        ),
        np.asarray(
            y,
            dtype=np.float32,
        ),
    )

# ============================================================
# SPLIT DATA
# ============================================================

train_df = pairwise[
    pairwise["person_id"]
    .isin(train_people)
].copy()

val_df = pairwise[
    pairwise["person_id"]
    .isin(val_people)
].copy()

test_df = pairwise[
    pairwise["person_id"]
    .isin(test_people)
].copy()

print("\nPairwise rows:")
print(
    "Train:",
    len(train_df)
)

print(
    "Val  :",
    len(val_df)
)

print(
    "Test :",
    len(test_df)
)

# ============================================================
# BUILD PAIRWISE TENSORS
# ============================================================
#
# For pairwise learning we create:
#
# X = positive_features - negative_features
#
# This gives 27 dimensions.
#
# However the original Experiment #1 model
# was trained using the 47-dimensional representation.
#
# We therefore construct:
#
#   positive 27
#   difference first 20
#
# = 47
# ============================================================

def build_X(
    frame
):

    X = []

    for _, row in frame.iterrows():

        pos = make_features(
            row["person_id"],
            row["positive_product_id"],
        )

        neg = make_features(
            row["person_id"],
            row["negative_product_id"],
        )

        diff = (
            pos[:20]
            - neg[:20]
        )

        combined = np.concatenate(
            [
                pos,
                diff,
            ]
        )

        X.append(
            combined
        )

    return np.asarray(
        X,
        dtype=np.float32,
    )

X_train = build_X(
    train_df
)

X_val = build_X(
    val_df
)

X_test = build_X(
    test_df
)

# ============================================================
# IMPUTATION
# ============================================================

imputer = SimpleImputer(
    strategy="median",
    add_indicator=False,
)

X_train = imputer.fit_transform(
    X_train
)

X_val = imputer.transform(
    X_val
)

X_test = imputer.transform(
    X_test
)

# ============================================================
# SCALING
# ============================================================

scaler = StandardScaler()

X_train = scaler.fit_transform(
    X_train
)

X_val = scaler.transform(
    X_val
)

X_test = scaler.transform(
    X_test
)

# ============================================================
# SANITY
# ============================================================

print("\n" + "=" * 65)
print("PAIRWISE TENSORS")
print("=" * 65)

print(
    "Train:",
    X_train.shape
)

print(
    "Val:",
    X_val.shape
)

print(
    "Test:",
    X_test.shape
)

print(
    "NaN:",
    np.isnan(X_train).sum()
    + np.isnan(X_val).sum()
    + np.isnan(X_test).sum()
)

print(
    "Inf:",
    np.isinf(X_train).sum()
    + np.isinf(X_val).sum()
    + np.isinf(X_test).sum()
)

# ============================================================
# TORCH
# ============================================================

X_train_t = torch.tensor(
    X_train,
    dtype=torch.float32,
    device=device,
)

X_val_t = torch.tensor(
    X_val,
    dtype=torch.float32,
    device=device,
)

X_test_t = torch.tensor(
    X_test,
    dtype=torch.float32,
    device=device,
)

# ============================================================
# MODEL
# ============================================================

class PairwiseRanker(
    nn.Module
):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)

# ============================================================
# CREATE MODEL
# ============================================================

input_dim = X_train.shape[1]

model = PairwiseRanker(
    input_dim
).to(device)

print("\n" + "=" * 65)
print("MODEL")
print("=" * 65)

print(
    "Input dimension:",
    input_dim
)

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)

# ============================================================
# PAIRWISE LOSS
# ============================================================
#
# Since each X represents:
#
# positive - negative
#
# the model should output a positive value.
#
# We use softplus(-score).
# ============================================================

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4,
)

def ranking_loss(scores):

    return torch.nn.functional.softplus(
        -scores
    ).mean()

# ============================================================
# TRAINING
# ============================================================

EPOCHS = 50

print("\n" + "=" * 65)
print("TRAINING")
print("=" * 65)

best_val_acc = -np.inf
best_state = None

for epoch in range(
    1,
    EPOCHS + 1
):

    model.train()

    optimizer.zero_grad()

    train_scores = model(
        X_train_t
    )

    loss = ranking_loss(
        train_scores
    )

    loss.backward()

    optimizer.step()

    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------

    model.eval()

    with torch.no_grad():

        val_scores = model(
            X_val_t
        )

        train_acc = (
            train_scores > 0
        ).float().mean().item()

        val_acc = (
            val_scores > 0
        ).float().mean().item()

    if val_acc > best_val_acc:

        best_val_acc = val_acc

        best_state = {
            k: v.detach()
            .cpu()
            .clone()
            for k, v
            in model.state_dict().items()
        }

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d}/{EPOCHS} "
            f"| Loss: {loss.item():.4f} "
            f"| Train Rank Acc: {train_acc:.4f} "
            f"| Val Rank Acc: {val_acc:.4f}"
        )

# ============================================================
# RESTORE BEST MODEL
# ============================================================

model.load_state_dict(
    best_state
)

model.eval()

# ============================================================
# FINAL RESULTS
# ============================================================

with torch.no_grad():

    train_scores = model(
        X_train_t
    )

    val_scores = model(
        X_val_t
    )

    test_scores = model(
        X_test_t
    )

train_accuracy = (
    train_scores > 0
).float().mean().item()

val_accuracy = (
    val_scores > 0
).float().mean().item()

test_accuracy = (
    test_scores > 0
).float().mean().item()

# ============================================================
# RESULTS
# ============================================================

print("\n" + "=" * 65)
print("FINAL EXPERIMENT #2 RESULTS")
print("=" * 65)

print(
    "Train Ranking Accuracy :",
    f"{train_accuracy:.4f}"
)

print(
    "Validation Ranking Acc :",
    f"{val_accuracy:.4f}"
)

print(
    "Test Ranking Accuracy  :",
    f"{test_accuracy:.4f}"
)

print(
    "Best Validation Acc    :",
    f"{best_val_acc:.4f}"
)

# ============================================================
# SCORE STATISTICS
# ============================================================

print("\n" + "=" * 65)
print("SCORE STATISTICS")
print("=" * 65)

print(
    "Train score mean:",
    train_scores.mean().item()
)

print(
    "Val score mean:",
    val_scores.mean().item()
)

print(
    "Test score mean:",
    test_scores.mean().item()
)

# ============================================================
# SAVE MODEL
# ============================================================

torch.save(
    {
        "model_state_dict":
            model.state_dict(),

        "input_dim":
            input_dim,

        "feature_names":
            FEATURES,

        "experiment":
            "V2_EXP2_BALANCED_NEGATIVES",

        "negative_types":
            [
                "hard",
                "semi-hard",
                "random",
            ],

        "seed":
            SEED,

        "train_people":
            sorted(
                train_people
            ),

        "val_people":
            sorted(
                val_people
            ),

        "test_people":
            sorted(
                test_people
            ),
    },
    MODEL_OUTPUT,
)

print("\n" + "=" * 65)
print("MODEL SAVED")
print("=" * 65)

print(
    MODEL_OUTPUT
)

# ============================================================
# COMPARISON WITH EXPERIMENT #1
# ============================================================

print("\n" + "=" * 65)
print("EXPERIMENT COMPARISON")
print("=" * 65)

print(
    "Experiment #1 test accuracy : 0.8417"
)

print(
    "Experiment #2 test accuracy :",
    f"{test_accuracy:.4f}"
)

print(
    "Difference:",
    f"{test_accuracy - 0.8417:+.4f}"
)

print("\nTraining complete.")

=================================================================
ZYRA V2 — EXPERIMENT #2 TRAINING
=================================================================
Device: mps

Pairwise rows: 7938
People: 56

Negative types:
negative_type
random       2990
semi-hard    2816
hard         2132
Name: count, dtype: int64

Feature dimension: 27

=================================================================
PERSON-LEVEL SPLIT
=================================================================
Train people: 40
Val people: 8
Test people: 8

Pairwise rows:
Train: 5978
Val  : 953
Test : 1007

=================================================================
PAIRWISE TENSORS
=================================================================
Train: (5978, 47)
Val: (953, 47)
Test: (1007, 47)
NaN: 0
Inf: 0

=================================================================
MODEL
=================================================================
Input dimension: 47
Parameters: 5185

=================================================================
TRAINING
=================================================================
Epoch 01/50 | Loss: 0.6832 | Train Rank Acc: 0.6634 | Val Rank Acc: 0.9601
Epoch 05/50 | Loss: 0.6046 | Train Rank Acc: 0.9988 | Val Rank Acc: 1.0000
Epoch 10/50 | Loss: 0.5062 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 15/50 | Loss: 0.4101 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 20/50 | Loss: 0.3193 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 25/50 | Loss: 0.2388 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 30/50 | Loss: 0.1727 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 35/50 | Loss: 0.1222 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 40/50 | Loss: 0.0861 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 45/50 | Loss: 0.0611 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000
Epoch 50/50 | Loss: 0.0443 | Train Rank Acc: 1.0000 | Val Rank Acc: 1.0000

=================================================================
FINAL EXPERIMENT #2 RESULTS
=================================================================
Train Ranking Accuracy : 0.9988
Validation Ranking Acc : 1.0000
Test Ranking Accuracy  : 1.0000
Best Validation Acc    : 1.0000

=================================================================
SCORE STATISTICS
=================================================================
Train score mean: 0.1877296417951584
Val score mean: 0.21507683396339417
Test score mean: 0.19718122482299805

=================================================================
MODEL SAVED
=================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_pairwise_ranker_exp2.pt

=================================================================
EXPERIMENT COMPARISON
=================================================================
Experiment #1 test accuracy : 0.8417
Experiment #2 test accuracy : 1.0000
Difference: +0.1583

Training complete.

In [65]:
# ============================================================
# ZYRA V2 — EXPERIMENT #2
# CORRECT TRUE PAIRWISE RANKING TRAINING
# ============================================================
#
# Dataset:
#   v2_balanced_negative_sampling.csv
#
# Training:
#   positive garment -> positive score
#   negative garment -> negative score
#
# Loss:
#   softplus(-(positive_score - negative_score))
#
# IMPORTANT:
#   This is TRUE pairwise ranking.
#   The previous Experiment #2 training formulation is NOT used.
#
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

DATA_PATH = (
    BASE /
    "data/v2/v2_balanced_negative_sampling.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_pairwise_ranker_exp2_correct.pt"
)

SEED = 42
EPOCHS = 50
LR = 1e-3
WEIGHT_DECAY = 1e-4

np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================
# DEVICE
# ============================================================

if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("=" * 65)
print("ZYRA V2 — EXPERIMENT #2 TRUE PAIRWISE TRAINING")
print("=" * 65)

print("Device:", device)

# ============================================================
# LOAD DATA
# ============================================================

pairwise = pd.read_csv(
    DATA_PATH
)

raw = pd.read_csv(
    RAW_PATH
)

print(
    "\nPairwise rows:",
    len(pairwise)
)

print(
    "People:",
    pairwise["person_id"].nunique()
)

print(
    "\nNegative types:"
)

print(
    pairwise[
        "negative_type"
    ].value_counts()
)

# ============================================================
# FEATURE ENGINEERING
# ============================================================

def add_features(df):

    df = df.copy()

    # --------------------------------------------------------
    # Ease
    # --------------------------------------------------------

    df["bust_ease"] = (
        df["garment_bust"]
        - df["bust"]
    )

    df["waist_ease"] = (
        df["garment_waist"]
        - df["waist"]
    )

    df["hip_ease"] = (
        df["garment_hip"]
        - df["hips"]
    )

    # --------------------------------------------------------
    # Ratios
    # --------------------------------------------------------

    df["bust_ratio"] = (
        df["garment_bust"]
        / df["bust"]
    )

    df["waist_ratio"] = (
        df["garment_waist"]
        / df["waist"]
    )

    df["hip_ratio"] = (
        df["garment_hip"]
        / df["hips"]
    )

    # --------------------------------------------------------
    # Absolute mismatch
    # --------------------------------------------------------

    df["bust_mismatch"] = abs(
        df["garment_bust"]
        - df["bust"]
    )

    df["waist_mismatch"] = abs(
        df["garment_waist"]
        - df["waist"]
    )

    df["hip_mismatch"] = abs(
        df["garment_hip"]
        - df["hips"]
    )

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    df["bust_relative_mismatch"] = (
        df["bust_mismatch"]
        / df["bust"]
    )

    df["waist_relative_mismatch"] = (
        df["waist_mismatch"]
        / df["waist"]
    )

    df["hip_relative_mismatch"] = (
        df["hip_mismatch"]
        / df["hips"]
    )

    # --------------------------------------------------------
    # Aggregate ease
    # --------------------------------------------------------

    ease_cols = [
        "bust_ease",
        "waist_ease",
        "hip_ease",
    ]

    df["mean_ease"] = (
        df[ease_cols]
        .mean(axis=1)
    )

    df["ease_std"] = (
        df[ease_cols]
        .std(axis=1)
    )

    # --------------------------------------------------------
    # Missingness / compatibility counts
    # --------------------------------------------------------

    df["known_fit_dimensions"] = (
        df[ease_cols]
        .notna()
        .sum(axis=1)
    )

    df["tight_dimension_count"] = (
        df[ease_cols]
        .lt(0)
        .sum(axis=1)
    )

    df["extreme_ease_count"] = (
        df[ease_cols]
        .gt(50)
        .sum(axis=1)
    )

    # --------------------------------------------------------
    # Length
    # --------------------------------------------------------

    df["length_height_ratio"] = (
        df["garment_length"]
        / df["height"]
    )

    return df


raw = add_features(raw)

# ============================================================
# FEATURE LIST
# ============================================================

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

print(
    "\nFeature dimension:",
    len(FEATURES)
)

# ============================================================
# LOOKUPS
# ============================================================

person_cols = [
    "height",
    "bust",
    "waist",
    "hips",
]

garment_cols = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

person_lookup = (
    raw[
        ["person_id"] + person_cols
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

garment_lookup = (
    raw[
        ["product_id"] + garment_cols
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

# ============================================================
# FEATURE VECTOR
# ============================================================

def make_features(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    row = {}

    # --------------------------------------------------------
    # Body
    # --------------------------------------------------------

    for f in person_cols:
        row[f] = p[f]

    # --------------------------------------------------------
    # Garment
    # --------------------------------------------------------

    for f in garment_cols:
        row[f] = g[f]

    # --------------------------------------------------------
    # Ease
    # --------------------------------------------------------

    row["bust_ease"] = (
        g["garment_bust"]
        - p["bust"]
    )

    row["waist_ease"] = (
        g["garment_waist"]
        - p["waist"]
    )

    row["hip_ease"] = (
        g["garment_hip"]
        - p["hips"]
    )

    # --------------------------------------------------------
    # Ratios
    # --------------------------------------------------------

    row["bust_ratio"] = (
        g["garment_bust"]
        / p["bust"]
    )

    row["waist_ratio"] = (
        g["garment_waist"]
        / p["waist"]
    )

    row["hip_ratio"] = (
        g["garment_hip"]
        / p["hips"]
    )

    # --------------------------------------------------------
    # Mismatch
    # --------------------------------------------------------

    row["bust_mismatch"] = abs(
        g["garment_bust"]
        - p["bust"]
    )

    row["waist_mismatch"] = abs(
        g["garment_waist"]
        - p["waist"]
    )

    row["hip_mismatch"] = abs(
        g["garment_hip"]
        - p["hips"]
    )

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    row["bust_relative_mismatch"] = (
        row["bust_mismatch"]
        / p["bust"]
    )

    row["waist_relative_mismatch"] = (
        row["waist_mismatch"]
        / p["waist"]
    )

    row["hip_relative_mismatch"] = (
        row["hip_mismatch"]
        / p["hips"]
    )

    # --------------------------------------------------------
    # Aggregate
    # --------------------------------------------------------

    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    if np.all(
        np.isnan(eases)
    ):

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    else:

        row["mean_ease"] = np.nanmean(
            eases
        )

        row["ease_std"] = np.nanstd(
            eases
        )

    row["known_fit_dimensions"] = (
        np.sum(
            ~np.isnan(eases)
        )
    )

    row["tight_dimension_count"] = (
        np.sum(
            eases < 0
        )
    )

    row["extreme_ease_count"] = (
        np.sum(
            eases > 50
        )
    )

    # --------------------------------------------------------
    # Length
    # --------------------------------------------------------

    row["length_height_ratio"] = (
        g["garment_length"]
        / p["height"]
    )

    return np.array(
        [
            row[f]
            for f in FEATURES
        ],
        dtype=np.float32,
    )

# ============================================================
# PERSON LEVEL SPLIT
# ============================================================

people = sorted(
    pairwise[
        "person_id"
    ].unique()
)

train_people, temp_people = (
    train_test_split(
        people,
        test_size=16,
        random_state=SEED,
    )
)

val_people, test_people = (
    train_test_split(
        temp_people,
        test_size=8,
        random_state=SEED,
    )
)

train_people = set(
    train_people
)

val_people = set(
    val_people
)

test_people = set(
    test_people
)

print("\n" + "=" * 65)
print("PERSON-LEVEL SPLIT")
print("=" * 65)

print(
    "Train people:",
    len(train_people)
)

print(
    "Val people:",
    len(val_people)
)

print(
    "Test people:",
    len(test_people)
)

print(
    "\nLeakage:"
)

print(
    "Train ∩ Val:",
    train_people & val_people
)

print(
    "Train ∩ Test:",
    train_people & test_people
)

print(
    "Val ∩ Test:",
    val_people & test_people
)

# ============================================================
# DATA SPLIT
# ============================================================

train_df = pairwise[
    pairwise["person_id"]
    .isin(train_people)
].copy()

val_df = pairwise[
    pairwise["person_id"]
    .isin(val_people)
].copy()

test_df = pairwise[
    pairwise["person_id"]
    .isin(test_people)
].copy()

print(
    "\nPairwise rows:"
)

print(
    "Train:",
    len(train_df)
)

print(
    "Val  :",
    len(val_df)
)

print(
    "Test :",
    len(test_df)
)

# ============================================================
# BUILD POSITIVE + NEGATIVE MATRICES
# ============================================================

def build_pair_data(frame):

    positive_X = []
    negative_X = []

    for _, row in frame.iterrows():

        positive_vector = make_features(
            row["person_id"],
            row["positive_product_id"],
        )

        negative_vector = make_features(
            row["person_id"],
            row["negative_product_id"],
        )

        positive_X.append(
            positive_vector
        )

        negative_X.append(
            negative_vector
        )

    return (
        np.asarray(
            positive_X,
            dtype=np.float32,
        ),
        np.asarray(
            negative_X,
            dtype=np.float32,
        ),
    )

X_pos_train, X_neg_train = (
    build_pair_data(
        train_df
    )
)

X_pos_val, X_neg_val = (
    build_pair_data(
        val_df
    )
)

X_pos_test, X_neg_test = (
    build_pair_data(
        test_df
    )
)

# ============================================================
# IMPUTATION
# ============================================================
#
# Fit ONLY on training features.
# ============================================================

imputer = SimpleImputer(
    strategy="median"
)

train_combined = np.vstack(
    [
        X_pos_train,
        X_neg_train,
    ]
)

imputer.fit(
    train_combined
)

X_pos_train = imputer.transform(
    X_pos_train
)

X_neg_train = imputer.transform(
    X_neg_train
)

X_pos_val = imputer.transform(
    X_pos_val
)

X_neg_val = imputer.transform(
    X_neg_val
)

X_pos_test = imputer.transform(
    X_pos_test
)

X_neg_test = imputer.transform(
    X_neg_test
)

# ============================================================
# SCALING
# ============================================================

scaler = StandardScaler()

scaler.fit(
    train_combined
)

X_pos_train = scaler.transform(
    X_pos_train
)

X_neg_train = scaler.transform(
    X_neg_train
)

X_pos_val = scaler.transform(
    X_pos_val
)

X_neg_val = scaler.transform(
    X_neg_val
)

X_pos_test = scaler.transform(
    X_pos_test
)

X_neg_test = scaler.transform(
    X_neg_test
)

# ============================================================
# TENSORS
# ============================================================

X_pos_train = torch.tensor(
    X_pos_train,
    dtype=torch.float32,
    device=device,
)

X_neg_train = torch.tensor(
    X_neg_train,
    dtype=torch.float32,
    device=device,
)

X_pos_val = torch.tensor(
    X_pos_val,
    dtype=torch.float32,
    device=device,
)

X_neg_val = torch.tensor(
    X_neg_val,
    dtype=torch.float32,
    device=device,
)

X_pos_test = torch.tensor(
    X_pos_test,
    dtype=torch.float32,
    device=device,
)

X_neg_test = torch.tensor(
    X_neg_test,
    dtype=torch.float32,
    device=device,
)

print("\n" + "=" * 65)
print("PAIRWISE TENSORS")
print("=" * 65)

print(
    "Feature dimension:",
    X_pos_train.shape[1]
)

print(
    "Train:",
    X_pos_train.shape
)

print(
    "Val:",
    X_pos_val.shape
)

print(
    "Test:",
    X_pos_test.shape
)

print(
    "NaN:",
    torch.isnan(
        X_pos_train
    ).sum().item()
    +
    torch.isnan(
        X_neg_train
    ).sum().item()
    +
    torch.isnan(
        X_pos_val
    ).sum().item()
    +
    torch.isnan(
        X_neg_val
    ).sum().item()
    +
    torch.isnan(
        X_pos_test
    ).sum().item()
    +
    torch.isnan(
        X_neg_test
    ).sum().item()
)

print(
    "Inf:",
    torch.isinf(
        X_pos_train
    ).sum().item()
    +
    torch.isinf(
        X_neg_train
    ).sum().item()
    +
    torch.isinf(
        X_pos_val
    ).sum().item()
    +
    torch.isinf(
        X_neg_val
    ).sum().item()
    +
    torch.isinf(
        X_pos_test
    ).sum().item()
    +
    torch.isinf(
        X_neg_test
    ).sum().item()
)

# ============================================================
# MODEL
# ============================================================

class CompatibilityScorer(
    nn.Module
):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)

# ============================================================
# MODEL
# ============================================================

model = CompatibilityScorer(
    X_pos_train.shape[1]
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LR,
    weight_decay=WEIGHT_DECAY,
)

print("\n" + "=" * 65)
print("MODEL")
print("=" * 65)

print(
    "Input dimension:",
    X_pos_train.shape[1]
)

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)

# ============================================================
# TRUE PAIRWISE LOSS
# ============================================================
#
# score_pos = model(positive)
# score_neg = model(negative)
#
# We want:
#
#       score_pos > score_neg
#
# Difference:
#
#       score_pos - score_neg
#
# Loss:
#
#       softplus(-(score_pos - score_neg))
#
# ============================================================

def pairwise_loss(
    positive_scores,
    negative_scores,
):

    difference = (
        positive_scores
        - negative_scores
    )

    return torch.nn.functional.softplus(
        -difference
    ).mean()

# ============================================================
# TRAINING
# ============================================================

print("\n" + "=" * 65)
print("TRAINING")
print("=" * 65)

best_val_accuracy = -np.inf
best_state = None

for epoch in range(
    1,
    EPOCHS + 1
):

    model.train()

    optimizer.zero_grad()

    positive_scores = model(
        X_pos_train
    )

    negative_scores = model(
        X_neg_train
    )

    loss = pairwise_loss(
        positive_scores,
        negative_scores,
    )

    loss.backward()

    optimizer.step()

    # --------------------------------------------------------
    # Train ranking accuracy
    # --------------------------------------------------------

    model.eval()

    with torch.no_grad():

        train_pos_scores = model(
            X_pos_train
        )

        train_neg_scores = model(
            X_neg_train
        )

        val_pos_scores = model(
            X_pos_val
        )

        val_neg_scores = model(
            X_neg_val
        )

        train_acc = (
            train_pos_scores
            >
            train_neg_scores
        ).float().mean().item()

        val_acc = (
            val_pos_scores
            >
            val_neg_scores
        ).float().mean().item()

    # --------------------------------------------------------
    # Save best validation model
    # --------------------------------------------------------

    if val_acc > best_val_accuracy:

        best_val_accuracy = val_acc

        best_state = {
            key: value.detach()
            .cpu()
            .clone()

            for key, value
            in model.state_dict().items()
        }

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d}/{EPOCHS} "
            f"| Loss: {loss.item():.4f} "
            f"| Train Rank Acc: {train_acc:.4f} "
            f"| Val Rank Acc: {val_acc:.4f}"
        )

# ============================================================
# RESTORE BEST MODEL
# ============================================================

model.load_state_dict(
    best_state
)

model.eval()

# ============================================================
# FINAL EVALUATION
# ============================================================

with torch.no_grad():

    train_pos_scores = model(
        X_pos_train
    )

    train_neg_scores = model(
        X_neg_train
    )

    val_pos_scores = model(
        X_pos_val
    )

    val_neg_scores = model(
        X_neg_val
    )

    test_pos_scores = model(
        X_pos_test
    )

    test_neg_scores = model(
        X_neg_test
    )

# ============================================================
# ACCURACY
# ============================================================

train_accuracy = (
    train_pos_scores
    >
    train_neg_scores
).float().mean().item()

val_accuracy = (
    val_pos_scores
    >
    val_neg_scores
).float().mean().item()

test_accuracy = (
    test_pos_scores
    >
    test_neg_scores
).float().mean().item()

# ============================================================
# SCORE GAP
# ============================================================

train_gap = (
    train_pos_scores
    -
    train_neg_scores
)

val_gap = (
    val_pos_scores
    -
    val_neg_scores
)

test_gap = (
    test_pos_scores
    -
    test_neg_scores
)

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n" + "=" * 65)
print("FINAL EXPERIMENT #2 RESULTS")
print("=" * 65)

print(
    "Train Ranking Accuracy :",
    f"{train_accuracy:.4f}"
)

print(
    "Validation Ranking Acc :",
    f"{val_accuracy:.4f}"
)

print(
    "Test Ranking Accuracy  :",
    f"{test_accuracy:.4f}"
)

print(
    "Best Validation Acc    :",
    f"{best_val_accuracy:.4f}"
)

print("\nScore gaps:")

print(
    "Train mean:",
    f"{train_gap.mean().item():.4f}"
)

print(
    "Val mean:",
    f"{val_gap.mean().item():.4f}"
)

print(
    "Test mean:",
    f"{test_gap.mean().item():.4f}"
)

print(
    "\nTest median gap:",
    f"{test_gap.median().item():.4f}"
)

# ============================================================
# PERFORMANCE BY NEGATIVE TYPE
# ============================================================

print("\n" + "=" * 65)
print("TEST PERFORMANCE BY NEGATIVE TYPE")
print("=" * 65)

test_copy = test_df.copy()

test_copy["positive_score"] = (
    test_pos_scores
    .detach()
    .cpu()
    .numpy()
)

test_copy["negative_score"] = (
    test_neg_scores
    .detach()
    .cpu()
    .numpy()
)

test_copy["score_gap"] = (
    test_copy[
        "positive_score"
    ]
    -
    test_copy[
        "negative_score"
    ]
)

test_copy["correct"] = (
    test_copy[
        "positive_score"
    ]
    >
    test_copy[
        "negative_score"
    ]
)

type_results = (
    test_copy
    .groupby(
        "negative_type"
    )
    .agg(
        pairs=(
            "correct",
            "size",
        ),
        ranking_accuracy=(
            "correct",
            "mean",
        ),
        mean_score_gap=(
            "score_gap",
            "mean",
        ),
        median_score_gap=(
            "score_gap",
            "median",
        ),
    )
)

print(
    type_results
)

# ============================================================
# SAVE MODEL
# ============================================================

torch.save(
    {
        "model_state_dict":
            model.state_dict(),

        "input_dim":
            X_pos_train.shape[1],

        "feature_names":
            FEATURES,

        "experiment":
            "V2_EXP2_TRUE_PAIRWISE",

        "negative_types":
            [
                "hard",
                "semi-hard",
                "random",
            ],

        "train_people":
            sorted(
                train_people
            ),

        "val_people":
            sorted(
                val_people
            ),

        "test_people":
            sorted(
                test_people
            ),

        "seed":
            SEED,
    },
    MODEL_PATH,
)

print("\n" + "=" * 65)
print("MODEL SAVED")
print("=" * 65)

print(
    MODEL_PATH
)

print("\n" + "=" * 65)
print("TRAINING COMPLETE")
print("=" * 65)

=================================================================
ZYRA V2 — EXPERIMENT #2 TRUE PAIRWISE TRAINING
=================================================================
Device: mps

Pairwise rows: 7938
People: 56

Negative types:
negative_type
random       2990
semi-hard    2816
hard         2132
Name: count, dtype: int64

Feature dimension: 27

=================================================================
PERSON-LEVEL SPLIT
=================================================================
Train people: 40
Val people: 8
Test people: 8

Leakage:
Train ∩ Val: set()
Train ∩ Test: set()
Val ∩ Test: set()

Pairwise rows:
Train: 5978
Val  : 953
Test : 1007

=================================================================
PAIRWISE TENSORS
=================================================================
Feature dimension: 27
Train: torch.Size([5978, 27])
Val: torch.Size([953, 27])
Test: torch.Size([1007, 27])
NaN: 0
Inf: 0

=================================================================
MODEL
=================================================================
Input dimension: 27
Parameters: 3905

=================================================================
TRAINING
=================================================================
Epoch 01/50 | Loss: 0.6954 | Train Rank Acc: 0.5328 | Val Rank Acc: 0.6506
Epoch 05/50 | Loss: 0.6722 | Train Rank Acc: 0.6713 | Val Rank Acc: 0.7660
Epoch 10/50 | Loss: 0.6471 | Train Rank Acc: 0.6760 | Val Rank Acc: 0.7702
Epoch 15/50 | Loss: 0.6260 | Train Rank Acc: 0.6782 | Val Rank Acc: 0.7660
Epoch 20/50 | Loss: 0.6115 | Train Rank Acc: 0.6770 | Val Rank Acc: 0.7650
Epoch 25/50 | Loss: 0.6039 | Train Rank Acc: 0.6802 | Val Rank Acc: 0.7650
Epoch 30/50 | Loss: 0.5984 | Train Rank Acc: 0.6823 | Val Rank Acc: 0.7597
Epoch 35/50 | Loss: 0.5923 | Train Rank Acc: 0.6848 | Val Rank Acc: 0.7629
Epoch 40/50 | Loss: 0.5867 | Train Rank Acc: 0.6912 | Val Rank Acc: 0.7555
Epoch 45/50 | Loss: 0.5823 | Train Rank Acc: 0.6950 | Val Rank Acc: 0.7471
Epoch 50/50 | Loss: 0.5783 | Train Rank Acc: 0.6977 | Val Rank Acc: 0.7492

=================================================================
FINAL EXPERIMENT #2 RESULTS
=================================================================
Train Ranking Accuracy : 0.6733
Validation Ranking Acc : 0.7712
Test Ranking Accuracy  : 0.7180
Best Validation Acc    : 0.7712

Score gaps:
Train mean: 0.0863
Val mean: 0.1431
Test mean: 0.0985

Test median gap: 0.1101

=================================================================
TEST PERFORMANCE BY NEGATIVE TYPE
=================================================================
               pairs  ranking_accuracy  mean_score_gap  median_score_gap
negative_type
hard             329          0.902736        0.187985          0.186627
random           339          0.563422        0.017477          0.027879
semi-hard        339          0.693215        0.092790          0.095618

=================================================================
MODEL SAVED
=================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_pairwise_ranker_exp2_correct.pt

=================================================================
TRAINING COMPLETE
=================================================================

In [66]:
# ============================================================
# ZYRA V2 — CORRECTED 1:1:1 NEGATIVE SAMPLING
# ============================================================
#
# For EVERY positive interaction:
#
#   1 HARD
#   1 SEMI-HARD
#   1 RANDOM
#
# Guarantees:
#   - no duplicate (person, negative_product)
#   - no positive/negative collision
#   - hard < semi-hard < random by physical distance
#
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_negative_sampling_1to1to1.csv"
)

SEED = 2026

rng = np.random.default_rng(SEED)

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(
    RAW_PATH
)

print("=" * 65)
print("ZYRA V2 — CORRECTED 1:1:1 NEGATIVE SAMPLING")
print("=" * 65)

print(
    "Input rows :",
    len(df)
)

print(
    "People     :",
    df["person_id"].nunique()
)

print(
    "Garments   :",
    df["product_id"].nunique()
)

# ============================================================
# POSITIVE INTERACTIONS
# ============================================================

positive_df = (
    df[
        df["label"] == 1
    ]
    [
        [
            "person_id",
            "product_id",
        ]
    ]
    .drop_duplicates()
    .copy()
)

print(
    "\nPositive interactions:",
    len(positive_df)
)

# ============================================================
# PERSON LOOKUP
# ============================================================

person_lookup = (
    df[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

# ============================================================
# GARMENT LOOKUP
# ============================================================

garment_lookup = (
    df[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
        ]
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

all_products = list(
    garment_lookup.index
)

# ============================================================
# POSITIVE PRODUCTS BY PERSON
# ============================================================

positive_by_person = (
    positive_df
    .groupby(
        "person_id"
    )[
        "product_id"
    ]
    .apply(set)
    .to_dict()
)

# ============================================================
# PHYSICAL DISTANCE
# ============================================================

def physical_distance(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    distances = []

    dimensions = [
        (
            p["bust"],
            g["garment_bust"],
        ),
        (
            p["waist"],
            g["garment_waist"],
        ),
        (
            p["hips"],
            g["garment_hip"],
        ),
        (
            p["height"],
            g["garment_length"],
        ),
    ]

    for person_value, garment_value in dimensions:

        if (
            pd.isna(person_value)
            or
            pd.isna(garment_value)
        ):
            continue

        if person_value == 0:
            continue

        distances.append(
            abs(
                garment_value
                -
                person_value
            )
            /
            abs(
                person_value
            )
        )

    if not distances:
        return np.nan

    return float(
        np.mean(distances)
    )

# ============================================================
# BUILD DISTANCE TABLE
# ============================================================

print(
    "\nComputing candidate distances..."
)

candidate_rows = []

for person_id in sorted(
    positive_by_person
):

    positive_products = (
        positive_by_person[
            person_id
        ]
    )

    for product_id in all_products:

        # Never sample a known positive
        if product_id in positive_products:
            continue

        distance = physical_distance(
            person_id,
            product_id,
        )

        if pd.isna(distance):
            continue

        candidate_rows.append(
            {
                "person_id":
                    person_id,

                "product_id":
                    product_id,

                "distance":
                    distance,
            }
        )

candidates_df = pd.DataFrame(
    candidate_rows
)

print(
    "Valid negative candidates:",
    len(candidates_df)
)

# ============================================================
# SAMPLE
# ============================================================

output_rows = []

failed_people = []

for person_id in sorted(
    positive_by_person
):

    person_candidates = (
        candidates_df[
            candidates_df[
                "person_id"
            ]
            ==
            person_id
        ]
        .copy()
        .sort_values(
            "distance"
        )
        .reset_index(
            drop=True
        )
    )

    n = len(
        person_candidates
    )

    if n < 3:

        failed_people.append(
            (
                person_id,
                n
            )
        )

        continue

    # --------------------------------------------------------
    # Create NON-OVERLAPPING pools
    # --------------------------------------------------------
    #
    # HARD:
    # closest 20%
    #
    # SEMI-HARD:
    # middle 40%
    #
    # RANDOM:
    # remaining 40%
    #
    # We explicitly remove selected products between stages.
    # --------------------------------------------------------

    hard_count = max(
        1,
        int(
            np.ceil(
                n * 0.20
            )
        )
    )

    semi_start = hard_count

    semi_end = max(
        semi_start + 1,
        int(
            np.ceil(
                n * 0.60
            )
        )
    )

    hard_pool = (
        person_candidates
        .iloc[
            :hard_count
        ]
        .copy()
    )

    semi_pool = (
        person_candidates
        .iloc[
            semi_start:semi_end
        ]
        .copy()
    )

    random_pool = (
        person_candidates
        .iloc[
            semi_end:
        ]
        .copy()
    )

    # --------------------------------------------------------
    # Safety fallback
    # --------------------------------------------------------

    if len(semi_pool) == 0:

        semi_pool = (
            person_candidates
            .iloc[
                hard_count:
            ]
            .copy()
        )

    if len(random_pool) == 0:

        random_pool = (
            person_candidates
            .iloc[
                hard_count:
            ]
            .copy()
        )

    # --------------------------------------------------------
    # Used negatives for THIS PERSON
    # --------------------------------------------------------

    used_for_person = set()

    positive_products = (
        positive_by_person[
            person_id
        ]
    )

    # --------------------------------------------------------
    # One sample per positive
    # --------------------------------------------------------

    person_positive_list = sorted(
        positive_products
    )

    for positive_product in person_positive_list:

        # ====================================================
        # HARD
        # ====================================================

        hard_candidates = (
            hard_pool[
                ~hard_pool[
                    "product_id"
                ].isin(
                    used_for_person
                )
            ]
        )

        if len(hard_candidates) == 0:

            # Fall back to closest unused candidate
            hard_candidates = (
                person_candidates[
                    ~person_candidates[
                        "product_id"
                    ].isin(
                        used_for_person
                    )
                ]
                .head(
                    max(
                        1,
                        min(
                            10,
                            len(
                                person_candidates
                            )
                        )
                    )
                )
            )

        if len(hard_candidates) == 0:
            break

        hard_row = (
            hard_candidates
            .iloc[
                rng.integers(
                    len(
                        hard_candidates
                    )
                )
            ]
        )

        hard_product = (
            hard_row[
                "product_id"
            ]
        )

        hard_distance = float(
            hard_row[
                "distance"
            ]
        )

        used_for_person.add(
            hard_product
        )

        # ====================================================
        # SEMI-HARD
        # ====================================================

        semi_candidates = (
            semi_pool[
                ~semi_pool[
                    "product_id"
                ].isin(
                    used_for_person
                )
            ]
        )

        if len(semi_candidates) == 0:

            # Find candidates strictly farther
            # than hard distance where possible.
            semi_candidates = (
                person_candidates[
                    (
                        person_candidates[
                            "distance"
                        ]
                        >
                        hard_distance
                    )
                    &
                    ~person_candidates[
                        "product_id"
                    ].isin(
                        used_for_person
                    )
                ]
            )

        if len(semi_candidates) == 0:

            semi_candidates = (
                person_candidates[
                    ~person_candidates[
                        "product_id"
                    ].isin(
                        used_for_person
                    )
                ]
            )

        if len(semi_candidates) == 0:
            break

        semi_row = (
            semi_candidates
            .iloc[
                rng.integers(
                    len(
                        semi_candidates
                    )
                )
            ]
        )

        semi_product = (
            semi_row[
                "product_id"
            ]
        )

        semi_distance = float(
            semi_row[
                "distance"
            ]
        )

        used_for_person.add(
            semi_product
        )

        # ====================================================
        # RANDOM
        # ====================================================

        random_candidates = (
            random_pool[
                ~random_pool[
                    "product_id"
                ].isin(
                    used_for_person
                )
            ]
        )

        if len(random_candidates) == 0:

            random_candidates = (
                person_candidates[
                    ~person_candidates[
                        "product_id"
                    ].isin(
                        used_for_person
                    )
                ]
            )

        if len(random_candidates) == 0:
            break

        random_row = (
            random_candidates
            .iloc[
                rng.integers(
                    len(
                        random_candidates
                    )
                )
            ]
        )

        random_product = (
            random_row[
                "product_id"
            ]
        )

        random_distance = float(
            random_row[
                "distance"
            ]
        )

        used_for_person.add(
            random_product
        )

        # ====================================================
        # STORE
        # ====================================================

        output_rows.extend(
            [
                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        hard_product,

                    "negative_type":
                        "hard",

                    "negative_distance":
                        hard_distance,
                },

                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        semi_product,

                    "negative_type":
                        "semi-hard",

                    "negative_distance":
                        semi_distance,
                },

                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        random_product,

                    "negative_type":
                        "random",

                    "negative_distance":
                        random_distance,
                },
            ]
        )

# ============================================================
# RESULT DATAFRAME
# ============================================================

result = pd.DataFrame(
    output_rows
)

# ============================================================
# RESULTS
# ============================================================

print("\n" + "=" * 65)
print("SAMPLING RESULTS")
print("=" * 65)

print(
    "Positive interactions:",
    len(positive_df)
)

print(
    "Generated ranking rows:",
    len(result)
)

print(
    "\nNegative type distribution:"
)

print(
    result[
        "negative_type"
    ].value_counts()
)

# ============================================================
# EXPECTED COUNTS
# ============================================================

expected_count = len(
    positive_df
)

hard_count_actual = (
    result[
        "negative_type"
    ]
    .eq("hard")
    .sum()
)

semi_count_actual = (
    result[
        "negative_type"
    ]
    .eq("semi-hard")
    .sum()
)

random_count_actual = (
    result[
        "negative_type"
    ]
    .eq("random")
    .sum()
)

print("\nExpected:")
print(
    "Hard      :",
    expected_count
)

print(
    "Semi-hard :",
    expected_count
)

print(
    "Random    :",
    expected_count
)

print("\nActual:")
print(
    "Hard      :",
    hard_count_actual
)

print(
    "Semi-hard :",
    semi_count_actual
)

print(
    "Random    :",
    random_count_actual
)

# ============================================================
# DUPLICATE CHECK
# ============================================================

duplicate_rows = (
    result[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "negative_type",
        ]
    ]
    .duplicated()
    .sum()
)

duplicate_person_negative = (
    result[
        [
            "person_id",
            "negative_product_id",
        ]
    ]
    .duplicated()
    .sum()
)

print("\n" + "=" * 65)
print("INTEGRITY")
print("=" * 65)

print(
    "Duplicate full rows:",
    duplicate_rows
)

print(
    "Duplicate person-negative pairs:",
    duplicate_person_negative
)

# ============================================================
# POSITIVE COLLISIONS
# ============================================================

positive_keys = set(
    zip(
        positive_df[
            "person_id"
        ],
        positive_df[
            "product_id"
        ],
    )
)

negative_keys = set(
    zip(
        result[
            "person_id"
        ],
        result[
            "negative_product_id"
        ],
    )
)

collisions = (
    positive_keys
    &
    negative_keys
)

print(
    "Positive-negative collisions:",
    len(collisions)
)

# ============================================================
# DISTANCE DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("DISTANCE DISTRIBUTION")
print("=" * 65)

distance_stats = (
    result
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .describe()
)

print(
    distance_stats
)

# ============================================================
# MEAN DISTANCE
# ============================================================

means = (
    result
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .mean()
)

hard_mean = means.get(
    "hard",
    np.nan
)

semi_mean = means.get(
    "semi-hard",
    np.nan
)

random_mean = means.get(
    "random",
    np.nan
)

print("\nMean distances:")

print(
    "Hard      :",
    f"{hard_mean:.6f}"
)

print(
    "Semi-hard :",
    f"{semi_mean:.6f}"
)

print(
    "Random    :",
    f"{random_mean:.6f}"
)

# ============================================================
# DIFFICULTY ORDER CHECK
# ============================================================

difficulty_ok = (
    hard_mean
    <
    semi_mean
    <
    random_mean
)

print(
    "\nHard < Semi-hard < Random:",
    difficulty_ok
)

# ============================================================
# PER PERSON COUNTS
# ============================================================

person_type_counts = (
    result
    .groupby(
        [
            "person_id",
            "negative_type",
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
)

print("\n" + "=" * 65)
print("PER-PERSON NEGATIVE COUNTS")
print("=" * 65)

print(
    person_type_counts
)

# ============================================================
# FAILED PEOPLE
# ============================================================

print("\n" + "=" * 65)
print("PEOPLE WITH INSUFFICIENT CANDIDATES")
print("=" * 65)

if failed_people:

    for person_id, count in failed_people:

        print(
            person_id,
            "candidates:",
            count
        )

else:

    print(
        "None"
    )

# ============================================================
# SAMPLE
# ============================================================

print("\n" + "=" * 65)
print("EXAMPLE SAMPLES")
print("=" * 65)

display(
    result.head(20)
)

# ============================================================
# FINAL PASS/FAIL
# ============================================================

counts_ok = (
    hard_count_actual
    ==
    expected_count
    and
    semi_count_actual
    ==
    expected_count
    and
    random_count_actual
    ==
    expected_count
)

integrity_ok = (
    duplicate_rows == 0
    and
    duplicate_person_negative == 0
    and
    len(collisions) == 0
)

final_pass = (
    counts_ok
    and
    integrity_ok
    and
    difficulty_ok
)

print("\n" + "=" * 65)
print("FINAL VALIDATION")
print("=" * 65)

print(
    "1:1:1 counts:",
    "PASS" if counts_ok else "FAIL"
)

print(
    "No duplicate rows:",
    "PASS"
    if duplicate_rows == 0
    else "FAIL"
)

print(
    "No duplicate person-negative pairs:",
    "PASS"
    if duplicate_person_negative == 0
    else "FAIL"
)

print(
    "No positive collisions:",
    "PASS"
    if len(collisions) == 0
    else "FAIL"
)

print(
    "Hard < Semi-hard < Random:",
    "PASS"
    if difficulty_ok
    else "FAIL"
)

print(
    "\nOVERALL:",
    "PASS" if final_pass else "FAIL"
)

# ============================================================
# SAVE ONLY IF VALID
# ============================================================

if final_pass:

    result.to_csv(
        OUTPUT_PATH,
        index=False,
    )

    print(
        "\nSaved:",
        OUTPUT_PATH
    )

else:

    print(
        "\nDataset NOT saved as valid."
    )

print(
    "\nCorrected negative sampling complete."
)

=================================================================
ZYRA V2 — CORRECTED 1:1:1 NEGATIVE SAMPLING
=================================================================
Input rows : 5980
People     : 56
Garments   : 897

Positive interactions: 2990

Computing candidate distances...
Valid negative candidates: 47242

=================================================================
SAMPLING RESULTS
=================================================================
Positive interactions: 2990
Generated ranking rows: 8781

Negative type distribution:
negative_type
hard         2927
semi-hard    2927
random       2927
Name: count, dtype: int64

Expected:
Hard      : 2990
Semi-hard : 2990
Random    : 2990

Actual:
Hard      : 2927
Semi-hard : 2927
Random    : 2927

=================================================================
INTEGRITY
=================================================================
Duplicate full rows: 0
Duplicate person-negative pairs: 0
Positive-negative collisions: 0

=================================================================
DISTANCE DISTRIBUTION
=================================================================
                count      mean       std       min       25%       50%  \
negative_type
hard           2927.0  0.292134  0.078275  0.020032  0.228357  0.281826
random         2927.0  0.589006  0.159529  0.273672  0.457878  0.595621
semi-hard      2927.0  0.407337  0.107358  0.215369  0.311028  0.412417

                    75%       max
negative_type
hard           0.354882  0.595657
random         0.684866  1.312500
semi-hard      0.497755  0.808254

Mean distances:
Hard      : 0.292134
Semi-hard : 0.407337
Random    : 0.589006

Hard < Semi-hard < Random: True

=================================================================
PER-PERSON NEGATIVE COUNTS
=================================================================
negative_type  hard  random  semi-hard
person_id
Alex             37      37         37
Amanda          108     108        108
Anna             87      87         87
Anna Maria       18      18         18
Anneliese         3       3          3
Bree              6       6          6
Charlotte        13      13         13
Chelsea          88      88         88
Chesska          11      11         11
Clementine       62      62         62
Denniel          26      26         26
Edith             3       3          3
Emma             87      87         87
Fiona           184     184        184
Gemma            84      84         84
Georgia         131     131        131
Grazi             1       1          1
Helen             8       8          8
Jess            215     215        215
Jira              1       1          1
Jude             14      14         14
Kate             52      52         52
Katie            24      24         24
Lara              3       3          3
Laura           217     217        217
Lauren           30      30         30
Lisa              8       8          8
Ljubenka        109     109        109
Louise            5       5          5
Lucy              4       4          4
Maddy            77      77         77
Madeline         37      37         37
Mae-Lee         159     159        159
Mandy             9       9          9
Marnee          141     141        141
Mercy            24      24         24
Miranda          27      27         27
Monique          29      29         29
Nadine           42      42         42
Natalia          46      46         46
Natalie          51      51         51
Nathalie         14      14         14
Nikki             9       9          9
Olivia           23      23         23
Palatina         49      49         49
Perrie           37      37         37
Riina           104     104        104
Rosaline          4       4          4
Shadae           35      35         35
Sophia           59      59         59
Sophie           54      54         54
Stacey           56      56         56
Stefania         33      33         33
Summer           95      95         95
Thais             3       3          3
Tia              71      71         71

=================================================================
PEOPLE WITH INSUFFICIENT CANDIDATES
=================================================================
None

=================================================================
EXAMPLE SAMPLES
=================================================================

,person_id,positive_product_id,negative_product_id,negative_type,negative_distance
0,Alex,jade-kimono-kaleidoscope#Blue,millie-top#Blush,hard,0.420420
1,Alex,jade-kimono-kaleidoscope#Blue,silver-dot-tie-sleeve-blouse#SilverDotP,semi-hard,0.463091
2,Alex,jade-kimono-kaleidoscope#Blue,voyager-stripe-crew#Stripe,random,0.620690
3,Alex,jade-kimono-sweet-blossoms#Blue,dusk-top#DuskPrint,hard,0.393230
4,Alex,jade-kimono-sweet-blossoms#Blue,ava-short-sleeve-linen-tee#Navy,semi-hard,0.500783
5,Alex,jade-kimono-sweet-blossoms#Blue,the-multi-stripe-cardi#Stripe,random,0.690682
6,Alex,lola-bell-sleeve-top-ditsy-daisies#Blue,bamboo-layer-tank#Chalk,hard,0.272774
7,Alex,lola-bell-sleeve-top-ditsy-daisies#Blue,foil-print-top-2#Navy,semi-hard,0.501581
8,Alex,lola-bell-sleeve-top-ditsy-daisies#Blue,the-shoulder-tie-top#Black,random,0.749058
9,Alex,lola-bell-sleeve-top-entangled-vines#Gold,eco-78-long-cardigan#DarkGreyM,hard,0.345893
10,Alex,lola-bell-sleeve-top-entangled-vines#Gold,to-the-beat-of-the-drum-kimono#Leaf,semi-hard,0.580980
11,Alex,lola-bell-sleeve-top-entangled-vines#Gold,prairie-romance-blouse#Blush,random,0.803924
12,Alex,the-batwing-tee#Black,animal-button-up-shirt#KhakiPrint,hard,0.401920
13,Alex,the-batwing-tee#Black,the-contrast-panel-top#BlkStripe,semi-hard,0.592699
14,Alex,the-batwing-tee#Black,tab-sleeve-longline-shirt#Navy,random,0.771538
15,Alex,the-batwing-tee#FrenchBlue,mila-knit-cardigan#StoneBlack,hard,0.330992
16,Alex,the-batwing-tee#FrenchBlue,the-lace-trim-top#Black,semi-hard,0.588997
17,Alex,the-batwing-tee#FrenchBlue,contrast-stripe-sweater#Pockets,random,0.749363
18,Alex,the-batwing-tee#Sea,back-to-you-top#BlackMagic,hard,0.284812
19,Alex,the-batwing-tee#Sea,tia-boyfriend-shirt#White,semi-hard,0.491188

=================================================================
FINAL VALIDATION
=================================================================
1:1:1 counts: FAIL
No duplicate rows: PASS
No duplicate person-negative pairs: PASS
No positive collisions: PASS
Hard < Semi-hard < Random: PASS

OVERALL: FAIL

Dataset NOT saved as valid.

Corrected negative sampling complete.

In [68]:
# ============================================================
# ZYRA V2 — FINAL 1:1:1 NEGATIVE SAMPLER
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_negative_sampling_1to1to1.csv"
)

SEED = 2026

rng = np.random.default_rng(SEED)

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(
    RAW_PATH
)

positive_df = (
    df[
        df["label"] == 1
    ][
        [
            "person_id",
            "product_id",
        ]
    ]
    .drop_duplicates()
    .copy()
)

person_lookup = (
    df[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

garment_lookup = (
    df[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
        ]
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

all_products = list(
    garment_lookup.index
)

positive_by_person = (
    positive_df
    .groupby(
        "person_id"
    )[
        "product_id"
    ]
    .apply(set)
    .to_dict()
)

# ============================================================
# DISTANCE
# ============================================================

def physical_distance(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    values = []

    dimensions = [
        (
            p["bust"],
            g["garment_bust"],
        ),
        (
            p["waist"],
            g["garment_waist"],
        ),
        (
            p["hips"],
            g["garment_hip"],
        ),
        (
            p["height"],
            g["garment_length"],
        ),
    ]

    for pv, gv in dimensions:

        if (
            pd.isna(pv)
            or
            pd.isna(gv)
        ):
            continue

        if pv == 0:
            continue

        values.append(
            abs(
                gv - pv
            )
            /
            abs(pv)
        )

    if not values:
        return np.nan

    return float(
        np.mean(values)
    )

# ============================================================
# BUILD CANDIDATES
# ============================================================

candidate_rows = []

for person_id in sorted(
    positive_by_person
):

    positives = (
        positive_by_person[
            person_id
        ]
    )

    for product_id in all_products:

        if product_id in positives:
            continue

        distance = physical_distance(
            person_id,
            product_id,
        )

        if pd.isna(distance):
            continue

        candidate_rows.append(
            {
                "person_id":
                    person_id,

                "product_id":
                    product_id,

                "distance":
                    distance,
            }
        )

candidates = pd.DataFrame(
    candidate_rows
)

# ============================================================
# SAMPLING
# ============================================================

rows = []

for person_id in sorted(
    positive_by_person
):

    positives = sorted(
        positive_by_person[
            person_id
        ]
    )

    person_candidates = (
        candidates[
            candidates[
                "person_id"
            ]
            ==
            person_id
        ]
        .sort_values(
            "distance"
        )
        .reset_index(
            drop=True
        )
    )

    n = len(
        person_candidates
    )

    if n < 3:

        raise ValueError(
            f"Person {person_id} has "
            f"only {n} valid negative candidates."
        )

    # --------------------------------------------------------
    # GLOBAL POOLS
    # --------------------------------------------------------

    hard_end = max(
        1,
        int(
            np.ceil(
                n * 0.20
            )
        )
    )

    semi_start = hard_end

    semi_end = max(
        semi_start + 1,
        int(
            np.ceil(
                n * 0.60
            )
        )
    )

    hard_pool = (
        person_candidates
        .iloc[
            :hard_end
        ]
        .copy()
    )

    semi_pool = (
        person_candidates
        .iloc[
            semi_start:semi_end
        ]
        .copy()
    )

    random_pool = (
        person_candidates
        .iloc[
            semi_end:
        ]
        .copy()
    )

    # Safety
    if len(semi_pool) == 0:
        semi_pool = person_candidates

    if len(random_pool) == 0:
        random_pool = person_candidates

    # --------------------------------------------------------
    # USED FULL KEYS
    #
    # IMPORTANT:
    # Same negative garment MAY be used for another positive
    # interaction.
    #
    # But the exact:
    #
    # person + positive + negative + type
    #
    # combination can never repeat.
    # --------------------------------------------------------

    used_keys = set()

    # --------------------------------------------------------
    # EVERY POSITIVE GETS THREE NEGATIVES
    # --------------------------------------------------------

    for positive_product in positives:

        # ====================================================
        # HARD
        # ====================================================

        hard_options = []

        for _, candidate in hard_pool.iterrows():

            key = (
                person_id,
                positive_product,
                candidate["product_id"],
                "hard",
            )

            if key not in used_keys:

                hard_options.append(
                    candidate
                )

        if not hard_options:

            raise RuntimeError(
                f"No hard negative available "
                f"for person={person_id}, "
                f"positive={positive_product}"
            )

        hard_row = hard_options[
            rng.integers(
                len(hard_options)
            )
        ]

        hard_product = (
            hard_row["product_id"]
        )

        hard_distance = float(
            hard_row["distance"]
        )

        hard_key = (
            person_id,
            positive_product,
            hard_product,
            "hard",
        )

        used_keys.add(
            hard_key
        )

        # ====================================================
        # SEMI-HARD
        # ====================================================

        semi_options = []

        for _, candidate in semi_pool.iterrows():

            key = (
                person_id,
                positive_product,
                candidate["product_id"],
                "semi-hard",
            )

            if key not in used_keys:

                # Prefer a garment farther away
                # than the hard negative.
                if (
                    candidate["distance"]
                    >
                    hard_distance
                ):

                    semi_options.append(
                        candidate
                    )

        if not semi_options:

            for _, candidate in semi_pool.iterrows():

                key = (
                    person_id,
                    positive_product,
                    candidate["product_id"],
                    "semi-hard",
                )

                if key not in used_keys:

                    semi_options.append(
                        candidate
                    )

        if not semi_options:

            raise RuntimeError(
                f"No semi-hard negative available "
                f"for person={person_id}, "
                f"positive={positive_product}"
            )

        semi_row = semi_options[
            rng.integers(
                len(semi_options)
            )
        ]

        semi_product = (
            semi_row["product_id"]
        )

        semi_distance = float(
            semi_row["distance"]
        )

        semi_key = (
            person_id,
            positive_product,
            semi_product,
            "semi-hard",
        )

        used_keys.add(
            semi_key
        )

        # ====================================================
        # RANDOM
        # ====================================================

        random_options = []

        for _, candidate in random_pool.iterrows():

            key = (
                person_id,
                positive_product,
                candidate["product_id"],
                "random",
            )

            if key not in used_keys:

                # Prefer distance greater than semi-hard.
                if (
                    candidate["distance"]
                    >
                    semi_distance
                ):

                    random_options.append(
                        candidate
                    )

        if not random_options:

            for _, candidate in random_pool.iterrows():

                key = (
                    person_id,
                    positive_product,
                    candidate["product_id"],
                    "random",
                )

                if key not in used_keys:

                    random_options.append(
                        candidate
                    )

        if not random_options:

            raise RuntimeError(
                f"No random negative available "
                f"for person={person_id}, "
                f"positive={positive_product}"
            )

        random_row = random_options[
            rng.integers(
                len(random_options)
            )
        ]

        random_product = (
            random_row["product_id"]
        )

        random_distance = float(
            random_row["distance"]
        )

        random_key = (
            person_id,
            positive_product,
            random_product,
            "random",
        )

        used_keys.add(
            random_key
        )

        # ====================================================
        # SAVE THREE
        # ====================================================

        rows.extend(
            [
                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        hard_product,

                    "negative_type":
                        "hard",

                    "negative_distance":
                        hard_distance,
                },

                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        semi_product,

                    "negative_type":
                        "semi-hard",

                    "negative_distance":
                        semi_distance,
                },

                {
                    "person_id":
                        person_id,

                    "positive_product_id":
                        positive_product,

                    "negative_product_id":
                        random_product,

                    "negative_type":
                        "random",

                    "negative_distance":
                        random_distance,
                },
            ]
        )

# ============================================================
# DATAFRAME
# ============================================================

result = pd.DataFrame(
    rows
)

# ============================================================
# COUNTS
# ============================================================

print("=" * 65)
print("FINAL 1:1:1 SAMPLING")
print("=" * 65)

print(
    "Positive interactions:",
    len(positive_df)
)

print(
    "Expected total:",
    len(positive_df) * 3
)

print(
    "Actual total:",
    len(result)
)

print(
    "\nNegative distribution:"
)

print(
    result[
        "negative_type"
    ].value_counts()
)

# ============================================================
# DUPLICATES
# ============================================================

duplicate_full = (
    result[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "negative_type",
        ]
    ]
    .duplicated()
    .sum()
)

print(
    "\nDuplicate full rows:",
    duplicate_full
)

# ============================================================
# POSITIVE COLLISIONS
# ============================================================

positive_keys = set(
    zip(
        positive_df[
            "person_id"
        ],
        positive_df[
            "product_id"
        ],
    )
)

negative_keys = set(
    zip(
        result[
            "person_id"
        ],
        result[
            "negative_product_id"
        ],
    )
)

collisions = (
    positive_keys
    &
    negative_keys
)

print(
    "Positive-negative collisions:",
    len(collisions)
)

# ============================================================
# DISTANCE
# ============================================================

distance_stats = (
    result
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .agg(
        [
            "count",
            "mean",
            "median",
            "min",
            "max",
        ]
    )
)

print(
    "\nDistance statistics:"
)

print(
    distance_stats
)

# ============================================================
# DIFFICULTY
# ============================================================

means = (
    result
    .groupby(
        "negative_type"
    )[
        "negative_distance"
    ]
    .mean()
)

hard_mean = means[
    "hard"
]

semi_mean = means[
    "semi-hard"
]

random_mean = means[
    "random"
]

difficulty_ok = (
    hard_mean
    <
    semi_mean
    <
    random_mean
)

print(
    "\nHard mean      :",
    hard_mean
)

print(
    "Semi-hard mean :",
    semi_mean
)

print(
    "Random mean    :",
    random_mean
)

print(
    "\nHard < Semi-hard < Random:",
    difficulty_ok
)

# ============================================================
# 1:1:1 VALIDATION
# ============================================================

hard_count = (
    result[
        "negative_type"
    ]
    .eq("hard")
    .sum()
)

semi_count = (
    result[
        "negative_type"
    ]
    .eq("semi-hard")
    .sum()
)

random_count = (
    result[
        "negative_type"
    ]
    .eq("random")
    .sum()
)

expected = len(
    positive_df
)

counts_ok = (
    hard_count == expected
    and
    semi_count == expected
    and
    random_count == expected
    and
    len(result)
    == expected * 3
)

print("\n" + "=" * 65)
print("FINAL VALIDATION")
print("=" * 65)

print(
    "Hard count:",
    hard_count,
    "/",
    expected
)

print(
    "Semi-hard count:",
    semi_count,
    "/",
    expected
)

print(
    "Random count:",
    random_count,
    "/",
    expected
)

print(
    "1:1:1 counts:",
    "PASS" if counts_ok else "FAIL"
)

print(
    "No duplicate rows:",
    "PASS"
    if duplicate_full == 0
    else "FAIL"
)

print(
    "No positive collisions:",
    "PASS"
    if len(collisions) == 0
    else "FAIL"
)

print(
    "Difficulty ordering:",
    "PASS"
    if difficulty_ok
    else "FAIL"
)

final_pass = (
    counts_ok
    and duplicate_full == 0
    and len(collisions) == 0
    and difficulty_ok
)

print(
    "\nOVERALL:",
    "PASS"
    if final_pass
    else "FAIL"
)

# ============================================================
# SAVE
# ============================================================

if final_pass:

    result.to_csv(
        OUTPUT_PATH,
        index=False,
    )

    print(
        "\nSaved:",
        OUTPUT_PATH
    )

else:

    print(
        "\nNOT SAVED — validation failed."
    )

print(
    "\nSampling complete."
)

=================================================================
FINAL 1:1:1 SAMPLING
=================================================================
Positive interactions: 2990
Expected total: 8970
Actual total: 8970

Negative distribution:
negative_type
hard         2990
semi-hard    2990
random       2990
Name: count, dtype: int64

Duplicate full rows: 0
Positive-negative collisions: 0

Distance statistics:
               count      mean    median       min       max
negative_type
hard            2990  0.284444  0.265095  0.050230  0.494243
random          2990  0.585875  0.592089  0.274068  1.312500
semi-hard       2990  0.402459  0.400747  0.215369  0.659820

Hard mean      : 0.2844442451397365
Semi-hard mean : 0.4024586567699007
Random mean    : 0.5858754781916342

Hard < Semi-hard < Random: True

=================================================================
FINAL VALIDATION
=================================================================
Hard count: 2990 / 2990
Semi-hard count: 2990 / 2990
Random count: 2990 / 2990
1:1:1 counts: PASS
No duplicate rows: PASS
No positive collisions: PASS
Difficulty ordering: PASS

OVERALL: PASS

Saved: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_negative_sampling_1to1to1.csv

Sampling complete.

In [69]:
# ============================================================
# ZYRA V2 — EXPERIMENT #2
# TRUE PAIRWISE RANKER — FINAL 1:1:1 DATASET
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# ============================================================
# CONFIG
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

DATA_PATH = (
    BASE /
    "data/v2/v2_negative_sampling_1to1to1.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_pairwise_ranker_exp2_final.pt"
)

SEED = 42
EPOCHS = 50
LR = 1e-3
WEIGHT_DECAY = 1e-4

np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================
# DEVICE
# ============================================================

if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("=" * 65)
print("ZYRA V2 — EXPERIMENT #2 FINAL TRUE PAIRWISE TRAINING")
print("=" * 65)

print("Device:", device)

# ============================================================
# LOAD DATA
# ============================================================

pairwise = pd.read_csv(DATA_PATH)
raw = pd.read_csv(RAW_PATH)

print("\nPairwise rows:", len(pairwise))
print("People:", pairwise["person_id"].nunique())

print("\nNegative types:")
print(pairwise["negative_type"].value_counts())

# ============================================================
# VERIFY 1:1:1 DATASET BEFORE TRAINING
# ============================================================

positive_count = pairwise[
    ["person_id", "positive_product_id"]
].drop_duplicates().shape[0]

hard_count = (
    pairwise["negative_type"]
    .eq("hard")
    .sum()
)

semi_count = (
    pairwise["negative_type"]
    .eq("semi-hard")
    .sum()
)

random_count = (
    pairwise["negative_type"]
    .eq("random")
    .sum()
)

print("\n" + "=" * 65)
print("INPUT DATASET VALIDATION")
print("=" * 65)

print("Positive interactions:", positive_count)
print("Hard negatives:", hard_count)
print("Semi-hard negatives:", semi_count)
print("Random negatives:", random_count)
print("Total rows:", len(pairwise))

assert hard_count == positive_count
assert semi_count == positive_count
assert random_count == positive_count
assert len(pairwise) == positive_count * 3

print("\n1:1:1 DATASET: PASS")

# ============================================================
# FEATURE ENGINEERING
# ============================================================

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

# ============================================================
# LOOKUPS
# ============================================================

person_lookup = (
    raw[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

garment_lookup = (
    raw[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

# ============================================================
# FEATURE BUILDER
# ============================================================

def make_features(person_id, product_id):

    p = person_lookup.loc[person_id]
    g = garment_lookup.loc[product_id]

    row = {}

    # --------------------------------------------------------
    # Body
    # --------------------------------------------------------

    row["height"] = p["height"]
    row["bust"] = p["bust"]
    row["waist"] = p["waist"]
    row["hips"] = p["hips"]

    # --------------------------------------------------------
    # Garment
    # --------------------------------------------------------

    row["garment_bust"] = g["garment_bust"]
    row["garment_waist"] = g["garment_waist"]
    row["garment_hip"] = g["garment_hip"]
    row["garment_length"] = g["garment_length"]
    row["garment_sleeve"] = g["garment_sleeve"]

    # --------------------------------------------------------
    # Ease
    # --------------------------------------------------------

    row["bust_ease"] = (
        g["garment_bust"] - p["bust"]
    )

    row["waist_ease"] = (
        g["garment_waist"] - p["waist"]
    )

    row["hip_ease"] = (
        g["garment_hip"] - p["hips"]
    )

    # --------------------------------------------------------
    # Ratios
    # --------------------------------------------------------

    row["bust_ratio"] = (
        g["garment_bust"] / p["bust"]
    )

    row["waist_ratio"] = (
        g["garment_waist"] / p["waist"]
    )

    row["hip_ratio"] = (
        g["garment_hip"] / p["hips"]
    )

    # --------------------------------------------------------
    # Absolute mismatch
    # --------------------------------------------------------

    row["bust_mismatch"] = abs(
        g["garment_bust"] - p["bust"]
    )

    row["waist_mismatch"] = abs(
        g["garment_waist"] - p["waist"]
    )

    row["hip_mismatch"] = abs(
        g["garment_hip"] - p["hips"]
    )

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    row["bust_relative_mismatch"] = (
        row["bust_mismatch"] / p["bust"]
    )

    row["waist_relative_mismatch"] = (
        row["waist_mismatch"] / p["waist"]
    )

    row["hip_relative_mismatch"] = (
        row["hip_mismatch"] / p["hips"]
    )

    # --------------------------------------------------------
    # Aggregate ease
    # --------------------------------------------------------

    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    valid_eases = eases[
        ~np.isnan(eases)
    ]

    if len(valid_eases) == 0:

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    else:

        row["mean_ease"] = np.mean(
            valid_eases
        )

        row["ease_std"] = np.std(
            valid_eases
        )

    row["known_fit_dimensions"] = (
        np.sum(
            ~np.isnan(eases)
        )
    )

    row["tight_dimension_count"] = (
        np.sum(
            eases < 0
        )
    )

    row["extreme_ease_count"] = (
        np.sum(
            eases > 50
        )
    )

    # --------------------------------------------------------
    # Length / height
    # --------------------------------------------------------

    if (
        pd.isna(g["garment_length"])
        or
        pd.isna(p["height"])
    ):

        row["length_height_ratio"] = np.nan

    else:

        row["length_height_ratio"] = (
            g["garment_length"]
            /
            p["height"]
        )

    return np.array(
        [
            row[f]
            for f in FEATURES
        ],
        dtype=np.float32,
    )

print("\nFeature dimension:", len(FEATURES))

# ============================================================
# PERSON-LEVEL SPLIT
# ============================================================

people = sorted(
    pairwise["person_id"].unique()
)

train_people, temp_people = train_test_split(
    people,
    test_size=16,
    random_state=SEED,
)

val_people, test_people = train_test_split(
    temp_people,
    test_size=8,
    random_state=SEED,
)

train_people = set(train_people)
val_people = set(val_people)
test_people = set(test_people)

print("\n" + "=" * 65)
print("PERSON-LEVEL SPLIT")
print("=" * 65)

print("Train people:", len(train_people))
print("Validation people:", len(val_people))
print("Test people:", len(test_people))

print("\nLeakage:")
print(
    "Train ∩ Val:",
    train_people & val_people
)
print(
    "Train ∩ Test:",
    train_people & test_people
)
print(
    "Val ∩ Test:",
    val_people & test_people
)

# ============================================================
# SPLIT PAIRWISE DATA
# ============================================================

train_df = pairwise[
    pairwise["person_id"].isin(train_people)
].copy()

val_df = pairwise[
    pairwise["person_id"].isin(val_people)
].copy()

test_df = pairwise[
    pairwise["person_id"].isin(test_people)
].copy()

print("\nPairwise rows:")
print("Train:", len(train_df))
print("Val  :", len(val_df))
print("Test :", len(test_df))

# ============================================================
# BUILD POSITIVE / NEGATIVE FEATURES
# ============================================================

def build_pair_features(frame):

    pos = []
    neg = []

    for _, row in frame.iterrows():

        pos.append(
            make_features(
                row["person_id"],
                row["positive_product_id"],
            )
        )

        neg.append(
            make_features(
                row["person_id"],
                row["negative_product_id"],
            )
        )

    return (
        np.asarray(pos, dtype=np.float32),
        np.asarray(neg, dtype=np.float32),
    )

X_pos_train, X_neg_train = build_pair_features(
    train_df
)

X_pos_val, X_neg_val = build_pair_features(
    val_df
)

X_pos_test, X_neg_test = build_pair_features(
    test_df
)

# ============================================================
# IMPUTATION
# ============================================================

imputer = SimpleImputer(
    strategy="median"
)

train_reference = np.vstack(
    [
        X_pos_train,
        X_neg_train,
    ]
)

imputer.fit(train_reference)

X_pos_train = imputer.transform(
    X_pos_train
)

X_neg_train = imputer.transform(
    X_neg_train
)

X_pos_val = imputer.transform(
    X_pos_val
)

X_neg_val = imputer.transform(
    X_neg_val
)

X_pos_test = imputer.transform(
    X_pos_test
)

X_neg_test = imputer.transform(
    X_neg_test
)

# ============================================================
# SCALING
# ============================================================

scaler = StandardScaler()

scaler.fit(
    train_reference
)

X_pos_train = scaler.transform(
    X_pos_train
)

X_neg_train = scaler.transform(
    X_neg_train
)

X_pos_val = scaler.transform(
    X_pos_val
)

X_neg_val = scaler.transform(
    X_neg_val
)

X_pos_test = scaler.transform(
    X_pos_test
)

X_neg_test = scaler.transform(
    X_neg_test
)

# ============================================================
# TENSORS
# ============================================================

def tensor(x):

    return torch.tensor(
        x,
        dtype=torch.float32,
        device=device,
    )

X_pos_train = tensor(X_pos_train)
X_neg_train = tensor(X_neg_train)

X_pos_val = tensor(X_pos_val)
X_neg_val = tensor(X_neg_val)

X_pos_test = tensor(X_pos_test)
X_neg_test = tensor(X_neg_test)

print("\n" + "=" * 65)
print("PAIRWISE TENSORS")
print("=" * 65)

print(
    "Train:",
    X_pos_train.shape
)

print(
    "Val:",
    X_pos_val.shape
)

print(
    "Test:",
    X_pos_test.shape
)

print(
    "NaN:",
    (
        torch.isnan(X_pos_train).sum()
        + torch.isnan(X_neg_train).sum()
        + torch.isnan(X_pos_val).sum()
        + torch.isnan(X_neg_val).sum()
        + torch.isnan(X_pos_test).sum()
        + torch.isnan(X_neg_test).sum()
    ).item()
)

print(
    "Inf:",
    (
        torch.isinf(X_pos_train).sum()
        + torch.isinf(X_neg_train).sum()
        + torch.isinf(X_pos_val).sum()
        + torch.isinf(X_neg_val).sum()
        + torch.isinf(X_pos_test).sum()
        + torch.isinf(X_neg_test).sum()
    ).item()
)

# ============================================================
# MODEL
# ============================================================

class CompatibilityScorer(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)


model = CompatibilityScorer(
    len(FEATURES)
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LR,
    weight_decay=WEIGHT_DECAY,
)

print("\n" + "=" * 65)
print("MODEL")
print("=" * 65)

print(
    "Input dimension:",
    len(FEATURES)
)

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)

# ============================================================
# TRUE PAIRWISE LOSS
# ============================================================

def pairwise_loss(
    positive_scores,
    negative_scores,
):

    margin = (
        positive_scores
        -
        negative_scores
    )

    return F.softplus(
        -margin
    ).mean()

# ============================================================
# TRAIN
# ============================================================

print("\n" + "=" * 65)
print("TRAINING")
print("=" * 65)

best_val_acc = -np.inf
best_state = None

for epoch in range(
    1,
    EPOCHS + 1
):

    model.train()

    optimizer.zero_grad()

    positive_scores = model(
        X_pos_train
    )

    negative_scores = model(
        X_neg_train
    )

    loss = pairwise_loss(
        positive_scores,
        negative_scores,
    )

    loss.backward()

    optimizer.step()

    # --------------------------------------------------------
    # Evaluation
    # --------------------------------------------------------

    model.eval()

    with torch.no_grad():

        train_pos = model(
            X_pos_train
        )

        train_neg = model(
            X_neg_train
        )

        val_pos = model(
            X_pos_val
        )

        val_neg = model(
            X_neg_val
        )

        train_acc = (
            train_pos > train_neg
        ).float().mean().item()

        val_acc = (
            val_pos > val_neg
        ).float().mean().item()

    # --------------------------------------------------------
    # Best checkpoint
    # --------------------------------------------------------

    if val_acc > best_val_acc:

        best_val_acc = val_acc

        best_state = {
            k: v.detach()
            .cpu()
            .clone()

            for k, v
            in model.state_dict().items()
        }

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d}/{EPOCHS} "
            f"| Loss: {loss.item():.4f} "
            f"| Train Rank Acc: {train_acc:.4f} "
            f"| Val Rank Acc: {val_acc:.4f}"
        )

# ============================================================
# RESTORE BEST CHECKPOINT
# ============================================================

model.load_state_dict(
    best_state
)

model.eval()

# ============================================================
# FINAL EVALUATION
# ============================================================

with torch.no_grad():

    train_pos = model(
        X_pos_train
    )

    train_neg = model(
        X_neg_train
    )

    val_pos = model(
        X_pos_val
    )

    val_neg = model(
        X_neg_val
    )

    test_pos = model(
        X_pos_test
    )

    test_neg = model(
        X_neg_test
    )

# ============================================================
# METRICS
# ============================================================

train_acc = (
    train_pos > train_neg
).float().mean().item()

val_acc = (
    val_pos > val_neg
).float().mean().item()

test_acc = (
    test_pos > test_neg
).float().mean().item()

train_gap = (
    train_pos - train_neg
)

val_gap = (
    val_pos - val_neg
)

test_gap = (
    test_pos - test_neg
)

# ============================================================
# FINAL RESULTS
# ============================================================

print("\n" + "=" * 65)
print("FINAL EXPERIMENT #2 RESULTS")
print("=" * 65)

print(
    "Train Ranking Accuracy :",
    f"{train_acc:.4f}"
)

print(
    "Validation Ranking Acc :",
    f"{val_acc:.4f}"
)

print(
    "Test Ranking Accuracy  :",
    f"{test_acc:.4f}"
)

print(
    "Best Validation Acc    :",
    f"{best_val_acc:.4f}"
)

print("\nScore gaps:")

print(
    "Train mean:",
    f"{train_gap.mean().item():.4f}"
)

print(
    "Validation mean:",
    f"{val_gap.mean().item():.4f}"
)

print(
    "Test mean:",
    f"{test_gap.mean().item():.4f}"
)

print(
    "Test median:",
    f"{test_gap.median().item():.4f}"
)

# ============================================================
# TEST PERFORMANCE BY NEGATIVE TYPE
# ============================================================

test_results = test_df.copy()

test_results["positive_score"] = (
    test_pos
    .detach()
    .cpu()
    .numpy()
)

test_results["negative_score"] = (
    test_neg
    .detach()
    .cpu()
    .numpy()
)

test_results["score_gap"] = (
    test_results["positive_score"]
    -
    test_results["negative_score"]
)

test_results["correct"] = (
    test_results["positive_score"]
    >
    test_results["negative_score"]
)

type_results = (
    test_results
    .groupby("negative_type")
    .agg(
        pairs=(
            "correct",
            "size"
        ),

        ranking_accuracy=(
            "correct",
            "mean"
        ),

        mean_score_gap=(
            "score_gap",
            "mean"
        ),

        median_score_gap=(
            "score_gap",
            "median"
        ),
    )
)

print("\n" + "=" * 65)
print("TEST PERFORMANCE BY NEGATIVE TYPE")
print("=" * 65)

print(
    type_results
)

# ============================================================
# SAVE MODEL
# ============================================================

torch.save(
    {
        "model_state_dict":
            model.state_dict(),

        "input_dim":
            len(FEATURES),

        "feature_names":
            FEATURES,

        "experiment":
            "V2_EXP2_FINAL_TRUE_PAIRWISE",

        "negative_sampling":
            "1:1:1",

        "negative_types":
            [
                "hard",
                "semi-hard",
                "random",
            ],

        "train_people":
            sorted(train_people),

        "val_people":
            sorted(val_people),

        "test_people":
            sorted(test_people),

        "seed":
            SEED,
    },
    MODEL_PATH,
)

print("\n" + "=" * 65)
print("MODEL SAVED")
print("=" * 65)

print(
    MODEL_PATH
)

print("\n" + "=" * 65)
print("EXPERIMENT #2 TRAINING COMPLETE")
print("=" * 65)

=================================================================
ZYRA V2 — EXPERIMENT #2 FINAL TRUE PAIRWISE TRAINING
=================================================================
Device: mps

Pairwise rows: 8970
People: 56

Negative types:
negative_type
hard         2990
semi-hard    2990
random       2990
Name: count, dtype: int64

=================================================================
INPUT DATASET VALIDATION
=================================================================
Positive interactions: 2990
Hard negatives: 2990
Semi-hard negatives: 2990
Random negatives: 2990
Total rows: 8970

1:1:1 DATASET: PASS

Feature dimension: 27

=================================================================
PERSON-LEVEL SPLIT
=================================================================
Train people: 40
Validation people: 8
Test people: 8

Leakage:
Train ∩ Val: set()
Train ∩ Test: set()
Val ∩ Test: set()

Pairwise rows:
Train: 6810
Val  : 1143
Test : 1017

=================================================================
PAIRWISE TENSORS
=================================================================
Train: torch.Size([6810, 27])
Val: torch.Size([1143, 27])
Test: torch.Size([1017, 27])
NaN: 0
Inf: 0

=================================================================
MODEL
=================================================================
Input dimension: 27
Parameters: 3905

=================================================================
TRAINING
=================================================================
Epoch 01/50 | Loss: 0.6957 | Train Rank Acc: 0.5075 | Val Rank Acc: 0.6115
Epoch 05/50 | Loss: 0.6814 | Train Rank Acc: 0.6043 | Val Rank Acc: 0.7375
Epoch 10/50 | Loss: 0.6675 | Train Rank Acc: 0.6166 | Val Rank Acc: 0.7367
Epoch 15/50 | Loss: 0.6560 | Train Rank Acc: 0.6217 | Val Rank Acc: 0.7367
Epoch 20/50 | Loss: 0.6456 | Train Rank Acc: 0.6270 | Val Rank Acc: 0.7358
Epoch 25/50 | Loss: 0.6362 | Train Rank Acc: 0.6333 | Val Rank Acc: 0.7323
Epoch 30/50 | Loss: 0.6285 | Train Rank Acc: 0.6414 | Val Rank Acc: 0.7305
Epoch 35/50 | Loss: 0.6223 | Train Rank Acc: 0.6558 | Val Rank Acc: 0.7332
Epoch 40/50 | Loss: 0.6170 | Train Rank Acc: 0.6630 | Val Rank Acc: 0.7262
Epoch 45/50 | Loss: 0.6118 | Train Rank Acc: 0.6711 | Val Rank Acc: 0.7165
Epoch 50/50 | Loss: 0.6067 | Train Rank Acc: 0.6750 | Val Rank Acc: 0.7017

=================================================================
FINAL EXPERIMENT #2 RESULTS
=================================================================
Train Ranking Accuracy : 0.6279
Validation Ranking Acc : 0.7384
Test Ranking Accuracy  : 0.6342
Best Validation Acc    : 0.7384

Score gaps:
Train mean: 0.1861
Validation mean: 0.3107
Test mean: 0.1923
Test median: 0.1655

=================================================================
TEST PERFORMANCE BY NEGATIVE TYPE
=================================================================
               pairs  ranking_accuracy  mean_score_gap  median_score_gap
negative_type
hard             339          0.861357        0.527458          0.590724
random           339          0.294985       -0.193847         -0.156871
semi-hard        339          0.746313        0.243335          0.243672

=================================================================
MODEL SAVED
=================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_pairwise_ranker_exp2_final.pt

=================================================================
EXPERIMENT #2 TRAINING COMPLETE
=================================================================

In [70]:
# ============================================================
# ZYRA V2 — EXPERIMENT #2 RANKING DIAGNOSTIC
# ============================================================
#
# Purpose:
#   Understand why:
#       HARD       -> 86.14%
#       SEMI-HARD  -> 74.63%
#       RANDOM     -> 29.50%
#
# This cell:
#   1. Loads the saved Experiment #2 model
#   2. Recreates the SAME test split
#   3. Scores positive / hard / semi-hard / random garments
#   4. Finds cases where random negatives beat positives
#   5. Compares physical compatibility features
#   6. Reports per-person behaviour
#
# NO TRAINING.
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

PAIRWISE_PATH = (
    BASE /
    "data/v2/v2_negative_sampling_1to1to1.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_pairwise_ranker_exp2_final.pt"
)

# ============================================================
# CONFIG
# ============================================================

SEED = 42

np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("=" * 70)
print("ZYRA V2 — EXPERIMENT #2 RANKING DIAGNOSTIC")
print("=" * 70)

print("Device:", device)

# ============================================================
# LOAD
# ============================================================

pairwise = pd.read_csv(
    PAIRWISE_PATH
)

raw = pd.read_csv(
    RAW_PATH
)

print(
    "\nPairwise rows:",
    len(pairwise)
)

print(
    "People:",
    pairwise["person_id"].nunique()
)

# ============================================================
# FEATURES
# ============================================================

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

# ============================================================
# LOOKUPS
# ============================================================

person_lookup = (
    raw[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

garment_lookup = (
    raw[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

# ============================================================
# FEATURE FUNCTION
# ============================================================

def make_features(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    row = {}

    # --------------------------------------------------------
    # Body
    # --------------------------------------------------------

    row["height"] = p["height"]
    row["bust"] = p["bust"]
    row["waist"] = p["waist"]
    row["hips"] = p["hips"]

    # --------------------------------------------------------
    # Garment
    # --------------------------------------------------------

    row["garment_bust"] = g["garment_bust"]
    row["garment_waist"] = g["garment_waist"]
    row["garment_hip"] = g["garment_hip"]
    row["garment_length"] = g["garment_length"]
    row["garment_sleeve"] = g["garment_sleeve"]

    # --------------------------------------------------------
    # Ease
    # --------------------------------------------------------

    row["bust_ease"] = (
        g["garment_bust"]
        -
        p["bust"]
    )

    row["waist_ease"] = (
        g["garment_waist"]
        -
        p["waist"]
    )

    row["hip_ease"] = (
        g["garment_hip"]
        -
        p["hips"]
    )

    # --------------------------------------------------------
    # Ratios
    # --------------------------------------------------------

    row["bust_ratio"] = (
        g["garment_bust"]
        /
        p["bust"]
    )

    row["waist_ratio"] = (
        g["garment_waist"]
        /
        p["waist"]
    )

    row["hip_ratio"] = (
        g["garment_hip"]
        /
        p["hips"]
    )

    # --------------------------------------------------------
    # Mismatch
    # --------------------------------------------------------

    row["bust_mismatch"] = abs(
        g["garment_bust"]
        -
        p["bust"]
    )

    row["waist_mismatch"] = abs(
        g["garment_waist"]
        -
        p["waist"]
    )

    row["hip_mismatch"] = abs(
        g["garment_hip"]
        -
        p["hips"]
    )

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    row["bust_relative_mismatch"] = (
        row["bust_mismatch"]
        /
        p["bust"]
    )

    row["waist_relative_mismatch"] = (
        row["waist_mismatch"]
        /
        p["waist"]
    )

    row["hip_relative_mismatch"] = (
        row["hip_mismatch"]
        /
        p["hips"]
    )

    # --------------------------------------------------------
    # Aggregate ease
    # --------------------------------------------------------

    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    valid = eases[
        ~np.isnan(eases)
    ]

    if len(valid) == 0:

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    else:

        row["mean_ease"] = np.mean(
            valid
        )

        row["ease_std"] = np.std(
            valid
        )

    row["known_fit_dimensions"] = (
        np.sum(
            ~np.isnan(eases)
        )
    )

    row["tight_dimension_count"] = (
        np.sum(
            eases < 0
        )
    )

    row["extreme_ease_count"] = (
        np.sum(
            eases > 50
        )
    )

    # --------------------------------------------------------
    # Length
    # --------------------------------------------------------

    if (
        pd.isna(
            g["garment_length"]
        )
        or
        pd.isna(
            p["height"]
        )
    ):

        row[
            "length_height_ratio"
        ] = np.nan

    else:

        row[
            "length_height_ratio"
        ] = (
            g["garment_length"]
            /
            p["height"]
        )

    return np.array(
        [
            row[f]
            for f in FEATURES
        ],
        dtype=np.float32,
    )

# ============================================================
# RECREATE EXACT PERSON SPLIT
# ============================================================

people = sorted(
    pairwise[
        "person_id"
    ].unique()
)

train_people, temp_people = (
    train_test_split(
        people,
        test_size=16,
        random_state=SEED,
    )
)

val_people, test_people = (
    train_test_split(
        temp_people,
        test_size=8,
        random_state=SEED,
    )
)

test_people = set(
    test_people
)

print("\n" + "=" * 70)
print("TEST PEOPLE")
print("=" * 70)

print(
    sorted(test_people)
)

# ============================================================
# TEST DATA
# ============================================================

test_df = pairwise[
    pairwise[
        "person_id"
    ].isin(
        test_people
    )
].copy()

print(
    "\nTest rows:",
    len(test_df)
)

# ============================================================
# BUILD TEST FEATURES
# ============================================================

positive_features = []
negative_features = []

for _, row in test_df.iterrows():

    positive_features.append(
        make_features(
            row["person_id"],
            row["positive_product_id"],
        )
    )

    negative_features.append(
        make_features(
            row["person_id"],
            row["negative_product_id"],
        )
    )

positive_features = np.asarray(
    positive_features,
    dtype=np.float32,
)

negative_features = np.asarray(
    negative_features,
    dtype=np.float32,
)

# ============================================================
# IMPUTE
# ============================================================

imputer = SimpleImputer(
    strategy="median"
)

# ------------------------------------------------------------
# IMPORTANT:
# Refit only using training people.
# ------------------------------------------------------------

train_df = pairwise[
    pairwise[
        "person_id"
    ].isin(
        set(train_people)
    )
].copy()

train_pos = []
train_neg = []

for _, row in train_df.iterrows():

    train_pos.append(
        make_features(
            row["person_id"],
            row["positive_product_id"],
        )
    )

    train_neg.append(
        make_features(
            row["person_id"],
            row["negative_product_id"],
        )
    )

train_reference = np.vstack(
    [
        np.asarray(
            train_pos,
            dtype=np.float32,
        ),
        np.asarray(
            train_neg,
            dtype=np.float32,
        ),
    ]
)

imputer.fit(
    train_reference
)

positive_features = imputer.transform(
    positive_features
)

negative_features = imputer.transform(
    negative_features
)

# ============================================================
# SCALE
# ============================================================

scaler = StandardScaler()

scaler.fit(
    train_reference
)

positive_features = scaler.transform(
    positive_features
)

negative_features = scaler.transform(
    negative_features
)

# ============================================================
# MODEL
# ============================================================

class CompatibilityScorer(
    nn.Module
):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(
        self,
        x,
    ):

        return self.network(
            x
        ).squeeze(-1)

# ============================================================
# LOAD MODEL
# ============================================================

checkpoint = torch.load(
    MODEL_PATH,
    map_location=device,
    weights_only=False,
)

model = CompatibilityScorer(
    len(FEATURES)
).to(device)

model.load_state_dict(
    checkpoint[
        "model_state_dict"
    ]
)

model.eval()

print(
    "\nModel loaded."
)

# ============================================================
# SCORE
# ============================================================

pos_tensor = torch.tensor(
    positive_features,
    dtype=torch.float32,
    device=device,
)

neg_tensor = torch.tensor(
    negative_features,
    dtype=torch.float32,
    device=device,
)

with torch.no_grad():

    pos_scores = (
        model(
            pos_tensor
        )
        .detach()
        .cpu()
        .numpy()
    )

    neg_scores = (
        model(
            neg_tensor
        )
        .detach()
        .cpu()
        .numpy()
    )

test_df[
    "positive_score"
] = pos_scores

test_df[
    "negative_score"
] = neg_scores

test_df[
    "score_gap"
] = (
    test_df[
        "positive_score"
    ]
    -
    test_df[
        "negative_score"
    ]
)

test_df[
    "correct"
] = (
    test_df[
        "positive_score"
    ]
    >
    test_df[
        "negative_score"
    ]
)

# ============================================================
# OVERALL RESULTS
# ============================================================

print("\n" + "=" * 70)
print("OVERALL TEST DIAGNOSTIC")
print("=" * 70)

print(
    "Positive mean:",
    f"{pos_scores.mean():.6f}"
)

print(
    "Negative mean:",
    f"{neg_scores.mean():.6f}"
)

print(
    "Mean score gap:",
    f"{(pos_scores - neg_scores).mean():.6f}"
)

print(
    "Ranking accuracy:",
    f"{(pos_scores > neg_scores).mean():.4f}"
)

# ============================================================
# BY TYPE
# ============================================================

print("\n" + "=" * 70)
print("PER NEGATIVE TYPE")
print("=" * 70)

type_stats = (
    test_df
    .groupby(
        "negative_type"
    )
    .agg(
        pairs=(
            "correct",
            "size",
        ),

        ranking_accuracy=(
            "correct",
            "mean",
        ),

        positive_score=(
            "positive_score",
            "mean",
        ),

        negative_score=(
            "negative_score",
            "mean",
        ),

        mean_gap=(
            "score_gap",
            "mean",
        ),

        median_gap=(
            "score_gap",
            "median",
        ),
    )
)

print(
    type_stats
)

# ============================================================
# RANDOM FAILURES
# ============================================================

random_failures = test_df[
    (
        test_df[
            "negative_type"
        ]
        ==
        "random"
    )
    &
    (
        test_df[
            "negative_score"
        ]
        >=
        test_df[
            "positive_score"
        ]
    )
].copy()

print("\n" + "=" * 70)
print("RANDOM NEGATIVES BEATING POSITIVES")
print("=" * 70)

print(
    "Failures:",
    len(random_failures)
)

print(
    "Total random:",
    (
        test_df[
            "negative_type"
        ]
        ==
        "random"
    ).sum()
)

print(
    "Failure rate:",
    f"{len(random_failures) / max(1, (test_df['negative_type'] == 'random').sum()):.4f}"
)

# ============================================================
# WORST RANDOM FAILURES
# ============================================================

print("\n" + "=" * 70)
print("WORST RANDOM FAILURES")
print("=" * 70)

worst_random = (
    random_failures
    .sort_values(
        "score_gap"
    )
)

display(
    worst_random[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "negative_distance",
            "positive_score",
            "negative_score",
            "score_gap",
        ]
    ]
    .head(30)
)

# ============================================================
# BEST RANDOM NEGATIVES
# ============================================================

print("\n" + "=" * 70)
print("RANDOM NEGATIVES CORRECTLY REJECTED")
print("=" * 70)

random_correct = test_df[
    (
        test_df[
            "negative_type"
        ]
        ==
        "random"
    )
    &
    (
        test_df[
            "positive_score"
        ]
        >
        test_df[
            "negative_score"
        ]
    )
].copy()

display(
    random_correct[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "negative_distance",
            "positive_score",
            "negative_score",
            "score_gap",
        ]
    ]
    .sort_values(
        "score_gap"
    )
    .head(20)
)

# ============================================================
# PHYSICAL FEATURE COMPARISON
# ============================================================

diagnostic_features = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "mean_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "length_height_ratio",
    "garment_sleeve",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",
]

# ============================================================
# CREATE FEATURE DATAFRAME
# ============================================================

feature_rows = []

for _, row in test_df.iterrows():

    positive_raw = make_features(
        row["person_id"],
        row["positive_product_id"],
    )

    negative_raw = make_features(
        row["person_id"],
        row["negative_product_id"],
    )

    item = {
        "person_id":
            row["person_id"],

        "negative_type":
            row["negative_type"],

        "score_gap":
            row["score_gap"],

        "correct":
            row["correct"],
    }

    for feature_name in diagnostic_features:

        idx = FEATURES.index(
            feature_name
        )

        item[
            "pos_" + feature_name
        ] = positive_raw[idx]

        item[
            "neg_" + feature_name
        ] = negative_raw[idx]

        item[
            "diff_" + feature_name
        ] = (
            positive_raw[idx]
            -
            negative_raw[idx]
        )

    feature_rows.append(
        item
    )

feature_df = pd.DataFrame(
    feature_rows
)

# ============================================================
# RANDOM FAILURE FEATURE ANALYSIS
# ============================================================

random_feature_df = feature_df[
    feature_df[
        "negative_type"
    ]
    ==
    "random"
].copy()

random_failure_features = (
    random_feature_df[
        random_feature_df[
            "correct"
        ]
        ==
        False
    ]
)

random_success_features = (
    random_feature_df[
        random_feature_df[
            "correct"
        ]
        ==
        True
    ]
)

print("\n" + "=" * 70)
print("RANDOM FAILURE FEATURE COMPARISON")
print("=" * 70)

comparison_rows = []

for feature in diagnostic_features:

    failure_mean = (
        random_failure_features[
            "diff_" + feature
        ]
        .mean()
    )

    success_mean = (
        random_success_features[
            "diff_" + feature
        ]
        .mean()
    )

    comparison_rows.append(
        {
            "feature":
                feature,

            "failure_mean_diff":
                failure_mean,

            "success_mean_diff":
                success_mean,

            "difference":
                failure_mean
                -
                success_mean,
        }
    )

comparison_df = (
    pd.DataFrame(
        comparison_rows
    )
    .sort_values(
        "difference",
        ascending=False,
    )
)

display(
    comparison_df
)

# ============================================================
# PER PERSON
# ============================================================

print("\n" + "=" * 70)
print("PER-PERSON RANDOM PERFORMANCE")
print("=" * 70)

random_person = (
    test_df[
        test_df[
            "negative_type"
        ]
        ==
        "random"
    ]
    .groupby(
        "person_id"
    )
    .agg(
        pairs=(
            "correct",
            "size",
        ),

        accuracy=(
            "correct",
            "mean",
        ),

        mean_gap=(
            "score_gap",
            "mean",
        ),

        median_gap=(
            "score_gap",
            "median",
        ),
    )
    .sort_values(
        "accuracy"
    )
)

display(
    random_person
)

# ============================================================
# SCORE DISTRIBUTIONS
# ============================================================

print("\n" + "=" * 70)
print("SCORE DISTRIBUTION")
print("=" * 70)

for negative_type in [
    "hard",
    "semi-hard",
    "random",
]:

    subset = test_df[
        test_df[
            "negative_type"
        ]
        ==
        negative_type
    ]

    print(
        f"\n{negative_type.upper()}"
    )

    print(
        "Positive score:"
    )

    print(
        subset[
            "positive_score"
        ]
        .describe()
    )

    print(
        "Negative score:"
    )

    print(
        subset[
            "negative_score"
        ]
        .describe()
    )

# ============================================================
# FINAL INTERPRETATION FLAGS
# ============================================================

random_accuracy = (
    test_df[
        test_df[
            "negative_type"
        ]
        ==
        "random"
    ][
        "correct"
    ]
    .mean()
)

hard_accuracy = (
    test_df[
        test_df[
            "negative_type"
        ]
        ==
        "hard"
    ][
        "correct"
    ]
    .mean()
)

semi_accuracy = (
    test_df[
        test_df[
            "negative_type"
        ]
        ==
        "semi-hard"
    ][
        "correct"
    ]
    .mean()
)

print("\n" + "=" * 70)
print("DIAGNOSTIC SUMMARY")
print("=" * 70)

print(
    f"Hard accuracy      : {hard_accuracy:.4f}"
)

print(
    f"Semi-hard accuracy : {semi_accuracy:.4f}"
)

print(
    f"Random accuracy    : {random_accuracy:.4f}"
)

print(
    f"Random failure rate: {1 - random_accuracy:.4f}"
)

print("\nInterpretation:")

if random_accuracy < 0.50:

    print(
        "CRITICAL: model systematically "
        "prefers many unseen random negatives."
    )

elif random_accuracy < 0.65:

    print(
        "WEAK: random-negative "
        "generalization is insufficient."
    )

else:

    print(
        "ACCEPTABLE: random-negative "
        "generalization is reasonable."
    )

if (
    hard_accuracy > 0.80
    and
    random_accuracy < 0.50
):

    print(
        "\nIMPORTANT:"
    )

    print(
        "The model is strongly sensitive "
        "to local physical similarity but "
        "does not learn a robust global "
        "compatibility function."
    )

print(
    "\nDiagnostic complete."
)

======================================================================
ZYRA V2 — EXPERIMENT #2 RANKING DIAGNOSTIC
======================================================================
Device: mps

Pairwise rows: 8970
People: 56

======================================================================
TEST PEOPLE
======================================================================
['Alex', 'Anna Maria', 'Bree', 'Chesska', 'Emma', 'Maddy', 'Palatina', 'Sophie']

Test rows: 1017

Model loaded.

======================================================================
OVERALL TEST DIAGNOSTIC
======================================================================
Positive mean: 0.055910
Negative mean: -0.136406
Mean score gap: 0.192315
Ranking accuracy: 0.6342

======================================================================
PER NEGATIVE TYPE
======================================================================
               pairs  ranking_accuracy  positive_score  negative_score  \
negative_type
hard             339          0.861357         0.05591       -0.471548
random           339          0.294985         0.05591        0.249757
semi-hard        339          0.746313         0.05591       -0.187425

               mean_gap  median_gap
negative_type
hard           0.527458    0.590724
random        -0.193847   -0.156871
semi-hard      0.243335    0.243672

======================================================================
RANDOM NEGATIVES BEATING POSITIVES
======================================================================
Failures: 239
Total random: 339
Failure rate: 0.7050

======================================================================
WORST RANDOM FAILURES
======================================================================

,person_id,positive_product_id,negative_product_id,negative_distance,positive_score,negative_score,score_gap
7298,Palatina,the-boat-neck-top#Navy,triangle-detail-long-sleeve-tee#Bordeaux,0.418352,-1.365466,0.163153,-1.528619
7295,Palatina,the-boat-neck-top#Black,cross-my-heart-sweater#Regal,0.406056,-1.365466,-0.074988,-1.290478
7280,Palatina,pure-merino-fine-rib-v-neck#Charcoal,spot-layered-tee#Blue,0.442562,-1.044073,0.128765,-1.172839
1106,Chesska,soho-ruffle-jumper#OatmealMar,meredith-78-oversized-pullover-knit#WhiteCapGr,0.965270,-0.512140,0.552429,-1.064569
1097,Chesska,dream-girl-ruffle-jumper#SoftPink,relaxed-animal-print-blouse#Leopard,0.612767,-0.804989,0.254172,-1.059161
23,Alex,the-batwing-tee#Stone,on-the-horizon-swing-top-1#Khaki,0.908081,-0.371437,0.683120,-1.054557
5273,Maddy,the-long-sleeve-v-neck-tee#White,the-button-up-swing-tunic#Wine,0.766677,-0.535841,0.505838,-1.041679
50,Alex,the-cotton-bamboo-tee#White,the-check-pullover#PinkCheck,1.112077,-0.139734,0.896939,-1.036673
5144,Maddy,saba-top-2#Catus,the-on-or-off-the-shoulder-top#FrenchNavy,0.720585,-0.659649,0.336513,-0.996162
7205,Palatina,collared-shirt-1#White,the-bonded-cotton-tunic-dress#Navy,0.461234,-0.569074,0.418409,-0.987483
5162,Maddy,the-batwing-tee#Stone,belle-flocked-tunic#White,0.826866,-0.383345,0.600524,-0.983869
1391,Emma,aztec-cardigan#BlackIvory,beach-walk-shirt#Khaki,0.823755,-0.344814,0.637205,-0.982019
5291,Maddy,the-short-sleeve-wrap-jersey-top#Black,the-high-low-drape-tee#Grey,0.583806,-0.544107,0.421398,-0.965506
5123,Maddy,elina-lace-frill-blouse#Black,chasing-birds-blouse#White,0.562386,-0.766060,0.171385,-0.937446
1433,Emma,block-vest#Blockvest,the-double-layer-top#White,0.797859,-0.495308,0.429341,-0.924649
5141,Maddy,pulkari-emb-top#Pulkari,contrast-pocket-tunic#Pinkpocket,0.775428,-0.548343,0.351161,-0.899504
77,Alex,the-short-sleeve-wrap-jersey-top#Black,oversize-contrast-hood-top#Steel,0.900448,-0.358764,0.515034,-0.873798
5252,Maddy,the-half-sleeve-tee#White,the-oversized-cotton-blend-shirt#Sand,0.836907,-0.304502,0.561981,-0.866483
14,Alex,the-batwing-tee#Black,tab-sleeve-longline-shirt#Navy,0.771538,-0.371437,0.489247,-0.860684
1454,Emma,everyday-linen-tunic#BotanicalB,falling-flowers-cardi#GreyMarle,0.676170,-0.386879,0.471724,-0.858603
5126,Maddy,long-sleeve-tee-2#NavyWhite,cross-over-top-with-pocket#Emerald,0.550635,-0.765189,0.044947,-0.810135
1460,Emma,forget-me-knot-tunic#ForgetMeK,belle-handkerchief-printed-cami#RustFlwrs,0.776900,-0.352856,0.456728,-0.809583
737,Anna Maria,the-cross-over-top#NavyStripe,open-plains-kimono-throw-1#Rust,1.115934,0.235989,1.022832,-0.786843
1625,Emma,the-relaxed-long-sleeve-tee#Navy,flow-with-me-slouch-top#Brick,1.140680,0.161363,0.947737,-0.786374
5294,Maddy,the-short-sleeve-wrap-jersey-top#Blue,the-luxe-long-sleeve-tee#GreyMarle,0.564332,-0.544107,0.238037,-0.782145
7259,Palatina,merino-boyfriend-cardigan#MelangeStr,the-daily-essential-jumper#Grey,0.522362,-0.701845,0.060067,-0.761912
7283,Palatina,reversible-stripe-vee-scoop-neck-tank#BlackWhite,the-cotton-bamboo-tank#DuckEgg,0.407463,-0.635629,0.119555,-0.755184
5129,Maddy,marjorie-tie-blouse#BluePrint,the-cosy-cardigan#Grey,0.570551,-0.376884,0.376660,-0.753544
17,Alex,the-batwing-tee#FrenchBlue,contrast-stripe-sweater#Pockets,0.749363,-0.371437,0.376354,-0.747791
7211,Palatina,falling-flowers-blouse#DustyPink,for-the-frill-top#Ivory,0.472368,-0.574440,0.173214,-0.747654

======================================================================
RANDOM NEGATIVES CORRECTLY REJECTED
======================================================================

,person_id,positive_product_id,negative_product_id,negative_distance,positive_score,negative_score,score_gap
74,Alex,the-cross-over-blouse#White,sugar-snaps-round-neck-layer-tank#Black,0.728872,0.335890,0.333991,0.001899
1511,Emma,long-sleeve-softly-swinging-bamboo-tee#SilverScon,placement-print-shirt#WhiteNavy,0.624728,0.216187,0.212143,0.004044
698,Anna Maria,falling-for-you-cardi#Black,skipping-stones-tunic#Forest,0.720203,0.355254,0.347597,0.007658
8060,Sophie,falling-for-you-tunic#Rust,the-lace-trim-top#Ivory,0.274068,0.207020,0.198918,0.008102
7265,Palatina,moonlight-kisses-bamboo-tee#Combat,crosses-jumper#xmyheart,0.437942,0.147235,0.135026,0.012209
8117,Sophie,the-contrast-panel-top#BlkStripe,the-pocket-tee#NavyStripe,0.294499,0.203333,0.188481,0.014852
1538,Emma,printed-tunic-7#RedCheck,the-flutter-sleeve-top#SnakePrint,0.638931,0.325138,0.306424,0.018714
110,Alex,viola-kimono-radiant-floral#Grey,the-define-flute-sleeve-blouse#Black,0.620854,0.194477,0.170222,0.024255
5282,Maddy,the-relaxed-long-sleeve-tee#Navy,cross-my-heart-sweater#Regal,0.550681,0.122256,0.097089,0.025168
8135,Sophie,the-daily-cross-over-top#SkyBlue,sky-shirt#Clouds,0.358247,0.195409,0.168680,0.026729
68,Alex,the-cross-over-blouse#Silver,the-flutter-sleeve-top#SnakePrint,0.638931,0.335890,0.306424,0.029466
731,Anna Maria,the-belle-sleeve-print-top#NavyPrint,the-cross-over-blouse#Black,0.658609,0.351987,0.319357,0.032630
1607,Emma,the-drape-tee-1#Stripe,the-cross-over-blouse#Silver,0.666210,0.372441,0.335890,0.036551
1469,Emma,hem-frill-stripe-top#SoFrilled,the-daily-cross-over-top#SkyBlue,0.632184,0.263605,0.224110,0.039495
1613,Emma,the-pocket-tee#GreyStripe,partly-cloudy-knit#Black,0.779113,0.258418,0.218303,0.040115
7232,Palatina,falling-for-you-cardi#Port,billow-top#Black,0.615980,0.519877,0.477645,0.042232
1424,Emma,belle-v-neck-forgiver-tunic#Tobacco,layered-stripe-top#PinkStripe,0.627704,0.209911,0.161787,0.048123
1556,Emma,stripe-me-happy-blouse#Ash,sky-jumper-1#Clouds,0.686884,0.251238,0.202618,0.048620
1601,Emma,the-drape-tee-1#Navy,the-zip-front-blouse#Navy,0.792882,0.372441,0.323463,0.048977
1436,Emma,contrast-pocket-tunic#Pinkpocket,the-twist-front-top#Navy,0.814012,0.413058,0.363195,0.049863

======================================================================
RANDOM FAILURE FEATURE COMPARISON
======================================================================

                    feature  failure_mean_diff  success_mean_diff  difference
15     known_fit_dimensions           0.179916          -0.420000    0.599916
16    tight_dimension_count           0.121339          -0.190000    0.311339
13      length_height_ratio           0.000114           0.094292   -0.094178
12    hip_relative_mismatch          -0.211106           0.023456   -0.234562
10   bust_relative_mismatch          -0.219384           0.073204   -0.292588
6                 hip_ratio          -0.221304           0.081537   -0.302841
4                bust_ratio          -0.230084           0.097240   -0.327324
11  waist_relative_mismatch          -0.294613           0.111324   -0.405937
5               waist_ratio          -0.305576           0.130555   -0.436131
17       extreme_ease_count          -0.979079          -0.050000   -0.929079
14           garment_sleeve          -0.261438           7.268657   -7.530095
9              hip_mismatch         -20.503067           1.875000  -22.378067
7             bust_mismatch         -19.322727           6.604939  -25.927666
8            waist_mismatch         -20.868965           8.159091  -29.028057
0                 bust_ease         -20.395454           9.320988  -29.716442
2                  hip_ease         -21.423313           9.541667  -30.964981
3                 mean_ease         -21.809626           9.395061  -31.204685
1                waist_ease         -21.779310          10.159091  -31.938400

======================================================================
PER-PERSON RANDOM PERFORMANCE
======================================================================

            pairs  accuracy  mean_gap  median_gap
person_id
Chesska        11  0.090909 -0.540591   -0.591407
Maddy          77  0.129870 -0.321657   -0.227564
Alex           37  0.216216 -0.290894   -0.198929
Emma           87  0.287356 -0.196011   -0.136158
Bree            6  0.333333 -0.122879   -0.082555
Sophie         54  0.351852 -0.031793   -0.201069
Palatina       49  0.428571 -0.106569   -0.060872
Anna Maria     18  0.777778  0.027330    0.089890

======================================================================
SCORE DISTRIBUTION
======================================================================

HARD
Positive score:
count    339.000000
mean       0.055910
std        0.321953
min       -1.365466
25%       -0.099698
50%        0.147235
75%        0.256945
max        0.760625
Name: positive_score, dtype: float64
Negative score:
count    339.000000
mean      -0.471548
std        0.330701
min       -1.315971
25%       -0.694419
50%       -0.516455
75%       -0.324177
max        0.482283
Name: negative_score, dtype: float64

SEMI-HARD
Positive score:
count    339.000000
mean       0.055910
std        0.321953
min       -1.365466
25%       -0.099698
50%        0.147235
75%        0.256945
max        0.760625
Name: positive_score, dtype: float64
Negative score:
count    339.000000
mean      -0.187425
std        0.338563
min       -1.327347
25%       -0.348799
50%       -0.102850
75%        0.044227
max        0.633639
Name: negative_score, dtype: float64

RANDOM
Positive score:
count    339.000000
mean       0.055910
std        0.321953
min       -1.365466
25%       -0.099698
50%        0.147235
75%        0.256945
max        0.760625
Name: positive_score, dtype: float64
Negative score:
count    339.000000
mean       0.249757
std        0.287492
min       -1.250192
25%        0.143309
50%        0.248458
75%        0.380655
max        1.022832
Name: negative_score, dtype: float64

======================================================================
DIAGNOSTIC SUMMARY
======================================================================
Hard accuracy      : 0.8614
Semi-hard accuracy : 0.7463
Random accuracy    : 0.2950
Random failure rate: 0.7050

Interpretation:
CRITICAL: model systematically prefers many unseen random negatives.

IMPORTANT:
The model is strongly sensitive to local physical similarity but does not learn a robust global compatibility function.

Diagnostic complete.

In [71]:
# ============================================================
# ZYRA V2 — NEGATIVE LABEL VALIDITY AUDIT
# ============================================================
#
# Goal:
# Determine whether "negative" garments are actually
# physically less compatible than positive garments.
#
# NO MODEL TRAINING.
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

from scipy.stats import mannwhitneyu
from sklearn.metrics import roc_auc_score

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

PAIRWISE_PATH = (
    BASE /
    "data/v2/v2_negative_sampling_1to1to1.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

# ============================================================
# LOAD
# ============================================================

pairwise = pd.read_csv(
    PAIRWISE_PATH
)

raw = pd.read_csv(
    RAW_PATH
)

print("=" * 70)
print("ZYRA V2 — NEGATIVE LABEL VALIDITY AUDIT")
print("=" * 70)

print(
    "Pairwise rows:",
    len(pairwise)
)

print(
    "People:",
    pairwise["person_id"].nunique()
)

# ============================================================
# LOOKUPS
# ============================================================

person_lookup = (
    raw[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

garment_lookup = (
    raw[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

# ============================================================
# PHYSICAL COMPATIBILITY FUNCTION
# ============================================================

def compatibility_features(
    person_id,
    product_id,
):

    p = person_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    # --------------------------------------------------------
    # Raw ease
    # --------------------------------------------------------

    bust_ease = (
        g["garment_bust"]
        - p["bust"]
    )

    waist_ease = (
        g["garment_waist"]
        - p["waist"]
    )

    hip_ease = (
        g["garment_hip"]
        - p["hips"]
    )

    # --------------------------------------------------------
    # Ratios
    # --------------------------------------------------------

    bust_ratio = (
        g["garment_bust"]
        / p["bust"]
    )

    waist_ratio = (
        g["garment_waist"]
        / p["waist"]
    )

    hip_ratio = (
        g["garment_hip"]
        / p["hips"]
    )

    # --------------------------------------------------------
    # Absolute mismatch
    # --------------------------------------------------------

    bust_mismatch = abs(
        g["garment_bust"]
        - p["bust"]
    )

    waist_mismatch = abs(
        g["garment_waist"]
        - p["waist"]
    )

    hip_mismatch = abs(
        g["garment_hip"]
        - p["hips"]
    )

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    bust_relative = (
        bust_mismatch
        /
        p["bust"]
    )

    waist_relative = (
        waist_mismatch
        /
        p["waist"]
    )

    hip_relative = (
        hip_mismatch
        /
        p["hips"]
    )

    # --------------------------------------------------------
    # Aggregate mismatch
    # --------------------------------------------------------

    mismatches = np.array(
        [
            bust_relative,
            waist_relative,
            hip_relative,
        ],
        dtype=float,
    )

    valid_mismatches = (
        mismatches[
            ~np.isnan(
                mismatches
            )
        ]
    )

    if len(valid_mismatches) > 0:

        mean_relative_mismatch = (
            np.mean(
                valid_mismatches
            )
        )

        mismatch_std = (
            np.std(
                valid_mismatches
            )
        )

    else:

        mean_relative_mismatch = np.nan
        mismatch_std = np.nan

    # --------------------------------------------------------
    # Ease aggregate
    # --------------------------------------------------------

    eases = np.array(
        [
            bust_ease,
            waist_ease,
            hip_ease,
        ],
        dtype=float,
    )

    valid_eases = (
        eases[
            ~np.isnan(
                eases
            )
        ]
    )

    if len(valid_eases) > 0:

        mean_ease = np.mean(
            valid_eases
        )

        ease_std = np.std(
            valid_eases
        )

    else:

        mean_ease = np.nan
        ease_std = np.nan

    # --------------------------------------------------------
    # Tight dimensions
    # --------------------------------------------------------

    tight_count = np.sum(
        eases < 0
    )

    # --------------------------------------------------------
    # Extreme ease
    # --------------------------------------------------------

    extreme_count = np.sum(
        eases > 50
    )

    # --------------------------------------------------------
    # Length ratio
    # --------------------------------------------------------

    if (
        pd.isna(
            g["garment_length"]
        )
        or
        pd.isna(
            p["height"]
        )
    ):

        length_ratio = np.nan

    else:

        length_ratio = (
            g["garment_length"]
            /
            p["height"]
        )

    return {
        "bust_ease":
            bust_ease,

        "waist_ease":
            waist_ease,

        "hip_ease":
            hip_ease,

        "bust_ratio":
            bust_ratio,

        "waist_ratio":
            waist_ratio,

        "hip_ratio":
            hip_ratio,

        "bust_mismatch":
            bust_mismatch,

        "waist_mismatch":
            waist_mismatch,

        "hip_mismatch":
            hip_mismatch,

        "bust_relative_mismatch":
            bust_relative,

        "waist_relative_mismatch":
            waist_relative,

        "hip_relative_mismatch":
            hip_relative,

        "mean_relative_mismatch":
            mean_relative_mismatch,

        "mismatch_std":
            mismatch_std,

        "mean_ease":
            mean_ease,

        "ease_std":
            ease_std,

        "tight_dimension_count":
            tight_count,

        "extreme_ease_count":
            extreme_count,

        "length_height_ratio":
            length_ratio,
    }


# ============================================================
# BUILD AUDIT DATASET
# ============================================================

rows = []

for _, row in pairwise.iterrows():

    person_id = row[
        "person_id"
    ]

    positive_product = row[
        "positive_product_id"
    ]

    negative_product = row[
        "negative_product_id"
    ]

    positive = compatibility_features(
        person_id,
        positive_product,
    )

    negative = compatibility_features(
        person_id,
        negative_product,
    )

    record = {
        "person_id":
            person_id,

        "positive_product_id":
            positive_product,

        "negative_product_id":
            negative_product,

        "negative_type":
            row["negative_type"],

        "negative_distance":
            row["negative_distance"],
    }

    for feature in positive:

        record[
            "positive_" + feature
        ] = positive[
            feature
        ]

        record[
            "negative_" + feature
        ] = negative[
            feature
        ]

        record[
            "difference_" + feature
        ] = (
            positive[
                feature
            ]
            -
            negative[
                feature
            ]
        )

    rows.append(
        record
    )

audit = pd.DataFrame(
    rows
)

print(
    "\nAudit rows:",
    len(audit)
)

# ============================================================
# DEFINE "MORE PHYSICALLY COMPATIBLE"
# ============================================================
#
# Smaller relative mismatch = better physical fit.
#
# This is an analytical proxy only.
# It is NOT assumed to be ground truth.
# ============================================================

audit[
    "positive_better_mismatch"
] = (
    audit[
        "positive_mean_relative_mismatch"
    ]
    <
    audit[
        "negative_mean_relative_mismatch"
    ]
)

# ============================================================
# OVERALL NEGATIVE VALIDITY
# ============================================================

print("\n" + "=" * 70)
print("OVERALL PHYSICAL COMPATIBILITY")
print("=" * 70)

overall = (
    audit[
        "positive_better_mismatch"
    ]
    .mean()
)

print(
    "Positive has lower physical mismatch:",
    f"{overall:.4f}"
)

print(
    "Negative has lower physical mismatch:",
    f"{1 - overall:.4f}"
)

# ============================================================
# BY NEGATIVE TYPE
# ============================================================

print("\n" + "=" * 70)
print("PHYSICAL COMPATIBILITY BY NEGATIVE TYPE")
print("=" * 70)

type_validity = (
    audit
    .groupby(
        "negative_type"
    )
    .agg(
        pairs=(
            "positive_better_mismatch",
            "size",
        ),

        positive_more_compatible=(
            "positive_better_mismatch",
            "mean",
        ),

        positive_mismatch=(
            "positive_mean_relative_mismatch",
            "mean",
        ),

        negative_mismatch=(
            "negative_mean_relative_mismatch",
            "mean",
        ),
    )
)

print(
    type_validity
)

# ============================================================
# POSITIVE VS NEGATIVE MISMATCH
# ============================================================

print("\n" + "=" * 70)
print("MISMATCH DISTRIBUTION")
print("=" * 70)

for negative_type in [
    "hard",
    "semi-hard",
    "random",
]:

    subset = audit[
        audit[
            "negative_type"
        ]
        ==
        negative_type
    ]

    print(
        f"\n{negative_type.upper()}"
    )

    print(
        "Positive mismatch:"
    )

    print(
        subset[
            "positive_mean_relative_mismatch"
        ]
        .describe()
    )

    print(
        "Negative mismatch:"
    )

    print(
        subset[
            "negative_mean_relative_mismatch"
        ]
        .describe()
    )

# ============================================================
# RANDOM NEGATIVES — CRITICAL ANALYSIS
# ============================================================

random = audit[
    audit[
        "negative_type"
    ]
    ==
    "random"
].copy()

print("\n" + "=" * 70)
print("RANDOM NEGATIVE VALIDITY")
print("=" * 70)

random_positive_better = (
    random[
        "positive_better_mismatch"
    ]
    .mean()
)

print(
    "Positive physically better:",
    f"{random_positive_better:.4f}"
)

print(
    "Random negative physically better:",
    f"{1 - random_positive_better:.4f}"
)

# ============================================================
# CASES WHERE RANDOM NEGATIVE IS PHYSICALLY BETTER
# ============================================================

random_suspicious = random[
    random[
        "negative_mean_relative_mismatch"
    ]
    <
    random[
        "positive_mean_relative_mismatch"
    ]
].copy()

random_suspicious[
    "mismatch_advantage"
] = (
    random_suspicious[
        "positive_mean_relative_mismatch"
    ]
    -
    random_suspicious[
        "negative_mean_relative_mismatch"
    ]
)

print("\n" + "=" * 70)
print("RANDOM NEGATIVES MORE PHYSICALLY COMPATIBLE")
print("=" * 70)

print(
    "Count:",
    len(random_suspicious)
)

print(
    "Percentage:",
    f"{len(random_suspicious) / max(1, len(random)):.4f}"
)

display(
    random_suspicious[
        [
            "person_id",
            "positive_product_id",
            "negative_product_id",
            "positive_mean_relative_mismatch",
            "negative_mean_relative_mismatch",
            "mismatch_advantage",
            "positive_mean_ease",
            "negative_mean_ease",
        ]
    ]
    .sort_values(
        "mismatch_advantage",
        ascending=False,
    )
    .head(50)
)

# ============================================================
# RANDOM NEGATIVES THAT LOOK EXTREMELY COMPATIBLE
# ============================================================

print("\n" + "=" * 70)
print("SUSPICIOUS RANDOM NEGATIVES")
print("=" * 70)

threshold = (
    random[
        "positive_mean_relative_mismatch"
    ]
    .median()
)

very_suspicious = random[
    random[
        "negative_mean_relative_mismatch"
    ]
    <
    threshold
].copy()

print(
    "Random negatives with mismatch better "
    "than positive median:",
    len(very_suspicious)
)

# ============================================================
# MANN-WHITNEY TEST
# ============================================================

print("\n" + "=" * 70)
print("STATISTICAL COMPARISON")
print("=" * 70)

for negative_type in [
    "hard",
    "semi-hard",
    "random",
]:

    subset = audit[
        audit[
            "negative_type"
        ]
        ==
        negative_type
    ]

    positive_values = (
        subset[
            "positive_mean_relative_mismatch"
        ]
        .dropna()
    )

    negative_values = (
        subset[
            "negative_mean_relative_mismatch"
        ]
        .dropna()
    )

    if (
        len(positive_values) > 0
        and
        len(negative_values) > 0
    ):

        stat, p = mannwhitneyu(
            positive_values,
            negative_values,
            alternative="less",
        )

        print(
            f"\n{negative_type}"
        )

        print(
            "Positive median:",
            positive_values.median()
        )

        print(
            "Negative median:",
            negative_values.median()
        )

        print(
            "p-value:",
            f"{p:.8f}"
        )

# ============================================================
# CAN SIMPLE PHYSICAL MISMATCH DISTINGUISH LABELS?
# ============================================================

print("\n" + "=" * 70)
print("MISMATCH AUC")
print("=" * 70)

# Build balanced positive/negative examples
classification_rows = []

for _, row in audit.iterrows():

    classification_rows.append(
        {
            "mismatch":
                row[
                    "positive_mean_relative_mismatch"
                ],

            "label":
                1,
        }
    )

    classification_rows.append(
        {
            "mismatch":
                row[
                    "negative_mean_relative_mismatch"
                ],

            "label":
                0,
        }
    )

classification = pd.DataFrame(
    classification_rows
).dropna()

# Smaller mismatch should indicate positive.
# Therefore invert it.
auc = roc_auc_score(
    classification["label"],
    -classification["mismatch"],
)

print(
    "Physical mismatch ROC-AUC:",
    f"{auc:.4f}"
)

# ============================================================
# PER-PERSON VALIDITY
# ============================================================

print("\n" + "=" * 70)
print("PER-PERSON RANDOM NEGATIVE VALIDITY")
print("=" * 70)

person_validity = (
    random
    .groupby(
        "person_id"
    )
    .agg(
        pairs=(
            "positive_better_mismatch",
            "size",
        ),

        positive_better_pct=(
            "positive_better_mismatch",
            "mean",
        ),

        positive_mismatch=(
            "positive_mean_relative_mismatch",
            "mean",
        ),

        negative_mismatch=(
            "negative_mean_relative_mismatch",
            "mean",
        ),
    )
    .sort_values(
        "positive_better_pct"
    )
)

display(
    person_validity
)

# ============================================================
# POSITIVE/NEGATIVE EASE COMPARISON
# ============================================================

print("\n" + "=" * 70)
print("EASE COMPARISON")
print("=" * 70)

ease_features = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "mean_ease",
]

ease_rows = []

for feature in ease_features:

    pos = (
        random[
            "positive_" + feature
        ]
        .dropna()
    )

    neg = (
        random[
            "negative_" + feature
        ]
        .dropna()
    )

    ease_rows.append(
        {
            "feature":
                feature,

            "positive_mean":
                pos.mean(),

            "negative_mean":
                neg.mean(),

            "difference":
                pos.mean()
                -
                neg.mean(),
        }
    )

ease_comparison = pd.DataFrame(
    ease_rows
)

display(
    ease_comparison
)

# ============================================================
# FINAL DIAGNOSIS
# ============================================================

print("\n" + "=" * 70)
print("FINAL NEGATIVE-LABEL DIAGNOSIS")
print("=" * 70)

if random_positive_better >= 0.70:

    print(
        "RANDOM NEGATIVES LOOK GENERALLY VALID."
    )

    print(
        "Most random negatives are physically "
        "less compatible than positives."
    )

elif random_positive_better >= 0.55:

    print(
        "RANDOM NEGATIVES SHOW MODERATE VALIDITY."
    )

    print(
        "There is meaningful label noise."
    )

else:

    print(
        "RANDOM NEGATIVES ARE HIGHLY QUESTIONABLE."
    )

    print(
        "A large fraction are physically "
        "more compatible than the recorded positives."
    )

print(
    "\nRandom positive-better rate:",
    f"{random_positive_better:.4f}"
)

print(
    "Physical mismatch AUC:",
    f"{auc:.4f}"
)

print(
    "\nAudit complete."
)

======================================================================
ZYRA V2 — NEGATIVE LABEL VALIDITY AUDIT
======================================================================
Pairwise rows: 8970
People: 56

Audit rows: 8970

======================================================================
OVERALL PHYSICAL COMPATIBILITY
======================================================================
Positive has lower physical mismatch: 0.3491
Negative has lower physical mismatch: 0.6509

======================================================================
PHYSICAL COMPATIBILITY BY NEGATIVE TYPE
======================================================================
               pairs  positive_more_compatible  positive_mismatch  \
negative_type
hard            2990                  0.071237           0.431902
random          2990                  0.695987           0.431902
semi-hard       2990                  0.279933           0.431902

               negative_mismatch
negative_type
hard                    0.182860
random                  0.578725
semi-hard               0.330449

======================================================================
MISMATCH DISTRIBUTION
======================================================================

HARD
Positive mismatch:
count    2845.000000
mean        0.431902
std         0.228979
min         0.034990
25%         0.260456
50%         0.392106
75%         0.594832
max         1.398505
Name: positive_mean_relative_mismatch, dtype: float64
Negative mismatch:
count    2929.000000
mean        0.182860
std         0.100092
min         0.009623
25%         0.100205
50%         0.146916
75%         0.270034
max         0.511628
Name: negative_mean_relative_mismatch, dtype: float64

SEMI-HARD
Positive mismatch:
count    2845.000000
mean        0.431902
std         0.228979
min         0.034990
25%         0.260456
50%         0.392106
75%         0.594832
max         1.398505
Name: positive_mean_relative_mismatch, dtype: float64
Negative mismatch:
count    2969.000000
mean        0.330449
std         0.150565
min         0.038921
25%         0.198020
50%         0.326733
75%         0.453741
max         0.790123
Name: negative_mean_relative_mismatch, dtype: float64

RANDOM
Positive mismatch:
count    2845.000000
mean        0.431902
std         0.228979
min         0.034990
25%         0.260456
50%         0.392106
75%         0.594832
max         1.398505
Name: positive_mean_relative_mismatch, dtype: float64
Negative mismatch:
count    2931.000000
mean        0.578725
std         0.227283
min         0.008772
25%         0.397015
50%         0.586428
75%         0.719869
max         1.356608
Name: negative_mean_relative_mismatch, dtype: float64

======================================================================
RANDOM NEGATIVE VALIDITY
======================================================================
Positive physically better: 0.6960
Random negative physically better: 0.3040

======================================================================
RANDOM NEGATIVES MORE PHYSICALLY COMPATIBLE
======================================================================
Count: 709
Percentage: 0.2371

,person_id,positive_product_id,negative_product_id,positive_mean_relative_mismatch,negative_mean_relative_mismatch,mismatch_advantage,positive_mean_ease,negative_mean_ease
6056,Marnee,flow-with-me-slouch-top#Brick,layered-sleeve-top#Moss,1.332658,0.609081,0.723577,100.666667,45.333333
2654,Georgia,open-plains-kimono-throw-1#Rust,the-cut-out-shoulder-blouse#Blue,1.398505,0.691362,0.707143,103.000000,49.666667
6143,Marnee,open-plains-kimono-throw-1#Rust,cross-over-top-with-pocket#NavyMustrd,1.352398,0.657802,0.694596,102.000000,48.666667
2564,Georgia,flow-with-me-slouch-top#Brick,the-cotton-tie-detail-top#Ivory,1.377996,0.714511,0.663485,101.666667,52.000000
5960,Marnee,beach-walk-shirt#Khaki,the-sleeveless-cross-over-blouse#Mint,1.222222,0.637725,0.584497,99.000000,47.333333
5942,Mandy,open-plains-kimono-throw-1#Rust,the-daily-cross-over-top#PinkPrint,0.855875,0.310680,0.545195,81.666667,32.000000
3902,Lara,pattern-tunic-1#Lattice,spot-layered-tee#Blue,1.276446,0.735431,0.541015,94.666667,54.000000
8390,Stefania,the-check-pullover#PinkCheck,the-cotton-bamboo-tank#White,0.971017,0.443600,0.527418,84.666667,38.333333
284,Amanda,the-oversize-knit#Ink,belle-tie-neck-blouse-tee#RoyalBlue,1.093023,0.573916,0.519107,94.000000,46.000000
2495,Georgia,cross-my-heart-bamboo-slouch-tee#White,belle-v-neck-forgiver-tunic#White,1.181890,0.669988,0.511903,84.333333,49.000000
3848,Katie,lavaux-bell-sleeve#Mustard,softly-swinging-bamboo-tee#Blush,1.184928,0.676693,0.508235,89.833333,52.166667
1973,Fiona,the-check-pullover#PinkCheck,milan-stretch-top#SilverMarl,0.791981,0.284220,0.507761,76.000000,26.333333
1754,Fiona,flow-with-me-slouch-top#Brick,butterfly-kisses-tee#MustardStr,0.823342,0.316832,0.506510,79.000000,32.000000
6287,Marnee,summer-whispers-kimono-1#Peacock,tracie-top#Black,1.199396,0.700127,0.499270,90.666667,52.333333
8267,Stacey,open-plains-kimono-throw-1#Rust,the-frill-detail-blouse#Chambray,0.956304,0.462902,0.493402,87.000000,41.666667
1868,Fiona,open-plains-kimono-throw-1#Rust,the-flutter-sleeve-top#Denim,0.838690,0.347180,0.491510,80.333333,37.500000
2303,Gemma,flow-with-me-slouch-top#Brick,the-shoulder-tie-top#Navy,1.188383,0.698818,0.489565,96.000000,56.333333
3665,Jude,pattern-tunic-1#Lattice,the-drape-tee-1#Stripe,1.220261,0.731515,0.488746,93.333333,62.000000
6779,Natalia,lavaux-bell-sleeve#Mustard,butterfly-kisses-tee#Stripe,0.856011,0.371134,0.484877,76.666667,36.000000
7940,Sophia,meredith-78-oversized-pullover-knit#WhiteCapGr,milan-stretch-top#NavyWhtStr,0.762529,0.286087,0.476441,70.500000,27.333333
7499,Riina,the-check-pullover#PinkCheck,leopard-print-kimono#GoldMulti,1.250010,0.775281,0.474729,96.000000,69.000000
2465,Georgia,be-mine-top-1#Sage,the-define-flute-sleeve-blouse#Black,1.128108,0.661017,0.467091,82.500000,48.333333
7193,Palatina,beach-walk-shirt#Stormy,grace-oversized-knit#Clay,0.855670,0.396061,0.459609,83.000000,36.666667
8711,Summer,striped-sleeve-sweater#Striped,print-tee-3#Boats,1.312500,0.866319,0.446181,84.000000,67.333333
7190,Palatina,beach-walk-shirt#Khaki,the-luxe-long-sleeve-tee#GreyMarle,0.855670,0.411993,0.443677,83.000000,42.000000
2804,Georgia,summer-whispers-kimono-1#Peacock,the-everyday-shirt#Cream,1.241917,0.798509,0.443408,91.666667,58.000000
7274,Palatina,on-the-horizon-swing-top-1#Khaki,baobab-sweater#Bark,0.744349,0.318074,0.426274,76.000000,33.000000
2885,Jess,belle-flocked-tunic#White,the-contrast-trim-knit#BlackWhite,0.698147,0.272727,0.425419,64.000000,27.000000
7610,Riina,the-oversize-knit#GreyMarle,meera-oversized-shirt#Mint,1.093023,0.673983,0.419040,94.000000,51.000000
7241,Palatina,flow-with-me-slouch-top#Brick,the-shoulder-tie-top#White,0.867960,0.449551,0.418409,82.000000,42.333333
1925,Fiona,sugar-snaps-throw-jacket#Duckegg,sailaway-blouse#OxfordBlue,0.658786,0.241202,0.417584,46.666667,21.000000
8303,Stacey,striped-sleeve-sweater#Striped,paint-stroke-top#Strokes,0.850000,0.434007,0.415993,68.000000,41.000000
5963,Marnee,beach-walk-shirt#Stormy,belle-deep-v-mesh-top#Black,1.222222,0.807271,0.414952,99.000000,60.000000
7598,Riina,the-longline-waterfall-cardi#Black,crosses-jumper#xmyheart,0.995558,0.588842,0.406715,87.000000,51.500000
1388,Emma,annabelle-sweater#Midnight,softly-swinging-bamboo-tee#Blush,1.077850,0.674292,0.403558,81.333333,52.333333
1400,Emma,belle-flute-sleeve-tee#Navy,the-cotton-bamboo-tank#White,1.066435,0.664872,0.401563,79.666667,50.666667
281,Amanda,the-oversize-knit#GreyMarle,the-drape-tee-1#Stripe,1.093023,0.693298,0.399726,94.000000,60.500000
4952,Ljubenka,summer-whispers-kimono-1#Peacock,the-cotton-blend-stripe-jumper#BlueStripe,0.587779,0.192308,0.395471,61.666667,20.000000
3911,Laura,be-mine-top-1#Sage,paradise-top#Red,0.736904,0.347056,0.389848,66.000000,26.500000
4028,Laura,flow-with-me-slouch-top#Brick,the-cross-over-top#NavyStripe,0.927823,0.538236,0.389586,84.000000,44.000000
4502,Laura,the-oversized-cotton-blend-shirt#Sand,2-in-1-layered-knit-top#Navy,0.736349,0.350004,0.386346,66.333333,30.666667
8330,Stacey,the-oversize-knit#Ink,lurex-stitch-top#White,0.782178,0.396220,0.385958,79.000000,35.666667
2363,Gemma,meredith-78-oversized-pullover-knit#WhiteCapGr,belle-handkerchief-printed-cami#RustFlwrs,1.119405,0.743719,0.375687,85.750000,60.333333
2930,Jess,belle-mesh-cardi#Black,abigail-stripe-shirt#BlackStrip,0.774476,0.399041,0.375435,65.500000,36.333333
5981,Marnee,chill-out-slouch-top#GreyMarle,the-cut-out-shoulder-blouse#Black,1.028715,0.658575,0.370140,77.333333,48.666667
4685,Lauren,sugar-snaps-throw-jacket#Black,triangle-detail-long-sleeve-tee#Bordeaux,0.591518,0.222200,0.369318,37.000000,22.000000
2888,Jess,belle-flute-sleeve-tee#Navy,the-define-flute-sleeve-blouse#White,0.689181,0.323311,0.365870,62.000000,29.000000
2054,Fiona,the-longline-waterfall-cardi#Black,the-cotton-bamboo-ls-top#NavyStripe,0.624666,0.260827,0.363840,66.500000,27.500000
5912,Mae-Lee,the-stripe-button-through-top#Coral,side-buttoned-sweater#Buttoned,0.372586,0.008772,0.363814,43.000000,-1.000000
8279,Stacey,poncho-2#NavySilver,the-drape-tee-1#Black,0.847621,0.486714,0.360906,77.000000,48.500000

======================================================================
SUSPICIOUS RANDOM NEGATIVES
======================================================================
Random negatives with mismatch better than positive median: 696

======================================================================
STATISTICAL COMPARISON
======================================================================

hard
Positive median: 0.3921060587600908
Negative median: 0.14691558441558442
p-value: 1.00000000

semi-hard
Positive median: 0.3921060587600908
Negative median: 0.32673267326732675
p-value: 1.00000000

random
Positive median: 0.3921060587600908
Negative median: 0.5864280780237492
p-value: 0.00000000

======================================================================
MISMATCH AUC
======================================================================
Physical mismatch ROC-AUC: 0.4055

======================================================================
PER-PERSON RANDOM NEGATIVE VALIDITY
======================================================================

            pairs  positive_better_pct  positive_mismatch  negative_mismatch
person_id
Jira            1             0.000000           0.760183           0.689680
Jude           14             0.214286           0.656310           0.767439
Anna Maria     18             0.222222           0.810197           0.759821
Lauren         30             0.500000           0.275434           0.289260
Clementine     62             0.516129           0.683499           0.702417
Sophia         59             0.525424           0.333086           0.410748
Amanda        108             0.527778           0.660623           0.705525
Marnee        141             0.531915           0.718541           0.768965
Georgia       131             0.549618           0.732655           0.811437
Palatina       49             0.551020           0.367616           0.444641
Fiona         184             0.554348           0.340939           0.392168
Natalia        46             0.586957           0.418792           0.500334
Mae-Lee       159             0.666667           0.184211           0.278598
Mandy           9             0.666667           0.323512           0.385094
Lara            3             0.666667           0.614307           0.909915
Nikki           9             0.666667           0.772906           0.909207
Sophie         54             0.666667           0.145944           0.229533
Gemma          84             0.678571           0.493856           0.703665
Riina         104             0.692308           0.617128           0.766761
Stefania       33             0.696970           0.409790           0.522885
Ljubenka      109             0.697248           0.228767           0.304703
Katie          24             0.708333           0.638560           0.754471
Jess          251             0.713147           0.323869           0.464994
Nathalie       14             0.714286           0.550767           0.754498
Tia            71             0.718310           0.249495           0.370459
Lisa            8             0.750000           0.434137           0.583766
Stacey         56             0.750000           0.345986           0.472720
Rosaline        4             0.750000           0.374997           0.460946
Mercy          24             0.750000           0.273504           0.388657
Chelsea        88             0.761364           0.454330           0.723066
Natalie        51             0.764706           0.548560           0.738310
Charlotte      13             0.769231           0.380024           0.661543
Emma           87             0.770115           0.636839           0.826495
Laura         244             0.770492           0.326368           0.503256
Olivia         23             0.782609           0.380408           0.475798
Madeline       37             0.783784           0.500123           0.796457
Summer         95             0.789474           0.472821           0.734263
Miranda        27             0.814815           0.557629           0.766444
Alex           37             0.837838           0.543156           0.789392
Nadine         42             0.857143           0.399674           0.645970
Monique        29             0.862069           0.482466           0.741938
Kate           52             0.865385           0.264007           0.399085
Maddy          77             0.870130           0.413399           0.630477
Anna           87             0.873563           0.434776           0.673463
Helen           8             0.875000           0.473105           0.693745
Denniel        26             0.884615           0.395269           0.652860
Perrie         37             0.891892           0.449587           0.770709
Chesska        11             0.909091           0.379100           0.671365
Shadae         35             0.942857           0.373309           0.755610
Thais           3             1.000000           0.517471           0.620703
Louise          5             1.000000           0.276399           0.518766
Edith           3             1.000000           0.614481           0.780570
Bree            6             1.000000           0.358684           0.508657
Grazi           1             1.000000           0.260669           0.544280
Anneliese       3             1.000000           0.481745           0.731303
Lucy            4             1.000000           0.163709           0.443354

======================================================================
EASE COMPARISON
======================================================================

      feature  positive_mean  negative_mean  difference
0   bust_ease      30.613245      41.610517  -10.997272
1  waist_ease      45.389790      60.029476  -14.639686
2    hip_ease      28.893554      43.745841  -14.852287
3   mean_ease      35.135208      47.859945  -12.724737

======================================================================
FINAL NEGATIVE-LABEL DIAGNOSIS
======================================================================
RANDOM NEGATIVES SHOW MODERATE VALIDITY.
There is meaningful label noise.

Random positive-better rate: 0.6960
Physical mismatch AUC: 0.4055

Audit complete.

In [72]:
# ============================================================
# ZYRA V2 — STEP 1
# COMPLETE PERSON × GARMENT CANDIDATE MATRIX
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(RAW_PATH)

print("=" * 70)
print("ZYRA V2 — COMPLETE CANDIDATE MATRIX")
print("=" * 70)

print("Raw rows:", len(df))

# ============================================================
# PEOPLE
# ============================================================

people = (
    df[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates(
        "person_id"
    )
    .reset_index(drop=True)
)

# ============================================================
# GARMENTS
# ============================================================

garments = (
    df[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates(
        "product_id"
    )
    .reset_index(drop=True)
)

print(
    "\nPeople:",
    len(people)
)

print(
    "Garments:",
    len(garments)
)

# ============================================================
# KNOWN POSITIVE INTERACTIONS
# ============================================================

positive_pairs = (
    df[
        df["label"] == 1
    ][
        [
            "person_id",
            "product_id",
        ]
    ]
    .drop_duplicates()
    .copy()
)

positive_keys = set(
    zip(
        positive_pairs[
            "person_id"
        ],
        positive_pairs[
            "product_id"
        ],
    )
)

print(
    "\nKnown positive interactions:",
    len(positive_keys)
)

# ============================================================
# COMPLETE CARTESIAN PRODUCT
# ============================================================

people["_tmp"] = 1
garments["_tmp"] = 1

candidates = (
    people
    .merge(
        garments,
        on="_tmp",
    )
    .drop(
        columns="_tmp"
    )
)

# ============================================================
# LABEL STATUS
# ============================================================

candidates[
    "label_status"
] = [
    (
        "positive"
        if (
            person_id,
            product_id,
        )
        in positive_keys
        else "unknown"
    )

    for person_id, product_id
    in zip(
        candidates[
            "person_id"
        ],
        candidates[
            "product_id"
        ],
    )
]

# ============================================================
# BASIC COUNTS
# ============================================================

print("\n" + "=" * 70)
print("CANDIDATE MATRIX")
print("=" * 70)

print(
    "Total candidates:",
    len(candidates)
)

print(
    "Expected:",
    len(people) * len(garments)
)

print(
    "\nLabel status:"
)

print(
    candidates[
        "label_status"
    ].value_counts()
)

# ============================================================
# VERIFY POSITIVES
# ============================================================

matrix_positive_count = (
    candidates[
        "label_status"
    ]
    .eq("positive")
    .sum()
)

print(
    "\nMatrix positives:",
    matrix_positive_count
)

assert (
    matrix_positive_count
    ==
    len(positive_keys)
)

# ============================================================
# VERIFY ONE ROW PER PERSON-GARMENT
# ============================================================

duplicate_pairs = (
    candidates[
        [
            "person_id",
            "product_id",
        ]
    ]
    .duplicated()
    .sum()
)

print(
    "Duplicate person-garment pairs:",
    duplicate_pairs
)

assert duplicate_pairs == 0

# ============================================================
# PHYSICAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("PHYSICAL COMPATIBILITY FEATURES")
print("=" * 70)


def safe_ratio(
    numerator,
    denominator,
):

    if (
        pd.isna(numerator)
        or
        pd.isna(denominator)
        or
        denominator == 0
    ):
        return np.nan

    return (
        numerator
        /
        denominator
    )


# ------------------------------------------------------------
# Ease
# ------------------------------------------------------------

candidates[
    "bust_ease"
] = (
    candidates[
        "garment_bust"
    ]
    -
    candidates[
        "bust"
    ]
)

candidates[
    "waist_ease"
] = (
    candidates[
        "garment_waist"
    ]
    -
    candidates[
        "waist"
    ]
)

candidates[
    "hip_ease"
] = (
    candidates[
        "garment_hip"
    ]
    -
    candidates[
        "hips"
    ]
)

# ------------------------------------------------------------
# Ratios
# ------------------------------------------------------------

candidates[
    "bust_ratio"
] = (
    candidates[
        "garment_bust"
    ]
    /
    candidates[
        "bust"
    ]
)

candidates[
    "waist_ratio"
] = (
    candidates[
        "garment_waist"
    ]
    /
    candidates[
        "waist"
    ]
)

candidates[
    "hip_ratio"
] = (
    candidates[
        "garment_hip"
    ]
    /
    candidates[
        "hips"
    ]
)

# ------------------------------------------------------------
# Absolute mismatch
# ------------------------------------------------------------

candidates[
    "bust_mismatch"
] = abs(
    candidates[
        "garment_bust"
    ]
    -
    candidates[
        "bust"
    ]
)

candidates[
    "waist_mismatch"
] = abs(
    candidates[
        "garment_waist"
    ]
    -
    candidates[
        "waist"
    ]
)

candidates[
    "hip_mismatch"
] = abs(
    candidates[
        "garment_hip"
    ]
    -
    candidates[
        "hips"
    ]
)

# ------------------------------------------------------------
# Relative mismatch
# ------------------------------------------------------------

candidates[
    "bust_relative_mismatch"
] = (
    candidates[
        "bust_mismatch"
    ]
    /
    candidates[
        "bust"
    ]
)

candidates[
    "waist_relative_mismatch"
] = (
    candidates[
        "waist_mismatch"
    ]
    /
    candidates[
        "waist"
    ]
)

candidates[
    "hip_relative_mismatch"
] = (
    candidates[
        "hip_mismatch"
    ]
    /
    candidates[
        "hips"
    ]
)

# ------------------------------------------------------------
# Mean ease
# ------------------------------------------------------------

ease_columns = [
    "bust_ease",
    "waist_ease",
    "hip_ease",
]

candidates[
    "mean_ease"
] = candidates[
    ease_columns
].mean(
    axis=1
)

candidates[
    "ease_std"
] = candidates[
    ease_columns
].std(
    axis=1
)

# ------------------------------------------------------------
# Known dimensions
# ------------------------------------------------------------

candidates[
    "known_fit_dimensions"
] = (
    candidates[
        ease_columns
    ]
    .notna()
    .sum(axis=1)
)

# ------------------------------------------------------------
# Tight dimensions
# ------------------------------------------------------------

candidates[
    "tight_dimension_count"
] = (
    candidates[
        ease_columns
    ]
    .lt(0)
    .sum(axis=1)
)

# ------------------------------------------------------------
# Extreme ease
# ------------------------------------------------------------

candidates[
    "extreme_ease_count"
] = (
    candidates[
        ease_columns
    ]
    .gt(50)
    .sum(axis=1)
)

# ------------------------------------------------------------
# Length / height
# ------------------------------------------------------------

candidates[
    "length_height_ratio"
] = (
    candidates[
        "garment_length"
    ]
    /
    candidates[
        "height"
    ]
)

# ============================================================
# PHYSICAL COMPATIBILITY PROXY
# ============================================================
#
# IMPORTANT:
# This is NOT a training label.
#
# It is only used later to identify confidently incompatible
# garments.
# ============================================================

relative_mismatch_columns = [
    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",
]

candidates[
    "physical_mismatch"
] = candidates[
    relative_mismatch_columns
].mean(
    axis=1
)

# ============================================================
# MISSINGNESS
# ============================================================

measurement_columns = [
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
]

candidates[
    "missing_measurement_count"
] = (
    candidates[
        measurement_columns
    ]
    .isna()
    .sum(axis=1)
)

candidates[
    "measurement_complete"
] = (
    candidates[
        "missing_measurement_count"
    ]
    == 0
)

# ============================================================
# CHECK POSITIVE / UNKNOWN
# ============================================================

print("\n" + "=" * 70)
print("LABEL SUMMARY")
print("=" * 70)

print(
    candidates[
        "label_status"
    ].value_counts()
)

print(
    "\nPositive percentage:",
    f"{matrix_positive_count / len(candidates) * 100:.3f}%"
)

print(
    "Unknown percentage:",
    f"{(len(candidates) - matrix_positive_count) / len(candidates) * 100:.3f}%"
)

# ============================================================
# PER PERSON
# ============================================================

print("\n" + "=" * 70)
print("PER-PERSON SUMMARY")
print("=" * 70)

person_summary = (
    candidates
    .groupby(
        "person_id"
    )
    .agg(
        total_garments=(
            "product_id",
            "count",
        ),

        positives=(
            "label_status",
            lambda x:
                (x == "positive").sum(),
        ),

        unknown=(
            "label_status",
            lambda x:
                (x == "unknown").sum(),
        ),
    )
)

person_summary[
    "positive_rate"
] = (
    person_summary[
        "positives"
    ]
    /
    person_summary[
        "total_garments"
    ]
)

print(
    person_summary
)

# ============================================================
# GARMENT SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PER-GARMENT SUMMARY")
print("=" * 70)

garment_summary = (
    candidates
    .groupby(
        "product_id"
    )
    .agg(
        people=(
            "person_id",
            "count",
        ),

        positive_count=(
            "label_status",
            lambda x:
                (x == "positive").sum(),
        ),
    )
)

garment_summary[
    "positive_rate"
] = (
    garment_summary[
        "positive_count"
    ]
    /
    garment_summary[
        "people"
    ]
)

print(
    garment_summary[
        "positive_count"
    ]
    .describe()
)

# ============================================================
# DATA QUALITY
# ============================================================

print("\n" + "=" * 70)
print("DATA QUALITY")
print("=" * 70)

numeric_columns = [
    "height",
    "bust",
    "waist",
    "hips",
    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",
    "bust_ease",
    "waist_ease",
    "hip_ease",
    "bust_ratio",
    "waist_ratio",
    "hip_ratio",
    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",
    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",
    "mean_ease",
    "ease_std",
    "length_height_ratio",
    "physical_mismatch",
]

nan_count = (
    candidates[
        numeric_columns
    ]
    .isna()
    .sum()
    .sum()
)

inf_count = (
    np.isinf(
        candidates[
            numeric_columns
        ]
        .select_dtypes(
            include=np.number
        )
        .to_numpy()
    )
    .sum()
)

print(
    "NaN values:",
    nan_count
)

print(
    "Inf values:",
    inf_count
)

# ============================================================
# SAVE
# ============================================================

candidates.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("CANDIDATE MATRIX SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print(
    "\nZYRA V2 STEP 1 COMPLETE"
)

======================================================================
ZYRA V2 — COMPLETE CANDIDATE MATRIX
======================================================================
Raw rows: 5980

People: 56
Garments: 897

Known positive interactions: 2990

======================================================================
CANDIDATE MATRIX
======================================================================
Total candidates: 50232
Expected: 50232

Label status:
label_status
unknown     47242
positive     2990
Name: count, dtype: int64

Matrix positives: 2990
Duplicate person-garment pairs: 0

======================================================================
PHYSICAL COMPATIBILITY FEATURES
======================================================================

======================================================================
LABEL SUMMARY
======================================================================
label_status
unknown     47242
positive     2990
Name: count, dtype: int64

Positive percentage: 5.952%
Unknown percentage: 94.048%

======================================================================
PER-PERSON SUMMARY
======================================================================
            total_garments  positives  unknown  positive_rate
person_id
Alex                   897         37      860       0.041249
Amanda                 897        108      789       0.120401
Anna                   897         87      810       0.096990
Anna Maria             897         18      879       0.020067
Anneliese              897          3      894       0.003344
Bree                   897          6      891       0.006689
Charlotte              897         13      884       0.014493
Chelsea                897         88      809       0.098105
Chesska                897         11      886       0.012263
Clementine             897         62      835       0.069119
Denniel                897         26      871       0.028986
Edith                  897          3      894       0.003344
Emma                   897         87      810       0.096990
Fiona                  897        184      713       0.205128
Gemma                  897         84      813       0.093645
Georgia                897        131      766       0.146042
Grazi                  897          1      896       0.001115
Helen                  897          8      889       0.008919
Jess                   897        251      646       0.279822
Jira                   897          1      896       0.001115
Jude                   897         14      883       0.015608
Kate                   897         52      845       0.057971
Katie                  897         24      873       0.026756
Lara                   897          3      894       0.003344
Laura                  897        244      653       0.272018
Lauren                 897         30      867       0.033445
Lisa                   897          8      889       0.008919
Ljubenka               897        109      788       0.121516
Louise                 897          5      892       0.005574
Lucy                   897          4      893       0.004459
Maddy                  897         77      820       0.085842
Madeline               897         37      860       0.041249
Mae-Lee                897        159      738       0.177258
Mandy                  897          9      888       0.010033
Marnee                 897        141      756       0.157191
Mercy                  897         24      873       0.026756
Miranda                897         27      870       0.030100
Monique                897         29      868       0.032330
Nadine                 897         42      855       0.046823
Natalia                897         46      851       0.051282
Natalie                897         51      846       0.056856
Nathalie               897         14      883       0.015608
Nikki                  897          9      888       0.010033
Olivia                 897         23      874       0.025641
Palatina               897         49      848       0.054627
Perrie                 897         37      860       0.041249
Riina                  897        104      793       0.115942
Rosaline               897          4      893       0.004459
Shadae                 897         35      862       0.039019
Sophia                 897         59      838       0.065775
Sophie                 897         54      843       0.060201
Stacey                 897         56      841       0.062430
Stefania               897         33      864       0.036789
Summer                 897         95      802       0.105909
Thais                  897          3      894       0.003344
Tia                    897         71      826       0.079153

======================================================================
PER-GARMENT SUMMARY
======================================================================
count    897.000000
mean       3.333333
std        2.900764
min        0.000000
25%        1.000000
50%        2.000000
75%        4.000000
max       14.000000
Name: positive_count, dtype: float64

======================================================================
DATA QUALITY
======================================================================
NaN values: 104552
Inf values: 0

======================================================================
CANDIDATE MATRIX SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_person_garment_candidates.csv

ZYRA V2 STEP 1 COMPLETE

In [73]:
# ============================================================
# ZYRA V2 — STEP 2
# CONFIDENT NEGATIVE MINING
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

INPUT_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_confident_training_dataset.csv"
)

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(
    INPUT_PATH
)

print("=" * 70)
print("ZYRA V2 — CONFIDENT NEGATIVE MINING")
print("=" * 70)

print(
    "Candidate rows:",
    len(df)
)

# ============================================================
# SEPARATE KNOWN POSITIVES / UNKNOWNS
# ============================================================

positive = df[
    df["label_status"] == "positive"
].copy()

unknown = df[
    df["label_status"] == "unknown"
].copy()

print(
    "\nKnown positives:",
    len(positive)
)

print(
    "Unknown pairs:",
    len(unknown)
)

# ============================================================
# IMPORTANT
# ============================================================
#
# We do NOT assume:
#
# unknown == negative
#
# Instead we look for garments that are clearly
# physically incompatible.
#
# ------------------------------------------------------------
# Primary signal:
#
# physical_mismatch
#
# This is the mean relative mismatch across:
#
# bust
# waist
# hips
#
# Higher = worse physical compatibility.
# ============================================================

print("\n" + "=" * 70)
print("PHYSICAL MISMATCH DISTRIBUTION")
print("=" * 70)

print(
    unknown[
        "physical_mismatch"
    ].describe(
        percentiles=[
            0.50,
            0.75,
            0.80,
            0.85,
            0.90,
            0.95,
            0.975,
            0.99,
        ]
    )
)

# ============================================================
# THRESHOLD
# ============================================================
#
# We intentionally use a conservative threshold.
#
# A pair is considered a confident negative when:
#
#   relative mismatch >= 0.30
#
# Meaning the average relative dimensional mismatch is
# at least 30%.
#
# We also require at least TWO known body/garment
# dimensions so that one missing measurement cannot
# create a false negative.
# ============================================================

MISMATCH_THRESHOLD = 0.30

MIN_KNOWN_DIMENSIONS = 2

confident_negative_mask = (
    (
        unknown[
            "physical_mismatch"
        ]
        >=
        MISMATCH_THRESHOLD
    )
    &
    (
        unknown[
            "known_fit_dimensions"
        ]
        >=
        MIN_KNOWN_DIMENSIONS
    )
)

confident_negative = (
    unknown[
        confident_negative_mask
    ]
    .copy()
)

remaining_unknown = (
    unknown[
        ~confident_negative_mask
    ]
    .copy()
)

print("\n" + "=" * 70)
print("CONFIDENT NEGATIVE MINING")
print("=" * 70)

print(
    "Threshold:",
    MISMATCH_THRESHOLD
)

print(
    "Minimum known dimensions:",
    MIN_KNOWN_DIMENSIONS
)

print(
    "\nConfident negatives:",
    len(confident_negative)
)

print(
    "Remaining unknown:",
    len(remaining_unknown)
)

# ============================================================
# ADD TRAINING LABEL
# ============================================================

positive[
    "training_label"
] = 1

confident_negative[
    "training_label"
] = 0

# ============================================================
# NEGATIVE QUALITY
# ============================================================

print("\n" + "=" * 70)
print("CONFIDENT NEGATIVE QUALITY")
print("=" * 70)

print(
    confident_negative[
        "physical_mismatch"
    ]
    .describe()
)

# ============================================================
# NEGATIVE MISMATCH BUCKETS
# ============================================================

def mismatch_bucket(x):

    if x < 0.30:
        return "ambiguous"

    if x < 0.40:
        return "moderate"

    if x < 0.50:
        return "strong"

    return "very_strong"


confident_negative[
    "negative_strength"
] = (
    confident_negative[
        "physical_mismatch"
    ]
    .apply(
        mismatch_bucket
    )
)

print(
    "\nNegative strength:"
)

print(
    confident_negative[
        "negative_strength"
    ]
    .value_counts()
)

# ============================================================
# DIMENSION AVAILABILITY
# ============================================================

print("\n" + "=" * 70)
print("KNOWN DIMENSIONS")
print("=" * 70)

print(
    confident_negative[
        "known_fit_dimensions"
    ]
    .value_counts()
    .sort_index()
)

# ============================================================
# POSITIVE VS NEGATIVE PHYSICAL MISMATCH
# ============================================================

print("\n" + "=" * 70)
print("POSITIVE VS CONFIDENT NEGATIVE")
print("=" * 70)

print(
    "Positive physical mismatch:"
)

print(
    positive[
        "physical_mismatch"
    ]
    .describe()
)

print(
    "\nConfident negative physical mismatch:"
)

print(
    confident_negative[
        "physical_mismatch"
    ]
    .describe()
)

# ============================================================
# PER PERSON
# ============================================================

print("\n" + "=" * 70)
print("PER-PERSON NEGATIVE COUNTS")
print("=" * 70)

person_positive_counts = (
    positive
    .groupby(
        "person_id"
    )
    .size()
    .rename(
        "positive_count"
    )
)

person_negative_counts = (
    confident_negative
    .groupby(
        "person_id"
    )
    .size()
    .rename(
        "negative_count"
    )
)

person_summary = pd.concat(
    [
        person_positive_counts,
        person_negative_counts,
    ],
    axis=1
).fillna(0)

person_summary[
    "negative_positive_ratio"
] = (
    person_summary[
        "negative_count"
    ]
    /
    person_summary[
        "positive_count"
    ]
)

print(
    person_summary
)

# ============================================================
# NEGATIVE-TO-POSITIVE RATIO
# ============================================================

total_positive = len(
    positive
)

total_negative = len(
    confident_negative
)

print("\n" + "=" * 70)
print("DATASET RATIO")
print("=" * 70)

print(
    "Positive:",
    total_positive
)

print(
    "Confident negative:",
    total_negative
)

print(
    "Negative / Positive:",
    f"{total_negative / max(1, total_positive):.3f}"
)

# ============================================================
# CAP NEGATIVES PER PERSON
# ============================================================
#
# We don't want people with many candidate garments to
# dominate training.
#
# Maximum negatives per person:
#
#   5 × number of positives
#
# ============================================================

MAX_NEGATIVE_MULTIPLIER = 5

selected_negative_parts = []

for person_id, group in (
    confident_negative
    .groupby(
        "person_id"
    )
):

    positive_count = (
        person_positive_counts
        .get(
            person_id,
            0
        )
    )

    max_negatives = max(
        1,
        int(
            positive_count
            *
            MAX_NEGATIVE_MULTIPLIER
        )
    )

    if len(group) <= max_negatives:

        selected = group

    else:

        # Prefer stronger physical incompatibility.
        selected = (
            group
            .sort_values(
                "physical_mismatch",
                ascending=False,
            )
            .head(
                max_negatives
            )
        )

    selected_negative_parts.append(
        selected
    )

if selected_negative_parts:

    selected_negative = pd.concat(
        selected_negative_parts,
        ignore_index=True,
    )

else:

    selected_negative = (
        confident_negative
        .iloc[0:0]
        .copy()
    )

# ============================================================
# FINAL TRAINING DATASET
# ============================================================

training = pd.concat(
    [
        positive,
        selected_negative,
    ],
    ignore_index=True,
)

# ============================================================
# SHUFFLE
# ============================================================

training = (
    training
    .sample(
        frac=1,
        random_state=42,
    )
    .reset_index(
        drop=True
    )
)

# ============================================================
# DUPLICATE CHECK
# ============================================================

duplicate_pairs = (
    training[
        [
            "person_id",
            "product_id",
        ]
    ]
    .duplicated()
    .sum()
)

label_conflicts = (
    training
    .groupby(
        [
            "person_id",
            "product_id",
        ]
    )[
        "training_label"
    ]
    .nunique()
)

label_conflicts = (
    label_conflicts
    .gt(1)
    .sum()
)

# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FINAL CONFIDENT TRAINING DATASET")
print("=" * 70)

print(
    "Positive:",
    (
        training[
            "training_label"
        ]
        == 1
    ).sum()
)

print(
    "Negative:",
    (
        training[
            "training_label"
        ] == 0
    ).sum()
)

print(
    "Total:",
    len(training)
)

print(
    "\nLabels:"
)

print(
    training[
        "training_label"
    ]
    .value_counts()
)

print(
    "\nDuplicate person-garment pairs:",
    duplicate_pairs
)

print(
    "Label conflicts:",
    label_conflicts
)

# ============================================================
# PER PERSON BALANCE
# ============================================================

balance = (
    training
    .groupby(
        [
            "person_id",
            "training_label",
        ]
    )
    .size()
    .unstack(
        fill_value=0
    )
)

if 0 not in balance.columns:
    balance[0] = 0

if 1 not in balance.columns:
    balance[1] = 0

balance[
    "difference"
] = (
    balance[1]
    -
    balance[0]
)

print("\n" + "=" * 70)
print("PERSON BALANCE")
print("=" * 70)

print(
    balance
)

# ============================================================
# SAVE
# ============================================================

assert duplicate_pairs == 0
assert label_conflicts == 0

training.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("CONFIDENT TRAINING DATASET SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print(
    "\nZYRA V2 STEP 2 COMPLETE"
)

======================================================================
ZYRA V2 — CONFIDENT NEGATIVE MINING
======================================================================
Candidate rows: 50232

Known positives: 2990
Unknown pairs: 47242

======================================================================
PHYSICAL MISMATCH DISTRIBUTION
======================================================================
count    46379.000000
mean         0.439982
std          0.236990
min          0.000000
50%          0.413124
75%          0.599193
80%          0.640057
85%          0.687307
90%          0.752776
95%          0.859836
97.5%        0.963811
99%          1.102845
max          1.472044
Name: physical_mismatch, dtype: float64

======================================================================
CONFIDENT NEGATIVE MINING
======================================================================
Threshold: 0.3
Minimum known dimensions: 2

Confident negatives: 29781
Remaining unknown: 17461

======================================================================
CONFIDENT NEGATIVE QUALITY
======================================================================
count    29781.000000
mean         0.553882
std          0.188918
min          0.300020
25%          0.400304
50%          0.521093
75%          0.664803
max          1.472044
Name: physical_mismatch, dtype: float64

Negative strength:
negative_strength
very_strong    16009
moderate        7421
strong          6351
Name: count, dtype: int64

======================================================================
KNOWN DIMENSIONS
======================================================================
known_fit_dimensions
2     6612
3    23169
Name: count, dtype: int64

======================================================================
POSITIVE VS CONFIDENT NEGATIVE
======================================================================
Positive physical mismatch:
count    2845.000000
mean        0.431902
std         0.228979
min         0.034990
25%         0.260456
50%         0.392106
75%         0.594832
max         1.398505
Name: physical_mismatch, dtype: float64

Confident negative physical mismatch:
count    29781.000000
mean         0.553882
std          0.188918
min          0.300020
25%          0.400304
50%          0.521093
75%          0.664803
max          1.472044
Name: physical_mismatch, dtype: float64

======================================================================
PER-PERSON NEGATIVE COUNTS
======================================================================
            positive_count  negative_count  negative_positive_ratio
person_id
Alex                    37             723                19.540541
Amanda                 108             611                 5.657407
Anna                    87             553                 6.356322
Anna Maria              18             730                40.555556
Anneliese                3             732               244.000000
Bree                     6             448                74.666667
Charlotte               13             655                50.384615
Chelsea                 88             605                 6.875000
Chesska                 11             620                56.363636
Clementine              62             653                10.532258
Denniel                 26             579                22.269231
Edith                    3             670               223.333333
Emma                    87             682                 7.839080
Fiona                  184             209                 1.135870
Gemma                   84             602                 7.166667
Georgia                131             664                 5.068702
Grazi                    1             669               669.000000
Helen                    8             728                91.000000
Jess                   251             248                 0.988048
Jira                     1             732               732.000000
Jude                    14             728                52.000000
Kate                    52             242                 4.653846
Katie                   24             732                30.500000
Lara                     3             766               255.333333
Laura                  244             276                 1.131148
Lauren                  30             118                 3.933333
Lisa                     8             646                80.750000
Ljubenka               109             135                 1.238532
Louise                   5             494                98.800000
Lucy                     4             384                96.000000
Maddy                   77             565                 7.337662
Madeline                37             735                19.864865
Mae-Lee                159             101                 0.635220
Mandy                    9             324                36.000000
Marnee                 141             648                 4.595745
Mercy                   24             235                 9.791667
Miranda                 27             743                27.518519
Monique                 29             688                23.724138
Nadine                  42             562                13.380952
Natalia                 46             421                 9.152174
Natalie                 51             651                12.764706
Nathalie                14             719                51.357143
Nikki                    9             791                87.888889
Olivia                  23             402                17.478261
Palatina                49             360                 7.346939
Perrie                  37             678                18.324324
Riina                  104             651                 6.259615
Rosaline                 4             415               103.750000
Shadae                  35             668                19.085714
Sophia                  59             289                 4.898305
Sophie                  54              55                 1.018519
Stacey                  56             422                 7.535714
Stefania                33             455                13.787879
Summer                  95             634                 6.673684
Thais                    3             743               247.666667
Tia                     71             192                 2.704225

======================================================================
DATASET RATIO
======================================================================
Positive: 2990
Confident negative: 29781
Negative / Positive: 9.960

======================================================================
FINAL CONFIDENT TRAINING DATASET
======================================================================
Positive: 2990
Negative: 10693
Total: 13683

Labels:
training_label
0    10693
1     2990
Name: count, dtype: int64

Duplicate person-garment pairs: 0
Label conflicts: 0

======================================================================
PERSON BALANCE
======================================================================
training_label    0    1  difference
person_id
Alex            185   37        -148
Amanda          540  108        -432
Anna            435   87        -348
Anna Maria       90   18         -72
Anneliese        15    3         -12
Bree             30    6         -24
Charlotte        65   13         -52
Chelsea         440   88        -352
Chesska          55   11         -44
Clementine      310   62        -248
Denniel         130   26        -104
Edith            15    3         -12
Emma            435   87        -348
Fiona           209  184         -25
Gemma           420   84        -336
Georgia         655  131        -524
Grazi             5    1          -4
Helen            40    8         -32
Jess            248  251           3
Jira              5    1          -4
Jude             70   14         -56
Kate            242   52        -190
Katie           120   24         -96
Lara             15    3         -12
Laura           276  244         -32
Lauren          118   30         -88
Lisa             40    8         -32
Ljubenka        135  109         -26
Louise           25    5         -20
Lucy             20    4         -16
Maddy           385   77        -308
Madeline        185   37        -148
Mae-Lee         101  159          58
Mandy            45    9         -36
Marnee          648  141        -507
Mercy           120   24         -96
Miranda         135   27        -108
Monique         145   29        -116
Nadine          210   42        -168
Natalia         230   46        -184
Natalie         255   51        -204
Nathalie         70   14         -56
Nikki            45    9         -36
Olivia          115   23         -92
Palatina        245   49        -196
Perrie          185   37        -148
Riina           520  104        -416
Rosaline         20    4         -16
Shadae          175   35        -140
Sophia          289   59        -230
Sophie           55   54          -1
Stacey          280   56        -224
Stefania        165   33        -132
Summer          475   95        -380
Thais            15    3         -12
Tia             192   71        -121

======================================================================
CONFIDENT TRAINING DATASET SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_confident_training_dataset.csv

ZYRA V2 STEP 2 COMPLETE

In [74]:
# ============================================================
# ZYRA V2 — STEP 3
# TRAIN COMPATIBILITY RANKER
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

DATA_PATH = (
    BASE /
    "data/v2/v2_confident_training_dataset.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_compatibility_ranker.pt"
)

SEED = 42
EPOCHS = 50
LR = 1e-3

np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================
# DEVICE
# ============================================================

device = (
    torch.device("mps")
    if torch.backends.mps.is_available()
    else torch.device("cpu")
)

print("=" * 70)
print("ZYRA V2 — STEP 3 MODEL TRAINING")
print("=" * 70)

print("Device:", device)

# ============================================================
# LOAD
# ============================================================

df = pd.read_csv(DATA_PATH)
raw = pd.read_csv(RAW_PATH)

print("\nTraining rows:", len(df))
print("People:", df["person_id"].nunique())

print("\nLabels:")
print(df["training_label"].value_counts())

# ============================================================
# FEATURES
# ============================================================

FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

# ============================================================
# LOOKUPS
# ============================================================

person_lookup = (
    raw[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates("person_id")
    .set_index("person_id")
)

garment_lookup = (
    raw[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates("product_id")
    .set_index("product_id")
)

# ============================================================
# FEATURE BUILDER
# ============================================================

def make_features(person_id, product_id):

    p = person_lookup.loc[person_id]
    g = garment_lookup.loc[product_id]

    row = {}

    row["height"] = p["height"]
    row["bust"] = p["bust"]
    row["waist"] = p["waist"]
    row["hips"] = p["hips"]

    row["garment_bust"] = g["garment_bust"]
    row["garment_waist"] = g["garment_waist"]
    row["garment_hip"] = g["garment_hip"]
    row["garment_length"] = g["garment_length"]
    row["garment_sleeve"] = g["garment_sleeve"]

    row["bust_ease"] = (
        g["garment_bust"] - p["bust"]
    )

    row["waist_ease"] = (
        g["garment_waist"] - p["waist"]
    )

    row["hip_ease"] = (
        g["garment_hip"] - p["hips"]
    )

    row["bust_ratio"] = (
        g["garment_bust"] / p["bust"]
    )

    row["waist_ratio"] = (
        g["garment_waist"] / p["waist"]
    )

    row["hip_ratio"] = (
        g["garment_hip"] / p["hips"]
    )

    row["bust_mismatch"] = abs(
        g["garment_bust"] - p["bust"]
    )

    row["waist_mismatch"] = abs(
        g["garment_waist"] - p["waist"]
    )

    row["hip_mismatch"] = abs(
        g["garment_hip"] - p["hips"]
    )

    row["bust_relative_mismatch"] = (
        row["bust_mismatch"] / p["bust"]
    )

    row["waist_relative_mismatch"] = (
        row["waist_mismatch"] / p["waist"]
    )

    row["hip_relative_mismatch"] = (
        row["hip_mismatch"] / p["hips"]
    )

    eases = np.array(
        [
            row["bust_ease"],
            row["waist_ease"],
            row["hip_ease"],
        ],
        dtype=float,
    )

    valid = eases[~np.isnan(eases)]

    if len(valid):

        row["mean_ease"] = np.mean(valid)
        row["ease_std"] = np.std(valid)

    else:

        row["mean_ease"] = np.nan
        row["ease_std"] = np.nan

    row["known_fit_dimensions"] = (
        np.sum(~np.isnan(eases))
    )

    row["tight_dimension_count"] = (
        np.sum(eases < 0)
    )

    row["extreme_ease_count"] = (
        np.sum(eases > 50)
    )

    if (
        pd.isna(g["garment_length"])
        or
        pd.isna(p["height"])
    ):

        row["length_height_ratio"] = np.nan

    else:

        row["length_height_ratio"] = (
            g["garment_length"]
            /
            p["height"]
        )

    return np.array(
        [row[f] for f in FEATURES],
        dtype=np.float32,
    )

# ============================================================
# PERSON-LEVEL SPLIT
# ============================================================

people = sorted(
    df["person_id"].unique()
)

train_people, temp_people = train_test_split(
    people,
    test_size=16,
    random_state=SEED,
)

val_people, test_people = train_test_split(
    temp_people,
    test_size=8,
    random_state=SEED,
)

train_people = set(train_people)
val_people = set(val_people)
test_people = set(test_people)

print("\n" + "=" * 70)
print("PERSON-LEVEL SPLIT")
print("=" * 70)

print("Train:", len(train_people))
print("Validation:", len(val_people))
print("Test:", len(test_people))

print(
    "Train ∩ Val:",
    train_people & val_people
)

print(
    "Train ∩ Test:",
    train_people & test_people
)

print(
    "Val ∩ Test:",
    val_people & test_people
)

# ============================================================
# SPLIT
# ============================================================

train_df = df[
    df["person_id"].isin(train_people)
].copy()

val_df = df[
    df["person_id"].isin(val_people)
].copy()

test_df = df[
    df["person_id"].isin(test_people)
].copy()

print("\nRows:")
print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

# ============================================================
# BUILD FEATURES
# ============================================================

def build_xy(frame):

    X = []
    y = []

    for _, row in frame.iterrows():

        X.append(
            make_features(
                row["person_id"],
                row["product_id"],
            )
        )

        y.append(
            row["training_label"]
        )

    return (
        np.asarray(X, dtype=np.float32),
        np.asarray(y, dtype=np.float32),
    )

X_train, y_train = build_xy(train_df)
X_val, y_val = build_xy(val_df)
X_test, y_test = build_xy(test_df)

# ============================================================
# IMPUTATION
# ============================================================

imputer = SimpleImputer(
    strategy="median"
)

imputer.fit(X_train)

X_train = imputer.transform(X_train)
X_val = imputer.transform(X_val)
X_test = imputer.transform(X_test)

# ============================================================
# SCALING
# ============================================================

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# ============================================================
# TENSORS
# ============================================================

X_train = torch.tensor(
    X_train,
    dtype=torch.float32,
    device=device,
)

y_train = torch.tensor(
    y_train,
    dtype=torch.float32,
    device=device,
)

X_val = torch.tensor(
    X_val,
    dtype=torch.float32,
    device=device,
)

y_val = torch.tensor(
    y_val,
    dtype=torch.float32,
    device=device,
)

X_test = torch.tensor(
    X_test,
    dtype=torch.float32,
    device=device,
)

y_test = torch.tensor(
    y_test,
    dtype=torch.float32,
    device=device,
)

print("\n" + "=" * 70)
print("TENSORS")
print("=" * 70)

print("Feature dimension:", X_train.shape[1])
print("Train:", X_train.shape)
print("Val:", X_val.shape)
print("Test:", X_test.shape)

print(
    "NaN:",
    torch.isnan(X_train).sum().item()
    +
    torch.isnan(X_val).sum().item()
    +
    torch.isnan(X_test).sum().item()
)

# ============================================================
# MODEL
# ============================================================

class CompatibilityRanker(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)


model = CompatibilityRanker(
    X_train.shape[1]
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LR,
    weight_decay=1e-4,
)

criterion = nn.BCEWithLogitsLoss()

print("\n" + "=" * 70)
print("MODEL")
print("=" * 70)

print(
    "Input dimension:",
    X_train.shape[1]
)

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)

# ============================================================
# TRAINING
# ============================================================

print("\n" + "=" * 70)
print("TRAINING")
print("=" * 70)

best_val_loss = float("inf")
best_state = None

for epoch in range(
    1,
    EPOCHS + 1
):

    model.train()

    optimizer.zero_grad()

    logits = model(
        X_train
    )

    loss = criterion(
        logits,
        y_train,
    )

    loss.backward()

    optimizer.step()

    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------

    model.eval()

    with torch.no_grad():

        val_logits = model(
            X_val
        )

        val_loss = criterion(
            val_logits,
            y_val,
        )

        train_pred = (
            torch.sigmoid(logits)
            >= 0.5
        )

        val_pred = (
            torch.sigmoid(val_logits)
            >= 0.5
        )

        train_acc = (
            train_pred
            ==
            y_train.bool()
        ).float().mean().item()

        val_acc = (
            val_pred
            ==
            y_val.bool()
        ).float().mean().item()

    # --------------------------------------------------------
    # Checkpoint
    # --------------------------------------------------------

    if val_loss.item() < best_val_loss:

        best_val_loss = (
            val_loss.item()
        )

        best_state = {
            k: v.detach()
            .cpu()
            .clone()

            for k, v
            in model.state_dict().items()
        }

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d}/{EPOCHS} "
            f"| Loss: {loss.item():.4f} "
            f"| Train Acc: {train_acc:.4f} "
            f"| Val Loss: {val_loss.item():.4f} "
            f"| Val Acc: {val_acc:.4f}"
        )

# ============================================================
# RESTORE BEST MODEL
# ============================================================

model.load_state_dict(
    best_state
)

model.eval()

# ============================================================
# FINAL SCORES
# ============================================================

with torch.no_grad():

    train_prob = torch.sigmoid(
        model(X_train)
    )

    val_prob = torch.sigmoid(
        model(X_val)
    )

    test_prob = torch.sigmoid(
        model(X_test)
    )

# ============================================================
# ACCURACY
# ============================================================

train_acc = (
    (train_prob >= 0.5)
    ==
    y_train.bool()
).float().mean().item()

val_acc = (
    (val_prob >= 0.5)
    ==
    y_val.bool()
).float().mean().item()

test_acc = (
    (test_prob >= 0.5)
    ==
    y_test.bool()
).float().mean().item()

# ============================================================
# SCORE SEPARATION
# ============================================================

test_prob_np = (
    test_prob
    .detach()
    .cpu()
    .numpy()
)

y_test_np = (
    y_test
    .detach()
    .cpu()
    .numpy()
)

positive_scores = (
    test_prob_np[
        y_test_np == 1
    ]
)

negative_scores = (
    test_prob_np[
        y_test_np == 0
    ]
)

# ============================================================
# RESULTS
# ============================================================

print("\n" + "=" * 70)
print("FINAL V2 RESULTS")
print("=" * 70)

print(
    "Train Accuracy:",
    f"{train_acc:.4f}"
)

print(
    "Validation Accuracy:",
    f"{val_acc:.4f}"
)

print(
    "Test Accuracy:",
    f"{test_acc:.4f}"
)

print(
    "\nPositive score mean:",
    f"{positive_scores.mean():.4f}"
)

print(
    "Negative score mean:",
    f"{negative_scores.mean():.4f}"
)

print(
    "Score gap:",
    f"{positive_scores.mean() - negative_scores.mean():.4f}"
)

# ============================================================
# SAVE MODEL
# ============================================================

torch.save(
    {
        "model_state_dict":
            model.state_dict(),

        "feature_names":
            FEATURES,

        "input_dim":
            len(FEATURES),

        "train_people":
            sorted(train_people),

        "val_people":
            sorted(val_people),

        "test_people":
            sorted(test_people),

        "imputer_statistics":
            imputer.statistics_,

        "scaler_mean":
            scaler.mean_,

        "scaler_scale":
            scaler.scale_,

        "seed":
            SEED,

        "dataset":
            "v2_confident_training_dataset",
    },
    MODEL_PATH,
)

print("\n" + "=" * 70)
print("MODEL SAVED")
print("=" * 70)

print(
    MODEL_PATH
)

print(
    "\nZYRA V2 STEP 3 COMPLETE"
)

======================================================================
ZYRA V2 — STEP 3 MODEL TRAINING
======================================================================
Device: mps

Training rows: 13683
People: 56

Labels:
training_label
0    10693
1     2990
Name: count, dtype: int64

======================================================================
PERSON-LEVEL SPLIT
======================================================================
Train: 40
Validation: 8
Test: 8
Train ∩ Val: set()
Train ∩ Test: set()
Val ∩ Test: set()

Rows:
Train: 10346
Val: 1518
Test: 1819

======================================================================
TENSORS
======================================================================
Feature dimension: 27
Train: torch.Size([10346, 27])
Val: torch.Size([1518, 27])
Test: torch.Size([1819, 27])
NaN: 0

======================================================================
MODEL
======================================================================
Input dimension: 27
Parameters: 3905

======================================================================
TRAINING
======================================================================
Epoch 01/50 | Loss: 0.6785 | Train Acc: 0.7100 | Val Loss: 0.6724 | Val Acc: 0.7167
Epoch 05/50 | Loss: 0.6445 | Train Acc: 0.8004 | Val Loss: 0.6411 | Val Acc: 0.7635
Epoch 10/50 | Loss: 0.6075 | Train Acc: 0.7827 | Val Loss: 0.6077 | Val Acc: 0.7497
Epoch 15/50 | Loss: 0.5731 | Train Acc: 0.7811 | Val Loss: 0.5790 | Val Acc: 0.7490
Epoch 20/50 | Loss: 0.5392 | Train Acc: 0.7812 | Val Loss: 0.5555 | Val Acc: 0.7490
Epoch 25/50 | Loss: 0.5086 | Train Acc: 0.7839 | Val Loss: 0.5410 | Val Acc: 0.7549
Epoch 30/50 | Loss: 0.4851 | Train Acc: 0.7910 | Val Loss: 0.5388 | Val Acc: 0.7589
Epoch 35/50 | Loss: 0.4697 | Train Acc: 0.7978 | Val Loss: 0.5456 | Val Acc: 0.7681
Epoch 40/50 | Loss: 0.4596 | Train Acc: 0.8094 | Val Loss: 0.5528 | Val Acc: 0.7734
Epoch 45/50 | Loss: 0.4509 | Train Acc: 0.8152 | Val Loss: 0.5545 | Val Acc: 0.7872
Epoch 50/50 | Loss: 0.4420 | Train Acc: 0.8253 | Val Loss: 0.5512 | Val Acc: 0.7846

======================================================================
FINAL V2 RESULTS
======================================================================
Train Accuracy: 0.7895
Validation Accuracy: 0.7576
Test Accuracy: 0.8131

Positive score mean: 0.3523
Negative score mean: 0.2468
Score gap: 0.1055

======================================================================
MODEL SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_compatibility_ranker.pt

ZYRA V2 STEP 3 COMPLETE

In [75]:
# ============================================================
# ZYRA V2 — STEP 4
# FULL PERSON × GARMENT TOP-K RANKING EVALUATION
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_compatibility_ranker.pt"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_topk_ranking_results.csv"
)

# ============================================================
# DEVICE
# ============================================================

device = (
    torch.device("mps")
    if torch.backends.mps.is_available()
    else torch.device("cpu")
)

print("=" * 70)
print("ZYRA V2 — FULL TOP-K RANKING EVALUATION")
print("=" * 70)

print("Device:", device)

# ============================================================
# LOAD DATA
# ============================================================

candidates = pd.read_csv(
    CANDIDATE_PATH
)

raw = pd.read_csv(
    RAW_PATH
)

checkpoint = torch.load(
    MODEL_PATH,
    map_location=device,
    weights_only=False,
)

FEATURES = checkpoint[
    "feature_names"
]

TEST_PEOPLE = set(
    checkpoint[
        "test_people"
    ]
)

print(
    "\nCandidate rows:",
    len(candidates)
)

print(
    "People:",
    candidates[
        "person_id"
    ].nunique()
)

print(
    "Garments:",
    candidates[
        "product_id"
    ].nunique()
)

print(
    "Held-out test people:",
    len(TEST_PEOPLE)
)

print(
    "Test people:",
    sorted(TEST_PEOPLE)
)

# ============================================================
# MODEL
# ============================================================

class CompatibilityRanker(nn.Module):

    def __init__(self, input_dim):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)


model = CompatibilityRanker(
    len(FEATURES)
)

model.load_state_dict(
    checkpoint[
        "model_state_dict"
    ]
)

model = model.to(device)
model.eval()

# ============================================================
# IMPUTER / SCALER
# ============================================================

imputer_statistics = np.asarray(
    checkpoint[
        "imputer_statistics"
    ],
    dtype=np.float32,
)

scaler_mean = np.asarray(
    checkpoint[
        "scaler_mean"
    ],
    dtype=np.float32,
)

scaler_scale = np.asarray(
    checkpoint[
        "scaler_scale"
    ],
    dtype=np.float32,
)

# ============================================================
# FEATURE MATRIX
# ============================================================

X = candidates[
    FEATURES
].copy()

# ------------------------------------------------------------
# Impute using TRAINING statistics
# ------------------------------------------------------------

for i, feature in enumerate(
    FEATURES
):

    X[feature] = (
        X[feature]
        .fillna(
            imputer_statistics[i]
        )
    )

# ------------------------------------------------------------
# Scale using TRAINING statistics
# ------------------------------------------------------------

X = (
    X
    .to_numpy(
        dtype=np.float32
    )
)

X = (
    X
    -
    scaler_mean
)

X = (
    X
    /
    np.where(
        scaler_scale == 0,
        1.0,
        scaler_scale,
    )
)

# ============================================================
# PREDICT ALL CANDIDATES
# ============================================================

X_tensor = torch.tensor(
    X,
    dtype=torch.float32,
    device=device,
)

print("\n" + "=" * 70)
print("SCORING ALL CANDIDATES")
print("=" * 70)

with torch.no_grad():

    scores = (
        model(
            X_tensor
        )
        .detach()
        .cpu()
        .numpy()
    )

candidates[
    "model_score"
] = scores

print(
    "Scored rows:",
    len(scores)
)

# ============================================================
# TEST SET ONLY
# ============================================================

test_candidates = candidates[
    candidates[
        "person_id"
    ].isin(TEST_PEOPLE)
].copy()

print(
    "Test candidate rows:",
    len(test_candidates)
)

# ============================================================
# VERIFY 897 GARMENTS PER PERSON
# ============================================================

garment_counts = (
    test_candidates
    .groupby(
        "person_id"
    )[
        "product_id"
    ]
    .nunique()
)

print("\nGarments per test person:")
print(garment_counts)

assert (
    garment_counts == 897
).all()

# ============================================================
# RANK
# ============================================================

test_candidates[
    "rank"
] = (
    test_candidates
    .groupby(
        "person_id"
    )[
        "model_score"
    ]
    .rank(
        method="first",
        ascending=False,
    )
)

# ============================================================
# KNOWN POSITIVES
# ============================================================

test_candidates[
    "is_positive"
] = (
    test_candidates[
        "label_status"
    ]
    ==
    "positive"
)

# ============================================================
# METRIC FUNCTIONS
# ============================================================

def recall_at_k(
    ranks,
    total_positives,
    k,
):

    if total_positives == 0:
        return np.nan

    hits = np.sum(
        ranks <= k
    )

    return (
        hits
        /
        total_positives
    )


def average_precision_at_k(
    ranks,
    total_positives,
    k,
):

    if total_positives == 0:
        return np.nan

    sorted_ranks = np.sort(
        ranks
    )

    hits = 0
    precision_sum = 0.0

    for rank in sorted_ranks:

        if rank > k:
            break

        hits += 1

        precision_sum += (
            hits
            /
            rank
        )

    return (
        precision_sum
        /
        min(
            total_positives,
            k,
        )
    )


def ndcg_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:
        return 0.0

    dcg = 0.0

    for rank in ranks:

        if rank <= k:

            dcg += (
                1.0
                /
                np.log2(
                    rank + 1
                )
            )

    ideal_count = min(
        len(ranks),
        k,
    )

    if ideal_count == 0:
        return 0.0

    idcg = sum(
        1.0
        /
        np.log2(
            i + 2
        )

        for i in range(
            ideal_count
        )
    )

    return dcg / idcg


def mrr(
    ranks
):

    if len(ranks) == 0:
        return 0.0

    return (
        1.0
        /
        np.min(ranks)
    )

# ============================================================
# PER PERSON EVALUATION
# ============================================================

results = []

print("\n" + "=" * 70)
print("PER-PERSON TOP-K RESULTS")
print("=" * 70)

for person_id, group in (
    test_candidates
    .groupby(
        "person_id"
    )
):

    positive_ranks = (
        group[
            group[
                "is_positive"
            ]
        ][
            "rank"
        ]
        .to_numpy()
    )

    total_positives = len(
        positive_ranks
    )

    result = {
        "person_id":
            person_id,

        "positive_count":
            total_positives,

        "recall@5":
            recall_at_k(
                positive_ranks,
                total_positives,
                5,
            ),

        "recall@10":
            recall_at_k(
                positive_ranks,
                total_positives,
                10,
            ),

        "recall@20":
            recall_at_k(
                positive_ranks,
                total_positives,
                20,
            ),

        "recall@50":
            recall_at_k(
                positive_ranks,
                total_positives,
                50,
            ),

        "recall@100":
            recall_at_k(
                positive_ranks,
                total_positives,
                100,
            ),

        "ndcg@10":
            ndcg_at_k(
                positive_ranks,
                10,
            ),

        "ndcg@20":
            ndcg_at_k(
                positive_ranks,
                20,
            ),

        "mrr":
            mrr(
                positive_ranks
            ),

        "average_precision@20":
            average_precision_at_k(
                positive_ranks,
                total_positives,
                20,
            ),

        "best_positive_rank":
            np.min(
                positive_ranks
            )
            if total_positives
            else np.nan,

        "median_positive_rank":
            np.median(
                positive_ranks
            )
            if total_positives
            else np.nan,
    }

    results.append(
        result
    )

results_df = pd.DataFrame(
    results
)

# ============================================================
# GLOBAL METRICS
# ============================================================

print("\n" + "=" * 70)
print("GLOBAL TOP-K RESULTS")
print("=" * 70)

metric_columns = [
    "recall@5",
    "recall@10",
    "recall@20",
    "recall@50",
    "recall@100",
    "ndcg@10",
    "ndcg@20",
    "mrr",
    "average_precision@20",
]

global_metrics = (
    results_df[
        metric_columns
    ]
    .mean()
)

for metric, value in (
    global_metrics.items()
):

    print(
        f"{metric:25s}: "
        f"{value:.4f}"
    )

# ============================================================
# POSITIVE RANK DISTRIBUTION
# ============================================================

all_positive_ranks = (
    test_candidates[
        test_candidates[
            "is_positive"
        ]
    ][
        "rank"
    ]
    .to_numpy()
)

print("\n" + "=" * 70)
print("POSITIVE RANK DISTRIBUTION")
print("=" * 70)

print(
    pd.Series(
        all_positive_ranks
    ).describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
        ]
    )
)

# ============================================================
# POSITIVES FOUND IN TOP K
# ============================================================

print("\n" + "=" * 70)
print("KNOWN POSITIVES FOUND IN TOP-K")
print("=" * 70)

total_positive_count = len(
    all_positive_ranks
)

for k in [
    1,
    5,
    10,
    20,
    50,
    100,
]:

    count = np.sum(
        all_positive_ranks
        <= k
    )

    percentage = (
        count
        /
        total_positive_count
        *
        100
    )

    print(
        f"Top-{k:3d}: "
        f"{count:4d} / "
        f"{total_positive_count} "
        f"({percentage:.2f}%)"
    )

# ============================================================
# TOP 10 RECOMMENDATIONS PER TEST PERSON
# ============================================================

print("\n" + "=" * 70)
print("TOP 10 RECOMMENDATIONS")
print("=" * 70)

top10 = (
    test_candidates[
        test_candidates[
            "rank"
        ] <= 10
    ]
    .sort_values(
        [
            "person_id",
            "rank",
        ]
    )
)

for person_id, group in (
    top10
    .groupby(
        "person_id"
    )
):

    print(
        f"\nPerson: {person_id}"
    )

    display(
        group[
            [
                "rank",
                "product_id",
                "model_score",
                "is_positive",
                "physical_mismatch",
                "garment_bust",
                "garment_waist",
                "garment_hip",
                "garment_length",
                "garment_sleeve",
            ]
        ]
    )

# ============================================================
# POSITIVE RANKS PER PERSON
# ============================================================

print("\n" + "=" * 70)
print("POSITIVE RANKS PER PERSON")
print("=" * 70)

for _, row in (
    results_df
    .sort_values(
        "person_id"
    )
    .iterrows()
):

    print(
        f"{row['person_id']}: "
        f"positives={int(row['positive_count'])} | "
        f"best={int(row['best_positive_rank'])} | "
        f"median={row['median_positive_rank']:.1f} | "
        f"R@10={row['recall@10']:.3f} | "
        f"NDCG@10={row['ndcg@10']:.3f}"
    )

# ============================================================
# SAVE RESULTS
# ============================================================

results_df.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("TOP-K EVALUATION SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print(
    "\nZYRA V2 STEP 4 COMPLETE"
)

======================================================================
ZYRA V2 — FULL TOP-K RANKING EVALUATION
======================================================================
Device: mps

Candidate rows: 50232
People: 56
Garments: 897
Held-out test people: 8
Test people: ['Alex', 'Anna Maria', 'Bree', 'Chesska', 'Emma', 'Maddy', 'Palatina', 'Sophie']

======================================================================
SCORING ALL CANDIDATES
======================================================================
Scored rows: 50232
Test candidate rows: 7176

Garments per test person:
person_id
Alex          897
Anna Maria    897
Bree          897
Chesska       897
Emma          897
Maddy         897
Palatina      897
Sophie        897
Name: product_id, dtype: int64

======================================================================
PER-PERSON TOP-K RESULTS
======================================================================

======================================================================
GLOBAL TOP-K RESULTS
======================================================================
recall@5                 : 0.0000
recall@10                : 0.0000
recall@20                : 0.0049
recall@50                : 0.0389
recall@100               : 0.0759
ndcg@10                  : 0.0000
ndcg@20                  : 0.0084
mrr                      : 0.0361
average_precision@20     : 0.0007

======================================================================
POSITIVE RANK DISTRIBUTION
======================================================================
count    339.000000
mean     482.327434
std      224.376326
min       16.000000
25%      348.000000
50%      521.000000
75%      645.000000
90%      743.400000
95%      818.500000
max      897.000000
dtype: float64

======================================================================
KNOWN POSITIVES FOUND IN TOP-K
======================================================================
Top-  1:    0 / 339 (0.00%)
Top-  5:    0 / 339 (0.00%)
Top- 10:    0 / 339 (0.00%)
Top- 20:    2 / 339 (0.59%)
Top- 50:   13 / 339 (3.83%)
Top-100:   31 / 339 (9.14%)

======================================================================
TOP 10 RECOMMENDATIONS
======================================================================

Person: Alex

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
37572,1.0,bamboo-layer-tank#Chalk,-0.090018,False,0.158717,72.0,74.0,72.0,67.0,NaN
37577,2.0,bamboo-layer-tank#Black,-0.090018,False,0.158717,72.0,74.0,72.0,67.0,NaN
36832,3.0,the-boat-neck-top#Navy,-0.151126,False,0.262284,57.0,53.0,62.0,62.0,64.0
37191,4.0,the-boat-neck-top#Black,-0.151126,False,0.262284,57.0,53.0,62.0,62.0,64.0
36835,5.0,monaco-knot-top#Black,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
36973,6.0,monaco-knot-top#Olive,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
37262,7.0,monaco-knot-top#ClaySpot,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
37519,8.0,monaco-knot-top#HeatheGrey,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
37446,9.0,pure-merino-fine-rib-polo#BlackStri,-0.168359,False,0.132264,92.0,80.0,90.0,68.0,69.0
37136,10.0,back-to-you-top#Rust,-0.214765,False,0.184347,92.0,90.0,90.0,72.0,55.0

Person: Anna Maria

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
34881,1.0,bamboo-layer-tank#Chalk,-0.063937,False,0.166369,72.0,74.0,72.0,67.0,NaN
34886,2.0,bamboo-layer-tank#Black,-0.063937,False,0.166369,72.0,74.0,72.0,67.0,NaN
34144,3.0,monaco-knot-top#Black,-0.124684,False,0.100066,86.0,76.0,82.0,64.0,70.0
34282,4.0,monaco-knot-top#Olive,-0.124684,False,0.100066,86.0,76.0,82.0,64.0,70.0
34571,5.0,monaco-knot-top#ClaySpot,-0.124684,False,0.100066,86.0,76.0,82.0,64.0,70.0
34828,6.0,monaco-knot-top#HeatheGrey,-0.124684,False,0.100066,86.0,76.0,82.0,64.0,70.0
34141,7.0,the-boat-neck-top#Navy,-0.166958,False,0.268138,57.0,53.0,62.0,62.0,64.0
34500,8.0,the-boat-neck-top#Black,-0.166958,False,0.268138,57.0,53.0,62.0,62.0,64.0
34840,9.0,henson-jumper#Cream,-0.191394,False,0.126389,84.0,84.0,84.0,56.0,68.0
34413,10.0,faith-jumper#Eventide,-0.204216,False,0.209127,94.0,88.0,78.0,62.0,70.0

Person: Bree

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
41344,1.0,pure-merino-fine-rib-v-neck#Charcoal,0.073433,False,0.102788,86.0,76.0,94.0,NaN,70.0
42057,2.0,bamboo-layer-tank#Chalk,0.073304,False,0.209203,72.0,74.0,72.0,67.0,NaN
42062,3.0,bamboo-layer-tank#Black,0.073304,False,0.209203,72.0,74.0,72.0,67.0,NaN
41320,4.0,monaco-knot-top#Black,0.065282,False,0.140171,86.0,76.0,82.0,64.0,70.0
41458,5.0,monaco-knot-top#Olive,0.065282,False,0.140171,86.0,76.0,82.0,64.0,70.0
41747,6.0,monaco-knot-top#ClaySpot,0.065282,False,0.140171,86.0,76.0,82.0,64.0,70.0
42004,7.0,monaco-knot-top#HeatheGrey,0.065282,False,0.140171,86.0,76.0,82.0,64.0,70.0
41931,8.0,pure-merino-fine-rib-polo#BlackStri,0.061554,False,0.113566,92.0,80.0,90.0,68.0,69.0
41618,9.0,the-reversible-cowl-neck-top-2#Ocean,0.058242,False,0.106493,95.0,82.0,92.0,63.0,49.0
41621,10.0,back-to-you-top#Rust,0.057752,False,0.159862,92.0,90.0,90.0,72.0,55.0

Person: Chesska

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
14250,1.0,bamboo-layer-tank#Chalk,-0.020527,False,0.165839,72.0,74.0,72.0,67.0,NaN
14255,2.0,bamboo-layer-tank#Black,-0.020527,False,0.165839,72.0,74.0,72.0,67.0,NaN
13513,3.0,monaco-knot-top#Black,-0.043241,False,0.087606,86.0,76.0,82.0,64.0,70.0
13651,4.0,monaco-knot-top#Olive,-0.043241,False,0.087606,86.0,76.0,82.0,64.0,70.0
13940,5.0,monaco-knot-top#ClaySpot,-0.043241,False,0.087606,86.0,76.0,82.0,64.0,70.0
14197,6.0,monaco-knot-top#HeatheGrey,-0.043241,False,0.087606,86.0,76.0,82.0,64.0,70.0
13944,7.0,holly-rib-long-sleeve-tee#Khaki,-0.058710,False,0.100454,86.0,86.0,92.0,65.0,66.0
13962,8.0,holly-rib-long-sleeve-tee#WhiteGrey,-0.058710,False,0.100454,86.0,86.0,92.0,65.0,66.0
14203,9.0,holly-rib-long-sleeve-tee#Black,-0.058710,False,0.100454,86.0,86.0,92.0,65.0,66.0
14209,10.0,henson-jumper#Cream,-0.072276,False,0.126651,84.0,84.0,84.0,56.0,68.0

Person: Emma

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
8868,1.0,bamboo-layer-tank#Chalk,-0.090018,False,0.158717,72.0,74.0,72.0,67.0,NaN
8873,2.0,bamboo-layer-tank#Black,-0.090018,False,0.158717,72.0,74.0,72.0,67.0,NaN
8128,3.0,the-boat-neck-top#Navy,-0.151126,False,0.262284,57.0,53.0,62.0,62.0,64.0
8487,4.0,the-boat-neck-top#Black,-0.151126,False,0.262284,57.0,53.0,62.0,62.0,64.0
8131,5.0,monaco-knot-top#Black,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
8269,6.0,monaco-knot-top#Olive,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
8558,7.0,monaco-knot-top#ClaySpot,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
8815,8.0,monaco-knot-top#HeatheGrey,-0.166716,False,0.116043,86.0,76.0,82.0,64.0,70.0
8742,9.0,pure-merino-fine-rib-polo#BlackStri,-0.168359,False,0.132264,92.0,80.0,90.0,68.0,69.0
8432,10.0,back-to-you-top#Rust,-0.214765,False,0.184347,92.0,90.0,90.0,72.0,55.0

Person: Maddy

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
13353,1.0,bamboo-layer-tank#Chalk,0.000711,False,0.169021,72.0,74.0,72.0,67.0,NaN
13358,2.0,bamboo-layer-tank#Black,0.000711,False,0.169021,72.0,74.0,72.0,67.0,NaN
12616,3.0,monaco-knot-top#Black,-0.043446,False,0.091278,86.0,76.0,82.0,64.0,70.0
12754,4.0,monaco-knot-top#Olive,-0.043446,False,0.091278,86.0,76.0,82.0,64.0,70.0
13043,5.0,monaco-knot-top#ClaySpot,-0.043446,False,0.091278,86.0,76.0,82.0,64.0,70.0
13300,6.0,monaco-knot-top#HeatheGrey,-0.043446,False,0.091278,86.0,76.0,82.0,64.0,70.0
13227,7.0,pure-merino-fine-rib-polo#BlackStri,-0.050315,False,0.107178,92.0,80.0,90.0,68.0,69.0
12914,8.0,the-reversible-cowl-neck-top-2#Ocean,-0.054207,False,0.121730,95.0,82.0,92.0,63.0,49.0
12640,9.0,pure-merino-fine-rib-v-neck#Charcoal,-0.057216,False,0.051674,86.0,76.0,94.0,NaN,70.0
12730,10.0,glasgow-top#Melange,-0.057858,False,0.110102,92.0,82.0,92.0,65.0,70.0

Person: Palatina

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
17153,1.0,manhattan-stretch-tee#White,0.096927,False,0.057346,94.0,92.0,104.0,65.0,29.0
17233,2.0,manhattan-stretch-tee#Navy,0.096927,False,0.057346,94.0,92.0,104.0,65.0,29.0
17421,3.0,manhattan-stretch-tee#Black,0.096927,False,0.057346,94.0,92.0,104.0,65.0,29.0
17526,4.0,manhattan-stretch-tee#NavyWhtStr,0.096927,False,0.057346,94.0,92.0,104.0,65.0,29.0
17532,5.0,holly-rib-long-sleeve-tee#Khaki,0.096767,False,0.097725,86.0,86.0,92.0,65.0,66.0
17550,6.0,holly-rib-long-sleeve-tee#WhiteGrey,0.096767,False,0.097725,86.0,86.0,92.0,65.0,66.0
17791,7.0,holly-rib-long-sleeve-tee#Black,0.096767,False,0.097725,86.0,86.0,92.0,65.0,66.0
17402,8.0,back-to-you-top#Rust,0.093363,False,0.099096,92.0,90.0,90.0,72.0,55.0
17406,9.0,back-to-you-top#BlackMagic,0.093363,False,0.099096,92.0,90.0,90.0,72.0,55.0
17790,10.0,ally-long-sleeve-tee#CosmosPr,0.091033,False,0.084736,88.0,86.0,94.0,64.0,71.0

Person: Sophie

,rank,product_id,model_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
16823,1.0,elina-lace-frill-blouse#Black,0.161372,False,0.188476,90.0,90.0,102.0,64.0,70.0
16967,2.0,ricki-one-shoulder-top#BlackWhite,0.160063,False,0.164705,92.0,94.0,104.0,66.0,70.0
16484,3.0,long-sleeve-tee-2#NavyWhite,0.159756,False,0.188987,92.0,88.0,102.0,64.0,66.0
16714,4.0,analia-top#White,0.157374,False,0.187116,90.0,92.0,100.0,68.0,NaN
16533,5.0,meadow-cardigan#Cream,0.153769,False,0.097256,104.0,104.0,104.0,107.0,70.0
16997,6.0,high-neck-tie-top#Black,0.152667,False,0.220816,82.0,92.0,96.0,60.0,NaN
16893,7.0,ally-long-sleeve-tee#CosmosPr,0.151542,False,0.227398,88.0,86.0,94.0,64.0,71.0
16443,8.0,germaine-blouse#Pearl,0.151457,False,0.109566,102.0,102.0,104.0,69.0,75.0
16292,9.0,hayley-button-down#NavySparro,0.150238,False,0.124595,100.0,96.0,108.0,66.0,73.0
16832,10.0,cherrington-top#GreyRose,0.150149,False,0.135035,96.0,98.0,106.0,65.0,69.0

======================================================================
POSITIVE RANKS PER PERSON
======================================================================
Alex: positives=37 | best=21 | median=508.0 | R@10=0.000 | NDCG@10=0.000
Anna Maria: positives=18 | best=304 | median=392.0 | R@10=0.000 | NDCG@10=0.000
Bree: positives=6 | best=201 | median=203.5 | R@10=0.000 | NDCG@10=0.000
Chesska: positives=11 | best=25 | median=266.0 | R@10=0.000 | NDCG@10=0.000
Emma: positives=87 | best=27 | median=595.0 | R@10=0.000 | NDCG@10=0.000
Maddy: positives=77 | best=23 | median=444.0 | R@10=0.000 | NDCG@10=0.000
Palatina: positives=49 | best=16 | median=516.0 | R@10=0.000 | NDCG@10=0.000
Sophie: positives=54 | best=20 | median=546.5 | R@10=0.000 | NDCG@10=0.000

======================================================================
TOP-K EVALUATION SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_topk_ranking_results.csv

ZYRA V2 STEP 4 COMPLETE

In [76]:
# ============================================================
# ZYRA V2.1 — RELATIONSHIP-ONLY PAIRWISE RANKER
# ============================================================
#
# Goal:
# Prevent the model from learning global garment-size shortcuts.
#
# Model sees:
#   person ↔ garment relationships
#
# Model does NOT directly see:
#   raw person measurements
#   raw garment measurements
#
# Evaluation:
#   8 completely unseen people
#   × 897 garments
#   → full ranking
#
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

DATA_PATH = (
    BASE /
    "data/v2/v2_confident_training_dataset.csv"
)

CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_compatibility_ranker_v21.pt"
)

RANKING_OUTPUT = (
    BASE /
    "data/v2/v2_v21_topk_results.csv"
)

SEED = 42
EPOCHS = 75
LR = 5e-4

np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================
# DEVICE
# ============================================================

device = (
    torch.device("mps")
    if torch.backends.mps.is_available()
    else torch.device("cpu")
)

print("=" * 70)
print("ZYRA V2.1 — RELATIONSHIP-ONLY RANKER")
print("=" * 70)

print("Device:", device)

# ============================================================
# LOAD
# ============================================================

train_df = pd.read_csv(
    DATA_PATH
)

candidates = pd.read_csv(
    CANDIDATE_PATH
)

print(
    "\nTraining rows:",
    len(train_df)
)

print(
    "Candidate rows:",
    len(candidates)
)

print(
    "People:",
    candidates["person_id"].nunique()
)

print(
    "Garments:",
    candidates["product_id"].nunique()
)

# ============================================================
# RELATIONSHIP FEATURES
# ============================================================
#
# IMPORTANT:
#
# No raw:
#   height
#   bust
#   waist
#   hips
#   garment_bust
#   garment_waist
#   garment_hip
#   garment_length
#   garment_sleeve
#
# are given directly to the model.
#
# Only person-garment relationships are used.
# ============================================================

FEATURES = [

    # --------------------------------------------------------
    # Absolute ease
    # --------------------------------------------------------

    "bust_ease",
    "waist_ease",
    "hip_ease",

    # --------------------------------------------------------
    # Relative fit
    # --------------------------------------------------------

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    # --------------------------------------------------------
    # Absolute mismatch
    # --------------------------------------------------------

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    # --------------------------------------------------------
    # Aggregate relationship features
    # --------------------------------------------------------

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",

    "tight_dimension_count",

    "extreme_ease_count",

    "length_height_ratio",

    # --------------------------------------------------------
    # NEW NONLINEAR FIT FEATURES
    # --------------------------------------------------------

    "abs_mean_ease",
    "positive_ease_count",
    "negative_ease_count",

    "max_relative_mismatch",
    "mean_relative_mismatch",

    # --------------------------------------------------------
    # FIT BALANCE
    # --------------------------------------------------------

    "bust_hip_balance",
    "bust_waist_balance",
    "waist_hip_balance",

    # --------------------------------------------------------
    # SOFT FIT PENALTY
    # --------------------------------------------------------

    "soft_fit_penalty",

]

print(
    "\nFeature count:",
    len(FEATURES)
)

# ============================================================
# FEATURE BUILDER
# ============================================================

def build_relationship_features(
    person_id,
    product_id,
    people_lookup,
    garment_lookup,
):

    p = people_lookup.loc[
        person_id
    ]

    g = garment_lookup.loc[
        product_id
    ]

    # --------------------------------------------------------
    # Raw relationships
    # --------------------------------------------------------

    bust_ease = (
        g["garment_bust"]
        -
        p["bust"]
    )

    waist_ease = (
        g["garment_waist"]
        -
        p["waist"]
    )

    hip_ease = (
        g["garment_hip"]
        -
        p["hips"]
    )

    # --------------------------------------------------------
    # Ratios
    # --------------------------------------------------------

    bust_ratio = (
        g["garment_bust"]
        /
        p["bust"]
    )

    waist_ratio = (
        g["garment_waist"]
        /
        p["waist"]
    )

    hip_ratio = (
        g["garment_hip"]
        /
        p["hips"]
    )

    # --------------------------------------------------------
    # Absolute mismatch
    # --------------------------------------------------------

    bust_mismatch = abs(
        bust_ease
    )

    waist_mismatch = abs(
        waist_ease
    )

    hip_mismatch = abs(
        hip_ease
    )

    # --------------------------------------------------------
    # Relative mismatch
    # --------------------------------------------------------

    bust_relative = (
        bust_mismatch
        /
        p["bust"]
    )

    waist_relative = (
        waist_mismatch
        /
        p["waist"]
    )

    hip_relative = (
        hip_mismatch
        /
        p["hips"]
    )

    # --------------------------------------------------------
    # Ease vector
    # --------------------------------------------------------

    eases = np.array(
        [
            bust_ease,
            waist_ease,
            hip_ease,
        ],
        dtype=float,
    )

    valid_eases = (
        eases[
            ~np.isnan(eases)
        ]
    )

    if len(valid_eases) > 0:

        mean_ease = (
            np.mean(
                valid_eases
            )
        )

        ease_std = (
            np.std(
                valid_eases
            )
        )

        abs_mean_ease = (
            np.mean(
                np.abs(
                    valid_eases
                )
            )
        )

        positive_ease_count = (
            np.sum(
                valid_eases > 0
            )
        )

        negative_ease_count = (
            np.sum(
                valid_eases < 0
            )
        )

    else:

        mean_ease = np.nan
        ease_std = np.nan
        abs_mean_ease = np.nan
        positive_ease_count = 0
        negative_ease_count = 0

    # --------------------------------------------------------
    # Known dimensions
    # --------------------------------------------------------

    known_fit_dimensions = (
        np.sum(
            ~np.isnan(eases)
        )
    )

    # --------------------------------------------------------
    # Tight dimensions
    # --------------------------------------------------------

    tight_dimension_count = (
        np.sum(
            eases < 0
        )
    )

    # --------------------------------------------------------
    # Extreme ease
    # --------------------------------------------------------

    extreme_ease_count = (
        np.sum(
            eases > 50
        )
    )

    # --------------------------------------------------------
    # Relative mismatch vector
    # --------------------------------------------------------

    relative_mismatches = np.array(
        [
            bust_relative,
            waist_relative,
            hip_relative,
        ],
        dtype=float,
    )

    valid_relative = (
        relative_mismatches[
            ~np.isnan(
                relative_mismatches
            )
        ]
    )

    if len(valid_relative) > 0:

        max_relative_mismatch = (
            np.max(
                valid_relative
            )
        )

        mean_relative_mismatch = (
            np.mean(
                valid_relative
            )
        )

    else:

        max_relative_mismatch = np.nan
        mean_relative_mismatch = np.nan

    # --------------------------------------------------------
    # Length / height relationship
    # --------------------------------------------------------

    if (
        pd.isna(
            g["garment_length"]
        )
        or
        pd.isna(
            p["height"]
        )
        or
        p["height"] == 0
    ):

        length_height_ratio = np.nan

    else:

        length_height_ratio = (
            g["garment_length"]
            /
            p["height"]
        )

    # --------------------------------------------------------
    # Balance features
    # --------------------------------------------------------

    bust_hip_balance = (
        bust_relative
        -
        hip_relative
    )

    bust_waist_balance = (
        bust_relative
        -
        waist_relative
    )

    waist_hip_balance = (
        waist_relative
        -
        hip_relative
    )

    # --------------------------------------------------------
    # Soft fit penalty
    #
    # Penalizes large mismatch smoothly instead of using
    # binary tight/extreme flags alone.
    # --------------------------------------------------------

    valid_for_penalty = (
        relative_mismatches[
            ~np.isnan(
                relative_mismatches
            )
        ]
    )

    if len(valid_for_penalty) > 0:

        soft_fit_penalty = np.mean(
            np.square(
                valid_for_penalty
            )
        )

    else:

        soft_fit_penalty = np.nan

    # --------------------------------------------------------
    # RETURN
    # --------------------------------------------------------

    return {

        "bust_ease":
            bust_ease,

        "waist_ease":
            waist_ease,

        "hip_ease":
            hip_ease,

        "bust_ratio":
            bust_ratio,

        "waist_ratio":
            waist_ratio,

        "hip_ratio":
            hip_ratio,

        "bust_mismatch":
            bust_mismatch,

        "waist_mismatch":
            waist_mismatch,

        "hip_mismatch":
            hip_mismatch,

        "bust_relative_mismatch":
            bust_relative,

        "waist_relative_mismatch":
            waist_relative,

        "hip_relative_mismatch":
            hip_relative,

        "mean_ease":
            mean_ease,

        "ease_std":
            ease_std,

        "known_fit_dimensions":
            known_fit_dimensions,

        "tight_dimension_count":
            tight_dimension_count,

        "extreme_ease_count":
            extreme_ease_count,

        "length_height_ratio":
            length_height_ratio,

        "abs_mean_ease":
            abs_mean_ease,

        "positive_ease_count":
            positive_ease_count,

        "negative_ease_count":
            negative_ease_count,

        "max_relative_mismatch":
            max_relative_mismatch,

        "mean_relative_mismatch":
            mean_relative_mismatch,

        "bust_hip_balance":
            bust_hip_balance,

        "bust_waist_balance":
            bust_waist_balance,

        "waist_hip_balance":
            waist_hip_balance,

        "soft_fit_penalty":
            soft_fit_penalty,
    }


# ============================================================
# LOOKUPS
# ============================================================

people_lookup = (
    candidates[
        [
            "person_id",
            "height",
            "bust",
            "waist",
            "hips",
        ]
    ]
    .drop_duplicates(
        "person_id"
    )
    .set_index(
        "person_id"
    )
)

garment_lookup = (
    candidates[
        [
            "product_id",
            "garment_bust",
            "garment_waist",
            "garment_hip",
            "garment_length",
            "garment_sleeve",
        ]
    ]
    .drop_duplicates(
        "product_id"
    )
    .set_index(
        "product_id"
    )
)

# ============================================================
# BUILD TRAINING FEATURES
# ============================================================

print("\n" + "=" * 70)
print("BUILDING RELATIONSHIP FEATURES")
print("=" * 70)

def build_matrix(frame):

    X = []
    y = []

    for _, row in frame.iterrows():

        features = (
            build_relationship_features(
                row["person_id"],
                row["product_id"],
                people_lookup,
                garment_lookup,
            )
        )

        X.append(
            [
                features[f]
                for f in FEATURES
            ]
        )

        y.append(
            row["training_label"]
        )

    return (
        np.asarray(
            X,
            dtype=np.float32,
        ),
        np.asarray(
            y,
            dtype=np.float32,
        ),
    )

# ============================================================
# PERSON SPLIT
# ============================================================

people = sorted(
    train_df[
        "person_id"
    ]
    .unique()
)

train_people, temp_people = (
    train_test_split(
        people,
        test_size=16,
        random_state=SEED,
    )
)

val_people, test_people = (
    train_test_split(
        temp_people,
        test_size=8,
        random_state=SEED,
    )
)

train_people = set(
    train_people
)

val_people = set(
    val_people
)

test_people = set(
    test_people
)

print(
    "Train people:",
    len(train_people)
)

print(
    "Validation people:",
    len(val_people)
)

print(
    "Test people:",
    len(test_people)
)

# ============================================================
# SPLIT DATA
# ============================================================

train_split = train_df[
    train_df[
        "person_id"
    ].isin(
        train_people
    )
].copy()

val_split = train_df[
    train_df[
        "person_id"
    ].isin(
        val_people
    )
].copy()

test_split = train_df[
    train_df[
        "person_id"
    ].isin(
        test_people
    )
].copy()

print(
    "\nTraining rows:",
    len(train_split)
)

print(
    "Validation rows:",
    len(val_split)
)

print(
    "Test rows:",
    len(test_split)
)

# ============================================================
# BUILD
# ============================================================

X_train, y_train = build_matrix(
    train_split
)

X_val, y_val = build_matrix(
    val_split
)

X_test, y_test = build_matrix(
    test_split
)

# ============================================================
# IMPUTATION
# ============================================================

imputer = SimpleImputer(
    strategy="median"
)

imputer.fit(
    X_train
)

X_train = imputer.transform(
    X_train
)

X_val = imputer.transform(
    X_val
)

X_test = imputer.transform(
    X_test
)

# ============================================================
# SCALING
# ============================================================

scaler = StandardScaler()

scaler.fit(
    X_train
)

X_train = scaler.transform(
    X_train
)

X_val = scaler.transform(
    X_val
)

X_test = scaler.transform(
    X_test
)

print("\n" + "=" * 70)
print("FEATURE MATRICES")
print("=" * 70)

print(
    "Feature dimension:",
    X_train.shape[1]
)

print(
    "Train:",
    X_train.shape
)

print(
    "Val:",
    X_val.shape
)

print(
    "Test:",
    X_test.shape
)

print(
    "NaN:",
    np.isnan(
        X_train
    ).sum()
    +
    np.isnan(
        X_val
    ).sum()
    +
    np.isnan(
        X_test
    ).sum()
)

# ============================================================
# TENSORS
# ============================================================

X_train_t = torch.tensor(
    X_train,
    dtype=torch.float32,
    device=device,
)

y_train_t = torch.tensor(
    y_train,
    dtype=torch.float32,
    device=device,
)

X_val_t = torch.tensor(
    X_val,
    dtype=torch.float32,
    device=device,
)

y_val_t = torch.tensor(
    y_val,
    dtype=torch.float32,
    device=device,
)

X_test_t = torch.tensor(
    X_test,
    dtype=torch.float32,
    device=device,
)

y_test_t = torch.tensor(
    y_test,
    dtype=torch.float32,
    device=device,
)

# ============================================================
# MODEL
# ============================================================

class V21Ranker(nn.Module):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                64,
            ),

            nn.ReLU(),

            nn.Dropout(
                0.10
            ),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Dropout(
                0.10
            ),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)


model = V21Ranker(
    len(FEATURES)
).to(device)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LR,
    weight_decay=1e-3,
)

criterion = nn.BCEWithLogitsLoss()

print("\n" + "=" * 70)
print("MODEL")
print("=" * 70)

print(
    "Input dimension:",
    len(FEATURES)
)

print(
    "Parameters:",
    sum(
        p.numel()
        for p in model.parameters()
    )
)

# ============================================================
# TRAIN
# ============================================================

print("\n" + "=" * 70)
print("TRAINING")
print("=" * 70)

best_val_loss = float(
    "inf"
)

best_state = None

patience = 12
patience_counter = 0

for epoch in range(
    1,
    EPOCHS + 1,
):

    model.train()

    optimizer.zero_grad()

    train_logits = model(
        X_train_t
    )

    loss = criterion(
        train_logits,
        y_train_t,
    )

    loss.backward()

    optimizer.step()

    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------

    model.eval()

    with torch.no_grad():

        val_logits = model(
            X_val_t
        )

        val_loss = criterion(
            val_logits,
            y_val_t,
        )

        train_pred = (
            torch.sigmoid(
                train_logits
            )
            >= 0.5
        )

        val_pred = (
            torch.sigmoid(
                val_logits
            )
            >= 0.5
        )

        train_acc = (
            train_pred
            ==
            y_train_t.bool()
        ).float().mean().item()

        val_acc = (
            val_pred
            ==
            y_val_t.bool()
        ).float().mean().item()

    # --------------------------------------------------------
    # Best checkpoint
    # --------------------------------------------------------

    if (
        val_loss.item()
        <
        best_val_loss
    ):

        best_val_loss = (
            val_loss.item()
        )

        best_state = {
            k:
                v.detach()
                .cpu()
                .clone()

            for k, v
            in model.state_dict().items()
        }

        patience_counter = 0

    else:

        patience_counter += 1

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d}/{EPOCHS} "
            f"| Loss {loss.item():.4f} "
            f"| Train {train_acc:.4f} "
            f"| Val Loss {val_loss.item():.4f} "
            f"| Val {val_acc:.4f}"
        )

    if patience_counter >= patience:

        print(
            "\nEarly stopping at epoch",
            epoch,
        )

        break

# ============================================================
# RESTORE BEST
# ============================================================

model.load_state_dict(
    best_state
)

model.eval()

# ============================================================
# CLASSIFICATION RESULTS
# ============================================================

with torch.no_grad():

    train_scores = torch.sigmoid(
        model(
            X_train_t
        )
    ).cpu().numpy()

    val_scores = torch.sigmoid(
        model(
            X_val_t
        )
    ).cpu().numpy()

    test_scores = torch.sigmoid(
        model(
            X_test_t
        )
    ).cpu().numpy()

train_acc = (
    (
        train_scores >= 0.5
    )
    ==
    y_train.astype(bool)
).mean()

val_acc = (
    (
        val_scores >= 0.5
    )
    ==
    y_val.astype(bool)
).mean()

test_acc = (
    (
        test_scores >= 0.5
    )
    ==
    y_test.astype(bool)
).mean()

positive_scores = (
    test_scores[
        y_test == 1
    ]
)

negative_scores = (
    test_scores[
        y_test == 0
    ]
)

print("\n" + "=" * 70)
print("V2.1 CLASSIFICATION RESULTS")
print("=" * 70)

print(
    "Train accuracy:",
    f"{train_acc:.4f}"
)

print(
    "Validation accuracy:",
    f"{val_acc:.4f}"
)

print(
    "Test accuracy:",
    f"{test_acc:.4f}"
)

print(
    "Positive mean score:",
    f"{positive_scores.mean():.4f}"
)

print(
    "Negative mean score:",
    f"{negative_scores.mean():.4f}"
)

print(
    "Score gap:",
    f"{positive_scores.mean() - negative_scores.mean():.4f}"
)

# ============================================================
# FULL CANDIDATE MATRIX FEATURES
# ============================================================

print("\n" + "=" * 70)
print("SCORING ALL 50,232 CANDIDATES")
print("=" * 70)

candidate_features = []

for _, row in candidates.iterrows():

    features = (
        build_relationship_features(
            row["person_id"],
            row["product_id"],
            people_lookup,
            garment_lookup,
        )
    )

    candidate_features.append(
        [
            features[f]
            for f in FEATURES
        ]
    )

candidate_X = np.asarray(
    candidate_features,
    dtype=np.float32,
)

candidate_X = imputer.transform(
    candidate_X
)

candidate_X = scaler.transform(
    candidate_X
)

candidate_tensor = torch.tensor(
    candidate_X,
    dtype=torch.float32,
    device=device,
)

with torch.no_grad():

    candidate_scores = (
        torch.sigmoid(
            model(
                candidate_tensor
            )
        )
        .cpu()
        .numpy()
    )

candidates[
    "v21_score"
] = candidate_scores

# ============================================================
# RANK ALL GARMENTS FOR TEST PEOPLE
# ============================================================

test_candidates = candidates[
    candidates[
        "person_id"
    ].isin(
        test_people
    )
].copy()

test_candidates[
    "rank"
] = (
    test_candidates
    .groupby(
        "person_id"
    )[
        "v21_score"
    ]
    .rank(
        method="first",
        ascending=False,
    )
)

test_candidates[
    "is_positive"
] = (
    test_candidates[
        "label_status"
    ]
    ==
    "positive"
)

# ============================================================
# METRICS
# ============================================================

def recall_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:
        return 0.0

    return np.mean(
        ranks <= k
    )


def ndcg_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:
        return 0.0

    dcg = sum(
        1.0
        /
        np.log2(
            r + 1
        )

        for r in ranks
        if r <= k
    )

    ideal_count = min(
        len(ranks),
        k,
    )

    idcg = sum(
        1.0
        /
        np.log2(
            i + 2
        )

        for i in range(
            ideal_count
        )
    )

    if idcg == 0:
        return 0.0

    return dcg / idcg


def reciprocal_rank(
    ranks
):

    if len(ranks) == 0:
        return 0.0

    return (
        1.0
        /
        np.min(ranks)
    )

# ============================================================
# PER PERSON
# ============================================================

ranking_results = []

for person_id, group in (
    test_candidates
    .groupby(
        "person_id"
    )
):

    positive_ranks = (
        group[
            group[
                "is_positive"
            ]
        ][
            "rank"
        ]
        .to_numpy()
    )

    ranking_results.append(
        {
            "person_id":
                person_id,

            "positive_count":
                len(
                    positive_ranks
                ),

            "recall@5":
                recall_at_k(
                    positive_ranks,
                    5,
                ),

            "recall@10":
                recall_at_k(
                    positive_ranks,
                    10,
                ),

            "recall@20":
                recall_at_k(
                    positive_ranks,
                    20,
                ),

            "recall@50":
                recall_at_k(
                    positive_ranks,
                    50,
                ),

            "recall@100":
                recall_at_k(
                    positive_ranks,
                    100,
                ),

            "ndcg@10":
                ndcg_at_k(
                    positive_ranks,
                    10,
                ),

            "ndcg@20":
                ndcg_at_k(
                    positive_ranks,
                    20,
                ),

            "mrr":
                reciprocal_rank(
                    positive_ranks
                ),

            "best_rank":
                np.min(
                    positive_ranks
                )
                if len(
                    positive_ranks
                )
                else np.nan,

            "median_rank":
                np.median(
                    positive_ranks
                )
                if len(
                    positive_ranks
                )
                else np.nan,
        }
    )

ranking_results = pd.DataFrame(
    ranking_results
)

# ============================================================
# GLOBAL
# ============================================================

print("\n" + "=" * 70)
print("V2.1 GLOBAL RANKING RESULTS")
print("=" * 70)

for metric in [
    "recall@5",
    "recall@10",
    "recall@20",
    "recall@50",
    "recall@100",
    "ndcg@10",
    "ndcg@20",
    "mrr",
]:

    print(
        f"{metric:15s}: "
        f"{ranking_results[metric].mean():.4f}"
    )

# ============================================================
# POSITIVE RANK DISTRIBUTION
# ============================================================

positive_ranks = (
    test_candidates[
        test_candidates[
            "is_positive"
        ]
    ][
        "rank"
    ]
    .to_numpy()
)

print("\n" + "=" * 70)
print("POSITIVE RANK DISTRIBUTION")
print("=" * 70)

print(
    pd.Series(
        positive_ranks
    ).describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
        ]
    )
)

# ============================================================
# TOP-K COUNTS
# ============================================================

print("\n" + "=" * 70)
print("KNOWN POSITIVES IN TOP-K")
print("=" * 70)

for k in [
    1,
    5,
    10,
    20,
    50,
    100,
]:

    count = np.sum(
        positive_ranks <= k
    )

    percentage = (
        count
        /
        len(
            positive_ranks
        )
        *
        100
    )

    print(
        f"Top-{k:3d}: "
        f"{count:4d} / "
        f"{len(positive_ranks)} "
        f"({percentage:.2f}%)"
    )

# ============================================================
# TOP 10 FOR EACH TEST PERSON
# ============================================================

print("\n" + "=" * 70)
print("TOP 10 V2.1 RECOMMENDATIONS")
print("=" * 70)

for person_id, group in (
    test_candidates
    .groupby(
        "person_id"
    )
):

    top10 = (
        group
        .sort_values(
            "rank"
        )
        .head(10)
    )

    print(
        f"\nPerson: {person_id}"
    )

    display(
        top10[
            [
                "rank",
                "product_id",
                "v21_score",
                "is_positive",
                "physical_mismatch",
                "garment_bust",
                "garment_waist",
                "garment_hip",
                "garment_length",
                "garment_sleeve",
            ]
        ]
    )

# ============================================================
# SAVE MODEL
# ============================================================

torch.save(
    {
        "model_state_dict":
            model.state_dict(),

        "feature_names":
            FEATURES,

        "input_dim":
            len(FEATURES),

        "train_people":
            sorted(
                train_people
            ),

        "val_people":
            sorted(
                val_people
            ),

        "test_people":
            sorted(
                test_people
            ),

        "imputer_statistics":
            imputer.statistics_,

        "scaler_mean":
            scaler.mean_,

        "scaler_scale":
            scaler.scale_,

        "seed":
            SEED,

        "version":
            "V2.1_relationship_only",
    },
    MODEL_PATH,
)

ranking_results.to_csv(
    RANKING_OUTPUT,
    index=False,
)

print("\n" + "=" * 70)
print("V2.1 COMPLETE")
print("=" * 70)

print(
    "Model:",
    MODEL_PATH
)

print(
    "Ranking results:",
    RANKING_OUTPUT
)

======================================================================
ZYRA V2.1 — RELATIONSHIP-ONLY RANKER
======================================================================
Device: mps

Training rows: 13683
Candidate rows: 50232
People: 56
Garments: 897

Feature count: 27

======================================================================
BUILDING RELATIONSHIP FEATURES
======================================================================
Train people: 40
Validation people: 8
Test people: 8

Training rows: 10346
Validation rows: 1518
Test rows: 1819

======================================================================
FEATURE MATRICES
======================================================================
Feature dimension: 27
Train: (10346, 27)
Val: (1518, 27)
Test: (1819, 27)
NaN: 0

======================================================================
MODEL
======================================================================
Input dimension: 27
Parameters: 3905

======================================================================
TRAINING
======================================================================
Epoch 01/75 | Loss 0.6967 | Train 0.5503 | Val Loss 0.6992 | Val 0.5310
Epoch 05/75 | Loss 0.6782 | Train 0.6820 | Val Loss 0.6807 | Val 0.6528
Epoch 10/75 | Loss 0.6568 | Train 0.7854 | Val Loss 0.6598 | Val 0.7510
Epoch 15/75 | Loss 0.6366 | Train 0.7957 | Val Loss 0.6409 | Val 0.7556
Epoch 20/75 | Loss 0.6170 | Train 0.7975 | Val Loss 0.6235 | Val 0.7582
Epoch 25/75 | Loss 0.5971 | Train 0.8001 | Val Loss 0.6069 | Val 0.7628
Epoch 30/75 | Loss 0.5766 | Train 0.8049 | Val Loss 0.5910 | Val 0.7661
Epoch 35/75 | Loss 0.5569 | Train 0.8083 | Val Loss 0.5766 | Val 0.7675
Epoch 40/75 | Loss 0.5375 | Train 0.8138 | Val Loss 0.5644 | Val 0.7727
Epoch 45/75 | Loss 0.5193 | Train 0.8210 | Val Loss 0.5556 | Val 0.7727
Epoch 50/75 | Loss 0.5035 | Train 0.8277 | Val Loss 0.5505 | Val 0.7740
Epoch 55/75 | Loss 0.4899 | Train 0.8287 | Val Loss 0.5483 | Val 0.7760
Epoch 60/75 | Loss 0.4804 | Train 0.8282 | Val Loss 0.5483 | Val 0.7747
Epoch 65/75 | Loss 0.4712 | Train 0.8291 | Val Loss 0.5494 | Val 0.7740

Early stopping at epoch 69

======================================================================
V2.1 CLASSIFICATION RESULTS
======================================================================
Train accuracy: 0.8347
Validation accuracy: 0.7747
Test accuracy: 0.8659
Positive mean score: 0.4083
Negative mean score: 0.2520
Score gap: 0.1563

======================================================================
SCORING ALL 50,232 CANDIDATES
======================================================================

======================================================================
V2.1 GLOBAL RANKING RESULTS
======================================================================
recall@5       : 0.0026
recall@10      : 0.0026
recall@20      : 0.0127
recall@50      : 0.0417
recall@100     : 0.0931
ndcg@10        : 0.0106
ndcg@20        : 0.0192
mrr            : 0.0449

======================================================================
POSITIVE RANK DISTRIBUTION
======================================================================
count    339.000000
mean     486.631268
std      233.349643
min        5.000000
25%      315.000000
50%      553.000000
75%      662.000000
90%      735.000000
95%      804.500000
max      895.000000
dtype: float64

======================================================================
KNOWN POSITIVES IN TOP-K
======================================================================
Top-  1:    0 / 339 (0.00%)
Top-  5:    1 / 339 (0.29%)
Top- 10:    1 / 339 (0.29%)
Top- 20:    4 / 339 (1.18%)
Top- 50:    9 / 339 (2.65%)
Top-100:   35 / 339 (10.32%)

======================================================================
TOP 10 V2.1 RECOMMENDATIONS
======================================================================

Person: Alex

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
36832,1.0,the-boat-neck-top#Navy,0.719234,False,0.262284,57.0,53.0,62.0,62.0,64.0
37191,2.0,the-boat-neck-top#Black,0.719234,False,0.262284,57.0,53.0,62.0,62.0,64.0
37572,3.0,bamboo-layer-tank#Chalk,0.718989,False,0.158717,72.0,74.0,72.0,67.0,NaN
37577,4.0,bamboo-layer-tank#Black,0.718989,False,0.158717,72.0,74.0,72.0,67.0,NaN
36835,5.0,monaco-knot-top#Black,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
36973,6.0,monaco-knot-top#Olive,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
37262,7.0,monaco-knot-top#ClaySpot,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
37519,8.0,monaco-knot-top#HeatheGrey,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
37531,9.0,henson-jumper#Cream,0.680560,False,0.142153,84.0,84.0,84.0,56.0,68.0
37446,10.0,pure-merino-fine-rib-polo#BlackStri,0.678594,False,0.132264,92.0,80.0,90.0,68.0,69.0

Person: Anna Maria

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
34881,1.0,bamboo-layer-tank#Chalk,0.716532,False,0.166369,72.0,74.0,72.0,67.0,NaN
34886,2.0,bamboo-layer-tank#Black,0.716532,False,0.166369,72.0,74.0,72.0,67.0,NaN
34141,3.0,the-boat-neck-top#Navy,0.714841,False,0.268138,57.0,53.0,62.0,62.0,64.0
34500,4.0,the-boat-neck-top#Black,0.714841,False,0.268138,57.0,53.0,62.0,62.0,64.0
34144,5.0,monaco-knot-top#Black,0.692140,False,0.100066,86.0,76.0,82.0,64.0,70.0
34282,6.0,monaco-knot-top#Olive,0.692140,False,0.100066,86.0,76.0,82.0,64.0,70.0
34571,7.0,monaco-knot-top#ClaySpot,0.692140,False,0.100066,86.0,76.0,82.0,64.0,70.0
34828,8.0,monaco-knot-top#HeatheGrey,0.692140,False,0.100066,86.0,76.0,82.0,64.0,70.0
34840,9.0,henson-jumper#Cream,0.692013,False,0.126389,84.0,84.0,84.0,56.0,68.0
34413,10.0,faith-jumper#Eventide,0.659624,False,0.209127,94.0,88.0,78.0,62.0,70.0

Person: Bree

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
41618,1.0,the-reversible-cowl-neck-top-2#Ocean,0.733638,False,0.106493,95.0,82.0,92.0,63.0,49.0
41434,2.0,glasgow-top#Melange,0.730080,False,0.116594,92.0,82.0,92.0,65.0,70.0
41600,3.0,long-sleeve-tee-2#NavyWhite,0.729833,False,0.113219,92.0,88.0,102.0,64.0,66.0
41372,4.0,manhattan-stretch-tee#White,0.728818,False,0.118773,94.0,92.0,104.0,65.0,29.0
41452,5.0,manhattan-stretch-tee#Navy,0.728818,False,0.118773,94.0,92.0,104.0,65.0,29.0
41640,6.0,manhattan-stretch-tee#Black,0.728818,False,0.118773,94.0,92.0,104.0,65.0,29.0
41745,7.0,manhattan-stretch-tee#NavyWhtStr,0.728818,False,0.118773,94.0,92.0,104.0,65.0,29.0
41931,8.0,pure-merino-fine-rib-polo#BlackStri,0.728586,False,0.113566,92.0,80.0,90.0,68.0,69.0
42045,9.0,everyday-linen-tunic#BotanicalB,0.728471,False,0.114565,98.0,94.0,104.0,86.0,51.0
41908,10.0,34-sleeve-shirt-1#SkyWhite,0.726497,False,0.124327,96.0,96.0,106.0,83.0,59.0

Person: Chesska

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
13513,1.0,monaco-knot-top#Black,0.736485,False,0.087606,86.0,76.0,82.0,64.0,70.0
13651,2.0,monaco-knot-top#Olive,0.736485,False,0.087606,86.0,76.0,82.0,64.0,70.0
13940,3.0,monaco-knot-top#ClaySpot,0.736485,False,0.087606,86.0,76.0,82.0,64.0,70.0
14197,4.0,monaco-knot-top#HeatheGrey,0.736485,False,0.087606,86.0,76.0,82.0,64.0,70.0
13944,5.0,holly-rib-long-sleeve-tee#Khaki,0.733864,False,0.100454,86.0,86.0,92.0,65.0,66.0
13962,6.0,holly-rib-long-sleeve-tee#WhiteGrey,0.733864,False,0.100454,86.0,86.0,92.0,65.0,66.0
14203,7.0,holly-rib-long-sleeve-tee#Black,0.733864,False,0.100454,86.0,86.0,92.0,65.0,66.0
14209,8.0,henson-jumper#Cream,0.728321,False,0.126651,84.0,84.0,84.0,56.0,68.0
13537,9.0,pure-merino-fine-rib-v-neck#Charcoal,0.711698,False,0.045052,86.0,76.0,94.0,NaN,70.0
14250,10.0,bamboo-layer-tank#Chalk,0.707871,False,0.165839,72.0,74.0,72.0,67.0,NaN

Person: Emma

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
8128,1.0,the-boat-neck-top#Navy,0.719234,False,0.262284,57.0,53.0,62.0,62.0,64.0
8487,2.0,the-boat-neck-top#Black,0.719234,False,0.262284,57.0,53.0,62.0,62.0,64.0
8868,3.0,bamboo-layer-tank#Chalk,0.718989,False,0.158717,72.0,74.0,72.0,67.0,NaN
8873,4.0,bamboo-layer-tank#Black,0.718989,False,0.158717,72.0,74.0,72.0,67.0,NaN
8131,5.0,monaco-knot-top#Black,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
8269,6.0,monaco-knot-top#Olive,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
8558,7.0,monaco-knot-top#ClaySpot,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
8815,8.0,monaco-knot-top#HeatheGrey,0.687402,False,0.116043,86.0,76.0,82.0,64.0,70.0
8827,9.0,henson-jumper#Cream,0.680560,False,0.142153,84.0,84.0,84.0,56.0,68.0
8742,10.0,pure-merino-fine-rib-polo#BlackStri,0.678594,False,0.132264,92.0,80.0,90.0,68.0,69.0

Person: Maddy

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
13312,1.0,henson-jumper#Cream,0.729083,False,0.130524,84.0,84.0,84.0,56.0,68.0
13409,2.0,high-neck-tie-top#Black,0.724419,False,0.136767,82.0,92.0,96.0,60.0,NaN
12640,3.0,pure-merino-fine-rib-v-neck#Charcoal,0.712038,False,0.051674,86.0,76.0,94.0,NaN,70.0
12616,4.0,monaco-knot-top#Black,0.705438,False,0.091278,86.0,76.0,82.0,64.0,70.0
12754,5.0,monaco-knot-top#Olive,0.705438,False,0.091278,86.0,76.0,82.0,64.0,70.0
13043,6.0,monaco-knot-top#ClaySpot,0.705438,False,0.091278,86.0,76.0,82.0,64.0,70.0
13300,7.0,monaco-knot-top#HeatheGrey,0.705438,False,0.091278,86.0,76.0,82.0,64.0,70.0
13353,8.0,bamboo-layer-tank#Chalk,0.704960,False,0.169021,72.0,74.0,72.0,67.0,NaN
13358,9.0,bamboo-layer-tank#Black,0.704960,False,0.169021,72.0,74.0,72.0,67.0,NaN
12613,10.0,the-boat-neck-top#Navy,0.703887,False,0.322068,57.0,53.0,62.0,62.0,64.0

Person: Palatina

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
17399,1.0,the-reversible-cowl-neck-top-2#Ocean,0.765691,False,0.066797,95.0,82.0,92.0,63.0,49.0
17215,2.0,glasgow-top#Melange,0.761908,False,0.077106,92.0,82.0,92.0,65.0,70.0
17712,3.0,pure-merino-fine-rib-polo#BlackStri,0.761888,False,0.091159,92.0,80.0,90.0,68.0,69.0
17691,4.0,forget-me-knot-tunic#ForgetMeK,0.758762,False,0.037177,94.0,78.0,108.0,123.0,65.0
17125,5.0,pure-merino-fine-rib-v-neck#Charcoal,0.758518,True,0.115418,86.0,76.0,94.0,NaN,70.0
17101,6.0,monaco-knot-top#Black,0.750737,False,0.152116,86.0,76.0,82.0,64.0,70.0
17239,7.0,monaco-knot-top#Olive,0.750737,False,0.152116,86.0,76.0,82.0,64.0,70.0
17528,8.0,monaco-knot-top#ClaySpot,0.750737,False,0.152116,86.0,76.0,82.0,64.0,70.0
17785,9.0,monaco-knot-top#HeatheGrey,0.750737,False,0.152116,86.0,76.0,82.0,64.0,70.0
17153,10.0,manhattan-stretch-tee#White,0.741772,False,0.057346,94.0,92.0,104.0,65.0,29.0

Person: Sophie

,rank,product_id,v21_score,is_positive,physical_mismatch,garment_bust,garment_waist,garment_hip,garment_length,garment_sleeve
16784,1.0,ynes#Black,0.781452,False,0.218251,110.0,56.0,110.0,67.0,71.0
16288,2.0,layer-me-bamboo-rouched-sleeve-tee#Copper,0.766349,False,0.075805,109.0,99.0,113.0,64.0,71.0
16634,3.0,layer-me-bamboo-rouched-sleeve-tee#White,0.766349,False,0.075805,109.0,99.0,113.0,64.0,71.0
16840,4.0,layer-me-bamboo-rouched-sleeve-tee#Fern,0.766349,False,0.075805,109.0,99.0,113.0,64.0,71.0
16855,5.0,layer-me-bamboo-rouched-sleeve-tee#Black,0.766349,False,0.075805,109.0,99.0,113.0,64.0,71.0
16575,6.0,the-short-sleeve-wrap-jersey-top#Blue,0.765013,False,0.121393,108.0,92.0,105.0,67.0,29.0
16605,7.0,the-short-sleeve-wrap-jersey-top#Black,0.765013,False,0.121393,108.0,92.0,105.0,67.0,29.0
16670,8.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.765013,False,0.121393,108.0,92.0,105.0,67.0,29.0
16774,9.0,the-short-sleeve-wrap-jersey-top#Emerald,0.765013,False,0.121393,108.0,92.0,105.0,67.0,29.0
17002,10.0,spliced-stripe-tunic#Navy,0.764738,False,0.042211,106.0,102.0,126.0,80.0,66.0

======================================================================
V2.1 COMPLETE
======================================================================
Model: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_compatibility_ranker_v21.pt
Ranking results: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_v21_topk_results.csv

In [77]:
# ============================================================
# ZYRA V2 — STEP 5
# GARMENT DATA INVENTORY
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# PATH
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

RAW_PATH = (
    BASE /
    "data/v2/v2_compatibility_raw.csv"
)

CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

print("=" * 70)
print("ZYRA V2 — GARMENT DATA INVENTORY")
print("=" * 70)

# ============================================================
# LOAD
# ============================================================

raw = pd.read_csv(
    RAW_PATH
)

candidates = pd.read_csv(
    CANDIDATE_PATH
)

print(
    "\nRaw rows:",
    len(raw)
)

print(
    "Raw columns:",
    len(raw.columns)
)

print(
    "Candidate rows:",
    len(candidates)
)

# ============================================================
# ALL COLUMNS
# ============================================================

print("\n" + "=" * 70)
print("ALL RAW COLUMNS")
print("=" * 70)

for i, col in enumerate(
    raw.columns,
    start=1
):

    dtype = raw[col].dtype

    unique = raw[col].nunique(
        dropna=True
    )

    missing = raw[col].isna().sum()

    missing_pct = (
        missing
        /
        len(raw)
        *
        100
    )

    print(
        f"{i:02d}. "
        f"{col:35s} "
        f"dtype={str(dtype):12s} "
        f"unique={unique:6d} "
        f"missing={missing:6d} "
        f"({missing_pct:6.2f}%)"
    )

# ============================================================
# GARMENT-LEVEL DATASET
# ============================================================

print("\n" + "=" * 70)
print("GARMENT-LEVEL INVENTORY")
print("=" * 70)

if "product_id" not in raw.columns:

    raise ValueError(
        "product_id column not found"
    )

garments = (
    raw
    .drop_duplicates(
        "product_id"
    )
    .copy()
)

print(
    "Unique garments:",
    len(garments)
)

# ============================================================
# GARMENT COLUMNS
# ============================================================

print("\n" + "=" * 70)
print("GARMENT COLUMNS")
print("=" * 70)

garment_columns = []

for col in garments.columns:

    # Exclude obvious person fields
    person_words = [
        "person",
        "user",
        "profile",
        "height",
        "bust",
        "waist",
        "hips",
    ]

    if any(
        word in col.lower()
        for word in person_words
    ):

        continue

    garment_columns.append(
        col
    )

for col in garment_columns:

    unique = garments[
        col
    ].nunique(
        dropna=True
    )

    missing = garments[
        col
    ].isna().sum()

    print(
        f"{col:35s} "
        f"unique={unique:6d} "
        f"missing={missing:6d}"
    )

# ============================================================
# TEXT / CATEGORICAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CATEGORICAL / TEXT FEATURES")
print("=" * 70)

categorical_candidates = []

for col in garment_columns:

    series = garments[col]

    if (
        series.dtype == "object"
        or
        str(
            series.dtype
        ).startswith(
            "category"
        )
    ):

        categorical_candidates.append(
            col
        )

        print(
            f"\n{col}"
        )

        print(
            "Unique:",
            series.nunique(
                dropna=True
            )
        )

        print(
            "Missing:",
            series.isna().sum()
        )

        values = (
            series
            .dropna()
            .astype(str)
            .value_counts()
            .head(20)
        )

        if len(values):

            print(
                values.to_string()
            )

# ============================================================
# NUMERIC GARMENT FEATURES
# ============================================================

print("\n" + "=" * 70)
print("NUMERIC GARMENT FEATURES")
print("=" * 70)

numeric_candidates = []

for col in garment_columns:

    if pd.api.types.is_numeric_dtype(
        garments[col]
    ):

        numeric_candidates.append(
            col
        )

        print(
            f"\n{col}"
        )

        print(
            garments[col]
            .describe()
            .to_string()
        )

# ============================================================
# POTENTIAL PRODUCT METADATA
# ============================================================

print("\n" + "=" * 70)
print("POTENTIAL PRODUCT METADATA")
print("=" * 70)

metadata_keywords = [
    "category",
    "type",
    "style",
    "color",
    "colour",
    "fabric",
    "material",
    "brand",
    "designer",
    "silhouette",
    "pattern",
    "occasion",
    "season",
    "sleeve",
    "neck",
    "collar",
    "length",
    "fit",
    "texture",
    "description",
    "name",
    "title",
    "product",
]

metadata_columns = []

for col in garments.columns:

    col_lower = col.lower()

    if any(
        keyword in col_lower
        for keyword in metadata_keywords
    ):

        metadata_columns.append(
            col
        )

        print(
            "FOUND:",
            col
        )

# ============================================================
# PRODUCT ID EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("PRODUCT ID EXAMPLES")
print("=" * 70)

print(
    garments[
        "product_id"
    ]
    .head(30)
    .to_string(
        index=False
    )
)

# ============================================================
# COMPLETE GARMENT EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("SAMPLE GARMENTS")
print("=" * 70)

sample_columns = [
    col
    for col in [
        "product_id",
        "product_name",
        "name",
        "title",
        "category",
        "type",
        "style",
        "color",
        "colour",
        "fabric",
        "material",
        "brand",
        "silhouette",
        "pattern",
        "occasion",
        "description",
        "garment_bust",
        "garment_waist",
        "garment_hip",
        "garment_length",
        "garment_sleeve",
    ]
    if col in garments.columns
]

if len(sample_columns):

    print(
        garments[
            sample_columns
        ]
        .head(10)
        .to_string(
            index=False
        )
    )

else:

    print(
        "No expected metadata columns found."
    )

# ============================================================
# VARIANT ANALYSIS
# ============================================================

print("\n" + "=" * 70)
print("PRODUCT VARIANT ANALYSIS")
print("=" * 70)

if "product_id" in raw.columns:

    variant_counts = (
        raw
        .groupby(
            "product_id"
        )
        .size()
    )

    print(
        "Rows per product:"
    )

    print(
        variant_counts
        .describe()
        .to_string()
    )

# ============================================================
# DUPLICATE PHYSICAL PRODUCTS
# ============================================================

physical_columns = [
    col
    for col in [
        "garment_bust",
        "garment_waist",
        "garment_hip",
        "garment_length",
        "garment_sleeve",
    ]
    if col in garments.columns
]

if len(
    physical_columns
) >= 2:

    duplicate_physical = (
        garments
        .groupby(
            physical_columns,
            dropna=False
        )
        .size()
        .sort_values(
            ascending=False
        )
    )

    print("\n" + "=" * 70)
    print("PHYSICAL-SPEC DUPLICATES")
    print("=" * 70)

    print(
        duplicate_physical
        .head(20)
        .to_string()
    )

# ============================================================
# INFORMATION DENSITY
# ============================================================

print("\n" + "=" * 70)
print("INFORMATION DENSITY")
print("=" * 70)

for col in garments.columns:

    non_null = (
        garments[col]
        .notna()
        .sum()
    )

    percentage = (
        non_null
        /
        len(garments)
        *
        100
    )

    if (
        percentage >= 50
    ):

        quality = "GOOD"

    elif (
        percentage >= 20
    ):

        quality = "PARTIAL"

    else:

        quality = "SPARSE"

    print(
        f"{col:35s} "
        f"{percentage:6.2f}% "
        f"{quality}"
    )

# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FINAL GARMENT DATA SUMMARY")
print("=" * 70)

print(
    "Unique garments:",
    len(garments)
)

print(
    "Categorical/text columns:",
    len(categorical_candidates)
)

print(
    "Numeric columns:",
    len(numeric_candidates)
)

print(
    "Potential metadata columns:",
    len(metadata_columns)
)

print(
    "\nCategorical:",
    categorical_candidates
)

print(
    "\nMetadata:",
    metadata_columns
)

print(
    "\nNumeric:",
    numeric_candidates
)

print("\n" + "=" * 70)
print("ZYRA V2 STEP 5 COMPLETE")
print("=" * 70)

======================================================================
ZYRA V2 — GARMENT DATA INVENTORY
======================================================================

Raw rows: 5980
Raw columns: 22
Candidate rows: 50232

======================================================================
ALL RAW COLUMNS
======================================================================
01. person_id                           dtype=str          unique=    56 missing=     0 (  0.00%)
02. product_id                          dtype=str          unique=   897 missing=     0 (  0.00%)
03. label                               dtype=int64        unique=     2 missing=     0 (  0.00%)
04. height                              dtype=float64      unique=    16 missing=     0 (  0.00%)
05. bust                                dtype=float64      unique=    22 missing=     0 (  0.00%)
06. waist                               dtype=float64      unique=    27 missing=     0 (  0.00%)
07. hips                                dtype=float64      unique=    26 missing=     0 (  0.00%)
08. garment_bust                        dtype=float64      unique=    83 missing=   274 (  4.58%)
09. garment_waist                       dtype=float64      unique=    83 missing=  1231 ( 20.59%)
10. garment_hip                         dtype=float64      unique=    89 missing=   883 ( 14.77%)
11. garment_length                      dtype=float64      unique=    71 missing=    58 (  0.97%)
12. garment_sleeve                      dtype=float64      unique=    65 missing=  1073 ( 17.94%)
13. model_size                          dtype=str          unique=    26 missing=  2990 ( 50.00%)
14. bust_ease                           dtype=float64      unique=   184 missing=   274 (  4.58%)
15. waist_ease                          dtype=float64      unique=   172 missing=  1231 ( 20.59%)
16. hip_ease                            dtype=float64      unique=   196 missing=   883 ( 14.77%)
17. length_height_ratio                 dtype=float64      unique=   730 missing=    58 (  0.97%)
18. missing_bust                        dtype=int64        unique=     2 missing=     0 (  0.00%)
19. missing_waist                       dtype=int64        unique=     2 missing=     0 (  0.00%)
20. missing_hip                         dtype=int64        unique=     2 missing=     0 (  0.00%)
21. missing_length                      dtype=int64        unique=     2 missing=     0 (  0.00%)
22. missing_sleeve                      dtype=int64        unique=     2 missing=     0 (  0.00%)

======================================================================
GARMENT-LEVEL INVENTORY
======================================================================
Unique garments: 897

======================================================================
GARMENT COLUMNS
======================================================================
product_id                          unique=   897 missing=     0
label                               unique=     2 missing=     0
garment_hip                         unique=    89 missing=   125
garment_length                      unique=    71 missing=    12
garment_sleeve                      unique=    65 missing=   143
model_size                          unique=    17 missing=   461
hip_ease                            unique=   134 missing=   125
missing_hip                         unique=     2 missing=     0
missing_length                      unique=     2 missing=     0
missing_sleeve                      unique=     2 missing=     0

======================================================================
CATEGORICAL / TEXT FEATURES
======================================================================

======================================================================
NUMERIC GARMENT FEATURES
======================================================================

label
count    897.000000
mean       0.486065
std        0.500085
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000

garment_hip
count    772.000000
mean     126.847150
std       22.159075
min       58.000000
25%      110.000000
50%      124.000000
75%      142.000000
max      180.000000

garment_length
count    885.000000
mean      72.258757
std       13.932276
min       46.000000
25%       64.000000
50%       69.000000
75%       76.000000
max      132.000000

garment_sleeve
count    754.000000
mean      59.270557
std       15.928159
min       20.000000
25%       51.000000
50%       65.000000
75%       71.000000
max      133.000000

hip_ease
count    772.000000
mean      24.470855
std       24.681856
min      -57.000000
25%        7.000000
50%       22.000000
75%       42.000000
max       91.000000

missing_hip
count    897.000000
mean       0.139353
std        0.346508
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

missing_length
count    897.000000
mean       0.013378
std        0.114951
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

missing_sleeve
count    897.000000
mean       0.159420
std        0.366272
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

======================================================================
POTENTIAL PRODUCT METADATA
======================================================================
FOUND: product_id
FOUND: garment_length
FOUND: garment_sleeve
FOUND: length_height_ratio
FOUND: missing_length
FOUND: missing_sleeve

======================================================================
PRODUCT ID EXAMPLES
======================================================================
   nova-lux-long-sleeve-tie-top-1#NightSky
                           tracie-top#Opal
            leopard-print-kimono#GoldMulti
                 the-tie-detail-hoody#Pink
         belle-off-the-shoulder-tee#Stripe
         the-contrast-panel-top#SageStripe
                the-stripe-jersey-top#Blue
                   napoleon-top-1#NemoBlue
                 the-longline-cardi-1#Nude
                  bo-cosy-cardigan#Blossom
                      wellington-tee#Olive
the-relaxed-long-sleeve-tee-1#Ink%20Stripe
                   milan-stretch-top#Black
             mila-knit-cardigan#StoneBlack
          on-the-horizon-swing-top-1#Khaki
          sequin-heart-layered-top#Natural
                    the-excess-shirt#Pearl
            belle-cowl-swing-sweater#Green
                  stara-cardigan#GreyMarle
                 the-half-sleeve-tee#Black
                falling-for-you-cardi#Teal
                the-batwing-tee#FrenchBlue
                true-love-bell-blouse#Jade
                      foil-spot-tee-1#Navy
                       vivian-blouse#Check
         lilly-layer-stripe-tank#NavyWhite
         reversible-scoopv-neck-tank#Black
            the-essential-pullover#SkyBlue
                    belle-drape-tee#Sliver
                    maui-stretch-tee#Black

======================================================================
SAMPLE GARMENTS
======================================================================
                             product_id  garment_bust  garment_waist  garment_hip  garment_length  garment_sleeve
nova-lux-long-sleeve-tie-top-1#NightSky         100.0          104.0        106.0            60.0            73.0
                        tracie-top#Opal         127.0          129.0        135.0            55.0            66.0
         leopard-print-kimono#GoldMulti           NaN            NaN        158.0            89.0            57.0
              the-tie-detail-hoody#Pink         134.0            NaN          NaN            70.0            69.0
      belle-off-the-shoulder-tee#Stripe         121.0          117.0        129.0            67.0            64.0
      the-contrast-panel-top#SageStripe         130.0            NaN          NaN            73.0             NaN
             the-stripe-jersey-top#Blue         136.0          108.0        108.0            70.0            52.0
                napoleon-top-1#NemoBlue         100.0          110.0        108.0            60.0            54.0
              the-longline-cardi-1#Nude          97.0          108.0        115.0           102.0             NaN
               bo-cosy-cardigan#Blossom         112.0          114.0        116.0            82.0            75.0

======================================================================
PRODUCT VARIANT ANALYSIS
======================================================================
Rows per product:
count    897.000000
mean       6.666667
std        2.932144
min        1.000000
25%        5.000000
50%        6.000000
75%        8.000000
max       17.000000

======================================================================
PHYSICAL-SPEC DUPLICATES
======================================================================
garment_bust  garment_waist  garment_hip  garment_length  garment_sleeve
113.0         121.0          153.0        78.0            72.0              14
109.0         120.0          164.0        77.0            32.0              12
NaN           NaN            NaN          116.0           64.0              11
126.0         132.0          139.0        67.0            NaN               10
125.0         121.0          132.0        83.0            74.0               9
136.0         132.0          129.0        86.0            54.0               8
126.0         125.0          125.0        63.0            NaN                7
130.0         122.0          126.0        62.0            57.0               6
104.0         106.0          112.0        69.0            NaN                6
127.0         117.0          125.0        84.0            52.0               6
130.0         128.0          122.0        64.0            39.0               6
104.0         104.0          108.0        70.0            26.0               5
114.0         124.0          138.0        61.0            56.0               5
115.0         124.0          149.0        71.0            NaN                5
121.0         NaN            142.0        73.0            76.0               5
134.0         135.0          136.0        57.0            77.0               5
155.0         NaN            141.0        73.0            NaN                5
130.0         96.0           96.0         66.0            29.0               4
118.0         NaN            138.0        50.0            NaN                4
100.0         104.0          106.0        60.0            73.0               4

======================================================================
INFORMATION DENSITY
======================================================================
person_id                           100.00% GOOD
product_id                          100.00% GOOD
label                               100.00% GOOD
height                              100.00% GOOD
bust                                100.00% GOOD
waist                               100.00% GOOD
hips                                100.00% GOOD
garment_bust                         97.10% GOOD
garment_waist                        81.27% GOOD
garment_hip                          86.06% GOOD
garment_length                       98.66% GOOD
garment_sleeve                       84.06% GOOD
model_size                           48.61% PARTIAL
bust_ease                            97.10% GOOD
waist_ease                           81.27% GOOD
hip_ease                             86.06% GOOD
length_height_ratio                  98.66% GOOD
missing_bust                        100.00% GOOD
missing_waist                       100.00% GOOD
missing_hip                         100.00% GOOD
missing_length                      100.00% GOOD
missing_sleeve                      100.00% GOOD

======================================================================
FINAL GARMENT DATA SUMMARY
======================================================================
Unique garments: 897
Categorical/text columns: 0
Numeric columns: 8
Potential metadata columns: 6

Categorical: []

Metadata: ['product_id', 'garment_length', 'garment_sleeve', 'length_height_ratio', 'missing_length', 'missing_sleeve']

Numeric: ['label', 'garment_hip', 'garment_length', 'garment_sleeve', 'hip_ease', 'missing_hip', 'missing_length', 'missing_sleeve']

======================================================================
ZYRA V2 STEP 5 COMPLETE
======================================================================

In [78]:
# ============================================================
# ZYRA V2 — STEP 6
# PRODUCT_ID SEMANTIC FEATURE EXTRACTION
# ============================================================

import pandas as pd
import numpy as np
import re
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

INPUT_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_garment_semantic_features.csv"
)

# ============================================================
# LOAD UNIQUE GARMENTS
# ============================================================

df = pd.read_csv(INPUT_PATH)

garments = (
    df[
        ["product_id"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("=" * 70)
print("ZYRA V2 — PRODUCT SEMANTIC EXTRACTION")
print("=" * 70)

print(
    "Unique garments:",
    len(garments)
)

# ============================================================
# DICTIONARIES
# ============================================================

CATEGORY_WORDS = {
    "top": [
        "top",
        "tee",
        "tank",
        "shirt",
        "blouse",
        "tunic",
        "pullover",
        "sweater",
        "hoodie",
        "jersey",
    ],

    "cardigan": [
        "cardigan",
        "cowl",
    ],

    "kimono": [
        "kimono",
        "poncho",
    ],

    "dress": [
        "dress",
    ],

    "skirt": [
        "skirt",
    ],

    "pants": [
        "pant",
        "trouser",
        "legging",
        "jean",
    ],

    "shorts": [
        "short",
    ],

    "jacket": [
        "jacket",
        "blazer",
        "coat",
    ],

    "outerwear": [
        "cape",
        "wrap",
    ],
}

STYLE_WORDS = {
    "relaxed": [
        "relaxed",
        "cosy",
        "oversized",
        "swing",
        "batwing",
        "loose",
    ],

    "fitted": [
        "fitted",
        "stretch",
        "slim",
        "fitted",
        "tailored",
    ],

    "casual": [
        "tee",
        "hoodie",
        "jersey",
        "tank",
        "pullover",
    ],

    "elegant": [
        "blouse",
        "cowl",
        "drape",
        "luxe",
        "silk",
    ],

    "romantic": [
        "love",
        "belle",
        "ruffle",
        "floral",
        "bell",
    ],

    "sporty": [
        "jersey",
        "crew",
        "sport",
    ],

    "layering": [
        "cardigan",
        "kimono",
        "poncho",
        "wrap",
    ],
}

PATTERN_WORDS = {
    "stripe": [
        "stripe",
        "striped",
    ],

    "floral": [
        "floral",
        "flower",
    ],

    "animal": [
        "leopard",
        "animal",
        "tiger",
        "zebra",
    ],

    "check": [
        "check",
        "checked",
        "plaid",
    ],

    "spot": [
        "spot",
        "dot",
        "polka",
    ],

    "sequin": [
        "sequin",
        "sequins",
    ],

    "plain": [
        "plain",
        "solid",
        "essential",
    ],
}

MATERIAL_WORDS = {
    "knit": [
        "knit",
        "knitted",
    ],

    "jersey": [
        "jersey",
    ],

    "stretch": [
        "stretch",
    ],

    "cosy": [
        "cosy",
        "cozy",
    ],

    "textured": [
        "textured",
        "texture",
    ],

    "sequin": [
        "sequin",
        "sequins",
    ],
}

SILHOUETTE_WORDS = {
    "swing": [
        "swing",
    ],

    "oversized": [
        "oversized",
        "oversize",
        "loose",
    ],

    "relaxed": [
        "relaxed",
        "cosy",
        "batwing",
    ],

    "fitted": [
        "fitted",
        "stretch",
        "slim",
    ],

    "longline": [
        "longline",
        "long",
    ],

    "cropped": [
        "crop",
        "cropped",
    ],
}

SLEEVE_WORDS = {
    "long": [
        "long-sleeve",
        "longsleeve",
    ],

    "short": [
        "short-sleeve",
        "shortsleeve",
        "half-sleeve",
    ],

    "flute": [
        "flute-sleeve",
    ],

    "bell": [
        "bell-sleeve",
    ],

    "batwing": [
        "batwing",
    ],
}

NECKLINE_WORDS = {
    "cowl": [
        "cowl",
    ],

    "v_neck": [
        "vneck",
        "v-neck",
        "v-neck",
    ],

    "scoop": [
        "scoop",
    ],

    "off_shoulder": [
        "off-the-shoulder",
        "off-shoulder",
    ],

    "crew": [
        "crew",
    ],

    "collared": [
        "collar",
        "collared",
    ],
}

LENGTH_WORDS = {
    "long": [
        "long",
        "longline",
    ],

    "short": [
        "short",
        "cropped",
    ],

    "mid": [
        "midi",
        "mid",
    ],
}

COLOR_WORDS = [
    "black",
    "white",
    "pink",
    "blue",
    "navy",
    "green",
    "jade",
    "khaki",
    "grey",
    "gray",
    "nude",
    "blush",
    "teal",
    "wine",
    "red",
    "orange",
    "yellow",
    "lime",
    "purple",
    "violet",
    "brown",
    "cream",
    "natural",
    "opal",
    "gold",
    "silver",
    "olive",
    "stone",
    "stripe",
]

# ============================================================
# HELPERS
# ============================================================

def normalize_text(text):

    text = str(text).lower()

    text = (
        text
        .replace("%20", "-")
        .replace("_", "-")
    )

    text = re.sub(
        r"[^a-z0-9#\-]",
        "-",
        text,
    )

    text = re.sub(
        r"-+",
        "-",
        text,
    )

    return text.strip("-")


def extract_name_and_color(product_id):

    product_id = str(
        product_id
    )

    if "#" in product_id:

        name, color = (
            product_id
            .split(
                "#",
                1,
            )
        )

    else:

        name = product_id
        color = ""

    return (
        normalize_text(name),
        normalize_text(color),
    )


def find_matches(
    text,
    dictionary,
):

    matches = []

    for category, words in (
        dictionary.items()
    ):

        for word in words:

            word = normalize_text(
                word
            )

            if (
                word in text
            ):

                matches.append(
                    category
                )

                break

    return matches


def find_color(
    color_text,
    name_text,
):

    text = (
        color_text
        +
        "-"
        +
        name_text
    )

    matches = []

    for color in COLOR_WORDS:

        if (
            normalize_text(color)
            in text
        ):

            matches.append(
                color
            )

    # Preserve order
    matches = list(
        dict.fromkeys(
            matches
        )
    )

    return matches


# ============================================================
# EXTRACT
# ============================================================

rows = []

for product_id in garments[
    "product_id"
]:

    name, color = (
        extract_name_and_color(
            product_id
        )
    )

    combined = (
        name
        +
        "-"
        +
        color
    )

    categories = find_matches(
        combined,
        CATEGORY_WORDS,
    )

    styles = find_matches(
        combined,
        STYLE_WORDS,
    )

    patterns = find_matches(
        combined,
        PATTERN_WORDS,
    )

    materials = find_matches(
        combined,
        MATERIAL_WORDS,
    )

    silhouettes = find_matches(
        combined,
        SILHOUETTE_WORDS,
    )

    sleeves = find_matches(
        combined,
        SLEEVE_WORDS,
    )

    necklines = find_matches(
        combined,
        NECKLINE_WORDS,
    )

    lengths = find_matches(
        combined,
        LENGTH_WORDS,
    )

    colors = find_color(
        color,
        name,
    )

    # --------------------------------------------------------
    # Primary values
    # --------------------------------------------------------

    primary_category = (
        categories[0]
        if categories
        else "unknown"
    )

    primary_style = (
        styles[0]
        if styles
        else "unknown"
    )

    primary_pattern = (
        patterns[0]
        if patterns
        else "plain"
    )

    primary_material = (
        materials[0]
        if materials
        else "unknown"
    )

    primary_silhouette = (
        silhouettes[0]
        if silhouettes
        else "unknown"
    )

    primary_sleeve = (
        sleeves[0]
        if sleeves
        else "unknown"
    )

    primary_neckline = (
        necklines[0]
        if necklines
        else "unknown"
    )

    primary_length = (
        lengths[0]
        if lengths
        else "unknown"
    )

    primary_color = (
        colors[0]
        if colors
        else "unknown"
    )

    # --------------------------------------------------------
    # Binary semantic features
    # --------------------------------------------------------

    rows.append(
        {
            "product_id":
                product_id,

            "product_name":
                name,

            "product_color_raw":
                color,

            "category":
                primary_category,

            "style":
                primary_style,

            "pattern":
                primary_pattern,

            "material":
                primary_material,

            "silhouette":
                primary_silhouette,

            "sleeve_type":
                primary_sleeve,

            "neckline":
                primary_neckline,

            "length_style":
                primary_length,

            "color":
                primary_color,

            "category_count":
                len(categories),

            "style_count":
                len(styles),

            "pattern_count":
                len(patterns),

            "material_count":
                len(materials),

            "semantic_token_count":
                len(
                    set(
                        categories
                        +
                        styles
                        +
                        patterns
                        +
                        materials
                        +
                        silhouettes
                        +
                        sleeves
                        +
                        necklines
                        +
                        lengths
                        +
                        colors
                    )
                ),

            # Binary flags

            "is_striped":
                int(
                    "stripe"
                    in patterns
                ),

            "is_floral":
                int(
                    "floral"
                    in patterns
                ),

            "is_animal_print":
                int(
                    "animal"
                    in patterns
                ),

            "is_checked":
                int(
                    "check"
                    in patterns
                ),

            "is_sequin":
                int(
                    "sequin"
                    in patterns
                ),

            "is_knit":
                int(
                    "knit"
                    in materials
                ),

            "is_stretch":
                int(
                    "stretch"
                    in materials
                ),

            "is_relaxed":
                int(
                    (
                        "relaxed"
                        in styles
                    )
                    or
                    (
                        "relaxed"
                        in silhouettes
                    )
                ),

            "is_fitted":
                int(
                    (
                        "fitted"
                        in styles
                    )
                    or
                    (
                        "fitted"
                        in silhouettes
                    )
                ),

            "is_swing":
                int(
                    "swing"
                    in silhouettes
                ),

            "is_longline":
                int(
                    "longline"
                    in silhouettes
                ),

            "is_off_shoulder":
                int(
                    "off_shoulder"
                    in necklines
                ),

            "is_batwing":
                int(
                    "batwing"
                    in silhouettes
                ),

            "is_long_sleeve":
                int(
                    "long"
                    in sleeves
                ),

            "is_short_sleeve":
                int(
                    "short"
                    in sleeves
                ),
        }
    )

# ============================================================
# DATAFRAME
# ============================================================

semantic = pd.DataFrame(
    rows
)

# ============================================================
# CHECK
# ============================================================

print("\n" + "=" * 70)
print("SEMANTIC EXTRACTION SUMMARY")
print("=" * 70)

print(
    "Rows:",
    len(semantic)
)

print(
    "Unique products:",
    semantic[
        "product_id"
    ].nunique()
)

assert (
    len(semantic)
    ==
    garments[
        "product_id"
    ].nunique()
)

assert (
    semantic[
        "product_id"
    ].duplicated()
    .sum()
    ==
    0
)

# ============================================================
# DISTRIBUTIONS
# ============================================================

for column in [
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]:

    print(
        "\n" + "-" * 60
    )

    print(
        column.upper()
    )

    print(
        semantic[
            column
        ]
        .value_counts()
        .head(20)
        .to_string()
    )

# ============================================================
# COVERAGE
# ============================================================

print("\n" + "=" * 70)
print("SEMANTIC COVERAGE")
print("=" * 70)

semantic_columns = [
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]

for column in semantic_columns:

    known = (
        semantic[
            column
        ]
        != "unknown"
    ).sum()

    coverage = (
        known
        /
        len(semantic)
        *
        100
    )

    print(
        f"{column:20s}: "
        f"{known:4d}/{len(semantic)} "
        f"({coverage:6.2f}%)"
    )

# ============================================================
# EXAMPLES
# ============================================================

print("\n" + "=" * 70)
print("PARSED PRODUCT EXAMPLES")
print("=" * 70)

display(
    semantic[
        [
            "product_id",
            "product_name",
            "product_color_raw",
            "category",
            "style",
            "pattern",
            "material",
            "silhouette",
            "sleeve_type",
            "neckline",
            "length_style",
            "color",
        ]
    ]
    .head(30)
)

# ============================================================
# SAVE
# ============================================================

semantic.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("SEMANTIC FEATURES SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print(
    "\nZYRA V2 STEP 6 COMPLETE"
)

======================================================================
ZYRA V2 — PRODUCT SEMANTIC EXTRACTION
======================================================================
Unique garments: 897

======================================================================
SEMANTIC EXTRACTION SUMMARY
======================================================================
Rows: 897
Unique products: 897

------------------------------------------------------------
CATEGORY
category
top          697
unknown      135
cardigan      40
kimono        17
jacket         5
outerwear      2
pants          1

------------------------------------------------------------
STYLE
style
unknown     404
casual      198
elegant      94
relaxed      71
romantic     55
layering     50
fitted       16
sporty        9

------------------------------------------------------------
PATTERN
pattern
plain     770
stripe     67
spot       29
floral     12
animal     11
sequin      4
check       4

------------------------------------------------------------
MATERIAL
material
unknown     781
knit         67
jersey       16
stretch      16
cosy          8
sequin        7
textured      2

------------------------------------------------------------
SILHOUETTE
silhouette
unknown      758
longline      48
swing         34
relaxed       26
fitted        16
oversized     14
cropped        1

------------------------------------------------------------
SLEEVE_TYPE
sleeve_type
unknown    811
long        52
short       17
bell         8
batwing      6
flute        3

------------------------------------------------------------
NECKLINE
neckline
unknown         835
v_neck           34
crew              9
off_shoulder      7
cowl              5
scoop             5
collared          2

------------------------------------------------------------
LENGTH_STYLE
length_style
unknown    817
long        68
short        7
mid          5

------------------------------------------------------------
COLOR
color
unknown    287
black      118
white      116
navy        98
blue        58
grey        47
pink        33
stripe      30
khaki       20
red         17
silver      16
natural     11
blush       10
green        6
cream        6
olive        5
stone        5
gold         4
teal         2
wine         2

======================================================================
SEMANTIC COVERAGE
======================================================================
category            :  762/897 ( 84.95%)
style               :  493/897 ( 54.96%)
pattern             :  897/897 (100.00%)
material            :  116/897 ( 12.93%)
silhouette          :  139/897 ( 15.50%)
sleeve_type         :   86/897 (  9.59%)
neckline            :   62/897 (  6.91%)
length_style        :   80/897 (  8.92%)
color               :  610/897 ( 68.00%)

======================================================================
PARSED PRODUCT EXAMPLES
======================================================================

,product_id,product_name,product_color_raw,category,style,pattern,material,silhouette,sleeve_type,neckline,length_style,color
0,nova-lux-long-sleeve-tie-top-1#NightSky,nova-lux-long-sleeve-tie-top-1,nightsky,top,unknown,plain,unknown,longline,long,unknown,long,unknown
1,tracie-top#Opal,tracie-top,opal,top,unknown,plain,unknown,unknown,unknown,unknown,unknown,opal
2,leopard-print-kimono#GoldMulti,leopard-print-kimono,goldmulti,kimono,layering,animal,unknown,unknown,unknown,unknown,unknown,gold
3,the-tie-detail-hoody#Pink,the-tie-detail-hoody,pink,unknown,unknown,plain,unknown,unknown,unknown,unknown,unknown,pink
4,belle-off-the-shoulder-tee#Stripe,belle-off-the-shoulder-tee,stripe,top,casual,stripe,unknown,unknown,unknown,off_shoulder,unknown,stripe
5,the-contrast-panel-top#SageStripe,the-contrast-panel-top,sagestripe,top,unknown,stripe,unknown,unknown,unknown,unknown,unknown,stripe
6,the-stripe-jersey-top#Blue,the-stripe-jersey-top,blue,top,casual,stripe,jersey,unknown,unknown,unknown,unknown,blue
7,napoleon-top-1#NemoBlue,napoleon-top-1,nemoblue,top,unknown,plain,unknown,unknown,unknown,unknown,unknown,blue
8,the-longline-cardi-1#Nude,the-longline-cardi-1,nude,unknown,unknown,plain,unknown,longline,unknown,unknown,long,nude
9,bo-cosy-cardigan#Blossom,bo-cosy-cardigan,blossom,cardigan,relaxed,plain,cosy,relaxed,unknown,unknown,unknown,unknown
10,wellington-tee#Olive,wellington-tee,olive,top,casual,plain,unknown,unknown,unknown,unknown,unknown,olive
11,the-relaxed-long-sleeve-tee-1#Ink%20Stripe,the-relaxed-long-sleeve-tee-1,ink-stripe,top,relaxed,stripe,unknown,relaxed,long,unknown,long,stripe
12,milan-stretch-top#Black,milan-stretch-top,black,top,fitted,plain,stretch,fitted,unknown,unknown,unknown,black
13,mila-knit-cardigan#StoneBlack,mila-knit-cardigan,stoneblack,cardigan,layering,plain,knit,unknown,unknown,unknown,unknown,black
14,on-the-horizon-swing-top-1#Khaki,on-the-horizon-swing-top-1,khaki,top,relaxed,plain,unknown,swing,unknown,unknown,unknown,khaki
15,sequin-heart-layered-top#Natural,sequin-heart-layered-top,natural,top,unknown,sequin,sequin,unknown,unknown,unknown,unknown,red
16,the-excess-shirt#Pearl,the-excess-shirt,pearl,top,unknown,plain,unknown,unknown,unknown,unknown,unknown,unknown
17,belle-cowl-swing-sweater#Green,belle-cowl-swing-sweater,green,top,relaxed,plain,unknown,swing,unknown,cowl,unknown,green
18,stara-cardigan#GreyMarle,stara-cardigan,greymarle,cardigan,layering,plain,unknown,unknown,unknown,unknown,unknown,grey
19,the-half-sleeve-tee#Black,the-half-sleeve-tee,black,top,casual,plain,unknown,unknown,short,unknown,unknown,black
20,falling-for-you-cardi#Teal,falling-for-you-cardi,teal,unknown,unknown,plain,unknown,unknown,unknown,unknown,unknown,teal
21,the-batwing-tee#FrenchBlue,the-batwing-tee,frenchblue,top,relaxed,plain,unknown,relaxed,batwing,unknown,unknown,blue
22,true-love-bell-blouse#Jade,true-love-bell-blouse,jade,top,elegant,plain,unknown,unknown,unknown,unknown,unknown,jade
23,foil-spot-tee-1#Navy,foil-spot-tee-1,navy,top,casual,spot,unknown,unknown,unknown,unknown,unknown,navy
24,vivian-blouse#Check,vivian-blouse,check,top,elegant,check,unknown,unknown,unknown,unknown,unknown,unknown
25,lilly-layer-stripe-tank#NavyWhite,lilly-layer-stripe-tank,navywhite,top,casual,stripe,unknown,unknown,unknown,unknown,unknown,white
26,reversible-scoopv-neck-tank#Black,reversible-scoopv-neck-tank,black,top,casual,plain,unknown,unknown,unknown,v_neck,unknown,black
27,the-essential-pullover#SkyBlue,the-essential-pullover,skyblue,top,casual,plain,unknown,unknown,unknown,unknown,unknown,blue
28,belle-drape-tee#Sliver,belle-drape-tee,sliver,top,casual,plain,unknown,unknown,unknown,unknown,unknown,unknown
29,maui-stretch-tee#Black,maui-stretch-tee,black,top,fitted,plain,stretch,fitted,unknown,unknown,unknown,black

======================================================================
SEMANTIC FEATURES SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_garment_semantic_features.csv

ZYRA V2 STEP 6 COMPLETE

In [80]:
# ============================================================
# ZYRA V2 — STEP 7 CORRECTED
# HYBRID PERSON × GARMENT DATASET
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

TRAINING_PATH = (
    BASE /
    "data/v2/v2_confident_training_dataset.csv"
)

SEMANTIC_PATH = (
    BASE /
    "data/v2/v2_garment_semantic_features.csv"
)

OUTPUT_CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_hybrid_candidates.csv"
)

OUTPUT_TRAINING_PATH = (
    BASE /
    "data/v2/v2_hybrid_training_dataset.csv"
)

# ============================================================
# LOAD
# ============================================================

candidates = pd.read_csv(
    CANDIDATE_PATH
)

training = pd.read_csv(
    TRAINING_PATH
)

semantic = pd.read_csv(
    SEMANTIC_PATH
)

print("=" * 70)
print("ZYRA V2 — STEP 7 CORRECTED HYBRID DATASET")
print("=" * 70)

print(
    "Candidates:",
    len(candidates)
)

print(
    "Training:",
    len(training)
)

print(
    "Semantic garments:",
    len(semantic)
)

# ============================================================
# VALIDATE SEMANTIC TABLE
# ============================================================

assert "product_id" in semantic.columns

assert (
    semantic["product_id"]
    .duplicated()
    .sum()
    == 0
)

# ============================================================
# SEMANTIC COLUMNS
# ============================================================

SEMANTIC_CATEGORICAL = [
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]

SEMANTIC_NUMERIC = [
    "category_count",
    "style_count",
    "pattern_count",
    "material_count",
    "semantic_token_count",

    "is_striped",
    "is_floral",
    "is_animal_print",
    "is_checked",
    "is_sequin",

    "is_knit",
    "is_stretch",

    "is_relaxed",
    "is_fitted",
    "is_swing",
    "is_longline",

    "is_off_shoulder",
    "is_batwing",

    "is_long_sleeve",
    "is_short_sleeve",
]

# ============================================================
# KEEP ONLY EXISTING SEMANTIC COLUMNS
# ============================================================

available_cat = [
    c
    for c in SEMANTIC_CATEGORICAL
    if c in semantic.columns
]

available_num = [
    c
    for c in SEMANTIC_NUMERIC
    if c in semantic.columns
]

print("\n" + "=" * 70)
print("AVAILABLE SEMANTIC FEATURES")
print("=" * 70)

print(
    "Categorical:",
    available_cat
)

print(
    "Numeric:",
    available_num
)

# ============================================================
# MERGE
# ============================================================

semantic_subset = semantic[
    [
        "product_id"
    ]
    +
    available_cat
    +
    available_num
].copy()

hybrid_candidates = candidates.merge(
    semantic_subset,
    on="product_id",
    how="left",
    validate="many_to_one",
)

hybrid_training = training.merge(
    semantic_subset,
    on="product_id",
    how="left",
    validate="many_to_one",
)

assert (
    len(hybrid_candidates)
    ==
    len(candidates)
)

assert (
    len(hybrid_training)
    ==
    len(training)
)

# ============================================================
# NORMALIZE CATEGORICALS
# ============================================================

for col in available_cat:

    hybrid_candidates[col] = (
        hybrid_candidates[col]
        .fillna("unknown")
        .astype(str)
        .str.strip()
        .str.lower()
    )

    hybrid_training[col] = (
        hybrid_training[col]
        .fillna("unknown")
        .astype(str)
        .str.strip()
        .str.lower()
    )

# ============================================================
# ONE-HOT ENCODING
# ============================================================

candidate_cat = pd.get_dummies(
    hybrid_candidates[
        available_cat
    ],
    prefix=available_cat,
    dtype=np.float32,
)

training_cat = pd.get_dummies(
    hybrid_training[
        available_cat
    ],
    prefix=available_cat,
    dtype=np.float32,
)

# ============================================================
# ALIGN COLUMNS
# ============================================================
#
# This is critical.
#
# Candidate and training matrices must have exactly the
# same semantic feature columns.
# ============================================================

candidate_cat, training_cat = (
    candidate_cat.align(
        training_cat,
        join="outer",
        axis=1,
        fill_value=0.0,
    )
)

# ============================================================
# BASE COLUMNS
# ============================================================

IDENTIFIERS = [
    "person_id",
    "product_id",
]

LABEL_COLUMNS = [
    "label_status",
    "training_label",
]

# ------------------------------------------------------------
# Physical features
# ------------------------------------------------------------

PHYSICAL_FEATURES = [
    "height",
    "bust",
    "waist",
    "hips",

    "garment_bust",
    "garment_waist",
    "garment_hip",
    "garment_length",
    "garment_sleeve",

    "bust_ease",
    "waist_ease",
    "hip_ease",

    "bust_ratio",
    "waist_ratio",
    "hip_ratio",

    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",

    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",

    "mean_ease",
    "ease_std",

    "known_fit_dimensions",
    "tight_dimension_count",
    "extreme_ease_count",

    "length_height_ratio",
]

# ============================================================
# SELECT EXISTING PHYSICAL FEATURES
# ============================================================

available_physical = [
    c
    for c in PHYSICAL_FEATURES
    if c in hybrid_training.columns
]

print("\n" + "=" * 70)
print("PHYSICAL FEATURES")
print("=" * 70)

print(
    "Available:",
    len(available_physical)
)

# ============================================================
# BUILD BASE MATRICES
# ============================================================

candidate_base = hybrid_candidates[
    available_physical
].copy()

training_base = hybrid_training[
    available_physical
].copy()

# ============================================================
# FORCE NUMERIC
# ============================================================

for col in available_physical:

    candidate_base[col] = pd.to_numeric(
        candidate_base[col],
        errors="coerce",
    )

    training_base[col] = pd.to_numeric(
        training_base[col],
        errors="coerce",
    )

# ============================================================
# SEMANTIC NUMERIC FEATURES
# ============================================================

candidate_num = hybrid_candidates[
    available_num
].copy()

training_num = hybrid_training[
    available_num
].copy()

for col in available_num:

    candidate_num[col] = pd.to_numeric(
        candidate_num[col],
        errors="coerce",
    )

    training_num[col] = pd.to_numeric(
        training_num[col],
        errors="coerce",
    )

# ============================================================
# RESET INDEX
# ============================================================

candidate_base = (
    candidate_base
    .reset_index(drop=True)
)

training_base = (
    training_base
    .reset_index(drop=True)
)

candidate_num = (
    candidate_num
    .reset_index(drop=True)
)

training_num = (
    training_num
    .reset_index(drop=True)
)

candidate_cat = (
    candidate_cat
    .reset_index(drop=True)
)

training_cat = (
    training_cat
    .reset_index(drop=True)
)

# ============================================================
# COMBINE
# ============================================================

candidate_features = pd.concat(
    [
        candidate_base,
        candidate_num,
        candidate_cat,
    ],
    axis=1,
)

training_features = pd.concat(
    [
        training_base,
        training_num,
        training_cat,
    ],
    axis=1,
)

# ============================================================
# FORCE ALL FEATURES NUMERIC
# ============================================================

for col in candidate_features.columns:

    candidate_features[col] = pd.to_numeric(
        candidate_features[col],
        errors="coerce",
    )

for col in training_features.columns:

    training_features[col] = pd.to_numeric(
        training_features[col],
        errors="coerce",
    )

# ============================================================
# FINAL COLUMN ALIGNMENT
# ============================================================

candidate_features, training_features = (
    candidate_features.align(
        training_features,
        join="outer",
        axis=1,
        fill_value=0.0,
    )
)

# ============================================================
# ADD IDENTIFIERS
# ============================================================

candidate_output = pd.concat(
    [
        hybrid_candidates[
            IDENTIFIERS
        ].reset_index(drop=True),

        candidate_features.reset_index(
            drop=True
        ),
    ],
    axis=1,
)

training_output = pd.concat(
    [
        hybrid_training[
            IDENTIFIERS
            +
            LABEL_COLUMNS
        ].reset_index(drop=True),

        training_features.reset_index(
            drop=True
        ),
    ],
    axis=1,
)

# ============================================================
# FEATURE LIST
# ============================================================

HYBRID_FEATURES = [
    col
    for col in training_output.columns
    if col not in (
        IDENTIFIERS
        +
        LABEL_COLUMNS
    )
]

# ============================================================
# VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL HYBRID VALIDATION")
print("=" * 70)

print(
    "Hybrid feature count:",
    len(HYBRID_FEATURES)
)

print(
    "Candidate shape:",
    candidate_output.shape
)

print(
    "Training shape:",
    training_output.shape
)

# ------------------------------------------------------------
# Numeric validation
# ------------------------------------------------------------

non_numeric_train = [
    col
    for col in HYBRID_FEATURES
    if not pd.api.types.is_numeric_dtype(
        training_output[col]
    )
]

non_numeric_candidate = [
    col
    for col in HYBRID_FEATURES
    if not pd.api.types.is_numeric_dtype(
        candidate_output[col]
    )
]

print(
    "\nNon-numeric training:",
    non_numeric_train
)

print(
    "Non-numeric candidate:",
    non_numeric_candidate
)

assert (
    len(non_numeric_train)
    == 0
)

assert (
    len(non_numeric_candidate)
    == 0
)

# ------------------------------------------------------------
# NaN / Inf
# ------------------------------------------------------------

train_matrix = (
    training_output[
        HYBRID_FEATURES
    ]
    .to_numpy(
        dtype=np.float32
    )
)

candidate_matrix = (
    candidate_output[
        HYBRID_FEATURES
    ]
    .to_numpy(
        dtype=np.float32
    )
)

train_nan = np.isnan(
    train_matrix
).sum()

candidate_nan = np.isnan(
    candidate_matrix
).sum()

train_inf = np.isinf(
    train_matrix
).sum()

candidate_inf = np.isinf(
    candidate_matrix
).sum()

print(
    "\nTraining NaN:",
    train_nan
)

print(
    "Candidate NaN:",
    candidate_nan
)

print(
    "Training Inf:",
    train_inf
)

print(
    "Candidate Inf:",
    candidate_inf
)

# NaN is allowed at this stage for physical measurements.
# It will be imputed during training.

assert train_inf == 0
assert candidate_inf == 0

# ============================================================
# DUPLICATE PAIRS
# ============================================================

candidate_duplicates = (
    candidate_output[
        [
            "person_id",
            "product_id",
        ]
    ]
    .duplicated()
    .sum()
)

training_duplicates = (
    training_output[
        [
            "person_id",
            "product_id",
        ]
    ]
    .duplicated()
    .sum()
)

print(
    "\nCandidate duplicate pairs:",
    candidate_duplicates
)

print(
    "Training duplicate pairs:",
    training_duplicates
)

assert candidate_duplicates == 0
assert training_duplicates == 0

# ============================================================
# LABEL COUNTS
# ============================================================

print("\n" + "=" * 70)
print("TRAINING LABELS")
print("=" * 70)

print(
    training_output[
        "training_label"
    ]
    .value_counts()
)

# ============================================================
# SAVE
# ============================================================

candidate_output.to_csv(
    OUTPUT_CANDIDATE_PATH,
    index=False,
)

training_output.to_csv(
    OUTPUT_TRAINING_PATH,
    index=False,
)

# ============================================================
# FINAL
# ============================================================

print("\n" + "=" * 70)
print("HYBRID DATASET SAVED")
print("=" * 70)

print(
    "Candidate:",
    OUTPUT_CANDIDATE_PATH
)

print(
    "Training:",
    OUTPUT_TRAINING_PATH
)

print(
    "\nFeature count:",
    len(HYBRID_FEATURES)
)

print(
    "\nZYRA V2 STEP 7 COMPLETE"
)

======================================================================
ZYRA V2 — STEP 7 CORRECTED HYBRID DATASET
======================================================================
Candidates: 50232
Training: 13683
Semantic garments: 897

======================================================================
AVAILABLE SEMANTIC FEATURES
======================================================================
Categorical: ['category', 'style', 'pattern', 'material', 'silhouette', 'sleeve_type', 'neckline', 'length_style', 'color']
Numeric: ['category_count', 'style_count', 'pattern_count', 'material_count', 'semantic_token_count', 'is_striped', 'is_floral', 'is_animal_print', 'is_checked', 'is_sequin', 'is_knit', 'is_stretch', 'is_relaxed', 'is_fitted', 'is_swing', 'is_longline', 'is_off_shoulder', 'is_batwing', 'is_long_sleeve', 'is_short_sleeve']

======================================================================
PHYSICAL FEATURES
======================================================================
Available: 27

======================================================================
FINAL HYBRID VALIDATION
======================================================================
Hybrid feature count: 125
Candidate shape: (50232, 127)
Training shape: (13683, 129)

Non-numeric training: []
Non-numeric candidate: []

Training NaN: 24697
Candidate NaN: 103544
Training Inf: 0
Candidate Inf: 0

Candidate duplicate pairs: 0
Training duplicate pairs: 0

======================================================================
TRAINING LABELS
======================================================================
training_label
0    10693
1     2990
Name: count, dtype: int64

======================================================================
HYBRID DATASET SAVED
======================================================================
Candidate: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_hybrid_candidates.csv
Training: /Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_hybrid_training_dataset.csv

Feature count: 125

ZYRA V2 STEP 7 COMPLETE

In [84]:
# ============================================================
# ZYRA V2 — SAVE CURRENT HYBRID MODEL
# ============================================================

from pathlib import Path
import torch

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_hybrid_ranker.pt"
)

# These objects should still exist from Step 8:
# model
# FEATURES
# train_people
# val_people
# test_people
# imputer
# scaler

required = [
    "model",
    "FEATURES",
    "train_people",
    "val_people",
    "test_people",
    "imputer",
    "scaler",
]

missing = [
    name
    for name in required
    if name not in globals()
]

if missing:

    raise RuntimeError(
        "Missing objects from training session: "
        + str(missing)
        + "\n\n"
        "If 'model' is missing, the training cell "
        "must be rerun."
    )

checkpoint = {
    "model_state_dict":
        model.state_dict(),

    "feature_names":
        list(FEATURES),

    "input_dim":
        len(FEATURES),

    "train_people":
        sorted(
            train_people
        ),

    "validation_people":
        sorted(
            val_people
        ),

    "test_people":
        sorted(
            test_people
        ),

    "imputer_statistics":
        imputer.statistics_,

    "scaler_mean":
        scaler.mean_,

    "scaler_scale":
        scaler.scale_,

    "version":
        "ZYRA_V2_HYBRID",

    "seed":
        42,
}

MODEL_PATH.parent.mkdir(
    parents=True,
    exist_ok=True,
)

torch.save(
    checkpoint,
    MODEL_PATH,
)

print("=" * 70)
print("HYBRID MODEL SAVED")
print("=" * 70)

print(
    MODEL_PATH
)

print(
    "\nInput features:",
    len(FEATURES)
)

print(
    "Train people:",
    len(train_people)
)

print(
    "Validation people:",
    len(val_people)
)

print(
    "Test people:",
    len(test_people)
)

print(
    "\nFile exists:",
    MODEL_PATH.exists()
)

print("=" * 70)

======================================================================
HYBRID MODEL SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_hybrid_ranker.pt

Input features: 125
Train people: 40
Validation people: 8
Test people: 8

File exists: True
======================================================================

In [85]:
# ============================================================
# ZYRA V2 — STEP 8
# HYBRID FULL-CATALOG RANKING EVALUATION
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_hybrid_ranker.pt"
)

HYBRID_PATH = (
    BASE /
    "data/v2/v2_hybrid_candidates.csv"
)

ORIGINAL_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

RESULT_PATH = (
    BASE /
    "data/v2/v2_hybrid_ranking_results.csv"
)

# ============================================================
# LOAD
# ============================================================

print("=" * 70)
print("ZYRA V2 — HYBRID FULL-CATALOG EVALUATION")
print("=" * 70)

hybrid = pd.read_csv(
    HYBRID_PATH
)

original = pd.read_csv(
    ORIGINAL_PATH
)

checkpoint = torch.load(
    MODEL_PATH,
    map_location="cpu",
    weights_only=False,
)

FEATURES = checkpoint[
    "feature_names"
]

TEST_PEOPLE = set(
    checkpoint[
        "test_people"
    ]
)

print(
    "Hybrid rows:",
    len(hybrid)
)

print(
    "Original rows:",
    len(original)
)

print(
    "Feature count:",
    len(FEATURES)
)

print(
    "Test people:",
    sorted(TEST_PEOPLE)
)

# ============================================================
# MODEL
# ============================================================

class HybridRanker(nn.Module):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                128,
            ),

            nn.ReLU(),

            nn.BatchNorm1d(
                128
            ),

            nn.Dropout(
                0.15
            ),

            nn.Linear(
                128,
                64,
            ),

            nn.ReLU(),

            nn.Dropout(
                0.10
            ),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(self, x):

        return self.network(
            x
        ).squeeze(-1)


model = HybridRanker(
    len(FEATURES)
)

model.load_state_dict(
    checkpoint[
        "model_state_dict"
    ]
)

model.eval()

print(
    "\nModel loaded successfully."
)

# ============================================================
# RECONSTRUCT GROUND TRUTH
# ============================================================

ground_truth = original[
    [
        "person_id",
        "product_id",
        "label_status",
    ]
].copy()

# ============================================================
# VERIFY PAIRS
# ============================================================

hybrid_pairs = set(
    zip(
        hybrid[
            "person_id"
        ],
        hybrid[
            "product_id"
        ],
    )
)

truth_pairs = set(
    zip(
        ground_truth[
            "person_id"
        ],
        ground_truth[
            "product_id"
        ],
    )
)

print("\n" + "=" * 70)
print("GROUND-TRUTH ALIGNMENT")
print("=" * 70)

print(
    "Hybrid pairs:",
    len(hybrid_pairs)
)

print(
    "Ground-truth pairs:",
    len(truth_pairs)
)

print(
    "Missing pairs:",
    len(
        truth_pairs
        -
        hybrid_pairs
    )
)

print(
    "Extra pairs:",
    len(
        hybrid_pairs
        -
        truth_pairs
    )
)

assert (
    hybrid_pairs
    ==
    truth_pairs
)

# ============================================================
# MERGE GROUND TRUTH
# ============================================================

ranking_df = hybrid.merge(
    ground_truth,
    on=[
        "person_id",
        "product_id",
    ],
    how="left",
    validate="one_to_one",
)

assert (
    ranking_df[
        "label_status"
    ]
    .notna()
    .all()
)

print(
    "\nGround truth successfully attached."
)

# ============================================================
# FEATURE MATRIX
# ============================================================

X = (
    ranking_df[
        FEATURES
    ]
    .to_numpy(
        dtype=np.float32
    )
)

print("\n" + "=" * 70)
print("FEATURE MATRIX")
print("=" * 70)

print(
    "Shape:",
    X.shape
)

# ============================================================
# IMPUTATION
# ============================================================

imputer_values = np.asarray(
    checkpoint[
        "imputer_statistics"
    ],
    dtype=np.float32,
)

for i in range(
    X.shape[1]
):

    missing = np.isnan(
        X[:, i]
    )

    if missing.any():

        X[
            missing,
            i
        ] = imputer_values[i]

# ============================================================
# SCALING
# ============================================================

scaler_mean = np.asarray(
    checkpoint[
        "scaler_mean"
    ],
    dtype=np.float32,
)

scaler_scale = np.asarray(
    checkpoint[
        "scaler_scale"
    ],
    dtype=np.float32,
)

scaler_scale = np.where(
    scaler_scale == 0,
    1.0,
    scaler_scale,
)

X = (
    X
    -
    scaler_mean
)

X = (
    X
    /
    scaler_scale
)

print(
    "NaN after preprocessing:",
    np.isnan(X).sum()
)

print(
    "Inf after preprocessing:",
    np.isinf(X).sum()
)

assert np.isnan(X).sum() == 0
assert np.isinf(X).sum() == 0

# ============================================================
# SCORE ALL CANDIDATES
# ============================================================

X_tensor = torch.tensor(
    X,
    dtype=torch.float32,
)

with torch.no_grad():

    scores = (
        torch.sigmoid(
            model(
                X_tensor
            )
        )
        .numpy()
    )

# ============================================================
# ADD SCORES
# ============================================================

ranking_df = pd.concat(
    [
        ranking_df.reset_index(
            drop=True
        ),

        pd.DataFrame(
            {
                "hybrid_score":
                    scores
            }
        ),
    ],
    axis=1,
)

# ============================================================
# TEST PEOPLE ONLY
# ============================================================

ranking_df = ranking_df[
    ranking_df[
        "person_id"
    ].isin(
        TEST_PEOPLE
    )
].copy()

# ============================================================
# POSITIVE FLAG
# ============================================================

ranking_df[
    "is_positive"
] = (
    ranking_df[
        "label_status"
    ]
    ==
    "positive"
)

# ============================================================
# FULL CATALOG VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("CATALOG VALIDATION")
print("=" * 70)

catalog_counts = (
    ranking_df
    .groupby(
        "person_id"
    )[
        "product_id"
    ]
    .nunique()
)

print(
    catalog_counts
)

assert (
    catalog_counts == 897
).all()

# ============================================================
# RANK
# ============================================================

ranking_df[
    "rank"
] = (
    ranking_df
    .groupby(
        "person_id"
    )[
        "hybrid_score"
    ]
    .rank(
        method="first",
        ascending=False,
    )
)

# ============================================================
# METRIC FUNCTIONS
# ============================================================

def recall_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:

        return 0.0

    return float(
        np.mean(
            ranks <= k
        )
    )


def ndcg_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:

        return 0.0

    dcg = sum(

        1.0
        /
        np.log2(
            rank + 1
        )

        for rank in ranks

        if rank <= k
    )

    ideal_count = min(
        len(ranks),
        k,
    )

    if ideal_count == 0:

        return 0.0

    idcg = sum(

        1.0
        /
        np.log2(
            i + 2
        )

        for i in range(
            ideal_count
        )
    )

    return float(
        dcg / idcg
    )


def reciprocal_rank(
    ranks
):

    if len(ranks) == 0:

        return 0.0

    return float(
        1.0
        /
        np.min(ranks)
    )

# ============================================================
# PER PERSON
# ============================================================

person_results = []

for person_id, group in (
    ranking_df
    .groupby(
        "person_id"
    )
):

    positive_ranks = (
        group[
            group[
                "is_positive"
            ]
        ][
            "rank"
        ]
        .to_numpy()
    )

    person_results.append(
        {
            "person_id":
                person_id,

            "positive_count":
                len(
                    positive_ranks
                ),

            "recall@5":
                recall_at_k(
                    positive_ranks,
                    5,
                ),

            "recall@10":
                recall_at_k(
                    positive_ranks,
                    10,
                ),

            "recall@20":
                recall_at_k(
                    positive_ranks,
                    20,
                ),

            "recall@50":
                recall_at_k(
                    positive_ranks,
                    50,
                ),

            "recall@100":
                recall_at_k(
                    positive_ranks,
                    100,
                ),

            "ndcg@10":
                ndcg_at_k(
                    positive_ranks,
                    10,
                ),

            "ndcg@20":
                ndcg_at_k(
                    positive_ranks,
                    20,
                ),

            "mrr":
                reciprocal_rank(
                    positive_ranks
                ),

            "best_rank":
                (
                    np.min(
                        positive_ranks
                    )
                    if len(
                        positive_ranks
                    )
                    else np.nan
                ),

            "median_rank":
                (
                    np.median(
                        positive_ranks
                    )
                    if len(
                        positive_ranks
                    )
                    else np.nan
                ),
        }
    )

person_results = pd.DataFrame(
    person_results
)

# ============================================================
# GLOBAL METRICS
# ============================================================

print("\n" + "=" * 70)
print("GLOBAL HYBRID RANKING RESULTS")
print("=" * 70)

metrics = [
    "recall@5",
    "recall@10",
    "recall@20",
    "recall@50",
    "recall@100",
    "ndcg@10",
    "ndcg@20",
    "mrr",
]

for metric in metrics:

    print(
        f"{metric:15s}: "
        f"{person_results[metric].mean():.4f}"
    )

# ============================================================
# ALL POSITIVE RANKS
# ============================================================

positive_ranks = (
    ranking_df[
        ranking_df[
            "is_positive"
        ]
    ][
        "rank"
    ]
    .to_numpy()
)

print("\n" + "=" * 70)
print("POSITIVE RANK DISTRIBUTION")
print("=" * 70)

print(
    pd.Series(
        positive_ranks
    ).describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
        ]
    )
)

# ============================================================
# TOP-K HIT COUNTS
# ============================================================

print("\n" + "=" * 70)
print("KNOWN POSITIVES IN TOP-K")
print("=" * 70)

total_positive = len(
    positive_ranks
)

for k in [
    1,
    5,
    10,
    20,
    50,
    100,
]:

    hits = np.sum(
        positive_ranks <= k
    )

    percentage = (
        hits
        /
        total_positive
        *
        100
    )

    print(
        f"Top-{k:3d}: "
        f"{hits:4d} / "
        f"{total_positive:4d} "
        f"({percentage:6.2f}%)"
    )

# ============================================================
# PER-PERSON RESULTS
# ============================================================

print("\n" + "=" * 70)
print("PER-PERSON RESULTS")
print("=" * 70)

print(
    person_results[
        [
            "person_id",
            "positive_count",
            "recall@10",
            "recall@20",
            "recall@100",
            "ndcg@10",
            "ndcg@20",
            "mrr",
            "best_rank",
            "median_rank",
        ]
    ]
    .sort_values(
        "person_id"
    )
    .to_string(
        index=False
    )
)

# ============================================================
# TOP 10 RECOMMENDATIONS
# ============================================================

print("\n" + "=" * 70)
print("TOP 10 HYBRID RECOMMENDATIONS")
print("=" * 70)

for person_id, group in (
    ranking_df
    .groupby(
        "person_id"
    )
):

    top10 = (
        group
        .sort_values(
            "rank"
        )
        .head(10)
    )

    print(
        f"\nPerson: {person_id}"
    )

    display(
        top10[
            [
                "rank",
                "product_id",
                "hybrid_score",
                "is_positive",
            ]
        ]
    )

# ============================================================
# SAVE DETAILED RANKINGS
# ============================================================

ranking_df.to_csv(
    RESULT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("EVALUATION SAVED")
print("=" * 70)

print(
    RESULT_PATH
)

print("\n" + "=" * 70)
print("ZYRA V2 STEP 8 COMPLETE")
print("=" * 70)

======================================================================
ZYRA V2 — HYBRID FULL-CATALOG EVALUATION
======================================================================
Hybrid rows: 50232
Original rows: 50232
Feature count: 125
Test people: ['Alex', 'Anna Maria', 'Bree', 'Chesska', 'Emma', 'Maddy', 'Palatina', 'Sophie']

Model loaded successfully.

======================================================================
GROUND-TRUTH ALIGNMENT
======================================================================
Hybrid pairs: 50232
Ground-truth pairs: 50232
Missing pairs: 0
Extra pairs: 0

Ground truth successfully attached.

======================================================================
FEATURE MATRIX
======================================================================
Shape: (50232, 125)
NaN after preprocessing: 0
Inf after preprocessing: 0

======================================================================
CATALOG VALIDATION
======================================================================
person_id
Alex          897
Anna Maria    897
Bree          897
Chesska       897
Emma          897
Maddy         897
Palatina      897
Sophie        897
Name: product_id, dtype: int64

======================================================================
GLOBAL HYBRID RANKING RESULTS
======================================================================
recall@5       : 0.0200
recall@10      : 0.0259
recall@20      : 0.0409
recall@50      : 0.0589
recall@100     : 0.1205
ndcg@10        : 0.1587
ndcg@20        : 0.1306
mrr            : 0.2805

======================================================================
POSITIVE RANK DISTRIBUTION
======================================================================
count    339.000000
mean     469.082596
std      238.191185
min        1.000000
25%      318.000000
50%      530.000000
75%      649.500000
90%      733.200000
95%      796.400000
max      896.000000
dtype: float64

======================================================================
KNOWN POSITIVES IN TOP-K
======================================================================
Top-  1:    2 /  339 (  0.59%)
Top-  5:    8 /  339 (  2.36%)
Top- 10:   10 /  339 (  2.95%)
Top- 20:   16 /  339 (  4.72%)
Top- 50:   25 /  339 (  7.37%)
Top-100:   47 /  339 ( 13.86%)

======================================================================
PER-PERSON RESULTS
======================================================================
 person_id  positive_count  recall@10  recall@20  recall@100  ndcg@10  ndcg@20      mrr  best_rank  median_rank
      Alex              37   0.135135   0.216216    0.324324 0.627409 0.516978 1.000000        1.0        541.0
Anna Maria              18   0.000000   0.000000    0.000000 0.000000 0.000000 0.006135      163.0        306.5
      Bree               6   0.000000   0.000000    0.000000 0.000000 0.000000 0.003968      252.0        282.0
   Chesska              11   0.000000   0.000000    0.181818 0.000000 0.000000 0.019231       52.0        321.0
      Emma              87   0.000000   0.000000    0.045977 0.000000 0.000000 0.031250       32.0        583.0
     Maddy              77   0.051948   0.090909    0.311688 0.563788 0.477366 1.000000        1.0        408.0
  Palatina              49   0.020408   0.020408    0.081633 0.078398 0.050596 0.166667        6.0        495.0
    Sophie              54   0.000000   0.000000    0.018519 0.000000 0.000000 0.016949       59.0        573.5

======================================================================
TOP 10 HYBRID RECOMMENDATIONS
======================================================================

Person: Alex

,rank,product_id,hybrid_score,is_positive
37405,1.0,the-short-sleeve-wrap-jersey-top#Emerald,0.733962,True
37236,2.0,the-short-sleeve-wrap-jersey-top#Black,0.732904,True
37206,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.730139,True
37301,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.728709,True
37572,5.0,bamboo-layer-tank#Chalk,0.687307,False
37191,6.0,the-boat-neck-top#Black,0.679452,False
37577,7.0,bamboo-layer-tank#Black,0.674327,False
36832,8.0,the-boat-neck-top#Navy,0.672654,False
37133,9.0,the-reversible-cowl-neck-top-2#Ocean,0.665976,False
36798,10.0,the-batwing-tee#FrenchBlue,0.659024,True

Person: Anna Maria

,rank,product_id,hybrid_score,is_positive
34545,1.0,the-short-sleeve-wrap-jersey-top#Black,0.742751,False
34714,2.0,the-short-sleeve-wrap-jersey-top#Emerald,0.740448,False
34515,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.739279,False
34610,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.736104,False
34881,5.0,bamboo-layer-tank#Chalk,0.698011,False
34500,6.0,the-boat-neck-top#Black,0.686076,False
34442,7.0,the-reversible-cowl-neck-top-2#Ocean,0.685611,False
34886,8.0,bamboo-layer-tank#Black,0.684563,False
34141,9.0,the-boat-neck-top#Navy,0.681379,False
34144,10.0,monaco-knot-top#Black,0.657359,False

Person: Bree

,rank,product_id,hybrid_score,is_positive
41721,1.0,the-short-sleeve-wrap-jersey-top#Black,0.790887,False
41691,2.0,the-short-sleeve-wrap-jersey-top#Blue,0.788749,False
41890,3.0,the-short-sleeve-wrap-jersey-top#Emerald,0.788061,False
41786,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.785653,False
41618,5.0,the-reversible-cowl-neck-top-2#Ocean,0.748486,False
41809,6.0,belle-cowl-swing-sweater#Black,0.706500,False
42057,7.0,bamboo-layer-tank#Chalk,0.703459,False
41344,8.0,pure-merino-fine-rib-v-neck#Charcoal,0.701599,False
42062,9.0,bamboo-layer-tank#Black,0.696537,False
41600,10.0,long-sleeve-tee-2#NavyWhite,0.692833,False

Person: Chesska

,rank,product_id,hybrid_score,is_positive
13914,1.0,the-short-sleeve-wrap-jersey-top#Black,0.753542,False
14083,2.0,the-short-sleeve-wrap-jersey-top#Emerald,0.750255,False
13884,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.749129,False
13979,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.746792,False
13811,5.0,the-reversible-cowl-neck-top-2#Ocean,0.710362,False
14250,6.0,bamboo-layer-tank#Chalk,0.694820,False
13962,7.0,holly-rib-long-sleeve-tee#WhiteGrey,0.685069,False
14255,8.0,bamboo-layer-tank#Black,0.683536,False
14202,9.0,ally-long-sleeve-tee#CosmosPr,0.678075,False
13869,10.0,the-boat-neck-top#Black,0.676566,False

Person: Emma

,rank,product_id,hybrid_score,is_positive
8701,1.0,the-short-sleeve-wrap-jersey-top#Emerald,0.733962,False
8532,2.0,the-short-sleeve-wrap-jersey-top#Black,0.732904,False
8502,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.730139,False
8597,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.728709,False
8868,5.0,bamboo-layer-tank#Chalk,0.687307,False
8487,6.0,the-boat-neck-top#Black,0.679452,False
8873,7.0,bamboo-layer-tank#Black,0.674327,False
8128,8.0,the-boat-neck-top#Navy,0.672654,False
8429,9.0,the-reversible-cowl-neck-top-2#Ocean,0.665976,False
8094,10.0,the-batwing-tee#FrenchBlue,0.659024,False

Person: Maddy

,rank,product_id,hybrid_score,is_positive
13017,1.0,the-short-sleeve-wrap-jersey-top#Black,0.763323,True
13186,2.0,the-short-sleeve-wrap-jersey-top#Emerald,0.758908,True
12987,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.758747,True
13082,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.756498,True
12914,5.0,the-reversible-cowl-neck-top-2#Ocean,0.721497,False
13353,6.0,bamboo-layer-tank#Chalk,0.702183,False
13358,7.0,bamboo-layer-tank#Black,0.689753,False
12972,8.0,the-boat-neck-top#Black,0.681050,False
13305,9.0,ally-long-sleeve-tee#CosmosPr,0.680479,False
13065,10.0,holly-rib-long-sleeve-tee#WhiteGrey,0.678960,False

Person: Palatina

,rank,product_id,hybrid_score,is_positive
17502,1.0,the-short-sleeve-wrap-jersey-top#Black,0.800731,False
17472,2.0,the-short-sleeve-wrap-jersey-top#Blue,0.797810,False
17671,3.0,the-short-sleeve-wrap-jersey-top#Emerald,0.797486,False
17567,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.795994,False
17399,5.0,the-reversible-cowl-neck-top-2#Ocean,0.771173,False
17125,6.0,pure-merino-fine-rib-v-neck#Charcoal,0.722367,True
17691,7.0,forget-me-knot-tunic#ForgetMeK,0.720378,False
17838,8.0,bamboo-layer-tank#Chalk,0.713205,False
17381,9.0,long-sleeve-tee-2#NavyWhite,0.711124,False
17550,10.0,holly-rib-long-sleeve-tee#WhiteGrey,0.708535,False

Person: Sophie

,rank,product_id,hybrid_score,is_positive
16605,1.0,the-short-sleeve-wrap-jersey-top#Black,0.822884,False
16575,2.0,the-short-sleeve-wrap-jersey-top#Blue,0.821927,False
16670,3.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.821274,False
16774,4.0,the-short-sleeve-wrap-jersey-top#Emerald,0.821124,False
16610,5.0,analia-jersey-top#Black,0.764081,False
16693,6.0,belle-cowl-swing-sweater#Black,0.764026,False
16502,7.0,the-reversible-cowl-neck-top-2#Ocean,0.763355,False
16710,8.0,ava-short-sleeve-linen-tee#Navy,0.762670,False
16527,9.0,analia-jersey-top#Navy,0.753667,False
16163,10.0,belle-cowl-swing-sweater#Green,0.751828,False

======================================================================
EVALUATION SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_hybrid_ranking_results.csv

======================================================================
ZYRA V2 STEP 8 COMPLETE
======================================================================

In [86]:
# ============================================================
# ZYRA V2 — STEP 9
# PERSON-SPECIFIC PREFERENCE PROFILES
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

TRAINING_PATH = (
    BASE /
    "data/v2/v2_confident_training_dataset.csv"
)

SEMANTIC_PATH = (
    BASE /
    "data/v2/v2_garment_semantic_features.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_person_preference_profiles.csv"
)

# ============================================================
# LOAD
# ============================================================

training = pd.read_csv(
    TRAINING_PATH
)

semantic = pd.read_csv(
    SEMANTIC_PATH
)

print("=" * 70)
print("ZYRA V2 — STEP 9 PERSON PREFERENCE PROFILES")
print("=" * 70)

# ============================================================
# POSITIVE INTERACTIONS ONLY
# ============================================================

positive = training[
    training[
        "training_label"
    ] == 1
].copy()

print(
    "Positive interactions:",
    len(positive)
)

print(
    "People:",
    positive[
        "person_id"
    ].nunique()
)

# ============================================================
# MERGE PRODUCT SEMANTICS
# ============================================================

semantic_columns = [
    "product_id",
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]

semantic_subset = semantic[
    [
        c
        for c in semantic_columns
        if c in semantic.columns
    ]
].copy()

positive = positive.merge(
    semantic_subset,
    on="product_id",
    how="left",
    validate="many_to_one",
)

# ============================================================
# UNKNOWN NORMALIZATION
# ============================================================

profile_columns = [
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]

for col in profile_columns:

    if col in positive.columns:

        positive[col] = (
            positive[col]
            .fillna("unknown")
            .astype(str)
            .str.lower()
            .str.strip()
        )

# ============================================================
# CREATE PROFILE ROWS
# ============================================================

profile_rows = []

for person_id, group in (
    positive.groupby(
        "person_id"
    )
):

    row = {
        "person_id":
            person_id,

        "positive_count":
            len(group),
    }

    # --------------------------------------------------------
    # CATEGORY
    # --------------------------------------------------------

    for column in profile_columns:

        if column not in group.columns:

            continue

        counts = (
            group[
                column
            ]
            .value_counts(
                normalize=True
            )
        )

        # Top preference
        if len(counts):

            row[
                f"{column}_top"
            ] = counts.index[0]

            row[
                f"{column}_top_share"
            ] = counts.iloc[0]

        else:

            row[
                f"{column}_top"
            ] = "unknown"

            row[
                f"{column}_top_share"
            ] = 0.0

        # ----------------------------------------------------
        # TOP 3 DISTRIBUTION
        # ----------------------------------------------------

        top3 = counts.head(3)

        for rank in range(
            3
        ):

            if rank < len(top3):

                value = (
                    top3.index[
                        rank
                    ]
                )

                share = (
                    top3.iloc[
                        rank
                    ]
                )

            else:

                value = "unknown"
                share = 0.0

            row[
                f"{column}_{rank+1}"
            ] = value

            row[
                f"{column}_{rank+1}_share"
            ] = share

    profile_rows.append(
        row
    )

# ============================================================
# DATAFRAME
# ============================================================

profiles = pd.DataFrame(
    profile_rows
)

# ============================================================
# DISPLAY
# ============================================================

print("\n" + "=" * 70)
print("PERSON PROFILES")
print("=" * 70)

print(
    "Profiles:",
    len(profiles)
)

print(
    "Columns:",
    len(profiles.columns)
)

display(
    profiles
)

# ============================================================
# DETAILED PROFILE REPORT
# ============================================================

print("\n" + "=" * 70)
print("DETAILED PREFERENCE PROFILES")
print("=" * 70)

for _, row in profiles.iterrows():

    print(
        f"\n{'=' * 50}"
    )

    print(
        "PERSON:",
        row[
            "person_id"
        ]
    )

    print(
        "Positive interactions:",
        row[
            "positive_count"
        ]
    )

    for column in profile_columns:

        top = row.get(
            f"{column}_top",
            "unknown",
        )

        share = row.get(
            f"{column}_top_share",
            0.0,
        )

        top2 = row.get(
            f"{column}_2",
            "unknown",
        )

        top2_share = row.get(
            f"{column}_2_share",
            0.0,
        )

        top3 = row.get(
            f"{column}_3",
            "unknown",
        )

        top3_share = row.get(
            f"{column}_3_share",
            0.0,
        )

        print(
            f"{column:15s}: "
            f"{top} ({share:.2f}) | "
            f"{top2} ({top2_share:.2f}) | "
            f"{top3} ({top3_share:.2f})"
        )

# ============================================================
# PROFILE DIVERSITY
# ============================================================

print("\n" + "=" * 70)
print("PROFILE DIVERSITY")
print("=" * 70)

for column in profile_columns:

    if column not in positive.columns:

        continue

    diversity = (
        positive
        .groupby(
            "person_id"
        )[column]
        .nunique()
    )

    print(
        f"\n{column}"
    )

    print(
        diversity.describe()
        .to_string()
    )

# ============================================================
# PREFERENCE ENTROPY
# ============================================================

print("\n" + "=" * 70)
print("PREFERENCE ENTROPY")
print("=" * 70)

def entropy(
    values
):

    probabilities = (
        values
        .value_counts(
            normalize=True
        )
        .to_numpy()
    )

    if len(
        probabilities
    ) == 0:

        return 0.0

    return float(
        -np.sum(
            probabilities
            *
            np.log2(
                probabilities
            )
        )
    )


entropy_rows = []

for person_id, group in (
    positive.groupby(
        "person_id"
    )
):

    result = {
        "person_id":
            person_id
    }

    for column in profile_columns:

        if column in group.columns:

            result[
                f"{column}_entropy"
            ] = entropy(
                group[
                    column
                ]
            )

    entropy_rows.append(
        result
    )

entropy_df = pd.DataFrame(
    entropy_rows
)

display(
    entropy_df
)

# ============================================================
# SAVE
# ============================================================

profiles.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("PREFERENCE PROFILES SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print("\n" + "=" * 70)
print("ZYRA V2 STEP 9 COMPLETE")
print("=" * 70)

======================================================================
ZYRA V2 — STEP 9 PERSON PREFERENCE PROFILES
======================================================================
Positive interactions: 2990
People: 56

======================================================================
PERSON PROFILES
======================================================================
Profiles: 56
Columns: 74

,person_id,positive_count,category_top,category_top_share,category_1,category_1_share,category_2,category_2_share,category_3,category_3_share,...,length_style_3,length_style_3_share,color_top,color_top_share,color_1,color_1_share,color_2,color_2_share,color_3,color_3_share
0,Alex,37,top,0.918919,top,0.918919,kimono,0.081081,unknown,0.000000,...,unknown,0.000000,unknown,0.351351,unknown,0.351351,blue,0.216216,white,0.135135
1,Amanda,108,top,0.759259,top,0.759259,unknown,0.212963,cardigan,0.018519,...,mid,0.018519,unknown,0.231481,unknown,0.231481,blue,0.129630,grey,0.120370
2,Anna,87,top,0.931034,top,0.931034,unknown,0.034483,cardigan,0.034483,...,short,0.045977,unknown,0.241379,unknown,0.241379,white,0.195402,black,0.183908
3,Anna Maria,18,top,0.500000,top,0.500000,unknown,0.500000,unknown,0.000000,...,unknown,0.000000,navy,0.277778,navy,0.277778,grey,0.222222,unknown,0.222222
4,Anneliese,3,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,black,0.666667,black,0.666667,opal,0.333333,unknown,0.000000
5,Bree,6,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.333333,unknown,0.333333,white,0.166667,pink,0.166667
6,Charlotte,13,top,0.384615,top,0.384615,unknown,0.307692,cardigan,0.230769,...,unknown,0.000000,natural,0.615385,natural,0.615385,blue,0.153846,red,0.153846
7,Chelsea,88,top,0.625000,top,0.625000,unknown,0.272727,cardigan,0.056818,...,unknown,0.000000,unknown,0.238636,unknown,0.238636,navy,0.204545,black,0.204545
8,Chesska,11,top,0.636364,top,0.636364,unknown,0.363636,unknown,0.000000,...,unknown,0.000000,unknown,0.363636,unknown,0.363636,white,0.272727,red,0.090909
9,Clementine,62,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.419355,unknown,0.419355,blue,0.112903,black,0.080645
10,Denniel,26,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.269231,unknown,0.269231,blue,0.230769,white,0.153846
11,Edith,3,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,1.000000,unknown,1.000000,unknown,0.000000,unknown,0.000000
12,Emma,87,top,0.896552,top,0.896552,cardigan,0.045977,unknown,0.034483,...,mid,0.011494,unknown,0.379310,unknown,0.379310,stripe,0.103448,navy,0.091954
13,Fiona,184,top,0.739130,top,0.739130,unknown,0.190217,kimono,0.032609,...,short,0.005435,unknown,0.293478,unknown,0.293478,white,0.141304,navy,0.119565
14,Gemma,84,top,0.797619,top,0.797619,unknown,0.142857,cardigan,0.047619,...,unknown,0.000000,unknown,0.345238,unknown,0.345238,black,0.154762,white,0.130952
15,Georgia,131,top,0.763359,top,0.763359,unknown,0.160305,kimono,0.045802,...,unknown,0.000000,unknown,0.503817,unknown,0.503817,white,0.122137,black,0.076336
16,Grazi,1,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,1.000000,unknown,1.000000,unknown,0.000000,unknown,0.000000
17,Helen,8,top,0.875000,top,0.875000,unknown,0.125000,unknown,0.000000,...,unknown,0.000000,unknown,0.375000,unknown,0.375000,blue,0.250000,navy,0.250000
18,Jess,251,top,0.872510,top,0.872510,unknown,0.103586,cardigan,0.011952,...,short,0.019920,unknown,0.318725,unknown,0.318725,black,0.139442,white,0.131474
19,Jira,1,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,black,1.000000,black,1.000000,unknown,0.000000,unknown,0.000000
20,Jude,14,unknown,0.642857,unknown,0.642857,top,0.285714,cardigan,0.071429,...,unknown,0.000000,unknown,0.500000,unknown,0.500000,stripe,0.142857,teal,0.071429
21,Kate,52,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.423077,unknown,0.423077,black,0.153846,blue,0.115385
22,Katie,24,top,0.750000,top,0.750000,unknown,0.166667,cardigan,0.083333,...,unknown,0.000000,unknown,0.291667,unknown,0.291667,navy,0.250000,pink,0.125000
23,Lara,3,top,0.666667,top,0.666667,cardigan,0.333333,unknown,0.000000,...,unknown,0.000000,unknown,0.666667,unknown,0.666667,stripe,0.333333,unknown,0.000000
24,Laura,244,top,0.897541,top,0.897541,unknown,0.073770,kimono,0.012295,...,short,0.016393,unknown,0.340164,unknown,0.340164,black,0.159836,white,0.151639
25,Lauren,30,top,0.500000,top,0.500000,unknown,0.200000,jacket,0.133333,...,unknown,0.000000,unknown,0.233333,unknown,0.233333,black,0.233333,white,0.133333
26,Lisa,8,top,0.500000,top,0.500000,unknown,0.375000,cardigan,0.125000,...,unknown,0.000000,unknown,0.375000,unknown,0.375000,black,0.250000,navy,0.125000
27,Ljubenka,109,top,0.889908,top,0.889908,unknown,0.091743,kimono,0.009174,...,long,0.009174,unknown,0.376147,unknown,0.376147,black,0.137615,white,0.137615
28,Louise,5,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,black,0.400000,black,0.400000,unknown,0.200000,navy,0.200000
29,Lucy,4,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.250000,unknown,0.250000,blue,0.250000,stone,0.250000
30,Maddy,77,top,0.987013,top,0.987013,unknown,0.012987,unknown,0.000000,...,short,0.051948,unknown,0.298701,unknown,0.298701,white,0.207792,black,0.168831
31,Madeline,37,top,0.783784,top,0.783784,unknown,0.108108,cardigan,0.081081,...,short,0.027027,unknown,0.270270,unknown,0.270270,natural,0.189189,white,0.162162
32,Mae-Lee,159,top,0.937107,top,0.937107,unknown,0.062893,unknown,0.000000,...,short,0.025157,unknown,0.364780,unknown,0.364780,white,0.144654,black,0.113208
33,Mandy,9,top,0.444444,top,0.444444,unknown,0.444444,kimono,0.111111,...,unknown,0.000000,unknown,0.555556,unknown,0.555556,navy,0.222222,white,0.111111
34,Marnee,141,top,0.780142,top,0.780142,unknown,0.148936,kimono,0.049645,...,mid,0.007092,unknown,0.460993,unknown,0.460993,white,0.120567,black,0.099291
35,Mercy,24,top,0.875000,top,0.875000,cardigan,0.083333,unknown,0.041667,...,unknown,0.000000,unknown,0.375000,unknown,0.375000,black,0.291667,green,0.125000
36,Miranda,27,top,0.888889,top,0.888889,unknown,0.074074,cardigan,0.037037,...,unknown,0.000000,unknown,0.481481,unknown,0.481481,white,0.222222,black,0.185185
37,Monique,29,top,0.965517,top,0.965517,unknown,0.034483,unknown,0.000000,...,unknown,0.000000,unknown,0.310345,unknown,0.310345,white,0.241379,black,0.172414
38,Nadine,42,top,0.595238,top,0.595238,unknown,0.309524,cardigan,0.071429,...,mid,0.023810,unknown,0.333333,unknown,0.333333,navy,0.214286,black,0.119048
39,Natalia,46,top,0.586957,top,0.586957,unknown,0.282609,kimono,0.065217,...,unknown,0.000000,unknown,0.391304,unknown,0.391304,navy,0.130435,grey,0.130435
40,Natalie,51,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,mid,0.019608,unknown,0.392157,unknown,0.392157,black,0.176471,white,0.137255
41,Nathalie,14,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.500000,unknown,0.500000,black,0.214286,pink,0.142857
42,Nikki,9,top,0.888889,top,0.888889,unknown,0.111111,unknown,0.000000,...,unknown,0.000000,navy,0.222222,navy,0.222222,unknown,0.222222,white,0.222222
43,Olivia,23,top,1.000000,top,1.000000,unknown,0.000000,unknown,0.000000,...,unknown,0.000000,unknown,0.565217,unknown,0.565217,black,0.130435,white,0.086957
44,Palatina,49,top,0.714286,top,0.714286,unknown,0.244898,kimono,0.020408,...,unknown,0.000000,unknown,0.387755,unknown,0.387755,white,0.142857,black,0.142857
45,Perrie,37,top,0.945946,top,0.945946,unknown,0.027027,cardigan,0.027027,...,mid,0.027027,unknown,0.270270,unknown,0.270270,blue,0.135135,white,0.108108
46,Riina,104,top,0.682692,top,0.682692,unknown,0.259615,cardigan,0.028846,...,mid,0.009615,unknown,0.173077,unknown,0.173077,grey,0.134615,navy,0.125000
47,Rosaline,4,unknown,0.500000,unknown,0.500000,jacket,0.250000,top,0.250000,...,unknown,0.000000,unknown,0.750000,unknown,0.750000,white,0.250000,unknown,0.000000
48,Shadae,35,top,0.771429,top,0.771429,unknown,0.200000,cardigan,0.028571,...,unknown,0.000000,black,0.200000,black,0.200000,unknown,0.200000,white,0.171429
49,Sophia,59,top,0.745763,top,0.745763,unknown,0.152542,jacket,0.050847,...,short,0.033898,unknown,0.220339,unknown,0.220339,black,0.135593,white,0.135593
50,Sophie,54,top,0.944444,top,0.944444,unknown,0.055556,unknown,0.000000,...,mid,0.018519,unknown,0.351852,unknown,0.351852,white,0.111111,black,0.111111
51,Stacey,56,top,0.517857,top,0.517857,unknown,0.392857,cardigan,0.053571,...,mid,0.017857,unknown,0.321429,unknown,0.321429,navy,0.160714,grey,0.107143
52,Stefania,33,top,0.545455,top,0.545455,unknown,0.363636,kimono,0.060606,...,unknown,0.000000,unknown,0.333333,unknown,0.333333,grey,0.151515,navy,0.151515
53,Summer,95,top,0.821053,top,0.821053,unknown,0.136842,cardigan,0.042105,...,unknown,0.000000,unknown,0.410526,unknown,0.410526,white,0.094737,navy,0.094737
54,Thais,3,top,0.666667,top,0.666667,kimono,0.333333,unknown,0.000000,...,unknown,0.000000,unknown,0.666667,unknown,0.666667,blue,0.333333,unknown,0.000000
55,Tia,71,top,0.971831,top,0.971831,unknown,0.028169,unknown,0.000000,...,unknown,0.000000,unknown,0.380282,unknown,0.380282,white,0.140845,black,0.126761

======================================================================
DETAILED PREFERENCE PROFILES
======================================================================

==================================================
PERSON: Alex
Positive interactions: 37
category       : top (0.92) | kimono (0.08) | unknown (0.00)
style          : elegant (0.41) | casual (0.35) | relaxed (0.11)
pattern        : plain (0.97) | floral (0.03) | unknown (0.00)
material       : unknown (0.89) | jersey (0.11) | unknown (0.00)
silhouette     : unknown (0.89) | relaxed (0.11) | unknown (0.00)
sleeve_type    : unknown (0.73) | short (0.11) | batwing (0.11)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (0.89) | short (0.11) | unknown (0.00)
color          : unknown (0.35) | blue (0.22) | white (0.14)

==================================================
PERSON: Amanda
Positive interactions: 108
category       : top (0.76) | unknown (0.21) | cardigan (0.02)
style          : unknown (0.56) | casual (0.18) | elegant (0.15)
pattern        : plain (0.81) | stripe (0.14) | spot (0.04)
material       : unknown (0.85) | knit (0.10) | jersey (0.03)
silhouette     : unknown (0.86) | relaxed (0.07) | longline (0.04)
sleeve_type    : unknown (0.92) | batwing (0.06) | bell (0.02)
neckline       : unknown (0.94) | v_neck (0.04) | off_shoulder (0.02)
length_style   : unknown (0.94) | long (0.04) | mid (0.02)
color          : unknown (0.23) | blue (0.13) | grey (0.12)

==================================================
PERSON: Anna
Positive interactions: 87
category       : top (0.93) | unknown (0.03) | cardigan (0.03)
style          : casual (0.34) | elegant (0.24) | unknown (0.15)
pattern        : plain (0.97) | stripe (0.02) | spot (0.01)
material       : unknown (0.82) | jersey (0.09) | stretch (0.09)
silhouette     : unknown (0.77) | relaxed (0.10) | fitted (0.09)
sleeve_type    : unknown (0.72) | short (0.14) | long (0.09)
neckline       : unknown (0.95) | v_neck (0.05) | unknown (0.00)
length_style   : unknown (0.85) | long (0.09) | short (0.05)
color          : unknown (0.24) | white (0.20) | black (0.18)

==================================================
PERSON: Anna Maria
Positive interactions: 18
category       : top (0.50) | unknown (0.50) | unknown (0.00)
style          : unknown (0.78) | romantic (0.22) | unknown (0.00)
pattern        : plain (0.72) | stripe (0.22) | spot (0.06)
material       : unknown (0.94) | textured (0.06) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (0.89) | bell (0.11) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : navy (0.28) | grey (0.22) | unknown (0.22)

==================================================
PERSON: Anneliese
Positive interactions: 3
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : unknown (1.00) | unknown (0.00) | unknown (0.00)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : black (0.67) | opal (0.33) | unknown (0.00)

==================================================
PERSON: Bree
Positive interactions: 6
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : romantic (1.00) | unknown (0.00) | unknown (0.00)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : short (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (0.33) | white (0.17) | pink (0.17)

==================================================
PERSON: Charlotte
Positive interactions: 13
category       : top (0.38) | unknown (0.31) | cardigan (0.23)
style          : unknown (0.62) | layering (0.31) | relaxed (0.08)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (0.54) | knit (0.31) | textured (0.08)
silhouette     : unknown (0.85) | cropped (0.08) | relaxed (0.08)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (0.92) | short (0.08) | unknown (0.00)
color          : natural (0.62) | blue (0.15) | red (0.15)

==================================================
PERSON: Chelsea
Positive interactions: 88
category       : top (0.62) | unknown (0.27) | cardigan (0.06)
style          : unknown (0.59) | casual (0.18) | elegant (0.09)
pattern        : plain (0.90) | stripe (0.06) | spot (0.03)
material       : unknown (0.92) | knit (0.07) | jersey (0.01)
silhouette     : unknown (0.94) | oversized (0.03) | relaxed (0.02)
sleeve_type    : unknown (0.98) | short (0.02) | unknown (0.00)
neckline       : unknown (0.91) | v_neck (0.03) | cowl (0.03)
length_style   : unknown (0.98) | short (0.02) | unknown (0.00)
color          : unknown (0.24) | navy (0.20) | black (0.20)

==================================================
PERSON: Chesska
Positive interactions: 11
category       : top (0.64) | unknown (0.36) | unknown (0.00)
style          : romantic (0.36) | unknown (0.27) | elegant (0.27)
pattern        : plain (0.82) | check (0.09) | spot (0.09)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (0.91) | crew (0.09) | unknown (0.00)
length_style   : unknown (0.91) | mid (0.09) | unknown (0.00)
color          : unknown (0.36) | white (0.27) | red (0.09)

==================================================
PERSON: Clementine
Positive interactions: 62
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : elegant (0.34) | casual (0.34) | unknown (0.27)
pattern        : plain (0.87) | stripe (0.08) | spot (0.05)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (0.98) | swing (0.02) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (0.95) | off_shoulder (0.03) | v_neck (0.02)
length_style   : unknown (0.98) | mid (0.02) | unknown (0.00)
color          : unknown (0.42) | blue (0.11) | black (0.08)

==================================================
PERSON: Denniel
Positive interactions: 26
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : elegant (0.54) | casual (0.31) | relaxed (0.15)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (0.85) | jersey (0.15) | unknown (0.00)
silhouette     : unknown (0.85) | relaxed (0.15) | unknown (0.00)
sleeve_type    : unknown (0.69) | short (0.15) | batwing (0.15)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (0.85) | short (0.15) | unknown (0.00)
color          : unknown (0.27) | blue (0.23) | white (0.15)

==================================================
PERSON: Edith
Positive interactions: 3
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : unknown (1.00) | unknown (0.00) | unknown (0.00)
pattern        : plain (0.67) | spot (0.33) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (0.67) | off_shoulder (0.33) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (1.00) | unknown (0.00) | unknown (0.00)

==================================================
PERSON: Emma
Positive interactions: 87
category       : top (0.90) | cardigan (0.05) | unknown (0.03)
style          : unknown (0.29) | casual (0.24) | relaxed (0.22)
pattern        : plain (0.80) | stripe (0.14) | check (0.02)
material       : unknown (0.99) | sequin (0.01) | unknown (0.00)
silhouette     : unknown (0.75) | swing (0.16) | relaxed (0.06)
sleeve_type    : unknown (0.70) | long (0.24) | bell (0.05)
neckline       : unknown (0.89) | v_neck (0.11) | unknown (0.00)
length_style   : unknown (0.74) | long (0.25) | mid (0.01)
color          : unknown (0.38) | stripe (0.10) | navy (0.09)

==================================================
PERSON: Fiona
Positive interactions: 184
category       : top (0.74) | unknown (0.19) | kimono (0.03)
style          : unknown (0.48) | casual (0.18) | romantic (0.12)
pattern        : plain (0.86) | stripe (0.08) | spot (0.04)
material       : unknown (0.91) | knit (0.05) | jersey (0.02)
silhouette     : unknown (0.83) | swing (0.09) | longline (0.05)
sleeve_type    : unknown (0.86) | long (0.12) | bell (0.02)
neckline       : unknown (0.91) | v_neck (0.07) | cowl (0.02)
length_style   : unknown (0.86) | long (0.14) | short (0.01)
color          : unknown (0.29) | white (0.14) | navy (0.12)

==================================================
PERSON: Gemma
Positive interactions: 84
category       : top (0.80) | unknown (0.14) | cardigan (0.05)
style          : unknown (0.48) | casual (0.23) | relaxed (0.15)
pattern        : plain (0.81) | animal (0.07) | floral (0.05)
material       : unknown (0.83) | knit (0.07) | cosy (0.06)
silhouette     : unknown (0.71) | longline (0.13) | relaxed (0.10)
sleeve_type    : unknown (0.94) | long (0.06) | unknown (0.00)
neckline       : unknown (0.98) | v_neck (0.01) | collared (0.01)
length_style   : unknown (0.87) | long (0.13) | unknown (0.00)
color          : unknown (0.35) | black (0.15) | white (0.13)

==================================================
PERSON: Georgia
Positive interactions: 131
category       : top (0.76) | unknown (0.16) | kimono (0.05)
style          : unknown (0.44) | casual (0.23) | relaxed (0.21)
pattern        : plain (0.97) | stripe (0.02) | floral (0.01)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (0.78) | swing (0.21) | longline (0.01)
sleeve_type    : unknown (0.89) | long (0.11) | unknown (0.00)
neckline       : unknown (0.99) | off_shoulder (0.01) | unknown (0.00)
length_style   : unknown (0.89) | long (0.11) | unknown (0.00)
color          : unknown (0.50) | white (0.12) | black (0.08)

==================================================
PERSON: Grazi
Positive interactions: 1
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : elegant (1.00) | unknown (0.00) | unknown (0.00)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (1.00) | unknown (0.00) | unknown (0.00)

==================================================
PERSON: Helen
Positive interactions: 8
category       : top (0.88) | unknown (0.12) | unknown (0.00)
style          : elegant (0.62) | unknown (0.38) | unknown (0.00)
pattern        : plain (0.88) | stripe (0.12) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (0.38) | blue (0.25) | navy (0.25)

==================================================
PERSON: Jess
Positive interactions: 251
category       : top (0.87) | unknown (0.10) | cardigan (0.01)
style          : unknown (0.34) | casual (0.24) | relaxed (0.14)
pattern        : plain (0.89) | stripe (0.06) | spot (0.04)
material       : unknown (0.94) | knit (0.03) | jersey (0.02)
silhouette     : unknown (0.84) | swing (0.12) | relaxed (0.02)
sleeve_type    : unknown (0.86) | long (0.07) | short (0.05)
neckline       : unknown (0.93) | v_neck (0.05) | off_shoulder (0.01)
length_style   : unknown (0.90) | long (0.08) | short (0.02)
color          : unknown (0.32) | black (0.14) | white (0.13)

==================================================
PERSON: Jira
Positive interactions: 1
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : elegant (1.00) | unknown (0.00) | unknown (0.00)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : black (1.00) | unknown (0.00) | unknown (0.00)

==================================================
PERSON: Jude
Positive interactions: 14
category       : unknown (0.64) | top (0.29) | cardigan (0.07)
style          : unknown (0.93) | layering (0.07) | unknown (0.00)
pattern        : plain (0.86) | stripe (0.14) | unknown (0.00)
material       : unknown (0.93) | knit (0.07) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (0.50) | stripe (0.14) | teal (0.07)

==================================================
PERSON: Kate
Positive interactions: 52
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : casual (0.35) | elegant (0.29) | unknown (0.17)
pattern        : plain (0.98) | spot (0.02) | unknown (0.00)
material       : unknown (0.92) | jersey (0.08) | unknown (0.00)
silhouette     : unknown (0.92) | relaxed (0.08) | unknown (0.00)
sleeve_type    : unknown (0.81) | short (0.12) | batwing (0.08)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (0.98) | mid (0.02) | unknown (0.00)
color          : unknown (0.42) | black (0.15) | blue (0.12)

==================================================
PERSON: Katie
Positive interactions: 24
category       : top (0.75) | unknown (0.17) | cardigan (0.08)
style          : unknown (0.46) | casual (0.29) | romantic (0.17)
pattern        : plain (0.75) | spot (0.08) | sequin (0.08)
material       : unknown (0.75) | knit (0.12) | sequin (0.08)
silhouette     : unknown (0.83) | longline (0.17) | unknown (0.00)
sleeve_type    : unknown (0.83) | long (0.12) | bell (0.04)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (0.83) | long (0.17) | unknown (0.00)
color          : unknown (0.29) | navy (0.25) | pink (0.12)

==================================================
PERSON: Lara
Positive interactions: 3
category       : top (0.67) | cardigan (0.33) | unknown (0.00)
style          : unknown (0.67) | layering (0.33) | unknown (0.00)
pattern        : plain (0.67) | stripe (0.33) | unknown (0.00)
material       : unknown (0.67) | knit (0.33) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (0.67) | stripe (0.33) | unknown (0.00)

==================================================
PERSON: Laura
Positive interactions: 244
category       : top (0.90) | unknown (0.07) | kimono (0.01)
style          : casual (0.31) | unknown (0.29) | elegant (0.14)
pattern        : plain (0.93) | stripe (0.04) | spot (0.02)
material       : unknown (0.89) | stretch (0.07) | jersey (0.04)
silhouette     : unknown (0.78) | fitted (0.07) | swing (0.06)
sleeve_type    : unknown (0.86) | long (0.06) | short (0.05)
neckline       : unknown (0.90) | v_neck (0.06) | scoop (0.02)
length_style   : unknown (0.91) | long (0.07) | short (0.02)
color          : unknown (0.34) | black (0.16) | white (0.15)

==================================================
PERSON: Lauren
Positive interactions: 30
category       : top (0.50) | unknown (0.20) | jacket (0.13)
style          : unknown (0.47) | casual (0.27) | romantic (0.10)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (0.77) | knit (0.13) | cosy (0.07)
silhouette     : unknown (0.93) | relaxed (0.07) | unknown (0.00)
sleeve_type    : unknown (0.93) | short (0.07) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (0.23) | black (0.23) | white (0.13)

==================================================
PERSON: Lisa
Positive interactions: 8
category       : top (0.50) | unknown (0.38) | cardigan (0.12)
style          : unknown (0.88) | layering (0.12) | unknown (0.00)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (0.62) | knit (0.38) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : unknown (0.38) | black (0.25) | navy (0.12)

==================================================
PERSON: Ljubenka
Positive interactions: 109
category       : top (0.89) | unknown (0.09) | kimono (0.01)
style          : casual (0.33) | unknown (0.21) | romantic (0.16)
pattern        : plain (0.96) | stripe (0.03) | spot (0.01)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (0.86) | swing (0.13) | longline (0.01)
sleeve_type    : unknown (0.91) | short (0.07) | flute (0.01)
neckline       : unknown (0.91) | v_neck (0.09) | unknown (0.00)
length_style   : unknown (0.98) | mid (0.01) | long (0.01)
color          : unknown (0.38) | black (0.14) | white (0.14)

==================================================
PERSON: Louise
Positive interactions: 5
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : unknown (0.60) | casual (0.40) | unknown (0.00)
pattern        : plain (0.80) | spot (0.20) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : unknown (1.00) | unknown (0.00) | unknown (0.00)
sleeve_type    : unknown (1.00) | unknown (0.00) | unknown (0.00)
neckline       : unknown (1.00) | unknown (0.00) | unknown (0.00)
length_style   : unknown (1.00) | unknown (0.00) | unknown (0.00)
color          : black (0.40) | unknown (0.20) | navy (0.20)

==================================================
PERSON: Lucy
Positive interactions: 4
category       : top (1.00) | unknown (0.00) | unknown (0.00)
style          : relaxed (1.00) | unknown (0.00) | unknown (0.00)
pattern        : plain (1.00) | unknown (0.00) | unknown (0.00)
material       : unknown (1.00) | unknown (0.00) | unknown (0.00)
silhouette     : relaxed (1.00) | unknown (0.00) | unknown (0.00)

,person_id,category_entropy,style_entropy,pattern_entropy,material_entropy,silhouette_entropy,sleeve_type_entropy,neckline_entropy,length_style_entropy,color_entropy
0,Alex,0.405977,1.926644,0.179256,0.494183,0.494183,1.253184,-0.000000,0.494183,2.730660
1,Amanda,0.945988,1.757019,0.874949,0.782884,0.809130,0.515850,0.360560,0.360560,3.250642
2,Anna,0.431017,2.355700,0.248062,0.872460,1.112918,1.252275,0.269055,0.793523,2.958444
3,Anna Maria,1.000000,0.764205,1.052941,0.309543,-0.000000,0.503258,-0.000000,-0.000000,2.636056
4,Anneliese,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.918296
5,Bree,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,2.251629
6,Charlotte,1.826245,1.238901,-0.000000,1.573402,0.773228,-0.000000,-0.000000,0.391244,1.546594
7,Chelsea,1.418255,1.776769,0.614395,0.447640,0.369850,0.156491,0.604159,0.156491,3.033131
8,Chesska,0.945660,1.867634,0.865857,-0.000000,-0.000000,-0.000000,0.439497,0.439497,2.299896
9,Clementine,-0.000000,1.825741,0.677931,-0.000000,0.119116,-0.000000,0.323939,0.119116,2.892308
10,Denniel,-0.000000,1.419556,-0.000000,0.619382,0.619382,1.198184,-0.000000,0.619382,2.655776
11,Edith,-0.000000,-0.000000,0.918296,-0.000000,-0.000000,-0.000000,0.918296,-0.000000,-0.000000
12,Emma,0.638159,2.290545,0.970882,0.090544,1.142697,1.132442,0.514646,0.901478,3.032556
13,Fiona,1.155711,2.122981,0.844476,0.615313,0.917042,0.660550,0.517125,0.620878,3.253374
14,Gemma,0.946514,2.026686,1.113064,0.905126,1.339137,0.325552,0.186136,0.560044,2.892596
15,Georgia,1.102973,2.010989,0.221836,-0.000000,0.810573,0.490403,0.064661,0.513353,2.715612
16,Grazi,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
17,Helen,0.543564,0.954434,0.543564,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,1.905639
18,Jess,0.663179,2.316844,0.672221,0.432485,0.848068,0.832342,0.452755,0.562457,3.201641
19,Jira,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
20,Jude,1.198117,0.371232,0.591673,0.371232,-0.000000,-0.000000,-0.000000,-0.000000,2.260820
21,Kate,-0.000000,2.129265,0.137099,0.391244,0.391244,0.892995,-0.000000,0.137099,2.563381
22,Katie,1.040852,1.763911,1.207519,1.176065,0.650022,0.785235,-0.000000,0.650022,2.723669
23,Lara,0.918296,0.918296,0.918296,0.918296,-0.000000,-0.000000,-0.000000,-0.000000,0.918296
24,Laura,0.605955,2.407527,0.411770,0.611092,1.242707,0.796414,0.614109,0.521528,2.921831
25,Lauren,1.944623,1.946466,-0.000000,1.105493,0.353359,0.353359,-0.000000,-0.000000,2.879799
26,Lisa,1.405639,0.543564,-0.000000,0.954434,-0.000000,-0.000000,-0.000000,-0.000000,2.155639
27,Ljubenka,0.590103,2.348882,0.256710,-0.000000,0.626585,0.526842,0.442262,0.150414,2.876137
28,Louise,-0.000000,0.970951,0.721928,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,1.921928
29,Lucy,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,2.000000
30,Maddy,0.100001,1.945321,0.336760,0.579157,0.981816,1.300820,0.627266,1.099662,2.930390
31,Madeline,1.057120,2.064028,-0.000000,1.131576,0.534488,0.179256,-0.000000,0.357429,2.705529
32,Mae-Lee,0.338824,2.230870,0.342299,0.201595,1.246526,1.124744,0.748175,0.819915,3.039933
33,Mandy,1.392147,0.986427,0.503258,0.503258,0.503258,-0.000000,-0.000000,0.503258,1.657743
34,Marnee,1.021859,2.028810,0.255510,-0.000000,0.986696,0.570327,-0.000000,0.648307,2.889343
35,Mercy,0.658351,1.643156,-0.000000,0.249882,0.413817,-0.000000,1.308502,0.249882,2.379308
36,Miranda,0.605291,1.566744,0.455021,0.605291,0.228538,0.380947,0.380947,0.228538,1.894697
37,Monique,0.216397,1.611103,0.643794,-0.000000,-0.000000,-0.000000,0.690695,-0.000000,2.589345
38,Nadine,1.369532,1.348395,0.436825,0.748635,0.526617,0.684533,0.689825,0.684533,2.845848
39,Natalia,1.480139,2.043767,0.556663,1.055629,0.495969,0.912025,-0.000000,0.151097,2.880345
40,Natalie,-0.000000,1.820287,0.139233,0.396628,0.712232,0.712232,0.322757,0.460257,2.687543
41,Nathalie,-0.000000,0.863121,0.371232,0.863121,-0.000000,-0.000000,-0.000000,0.371232,1.921185
42,Nikki,0.503258,0.991076,1.351644,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,2.281036
43,Olivia,-0.000000,1.720066,-0.000000,-0.000000,0.258019,-0.000000,-0.000000,-0.000000,2.138318
44,Palatina,1.072986,1.659093,0.286839,0.474133,0.286839,-0.000000,0.429325,-0.000000,2.571179
45,Perrie,0.357429,2.202470,0.876076,0.668913,0.668913,1.253184,-0.000000,0.668913,3.328810
46,Riina,1.202662,1.741425,0.778910,0.803915,0.860392,0.625505,0.318215,0.563695,3.387987
47,Rosaline,1.500000,0.811278,-0.000000,0.811278,-0.000000,-0.000000,-0.000000,-0.000000,0.811278
48,Shadae,0.899756,1.264763,0.932670,0.960948,0.422001,0.422001,0.187176,0.422001,2.934633
49,Sophia,1.213165,1.578396,0.412649,0.479865,0.682584,0.500968,0.123950,0.682584,3.274505
50,Sophie,0.309543,1.906802,0.511910,0.133040,1.321194,1.749021,-0.000000,1.057029,3.033601
51,Stacey,1.419072,1.608885,1.134201,1.017802,0.520773,0.520773,0.257999,0.429181,3.144895
52,Stefania,1.405661,1.737819,0.522978,0.613619,0.745518,0.928604,-0.000000,0.613619,2.861730
53,Summer,0.818623,1.798266,0.882660,0.379524,0.852530,0.568025,0.432012,0.629249,3.026537
54,Thais,0.918296,1.584963,0.918296,-0.000000,0.918296,-0.000000,0.918296,-0.000000,0.918296
55,Tia,0.185125,2.268425,0.705118,-0.000000,0.655444,0.106792,0.106792,0.185125,2.842682

======================================================================
PREFERENCE PROFILES SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_person_preference_profiles.csv

======================================================================
ZYRA V2 STEP 9 COMPLETE
======================================================================

In [87]:
# ============================================================
# ZYRA V2 — STEP 10
# PERSONALIZED PREFERENCE + PHYSICAL BASELINE
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

SEMANTIC_PATH = (
    BASE /
    "data/v2/v2_garment_semantic_features.csv"
)

PROFILE_PATH = (
    BASE /
    "data/v2/v2_person_preference_profiles.csv"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_hybrid_ranker.pt"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_personalized_baseline_results.csv"
)

# ============================================================
# LOAD
# ============================================================

candidates = pd.read_csv(
    CANDIDATE_PATH
)

semantic = pd.read_csv(
    SEMANTIC_PATH
)

profiles = pd.read_csv(
    PROFILE_PATH
)

print("=" * 70)
print("ZYRA V2 — STEP 10 PERSONALIZED BASELINE")
print("=" * 70)

print(
    "Candidate rows:",
    len(candidates)
)

print(
    "Garments:",
    semantic["product_id"].nunique()
)

print(
    "Profiles:",
    profiles["person_id"].nunique()
)

# ============================================================
# TEST PEOPLE
# ============================================================

# Load the exact held-out people used by V2.
# This prevents accidentally evaluating on training people.

import torch

checkpoint = torch.load(
    MODEL_PATH,
    map_location="cpu",
    weights_only=False,
)

TEST_PEOPLE = set(
    checkpoint[
        "test_people"
    ]
)

print(
    "\nTest people:",
    sorted(TEST_PEOPLE)
)

# ============================================================
# MERGE SEMANTICS
# ============================================================

semantic_columns = [
    "product_id",
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]

semantic_subset = semantic[
    [
        c
        for c in semantic_columns
        if c in semantic.columns
    ]
].copy()

df = candidates.merge(
    semantic_subset,
    on="product_id",
    how="left",
    validate="many_to_one",
)

# ============================================================
# NORMALIZE
# ============================================================

PROFILE_COLUMNS = [
    "category",
    "style",
    "pattern",
    "material",
    "silhouette",
    "sleeve_type",
    "neckline",
    "length_style",
    "color",
]

for col in PROFILE_COLUMNS:

    df[col] = (
        df[col]
        .fillna("unknown")
        .astype(str)
        .str.lower()
        .str.strip()
    )

# ============================================================
# PERSON PROFILE LOOKUP
# ============================================================

profile_lookup = (
    profiles
    .set_index(
        "person_id"
    )
)

# ============================================================
# PREFERENCE SIMILARITY
# ============================================================
#
# For each person × garment:
#
# score = average agreement with that person's
# top preferences.
#
# We deliberately use TOP-3 preference distributions,
# not only the single most common value.
#
# ============================================================

def preference_score(
    person_id,
    garment,
):

    if person_id not in profile_lookup.index:

        return 0.0

    profile = profile_lookup.loc[
        person_id
    ]

    scores = []

    for column in PROFILE_COLUMNS:

        value = garment[column]

        if value == "unknown":

            continue

        # ----------------------------------------------------
        # TOP 1
        # ----------------------------------------------------

        top1 = str(
            profile.get(
                f"{column}_1",
                "unknown",
            )
        )

        share1 = float(
            profile.get(
                f"{column}_1_share",
                0.0,
            )
        )

        if value == top1:

            scores.append(
                share1
            )

            continue

        # ----------------------------------------------------
        # TOP 2
        # ----------------------------------------------------

        top2 = str(
            profile.get(
                f"{column}_2",
                "unknown",
            )
        )

        share2 = float(
            profile.get(
                f"{column}_2_share",
                0.0,
            )
        )

        if value == top2:

            scores.append(
                share2
            )

            continue

        # ----------------------------------------------------
        # TOP 3
        # ----------------------------------------------------

        top3 = str(
            profile.get(
                f"{column}_3",
                "unknown",
            )
        )

        share3 = float(
            profile.get(
                f"{column}_3_share",
                0.0,
            )
        )

        if value == top3:

            scores.append(
                share3
            )

        else:

            scores.append(
                0.0
            )

    if len(scores) == 0:

        return 0.0

    return float(
        np.mean(
            scores
        )
    )

# ============================================================
# CALCULATE PREFERENCE SCORES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING PERSONALIZED PREFERENCE SCORES")
print("=" * 70)

preference_scores = []

for row in df.itertuples(
    index=False
):

    garment = {
        column:
            getattr(
                row,
                column,
            )
        for column in PROFILE_COLUMNS
    }

    score = preference_score(
        row.person_id,
        garment,
    )

    preference_scores.append(
        score
    )

df["preference_score"] = (
    preference_scores
)

# ============================================================
# PHYSICAL COMPATIBILITY
# ============================================================
#
# We use the existing physical compatibility features.
#
# Rather than relying on one arbitrary raw column, create
# a normalized physical compatibility score.
#
# Lower mismatch/ease violations = better.
#
# ============================================================

physical_score_columns = [
    "bust_mismatch",
    "waist_mismatch",
    "hip_mismatch",
    "bust_relative_mismatch",
    "waist_relative_mismatch",
    "hip_relative_mismatch",
]

available_physical = [
    c
    for c in physical_score_columns
    if c in df.columns
]

print(
    "\nPhysical features:",
    available_physical
)

physical_matrix = (
    df[
        available_physical
    ]
    .apply(
        pd.to_numeric,
        errors="coerce",
    )
    .to_numpy(
        dtype=np.float64
    )
)

# ------------------------------------------------------------
# Robust normalization
# ------------------------------------------------------------

physical_components = []

for i in range(
    physical_matrix.shape[1]
):

    values = physical_matrix[
        :,
        i
    ]

    median = np.nanmedian(
        values
    )

    q25 = np.nanpercentile(
        values,
        25
    )

    q75 = np.nanpercentile(
        values,
        75
    )

    iqr = q75 - q25

    if (
        not np.isfinite(iqr)
        or
        iqr < 1e-8
    ):

        iqr = 1.0

    z = (
        values
        -
        median
    ) / iqr

    z = np.nan_to_num(
        z,
        nan=0.0,
        posinf=5.0,
        neginf=-5.0,
    )

    # Smaller mismatch = better.
    compatibility = np.exp(
        -np.abs(z)
    )

    physical_components.append(
        compatibility
    )

physical_components = np.column_stack(
    physical_components
)

df[
    "physical_score"
] = np.mean(
    physical_components,
    axis=1,
)

# ============================================================
# SCORE WEIGHTS
# ============================================================
#
# Start with equal contribution.
#
# This is a BASELINE, not the final model.
# ============================================================

PHYSICAL_WEIGHT = 0.50
PREFERENCE_WEIGHT = 0.50

df[
    "personalized_score"
] = (
    PHYSICAL_WEIGHT
    *
    df[
        "physical_score"
    ]
    +
    PREFERENCE_WEIGHT
    *
    df[
        "preference_score"
    ]
)

# ============================================================
# TEST PEOPLE
# ============================================================

test_df = df[
    df[
        "person_id"
    ].isin(
        TEST_PEOPLE
    )
].copy()

# ============================================================
# FULL CATALOG VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("CATALOG VALIDATION")
print("=" * 70)

catalog_counts = (
    test_df
    .groupby(
        "person_id"
    )[
        "product_id"
    ]
    .nunique()
)

print(
    catalog_counts
)

assert (
    catalog_counts == 897
).all()

# ============================================================
# POSITIVE FLAG
# ============================================================

test_df[
    "is_positive"
] = (
    test_df[
        "label_status"
    ]
    ==
    "positive"
)

# ============================================================
# RANK
# ============================================================

test_df[
    "rank"
] = (
    test_df
    .groupby(
        "person_id"
    )[
        "personalized_score"
    ]
    .rank(
        method="first",
        ascending=False,
    )
)

# ============================================================
# METRICS
# ============================================================

def recall_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:

        return 0.0

    return float(
        np.mean(
            ranks <= k
        )
    )


def ndcg_at_k(
    ranks,
    k,
):

    if len(ranks) == 0:

        return 0.0

    dcg = sum(

        1.0
        /
        np.log2(
            rank + 1
        )

        for rank in ranks

        if rank <= k
    )

    ideal_count = min(
        len(ranks),
        k,
    )

    if ideal_count == 0:

        return 0.0

    idcg = sum(

        1.0
        /
        np.log2(
            i + 2
        )

        for i in range(
            ideal_count
        )
    )

    return float(
        dcg / idcg
    )


def mrr(
    ranks
):

    if len(ranks) == 0:

        return 0.0

    return float(
        1.0
        /
        np.min(ranks)
    )

# ============================================================
# PER PERSON
# ============================================================

results = []

for person_id, group in (
    test_df
    .groupby(
        "person_id"
    )
):

    ranks = (
        group[
            group[
                "is_positive"
            ]
        ][
            "rank"
        ]
        .to_numpy()
    )

    results.append(
        {
            "person_id":
                person_id,

            "positive_count":
                len(ranks),

            "recall@5":
                recall_at_k(
                    ranks,
                    5,
                ),

            "recall@10":
                recall_at_k(
                    ranks,
                    10,
                ),

            "recall@20":
                recall_at_k(
                    ranks,
                    20,
                ),

            "recall@50":
                recall_at_k(
                    ranks,
                    50,
                ),

            "recall@100":
                recall_at_k(
                    ranks,
                    100,
                ),

            "ndcg@10":
                ndcg_at_k(
                    ranks,
                    10,
                ),

            "ndcg@20":
                ndcg_at_k(
                    ranks,
                    20,
                ),

            "mrr":
                mrr(
                    ranks
                ),

            "best_rank":
                np.min(ranks),

            "median_rank":
                np.median(ranks),
        }
    )

results_df = pd.DataFrame(
    results
)

# ============================================================
# GLOBAL RESULTS
# ============================================================

print("\n" + "=" * 70)
print("PERSONALIZED BASELINE RESULTS")
print("=" * 70)

for metric in [
    "recall@5",
    "recall@10",
    "recall@20",
    "recall@50",
    "recall@100",
    "ndcg@10",
    "ndcg@20",
    "mrr",
]:

    print(
        f"{metric:15s}: "
        f"{results_df[metric].mean():.4f}"
    )

# ============================================================
# POSITIVE RANKS
# ============================================================

positive_ranks = (
    test_df[
        test_df[
            "is_positive"
        ]
    ][
        "rank"
    ]
    .to_numpy()
)

print("\n" + "=" * 70)
print("POSITIVE RANK DISTRIBUTION")
print("=" * 70)

print(
    pd.Series(
        positive_ranks
    ).describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
        ]
    )
)

# ============================================================
# TOP-K
# ============================================================

print("\n" + "=" * 70)
print("KNOWN POSITIVES IN TOP-K")
print("=" * 70)

for k in [
    1,
    5,
    10,
    20,
    50,
    100,
]:

    hits = np.sum(
        positive_ranks <= k
    )

    total = len(
        positive_ranks
    )

    pct = (
        hits
        /
        total
        *
        100
    )

    print(
        f"Top-{k:3d}: "
        f"{hits:4d} / "
        f"{total:4d} "
        f"({pct:6.2f}%)"
    )

# ============================================================
# PER-PERSON
# ============================================================

print("\n" + "=" * 70)
print("PER-PERSON RESULTS")
print("=" * 70)

print(
    results_df[
        [
            "person_id",
            "positive_count",
            "recall@10",
            "recall@20",
            "recall@100",
            "ndcg@10",
            "mrr",
            "best_rank",
            "median_rank",
        ]
    ]
    .sort_values(
        "person_id"
    )
    .to_string(
        index=False
    )
)

# ============================================================
# TOP 10
# ============================================================

print("\n" + "=" * 70)
print("TOP 10 PERSONALIZED RECOMMENDATIONS")
print("=" * 70)

for person_id, group in (
    test_df
    .groupby(
        "person_id"
    )
):

    top10 = (
        group
        .sort_values(
            "rank"
        )
        .head(10)
    )

    print(
        f"\nPerson: {person_id}"
    )

    display(
        top10[
            [
                "rank",
                "product_id",
                "personalized_score",
                "physical_score",
                "preference_score",
                "is_positive",
            ]
        ]
    )

# ============================================================
# SAVE
# ============================================================

test_df.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("PERSONALIZED BASELINE SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print("\n" + "=" * 70)
print("ZYRA V2 STEP 10 COMPLETE")
print("=" * 70)

======================================================================
ZYRA V2 — STEP 10 PERSONALIZED BASELINE
======================================================================
Candidate rows: 50232
Garments: 897
Profiles: 56

Test people: ['Alex', 'Anna Maria', 'Bree', 'Chesska', 'Emma', 'Maddy', 'Palatina', 'Sophie']

======================================================================
CALCULATING PERSONALIZED PREFERENCE SCORES
======================================================================

Physical features: ['bust_mismatch', 'waist_mismatch', 'hip_mismatch', 'bust_relative_mismatch', 'waist_relative_mismatch', 'hip_relative_mismatch']

======================================================================
CATALOG VALIDATION
======================================================================
person_id
Alex          897
Anna Maria    897
Bree          897
Chesska       897
Emma          897
Maddy         897
Palatina      897
Sophie        897
Name: product_id, dtype: int64

======================================================================
PERSONALIZED BASELINE RESULTS
======================================================================
recall@5       : 0.0380
recall@10      : 0.0394
recall@20      : 0.0973
recall@50      : 0.1887
recall@100     : 0.3041
ndcg@10        : 0.1501
ndcg@20        : 0.1334
mrr            : 0.2909

======================================================================
POSITIVE RANK DISTRIBUTION
======================================================================
count    339.000000
mean     397.699115
std      236.737748
min        1.000000
25%      211.000000
50%      425.000000
75%      585.500000
90%      694.200000
95%      769.600000
max      882.000000
dtype: float64

======================================================================
KNOWN POSITIVES IN TOP-K
======================================================================
Top-  1:    2 /  339 (  0.59%)
Top-  5:    8 /  339 (  2.36%)
Top- 10:    9 /  339 (  2.65%)
Top- 20:   14 /  339 (  4.13%)
Top- 50:   29 /  339 (  8.55%)
Top-100:   55 /  339 ( 16.22%)

======================================================================
PER-PERSON RESULTS
======================================================================
 person_id  positive_count  recall@10  recall@20  recall@100  ndcg@10      mrr  best_rank  median_rank
      Alex              37   0.000000   0.000000    0.027027 0.000000 0.010870       92.0        429.0
Anna Maria              18   0.222222   0.333333    0.500000 0.563788 1.000000        1.0        189.0
      Bree               6   0.000000   0.333333    1.000000 0.000000 0.076923       13.0         46.5
   Chesska              11   0.000000   0.000000    0.272727 0.000000 0.028571       35.0        415.0
      Emma              87   0.011494   0.011494    0.091954 0.073364 0.142857        7.0        581.0
     Maddy              77   0.000000   0.000000    0.025974 0.000000 0.012346       81.0        393.0
  Palatina              49   0.081633   0.081633    0.367347 0.563788 1.000000        1.0        190.0
    Sophie              54   0.000000   0.018519    0.148148 0.000000 0.055556       18.0        378.5

======================================================================
TOP 10 PERSONALIZED RECOMMENDATIONS
======================================================================

Person: Alex

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
36860,1.0,falling-for-you-cardi#Mustard,0.986486,1.000000,0.972973,False
36969,2.0,falling-for-you-cardi#Rust,0.986486,1.000000,0.972973,False
37011,3.0,falling-for-you-cardi#Port,0.986486,1.000000,0.972973,False
37239,4.0,falling-for-you-cardi#Dusty,0.986486,1.000000,0.972973,False
37554,5.0,falling-for-you-cardi-2#WinterRose,0.986486,1.000000,0.972973,False
37640,6.0,rising-mist-jumper#Nickel,0.986486,1.000000,0.972973,False
37113,7.0,side-buttoned-sweater#Buttoned,0.941541,0.937136,0.945946,False
37431,8.0,starry-night-cardi#Chalk,0.940296,0.907618,0.972973,False
37581,9.0,robyn-top-1#Roanne,0.938259,0.930572,0.945946,False
37292,10.0,frill-sleeve-top-1#LeafPrint,0.936410,0.926874,0.945946,False

Person: Anna Maria

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
34169,1.0,falling-for-you-cardi#Mustard,0.861111,1.000000,0.722222,True
34278,2.0,falling-for-you-cardi#Rust,0.861111,1.000000,0.722222,True
34320,3.0,falling-for-you-cardi#Port,0.861111,1.000000,0.722222,True
34548,4.0,falling-for-you-cardi#Dusty,0.861111,1.000000,0.722222,True
34863,5.0,falling-for-you-cardi-2#WinterRose,0.861111,1.000000,0.722222,False
34949,6.0,rising-mist-jumper#Nickel,0.861111,1.000000,0.722222,False
34740,7.0,starry-night-cardi#Chalk,0.832555,0.942887,0.722222,False
34616,8.0,cool-breeze-jumper#Dust,0.796469,0.870716,0.722222,False
34422,9.0,side-buttoned-sweater#Buttoned,0.793610,0.976108,0.611111,False
34526,10.0,mixed-messages-jumper#MixedStrip,0.790603,0.858983,0.722222,False

Person: Bree

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
41345,1.0,falling-for-you-cardi#Mustard,1.000000,1.000000,1.0,False
41454,2.0,falling-for-you-cardi#Rust,1.000000,1.000000,1.0,False
41496,3.0,falling-for-you-cardi#Port,1.000000,1.000000,1.0,False
41724,4.0,falling-for-you-cardi#Dusty,1.000000,1.000000,1.0,False
42039,5.0,falling-for-you-cardi-2#WinterRose,1.000000,1.000000,1.0,False
42125,6.0,rising-mist-jumper#Nickel,1.000000,1.000000,1.0,False
41773,7.0,the-contrast-detail-top#Ivory,0.989984,0.979969,1.0,False
41792,8.0,cool-breeze-jumper#Dust,0.977320,0.954641,1.0,False
41963,9.0,the-pleated-sleeve-top#Sage,0.964962,0.929924,1.0,False
41487,10.0,crossing-the-plains-sweater-1#Indigo,0.964735,0.929470,1.0,False

Person: Chesska

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
13538,1.0,falling-for-you-cardi#Mustard,0.909091,1.000000,0.818182,False
13647,2.0,falling-for-you-cardi#Rust,0.909091,1.000000,0.818182,False
13689,3.0,falling-for-you-cardi#Port,0.909091,1.000000,0.818182,False
13917,4.0,falling-for-you-cardi#Dusty,0.909091,1.000000,0.818182,False
14232,5.0,falling-for-you-cardi-2#WinterRose,0.909091,1.000000,0.818182,False
14318,6.0,rising-mist-jumper#Nickel,0.909091,1.000000,0.818182,False
14109,7.0,starry-night-cardi#Chalk,0.904359,0.990537,0.818182,False
13985,8.0,cool-breeze-jumper#Dust,0.870233,0.922284,0.818182,False
13497,9.0,walk-in-the-park-cardi#Sand,0.850722,0.883262,0.818182,False
13922,10.0,heartmade-cardi#DustyRose,0.849915,0.881647,0.818182,False

Person: Emma

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
8156,1.0,falling-for-you-cardi#Mustard,0.902299,1.000000,0.804598,False
8265,2.0,falling-for-you-cardi#Rust,0.902299,1.000000,0.804598,False
8307,3.0,falling-for-you-cardi#Port,0.902299,1.000000,0.804598,False
8535,4.0,falling-for-you-cardi#Dusty,0.902299,1.000000,0.804598,False
8850,5.0,falling-for-you-cardi-2#WinterRose,0.902299,1.000000,0.804598,False
8936,6.0,rising-mist-jumper#Nickel,0.902299,1.000000,0.804598,False
8409,7.0,side-buttoned-sweater#Buttoned,0.893855,0.937136,0.850575,True
8877,8.0,robyn-top-1#Roanne,0.890574,0.930572,0.850575,False
8588,9.0,frill-sleeve-top-1#LeafPrint,0.888725,0.926874,0.850575,False
8727,10.0,starry-night-cardi#Chalk,0.856108,0.907618,0.804598,False

Person: Maddy

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
12894,1.0,side-buttoned-sweater#Buttoned,0.979476,0.991420,0.967532,False
12641,2.0,falling-for-you-cardi#Mustard,0.974026,1.000000,0.948052,False
12750,3.0,falling-for-you-cardi#Rust,0.974026,1.000000,0.948052,False
12792,4.0,falling-for-you-cardi#Port,0.974026,1.000000,0.948052,False
13020,5.0,falling-for-you-cardi#Dusty,0.974026,1.000000,0.948052,False
13335,6.0,falling-for-you-cardi-2#WinterRose,0.974026,1.000000,0.948052,False
13421,7.0,rising-mist-jumper#Nickel,0.974026,1.000000,0.948052,False
13212,8.0,starry-night-cardi#Chalk,0.958221,0.968390,0.948052,False
13247,9.0,cross-my-heart-sweater#Regal,0.919223,0.870913,0.967532,False
13088,10.0,cool-breeze-jumper#Dust,0.919190,0.890328,0.948052,False

Person: Palatina

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
17126,1.0,falling-for-you-cardi#Mustard,0.979592,1.000000,0.959184,True
17235,2.0,falling-for-you-cardi#Rust,0.979592,1.000000,0.959184,True
17277,3.0,falling-for-you-cardi#Port,0.979592,1.000000,0.959184,True
17505,4.0,falling-for-you-cardi#Dusty,0.979592,1.000000,0.959184,True
17820,5.0,falling-for-you-cardi-2#WinterRose,0.979592,1.000000,0.959184,False
17906,6.0,rising-mist-jumper#Nickel,0.979592,1.000000,0.959184,False
17573,7.0,cool-breeze-jumper#Dust,0.968711,0.978239,0.959184,False
17323,8.0,snug-as-a-bug-jumper#Smoke,0.946867,0.934550,0.959184,False
17697,9.0,starry-night-cardi#Chalk,0.930295,0.901406,0.959184,False
17619,10.0,the-twist-hem-jumper#DenimMarle,0.913104,0.867025,0.959184,False

Person: Sophie

,rank,product_id,personalized_score,physical_score,preference_score,is_positive
16229,1.0,falling-for-you-cardi#Mustard,0.953704,1.000000,0.907407,False
16338,2.0,falling-for-you-cardi#Rust,0.953704,1.000000,0.907407,False
16380,3.0,falling-for-you-cardi#Port,0.953704,1.000000,0.907407,False
16608,4.0,falling-for-you-cardi#Dusty,0.953704,1.000000,0.907407,False
16923,5.0,falling-for-you-cardi-2#WinterRose,0.953704,1.000000,0.907407,False
17009,6.0,rising-mist-jumper#Nickel,0.953704,1.000000,0.907407,False
16847,7.0,the-pleated-sleeve-top#Sage,0.920660,0.915394,0.925926,False
16596,8.0,heartmade-sweater#Rust,0.907634,0.889342,0.925926,False
16657,9.0,the-contrast-detail-top#Ivory,0.901568,0.877210,0.925926,False
16637,10.0,the-flutter-sleeve-top#Denim,0.892797,0.859668,0.925926,False

======================================================================
PERSONALIZED BASELINE SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_personalized_baseline_results.csv

======================================================================
ZYRA V2 STEP 10 COMPLETE
======================================================================

In [88]:
# ============================================================
# ZYRA V2 — STEP 11
# ACTUAL RECOMMENDATION INFERENCE TEST
# ============================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from pathlib import Path

# ============================================================
# PATHS
# ============================================================

BASE = Path(
    "/Users/saketh/Desktop/Projects/weavly/core-model"
)

MODEL_PATH = (
    BASE /
    "data/v2/v2_hybrid_ranker.pt"
)

CANDIDATE_PATH = (
    BASE /
    "data/v2/v2_hybrid_candidates.csv"
)

ORIGINAL_PATH = (
    BASE /
    "data/v2/v2_person_garment_candidates.csv"
)

OUTPUT_PATH = (
    BASE /
    "data/v2/v2_actual_inference_results.csv"
)

# ============================================================
# LOAD MODEL
# ============================================================

print("=" * 70)
print("ZYRA V2 — ACTUAL RECOMMENDATION INFERENCE")
print("=" * 70)

checkpoint = torch.load(
    MODEL_PATH,
    map_location="cpu",
    weights_only=False,
)

FEATURES = checkpoint[
    "feature_names"
]

TEST_PEOPLE = checkpoint[
    "test_people"
]

print(
    "Model features:",
    len(FEATURES)
)

print(
    "Test people:",
    TEST_PEOPLE
)

# ============================================================
# MODEL
# ============================================================

class HybridRanker(nn.Module):

    def __init__(
        self,
        input_dim,
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                128,
            ),

            nn.ReLU(),

            nn.BatchNorm1d(
                128,
            ),

            nn.Dropout(
                0.15,
            ),

            nn.Linear(
                128,
                64,
            ),

            nn.ReLU(),

            nn.Dropout(
                0.10,
            ),

            nn.Linear(
                64,
                32,
            ),

            nn.ReLU(),

            nn.Linear(
                32,
                1,
            ),
        )

    def forward(
        self,
        x,
    ):

        return self.network(
            x
        ).squeeze(-1)


model = HybridRanker(
    len(FEATURES)
)

model.load_state_dict(
    checkpoint[
        "model_state_dict"
    ]
)

model.eval()

print(
    "\nModel loaded successfully."
)

# ============================================================
# LOAD CANDIDATES
# ============================================================

candidates = pd.read_csv(
    CANDIDATE_PATH
)

original = pd.read_csv(
    ORIGINAL_PATH
)

print(
    "\nCandidate rows:",
    len(candidates)
)

print(
    "Original rows:",
    len(original)
)

# ============================================================
# GROUND TRUTH
# ============================================================

ground_truth = original[
    [
        "person_id",
        "product_id",
        "label_status",
    ]
].copy()

# ============================================================
# MERGE LABELS
# ============================================================

df = candidates.merge(
    ground_truth,
    on=[
        "person_id",
        "product_id",
    ],
    how="left",
    validate="one_to_one",
)

assert (
    df[
        "label_status"
    ]
    .notna()
    .all()
)

# ============================================================
# FEATURE MATRIX
# ============================================================

X = (
    df[
        FEATURES
    ]
    .to_numpy(
        dtype=np.float32
    )
)

# ============================================================
# IMPUTATION
# ============================================================

imputer_values = np.asarray(
    checkpoint[
        "imputer_statistics"
    ],
    dtype=np.float32,
)

for i in range(
    X.shape[1]
):

    missing = np.isnan(
        X[:, i]
    )

    if missing.any():

        X[
            missing,
            i
        ] = imputer_values[i]

# ============================================================
# SCALING
# ============================================================

scaler_mean = np.asarray(
    checkpoint[
        "scaler_mean"
    ],
    dtype=np.float32,
)

scaler_scale = np.asarray(
    checkpoint[
        "scaler_scale"
    ],
    dtype=np.float32,
)

scaler_scale = np.where(
    scaler_scale == 0,
    1.0,
    scaler_scale,
)

X = (
    X
    -
    scaler_mean
)

X = (
    X
    /
    scaler_scale
)

# ============================================================
# VALIDATE
# ============================================================

assert (
    np.isnan(X).sum()
    == 0
)

assert (
    np.isinf(X).sum()
    == 0
)

# ============================================================
# MODEL INFERENCE
# ============================================================

with torch.no_grad():

    tensor = torch.tensor(
        X,
        dtype=torch.float32,
    )

    scores = (
        torch.sigmoid(
            model(
                tensor
            )
        )
        .numpy()
    )

df["zyra_score"] = scores

# ============================================================
# TEST PEOPLE
# ============================================================

df = df[
    df[
        "person_id"
    ].isin(
        TEST_PEOPLE
    )
].copy()

# ============================================================
# RANK
# ============================================================

df["rank"] = (
    df
    .groupby(
        "person_id"
    )[
        "zyra_score"
    ]
    .rank(
        method="first",
        ascending=False,
    )
)

df["is_positive"] = (
    df[
        "label_status"
    ]
    == "positive"
)

# ============================================================
# VERIFY CATALOG
# ============================================================

catalog_counts = (
    df
    .groupby(
        "person_id"
    )[
        "product_id"
    ]
    .nunique()
)

print("\n" + "=" * 70)
print("CATALOG")
print("=" * 70)

print(
    catalog_counts
)

assert (
    catalog_counts == 897
).all()

# ============================================================
# ACTUAL RECOMMENDATIONS
# ============================================================

print("\n" + "=" * 70)
print("ZYRA TOP-10 RECOMMENDATIONS")
print("=" * 70)

for person_id in TEST_PEOPLE:

    person_df = (
        df[
            df[
                "person_id"
            ]
            ==
            person_id
        ]
        .sort_values(
            "rank"
        )
    )

    top10 = (
        person_df
        .head(10)
        .copy()
    )

    print(
        "\n" + "-" * 70
    )

    print(
        f"PERSON: {person_id}"
    )

    print(
        "-" * 70
    )

    display(
        top10[
            [
                "rank",
                "product_id",
                "zyra_score",
                "is_positive",
            ]
        ]
    )

# ============================================================
# TOP-K POSITIVE COVERAGE
# ============================================================

print("\n" + "=" * 70)
print("ACTUAL RECOMMENDATION COVERAGE")
print("=" * 70)

all_positive_ranks = (
    df[
        df[
            "is_positive"
        ]
    ][
        "rank"
    ]
    .to_numpy()
)

total = len(
    all_positive_ranks
)

for k in [
    1,
    5,
    10,
    20,
    50,
    100,
]:

    hits = np.sum(
        all_positive_ranks <= k
    )

    print(
        f"Top-{k:3d}: "
        f"{hits:4d}/{total:4d} "
        f"("
        f"{100 * hits / total:.2f}%"
        f")"
    )

# ============================================================
# BEST POSITIVE PER PERSON
# ============================================================

print("\n" + "=" * 70)
print("BEST POSITIVE RANK PER PERSON")
print("=" * 70)

for person_id in TEST_PEOPLE:

    person_positive = (
        df[
            (
                df[
                    "person_id"
                ]
                ==
                person_id
            )
            &
            (
                df[
                    "is_positive"
                ]
            )
        ]
    )

    if len(
        person_positive
    ) == 0:

        print(
            person_id,
            ": NO POSITIVES"
        )

        continue

    best = (
        person_positive[
            "rank"
        ]
        .min()
    )

    median = (
        person_positive[
            "rank"
        ]
        .median()
    )

    print(
        f"{person_id:15s} "
        f"best={best:.0f} "
        f"median={median:.0f}"
    )

# ============================================================
# SCORE DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("SCORE DISTRIBUTION")
print("=" * 70)

print(
    df[
        "zyra_score"
    ].describe()
)

# ============================================================
# SAVE
# ============================================================

df.to_csv(
    OUTPUT_PATH,
    index=False,
)

print("\n" + "=" * 70)
print("INFERENCE RESULTS SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print("\n" + "=" * 70)
print("ZYRA V2 STEP 11 COMPLETE")
print("=" * 70)

======================================================================
ZYRA V2 — ACTUAL RECOMMENDATION INFERENCE
======================================================================
Model features: 125
Test people: ['Alex', 'Anna Maria', 'Bree', 'Chesska', 'Emma', 'Maddy', 'Palatina', 'Sophie']

Model loaded successfully.

Candidate rows: 50232
Original rows: 50232

======================================================================
CATALOG
======================================================================
person_id
Alex          897
Anna Maria    897
Bree          897
Chesska       897
Emma          897
Maddy         897
Palatina      897
Sophie        897
Name: product_id, dtype: int64

======================================================================
ZYRA TOP-10 RECOMMENDATIONS
======================================================================

----------------------------------------------------------------------
PERSON: Alex
----------------------------------------------------------------------

/var/folders/xr/kwlqndgn0kbbch4p_bf7k8_r0000gn/T/ipykernel_54859/615634888.py:317: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["zyra_score"] = scores

,rank,product_id,zyra_score,is_positive
37405,1.0,the-short-sleeve-wrap-jersey-top#Emerald,0.733962,True
37236,2.0,the-short-sleeve-wrap-jersey-top#Black,0.732904,True
37206,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.730139,True
37301,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.728709,True
37572,5.0,bamboo-layer-tank#Chalk,0.687307,False
37191,6.0,the-boat-neck-top#Black,0.679452,False
37577,7.0,bamboo-layer-tank#Black,0.674327,False
36832,8.0,the-boat-neck-top#Navy,0.672654,False
37133,9.0,the-reversible-cowl-neck-top-2#Ocean,0.665976,False
36798,10.0,the-batwing-tee#FrenchBlue,0.659024,True

----------------------------------------------------------------------
PERSON: Anna Maria
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
34545,1.0,the-short-sleeve-wrap-jersey-top#Black,0.742751,False
34714,2.0,the-short-sleeve-wrap-jersey-top#Emerald,0.740448,False
34515,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.739279,False
34610,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.736104,False
34881,5.0,bamboo-layer-tank#Chalk,0.698011,False
34500,6.0,the-boat-neck-top#Black,0.686076,False
34442,7.0,the-reversible-cowl-neck-top-2#Ocean,0.685611,False
34886,8.0,bamboo-layer-tank#Black,0.684563,False
34141,9.0,the-boat-neck-top#Navy,0.681379,False
34144,10.0,monaco-knot-top#Black,0.657359,False

----------------------------------------------------------------------
PERSON: Bree
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
41721,1.0,the-short-sleeve-wrap-jersey-top#Black,0.790887,False
41691,2.0,the-short-sleeve-wrap-jersey-top#Blue,0.788749,False
41890,3.0,the-short-sleeve-wrap-jersey-top#Emerald,0.788061,False
41786,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.785653,False
41618,5.0,the-reversible-cowl-neck-top-2#Ocean,0.748486,False
41809,6.0,belle-cowl-swing-sweater#Black,0.706500,False
42057,7.0,bamboo-layer-tank#Chalk,0.703459,False
41344,8.0,pure-merino-fine-rib-v-neck#Charcoal,0.701599,False
42062,9.0,bamboo-layer-tank#Black,0.696537,False
41600,10.0,long-sleeve-tee-2#NavyWhite,0.692833,False

----------------------------------------------------------------------
PERSON: Chesska
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
13914,1.0,the-short-sleeve-wrap-jersey-top#Black,0.753542,False
14083,2.0,the-short-sleeve-wrap-jersey-top#Emerald,0.750255,False
13884,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.749129,False
13979,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.746792,False
13811,5.0,the-reversible-cowl-neck-top-2#Ocean,0.710362,False
14250,6.0,bamboo-layer-tank#Chalk,0.694820,False
13962,7.0,holly-rib-long-sleeve-tee#WhiteGrey,0.685069,False
14255,8.0,bamboo-layer-tank#Black,0.683536,False
14202,9.0,ally-long-sleeve-tee#CosmosPr,0.678075,False
13869,10.0,the-boat-neck-top#Black,0.676566,False

----------------------------------------------------------------------
PERSON: Emma
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
8701,1.0,the-short-sleeve-wrap-jersey-top#Emerald,0.733962,False
8532,2.0,the-short-sleeve-wrap-jersey-top#Black,0.732904,False
8502,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.730139,False
8597,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.728709,False
8868,5.0,bamboo-layer-tank#Chalk,0.687307,False
8487,6.0,the-boat-neck-top#Black,0.679452,False
8873,7.0,bamboo-layer-tank#Black,0.674327,False
8128,8.0,the-boat-neck-top#Navy,0.672654,False
8429,9.0,the-reversible-cowl-neck-top-2#Ocean,0.665976,False
8094,10.0,the-batwing-tee#FrenchBlue,0.659024,False

----------------------------------------------------------------------
PERSON: Maddy
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
13017,1.0,the-short-sleeve-wrap-jersey-top#Black,0.763323,True
13186,2.0,the-short-sleeve-wrap-jersey-top#Emerald,0.758908,True
12987,3.0,the-short-sleeve-wrap-jersey-top#Blue,0.758747,True
13082,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.756498,True
12914,5.0,the-reversible-cowl-neck-top-2#Ocean,0.721497,False
13353,6.0,bamboo-layer-tank#Chalk,0.702183,False
13358,7.0,bamboo-layer-tank#Black,0.689753,False
12972,8.0,the-boat-neck-top#Black,0.681050,False
13305,9.0,ally-long-sleeve-tee#CosmosPr,0.680479,False
13065,10.0,holly-rib-long-sleeve-tee#WhiteGrey,0.678960,False

----------------------------------------------------------------------
PERSON: Palatina
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
17502,1.0,the-short-sleeve-wrap-jersey-top#Black,0.800731,False
17472,2.0,the-short-sleeve-wrap-jersey-top#Blue,0.797810,False
17671,3.0,the-short-sleeve-wrap-jersey-top#Emerald,0.797486,False
17567,4.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.795994,False
17399,5.0,the-reversible-cowl-neck-top-2#Ocean,0.771173,False
17125,6.0,pure-merino-fine-rib-v-neck#Charcoal,0.722367,True
17691,7.0,forget-me-knot-tunic#ForgetMeK,0.720378,False
17838,8.0,bamboo-layer-tank#Chalk,0.713205,False
17381,9.0,long-sleeve-tee-2#NavyWhite,0.711124,False
17550,10.0,holly-rib-long-sleeve-tee#WhiteGrey,0.708535,False

----------------------------------------------------------------------
PERSON: Sophie
----------------------------------------------------------------------

,rank,product_id,zyra_score,is_positive
16605,1.0,the-short-sleeve-wrap-jersey-top#Black,0.822884,False
16575,2.0,the-short-sleeve-wrap-jersey-top#Blue,0.821927,False
16670,3.0,the-short-sleeve-wrap-jersey-top#NavyWhite,0.821274,False
16774,4.0,the-short-sleeve-wrap-jersey-top#Emerald,0.821124,False
16610,5.0,analia-jersey-top#Black,0.764081,False
16693,6.0,belle-cowl-swing-sweater#Black,0.764026,False
16502,7.0,the-reversible-cowl-neck-top-2#Ocean,0.763355,False
16710,8.0,ava-short-sleeve-linen-tee#Navy,0.762670,False
16527,9.0,analia-jersey-top#Navy,0.753667,False
16163,10.0,belle-cowl-swing-sweater#Green,0.751828,False

======================================================================
ACTUAL RECOMMENDATION COVERAGE
======================================================================
Top-  1:    2/ 339 (0.59%)
Top-  5:    8/ 339 (2.36%)
Top- 10:   10/ 339 (2.95%)
Top- 20:   16/ 339 (4.72%)
Top- 50:   25/ 339 (7.37%)
Top-100:   47/ 339 (13.86%)

======================================================================
BEST POSITIVE RANK PER PERSON
======================================================================
Alex            best=1 median=541
Anna Maria      best=163 median=306
Bree            best=252 median=282
Chesska         best=52 median=321
Emma            best=32 median=583
Maddy           best=1 median=408
Palatina        best=6 median=495
Sophie          best=59 median=574

======================================================================
SCORE DISTRIBUTION
======================================================================
count    7176.000000
mean        0.426067
std         0.166616
min         0.025457
25%         0.300633
50%         0.431240
75%         0.563611
max         0.822884
Name: zyra_score, dtype: float64

======================================================================
INFERENCE RESULTS SAVED
======================================================================
/Users/saketh/Desktop/Projects/weavly/core-model/data/v2/v2_actual_inference_results.csv

======================================================================
ZYRA V2 STEP 11 COMPLETE
======================================================================

In [90]:
# ============================================================
# LOCATE OFFICIAL ViBA-NET REPOSITORY
# ============================================================

import requests
import re

url = (
    "https://openaccess.thecvf.com/"
    "content/WACV2024/html/"
    "Pang_Learning_Visual_Body-Shape-Aware_Embeddings_for_Fashion_Compatibility_WACV_2024_paper.html"
)

print("=" * 70)
print("SEARCHING ViBA-Net PAPER FOR OFFICIAL CODE")
print("=" * 70)

response = requests.get(
    url,
    timeout=20,
)

print(
    "HTTP status:",
    response.status_code
)

html = response.text

# Find GitHub links
github_links = sorted(
    set(
        re.findall(
            r'https?://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+',
            html,
        )
    )
)

print("\nGitHub repositories found:")

if github_links:

    for link in github_links:

        print(
            link
        )

else:

    print(
        "No GitHub repository link found on the paper page."
    )

print("\n" + "=" * 70)

======================================================================
SEARCHING ViBA-Net PAPER FOR OFFICIAL CODE
======================================================================
HTTP status: 200

GitHub repositories found:
No GitHub repository link found on the paper page.

======================================================================